### PR TITLE
[16.0][FIX] product_supplierinfo_for_customer_sale: handle no supplierinfo

### PR DESCRIPTION
**Pull request by alexey-pelykh**

### CODE REVIEW

**Comment by alexey-pelykh** [comment]
@AaronHForgeFlow @simahawk related to https://github.com/OCA/product-attribute/commit/03d244c9e172d2fff93c3c5796c7cb3083c29f34

**Review by AaronHForgeFlow — APPROVED** [review]
LGTM!

**Comment by simahawk** [comment]
Wouldn't be better to restore the empty recordset as you mentioned on the prev comment?

**Comment by alexey-pelykh** [comment]
@simahawk imho we should do both so that empty string is explicitly used for empty record set.

**Comment by simahawk** [comment]
Just do `supplierinfo.product_code or ""` if you care about the type although is not so relevant because Odoo sets empty fields as False anyway.

**Comment by alexey-pelykh** [comment]
Reasonable, then let's merge the other PR and close this one

**Review by AaronHForgeFlow — CHANGES_REQUESTED** [review]
as per comments

**Pull request closed without merging**
