### PR TITLE
[14.0][FIX] - sale_automatic_workflow: fix method header

### PR DESCRIPTION
**Pull request by sbejaoui**

### CODE REVIEW

**Review by rousseldenis — APPROVED** [review]
Obvious

**Review by dreispt — APPROVED** [review]

**Comment by dreispt** [comment]
Hmm, Travis is red, can you check @sbejaoui ?

**Comment by rousseldenis** [comment]
@sbejaoui Could you rebase ?

https://github.com/OCA/sale-workflow/pull/1641 fixed 14.0 branch.

**Pull request merged**
