### PR TITLE
[8.0][ADD] sale_delivery_split_date module

### PR DESCRIPTION
**Pull request by tafaRU**

### CODE REVIEW

**Review by andhit-r — APPROVED** [review]
Functionsl test.

**Review by stevech091 — APPROVED** [review]
functional test

**Review by SimoRubi — APPROVED** [review]
Looks good to me

**Comment by tafaRU** [comment]
Please note I rebased just to include  https://github.com/tafaRU/sale-workflow/blob/8.0-sale_delivery_split_date-add/sale_delivery_split_date/views/stock_picking.xml

**Pull request merged**
