### PR TITLE
12.0 mig sale automatic workflow [WIP]

### PR DESCRIPTION
**Pull request by gdgellatly**
PR #707 is dead, so I cherry-picked and started fixing it.  Just WIP for now. Lots and lots of change and my demo system is a bit full of installed stuff atm breaking tests so want to see if fixed here.

\cc @pedrobaeza you probably want to close #707

### CODE REVIEW

**Comment by gdgellatly** [comment]
@OCA/logistics-maintainers I've got this PR to a point where the tests operate correctly. However I am stuck in making one final test pass.  It is the automatic validation of picking. There is no longer a `_force_assign` and `_picking_assign` doesn't do it, nor does manually setting quantities (last attempt).  At a high level, how would you automatically validate a picking in code? or is this no longer desirable/feasible? I don't use this functionality myself so not really sure how to do properly.

**Comment by pedrobaeza** [comment]
@gdgellatly yeah it still makes sense. For doing that, you have to call stock.move assign method, but I don't have right now the exact method name.

**Comment by seancallahan88** [comment]
@pedrobaeza Was it force_assign in stock_move that called check_recompute_pack_op? It looks like many of the functions needed to force validation of a picking have been removed. Maybe they want us to edit the quantity_done field for each line and then validate?

**Comment by pedrobaeza** [comment]
@seancallahan88 yeah, you should manually fill that field, but the method I talked about is for populating stock.move.line.

**Comment by florian-dacosta** [comment]
@pedrobaeza 
I did a pull request to fix the issue here : https://github.com/odoonz/sale-workflow/pull/1
But, I don't really know the version 12 yet so I am not sure this is the best way. 
I don't use this feature either.
Anyway, all critics to improve it are welcome.

**Comment by gdgellatly** [comment]
@pedrobaeza I'm closing this PR. It is full of bugs in production.

AccessErrors, concurrency errors, accessing wrong company, cancelling stock moves, messing up quant reservations. Just not worth it for me to try and fix. I'll leave the branch open if anyone wants to pick it up.

**Comment by pedrobaeza** [comment]
OK, thanks any way for trying.

**Pull request closed without merging**
