### PR TITLE
[16.0][MIG] sale_force_invoiced

### PR DESCRIPTION
**Pull request by Highcooley**

### CODE REVIEW

**Comment by rousseldenis** [comment]
/ocabot migration sale_force_invoiced

@Highcooley Still draft ?

**Comment by alexis-via** [comment]
If my pull request had been merged in a reasonable amount of time, this kind of duplicate work would not happen. I guess @Highcooley didn't spot the PR... didn't you @Highcooley ?

**Comment by Highcooley** [comment]
@alexis-via Sorry, I totally missed that. Closing this PR

**Comment by rvalyi** [comment]
@alexis-via there is a small suggestion in your PR you didn't answer still https://github.com/OCA/sale-workflow/pull/2305#pullrequestreview-1218966479

**Pull request closed without merging**
