### PR TITLE
[MIG] sale_sourced_by_line: Migration to 16.0

### PR DESCRIPTION
**Pull request by punt-sistemes-salva**

### CODE REVIEW

**Comment by punt-sistemes-salva** [comment]
This PR depends of: sale_procurement_group_by_line: https://github.com/OCA/sale-workflow/pull/2403#pullrequestreview-1458120472

**Comment by flalexg** [comment]
Code LGTM! I think it would be interesting changing the sale.order field `procurement_group_id` from a Many2one to a Many2many to allow seeing how many procurement groups are in one sale. What do you think?

**Comment by punt-sistemes-salva** [comment]
Thanks! I thinks that is interesting but this field is declared in sale_procurement_group_by_line, this module is being migrated in that PR: https://github.com/OCA/sale-workflow/pull/2403#pullrequestreview-1458120472

**Comment by flalexg** [comment]
Okey. Could you fix the tests? The are failing. I will do a functional review later.

**Comment by celm1990** [comment]
please see PR https://github.com/OCA/sale-workflow/pull/2540

**Comment by rousseldenis** [comment]
@punt-sistemes-salva We will move to #2540. Do you agree ?

**Comment by punt-sistemes-salva** [comment]
> @punt-sistemes-salva We will move to #2540. Do you agree ?

Ok, thanks!

**Pull request closed without merging**
