### PR TITLE
[12.0][sale_exception] refactore sale exception to adapt it to base_exception refactore.

### PR DESCRIPTION
**Pull request by florian-dacosta**
Same refactore thant in version 10.

Depends on https://github.com/OCA/server-tools/pull/1589 and should be merged right after.
On merge, oca_dependencies should be fixed. (remove last commit)

### CODE REVIEW

**Review by bealdav — APPROVED** [review]

**Comment by florian-dacosta** [comment]
Force push to revert the oca depencies as the other PR has been merged

**Review by sebastienbeau — APPROVED** [review]
As discuss in 10.0
it's ok for me

**Comment by rafaelbn** [comment]
Hello @florian-dacosta @sebastienbeau @bealdav , after this PR runbot was warnings, check:



Please, could you check it?

**Comment by florian-dacosta** [comment]
@rafaelbn 
Do you have any idea how I can check what is wrong? I can't see any logs...

**Comment by florian-dacosta** [comment]
@rafaelbn I did force a build, and it seems to be good now.
Can you confirm?

**Comment by rafaelbn** [comment]
Yes  @florian-dacosta I confirm now is green. Temporally warnings? :smile: 

Thanks you!

**Pull request merged**
