### PR TITLE
[12.0][FIX] sale_order_lot_selection + sale_order_lot_generator: Prevent error in test with other addons

### PR DESCRIPTION
**Pull request by victoralmau**
Related to https://github.com/OCA/sale-workflow/issues/1446 (`sale_order_lot_selection` + `sale_order_lot_generator`)

Please @CarlosRoca13 and @chienandalu can you review it?

@Tecnativa TT28247

### CODE REVIEW

**Review by CarlosRoca13 — APPROVED** [review]

**Review by lmignon — CHANGES_REQUESTED** [review]
The problem is somewhere else. If you run the tests alone, everything is OK

**Review by lmignon — CHANGES_REQUESTED** [review]
The problem is somewhere else. If you run the tests alone, everything is OK
:-1:

**Review by lmignon — CHANGES_REQUESTED** [review]
The problem is somewhere else. If you run the tests alone, everything is OK
:-1:

**Comment by pedrobaeza** [comment]
@victoralmau instead of changing this, please change in the setup that the involved product is `consumable` instead. This problem comes from using demo data (that other modules may change), and that's why this is discouraged and not done in latest Odoo versions. So you can still reference the demo product, but writing explicitly such value, or use a newly created product for this test.

**Review by chienandalu — APPROVED** [review]

**Comment by pedrobaeza** [comment]
@lmignon do you agree now?

**Review by lmignon — APPROVED** [review]

**Comment by lmignon** [comment]
thank you for the fix @victoralmau

**Comment by bealdav** [comment]
Thanks a lot @victoralmau I note it's a good approach to systemically copy demo in test. Thanks

**Comment by victoralmau** [comment]
Actually travis fail related to `sale_order_lot_generator` https://github.com/OCA/sale-workflow/pull/1456

**Comment by pedrobaeza** [comment]
You must include both in the same PR, or we won't be able to merge this. But do it as separate commits.

**Comment by victoralmau** [comment]
Now included 2 commits (1 for each addon)

**Comment by pedrobaeza** [comment]
OK, and green with no conflicting changes, so

/ocabot merge patch

**Review by marcelsavegnago — APPROVED** [review]

**Pull request merged**
