### PR TITLE
[14.0][MIG] sale_order_priority: Migration to v14.0

### PR DESCRIPTION
**Pull request by GuillemCForgeFlow**

### CODE REVIEW

**Comment by MiquelRForgeFlow** [comment]
Please squash last commit into the previous one.

**Comment by GuillemCForgeFlow** [comment]
@ForgeFlow

**Review by MiquelRForgeFlow — APPROVED** [review]

**Review by BernatPForgeFlow — APPROVED** [review]

**Comment by GuillemCForgeFlow** [comment]
@pedrobaeza could you please check this, please?

**Comment by GuillemCForgeFlow** [comment]
@dreispt You can try again! I rebased, let's see now if it works

**Comment by rafaelbn** [comment]
@GuillemCForgeFlow could you please check https://github.com/OCA/sale-workflow/pull/1783#issuecomment-1032745846

Thanks! Gogogo! 😄

**Comment by GuillemCForgeFlow** [comment]
> @GuillemCForgeFlow could you please check [#1783 (comment)](https://github.com/OCA/sale-workflow/pull/1783#issuecomment-1032745846)
> 
> Thanks! Gogogo! smile

The build is failing because of a test of another module. I'll rebase and see if it works!

**Comment by GuillemCForgeFlow** [comment]
@rafaelbn The travis is working now, i changed the way the module works if you want to check. You can already merge it! :smile:

**Pull request merged**
