### PR TITLE
[14.0][MIG] sale_stock_picking_note: Migration to 14.0

### PR DESCRIPTION
**Pull request by victoralmau**
Superseed: https://github.com/OCA/sale-workflow/pull/1652

Migration to 14.0

Please @joao-p-marques  and @chienandalu can you review it?

@Tecnativa TT31833

### CODE REVIEW

**Review by chienandalu — APPROVED** [review]

**Review by joao-p-marques — APPROVED** [review]
Code review. LGTM :+1:

**Comment by rousseldenis** [comment]
@pedrobaeza @victoralmau Have you asked original PR author before merging this ? Moreover @pedrobaeza comment https://github.com/OCA/sale-workflow/pull/1652#issuecomment-920035771 hasn't been attended

**Comment by pedrobaeza** [comment]
After the comment https://github.com/OCA/sale-workflow/pull/1652#issuecomment-940905207 and no answer nor action about including  #1698, we consider it as stalled and no interest in keep going. We have no interest on superseding, just on getting this done. It's true anyways that #1698 is still not included. @victoralmau you forgot that one. @acsonefho you tell us if you finish the PR or should we do it.

**Comment by pedrobaeza** [comment]
As no further notice, and the comment has been honored, merging:

/ocabot merging nobump

/ocabot migration sale_stock_picking_note

**Pull request merged**
