### PR TITLE
[15.0][MIG]sale_mrp_bom : Migrated to 15.0

### PR DESCRIPTION
**Pull request by AnilKesariya**
Module works fine in 15.0

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Thanks for the contribution.

Please preserve commit history following technical method explained in https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-15.0.

If the jump is between several versions, you have to modify the source branch in the main command to accommodate it to this circumstance.

**Comment by AnilKesariya** [comment]
@pedrobaeza : How can I fix this pre-commit issue?

**Comment by pedrobaeza** [comment]
Please follow the procedure.

**Comment by rousseldenis** [comment]
@AnilKesariya

**Comment by rrebollo** [comment]
Hi @AnilKesariya @rousseldenis @pedrobaeza,

I’ve reviewed PR #2234 and would like to help to ensure it aligns with OCA standards. Let me know if I can proceed in any way, what can we do in this cases?

Thanks

**Comment by pedrobaeza** [comment]
Superseded by #2234

**Comment by pedrobaeza** [comment]
Sorry, I saw bad that you did a new PR. Anyway, this PR is not correct, as it doesn't preserve commit history.

**Comment by rrebollo** [comment]
@pedrobaeza can I start a new one then?

**Comment by pedrobaeza** [comment]
Yes. The non-written rule is to give some room to the contributor to fix the problems, but 2 years after with no response, it's clear that this PR can be superseded.

**Pull request closed without merging**
