### PR TITLE
[11.0][MIG] sale_manual_delivery

### PR DESCRIPTION
**Pull request by grindtildeath**
Based on: #404 
Supersedes: #922 

New feature added:
 - [x] IMP: Use a procurement group according to date planned (160d82b + 4e55bba)

TODO:
 - [ ] Converge with @aheficent 's work on #935
 - [ ] Squash commits

### CODE REVIEW

**Review by Tonow-c2c — APPROVED** [review]

**Comment by leemannd** [comment]
The bot is right, but is missing informations:
`oleksandrpaziuk o.paziuk@mobilunity.com (no github login found)`
The user formerly signed the CLA, but his account has been deleted when he left the mobilunity company.

**Comment by AaronHForgeFlow** [comment]
sorry for the lint error fix here: https://github.com/grindtildeath/sale-workflow/pull/3

**Comment by leemannd** [comment]
@AaronHForgeFlow @grindtildeath The last commit may be an improvment, but it is a no go for me.
There is a regression in the way we are currently using the module with our customer. Our base goal within this module was to target more the user that is in touch with the client than people working in warehouses.

There was the possibility to set the delivery address from the wizard. We are currently using this module to use the SO as a base contract for a project with:
- possibility to change a product later
- invoice manually when required
- invoice at the right place (you may want to ship to different places for the need of your project).

Sidenote: Thanks for the rest of the work, this is pretty nice. It goes further than our actual need and it has a great utility.

**Review by leemannd — CHANGES_REQUESTED** [review]
Please check my previous comment

**Comment by rousseldenis** [comment]
@grindtildeath Could you merge @AaronHForgeFlow PR to make travis happy ?

**Review by leemannd — CHANGES_REQUESTED** [review]
We need to restore the possibility to choose the delivery address from the wizard.

**Comment by grindtildeath** [comment]
@AaronHForgeFlow @rousseldenis Sorry for the late merge, I don't have much time to followup on this..

**Comment by AaronHForgeFlow** [comment]
Hi @mmequignon  what a coincidence. I was trying to do the same thing on https://github.com/OCA/sale-workflow/pull/935 and https://github.com/OCA/sale-workflow/pull/987 :smile:  I will cherry pick your changes in both PRs. Thank you!

**Comment by AaronHForgeFlow** [comment]
@grindtildeath @mmequignon I also noticed that the carrier_id was not being passed to the delivery order. I guess it was something I removed. In any case, I fixed that on https://github.com/grindtildeath/sale-workflow/pull/4 Also, I added the possibility of choosing the route at the time of delivering. This is important for us, as long we don't know from which warehouse we are going to ship at the moment of sales confirmation. Could you please take a look at that PR?

**Comment by AaronHForgeFlow** [comment]
It seems working nice. I just tested. travis is red because the build was stopped, only that.

**Review by leemannd — APPROVED** [review]

**Pull request closed without merging**
