### PR TITLE
[16.0] [MIG] sale_planner_calendar

### PR DESCRIPTION
**Pull request by angelmoya**
Depends #2554

### CODE REVIEW

**Comment by rousseldenis** [comment]
/ocabot migration sale_planner_calendar

@angelmoya FYI, you can embed depending PR's here in order to get tests running and runboat online to be able to functional test. https://github.com/OCA/maintainer-tools/wiki/Use-temporary-reference%28s%29-to-another-pull-request%28s%29

**Comment by sergio-teruel** [comment]
Please include this PR (https://github.com/OCA/sale-workflow/pull/3012) when it has been merged

Thanks

**Comment by pedrobaeza** [comment]
Please include #3139

**Comment by pilarvargas-tecnativa** [comment]
Please include https://github.com/OCA/sale-workflow/pull/3073

Thanks!

**Comment by pedrobaeza** [comment]
Superseded by #3198

**Pull request closed without merging**
