### PR TITLE
[ADD] New module Sale Order Invoice Link

### PR DESCRIPTION
**Pull request by mileo**

### CODE REVIEW

**Comment by pedrobaeza** [comment]
This maybe fits better in OCA/account-invoicing

**Comment by mileo** [comment]
We were also with this doubt.... 

But stock invoice link is here https://github.com/OCA/stock-logistics-workflow/tree/10.0/stock_picking_invoice_link

**Comment by pedrobaeza** [comment]
Yeah, I know, but I consider that also a past mistake. OCA/sale-workflow is enough populated I think, so we can move this one to OCA/account-invoicing, and see if we move the other also in next versions.

**Comment by mileo** [comment]
OK

**Pull request closed without merging**
