### PR TITLE
14.0 MIGR sale isolated quotation

### PR DESCRIPTION
**Pull request by Kev-Roche**

### CODE REVIEW

**Comment by bealdav** [comment]
cc @kittiu

**Review by bealdav — APPROVED** [review]
Just tested, it works

**Comment by youring** [comment]
Just found a small issue on runbot, maybe also exist in previous versions.
Create a quotation, then convert to order, refresh page(browser refresh F5), the order form status bar is gone.

**Review by atchuthan — APPROVED** [review]

**Comment by bealdav** [comment]
@youring you're right it's a limitation in this module but also in odoo in general.
Some informations are lost when refreshing. It's important to make think your customer to use menu after any refresh

**Comment by bealdav** [comment]
Thanks a lot @dreispt

**Pull request merged**
