### PR TITLE
[8.0][BKP] sale_triple_discount

### PR DESCRIPTION
**Pull request by SimoRubi**
Backport of module sale_triple_discount from v10

### CODE REVIEW

**Comment by rafaelbn** [comment]
Hello @SimoRubi ! This is a really complicated module.

IMHO if bots are green I could test and merge but In v10 (where more people use it) we have opened:

- FIX https://github.com/OCA/sale-workflow/pull/544
- Rework https://github.com/OCA/sale-workflow/pull/671
- FIX https://github.com/OCA/sale-workflow/pull/740

Now travis is :red_circle: 

Thanks

**Comment by SimoRubi** [comment]
Thanks @rafaelbn you reminded me that some work has been done on this module in the meanwhile, I have to backport that too

**Comment by SimoRubi** [comment]
Rebased from `10.0` module.
Travis is now still failing because the field `amount_untaxed` (and others, but let's just focus on this one) is not recomputed when `price_subtotal` changes.
In new APIs adding a dependency is simple with `api.depends` decorator, but right now I don't know how to add a trigger in old APIs.

I verified in local that hard-coding `discount2` and `discount3` among triggers for `amount_untaxed` fixes the tests so the problem is just that, any help is much appreciated :smile:

**Review by hurrinico — APPROVED** [review]
Working on our customer so LGTM.
About the hybrid test between old and new api it's quite hard, i'll study more the case and i'll make a suggest

**Comment by SimoRubi** [comment]
@pedrobaeza could you please have a look?
I managed to fix the automated tests with https://github.com/OCA/sale-workflow/pull/792/commits/ab68235e6c2694e25c6695207c18c792e595d646, but I see that in https://github.com/odoo/odoo/issues/3922#issuecomment-262022255 you were suggesting a different approach.

Do you think that I should move the code of https://github.com/OCA/sale-workflow/pull/792/commits/ab68235e6c2694e25c6695207c18c792e595d646 in `_register_hook` of `sale_procurement_group_by_line`?
In this case I should also call the same method in `sale_triple_discount`'s tests but this module does not depend on `sale_procurement_group_by_line`

**Comment by pedrobaeza** [comment]
Sorry, no clue right now and don't have time to dig in.

**Comment by SimoRubi** [comment]
@rafaelbn see my answers below:

> Hello @SimoRubi ! This is a really complicated module.
> 
> IMHO if bots are green I could test and merge but In v10 (where more people use it) we have opened:
> 
> * FIX #544

This is closed
> * Rework #671

Reviewed: https://github.com/OCA/sale-workflow/pull/671#pullrequestreview-232887228
> * FIX #740

Reviewed: https://github.com/OCA/sale-workflow/pull/740#pullrequestreview-232884553

> 
> Now travis is :red_circle: 

Now travis is :heavy_check_mark:

**Comment by SimoRubi** [comment]
@rafaelbn I did what I could for your comment, can I do anything else to help merging this PR?

**Comment by SimoRubi** [comment]
@OCA/crm-sales-marketing-maintainers how else can I help this PR to be merged? Thanks

**Comment by tafaRU** [comment]
@rafaelbn could you please update your review?

**Review by rafaelbn — APPROVED** [review]
:+1:

**Comment by rafaelbn** [comment]
2019-10-01 19:36:00,600 23158 ERROR ? openerp.sql_db: Connection to the database failed

**Comment by rafaelbn** [comment]
```
OperationalError: could not connect to server: No such file or directory
Is the server running locally and accepting
connections on Unix domain socket "/var/run/postgresql/.s.PGSQL.5432"?
2019-10-02 16:15:02,223 5866 CRITICAL ? openerp.service.server: Failed to initialize database `openerp_test`.
Traceback (most recent call last):
File "/home/travis/odoo-8.0/openerp/service/server.py", line 941, in preload_registries
registry = RegistryManager.new(dbname, update_module=update_module)
File "/home/travis/odoo-8.0/openerp/modules/registry.py", line 356, in new registry = Registry(db_name)
File "/home/travis/odoo-8.0/openerp/modules/registry.py", line 81, in __init__
cr = self.cursor()
```

**Pull request merged**
