### PR TITLE
[15.0][ADD]Sale-Workflow-Sale Quotation Numeration

### PR DESCRIPTION
**Pull request by Hardik-OSI**

### CODE REVIEW

**Comment by patrickrwilson** [comment]
@OCA/oca-contributors pre-check is failing due to the below. I'm not familiar with this error, so does anyone have a suggestion on how to fix this?
image

**Comment by jcdrubay** [comment]
The content of the `setup` folder is very different between your branch and the branch 15.0.
Maybe you should merge 15.0 into your branch as your branch could hold some old configuration.

In your branch:
https://github.com/OCA/sale-workflow/tree/29949b5a9a861760974cfc69749cc2c4e0e5e9de/setup

In the branch 15.0:
https://github.com/OCA/sale-workflow/tree/15.0/setup

Then, what the test is doing is to ensure that all files generated by pre-commit are in git, so you need to check that in your branch:

- you did run pre-commit
- you committed the files which should have been generated by pre-commit

**Comment by dreispt** [comment]
@Hardik-OSI @patrickrwilson First steps to fix this:
1. Use a feature branch, and not the "15.0" branch in your fork - anyone in the ursais team can force push into 15.0 to sync with latest OCA versions, and you will lose your work.
2. Rebase you feature branch on latest OCA 15.0, to ensure you get the latest pre-commit configs

**Comment by patrickrwilson** [comment]
Thanks @jcdrubay and @dreispt , @Hardik-OSI please fix the items noted above.

**Comment by bizzappdev** [comment]
is this duplicate of https://github.com/OCA/sale-workflow/pull/1945 ?

**Comment by rousseldenis** [comment]
> is this duplicate of #1945 ?

@Hardik-OSI @patrickrwilson @dreispt Please review this one instead : #1945 

Moreover you don't respect commit history

**Comment by patrickrwilson** [comment]
> > is this duplicate of #1945 ?
> 
> @Hardik-OSI @patrickrwilson @dreispt Please review this one instead : #1945
> 
> Moreover you don't respect commit history

Yes, that PR was missed, thanks for the link. This PR can be closed.

**Pull request closed without merging**
