### PR TITLE
[14.0][IMP] update dotfiles

### PR DESCRIPTION
**Pull request by HekkiMelody**
Superseeds #2750 

cc @etobella

### CODE REVIEW

**Comment by HekkiMelody** [comment]
Please do double check the changes to the templates where I removed `position="replace"` in favour of `t-if="False"` before merging.

**Comment by pedrobaeza** [comment]
What you have to do is to put `priority="999"`, but don't remove the replace ones.

**Comment by HekkiMelody** [comment]
Mmmh, ok.

**Comment by HekkiMelody** [comment]
done

**Review by pedrobaeza — APPROVED** [review]

**Pull request merged**
