### PR TITLE
move 4 modules from OCA/e-commerce

### PR DESCRIPTION
**Pull request by lepistone**
After the discussion on OCA/e-commerce#47, this adds four modules to `sale-workflow`. They are:
- `sale_automatic_workflow`
- `sale_payment_method_automatic_workflow`
- `sale_automatic_workflow_exception` (unported)
- `sale_payment_method_transaction_id` (unported)

### CODE REVIEW

**Comment by pedrobaeza** [comment]
:+1:

**Comment by lepistone** [comment]
I could not rebase these modules onto `8.0`, but I had to merge them. This is because `git rebase` tries to make the history linear, and there were conflicts due to manually-resolved merges in the original branch.

**Comment by gurneyalex** [comment]
:+1:

**Comment by lepistone** [comment]
Here I delete them from `e-commerce`: https://github.com/OCA/e-commerce/pull/87

**Comment by tafaRU** [comment]
Thanks :+1:  I merge then.

**Pull request merged**
