### PR TITLE
[MIG] sale_by_packaging: Migration to 14.0

### PR DESCRIPTION
**Pull request by phuctranfxvn**

### CODE REVIEW

**Comment by simahawk** [comment]
to be considered https://github.com/OCA/sale-workflow/pull/1276
@phuctranerp would you mind to give a review there? :pray:

**Comment by simahawk** [comment]
another one here https://github.com/OCA/sale-workflow/pull/1375

**Comment by kevinkhao** [comment]
made a new PR integrating the changes from #1276 #1375 

https://github.com/OCA/sale-workflow/pull/1527

**Comment by rousseldenis** [comment]
@phuctranerp Do you mind if we switch ?

**Comment by phuctranfxvn** [comment]
@rousseldenis, that's ok for me

**Pull request closed without merging**
