### PR TITLE
[15.0][MIG] sale_order_line_sequence

### PR DESCRIPTION
**Pull request by MiquelRForgeFlow**
Supersedes https://github.com/OCA/sale-workflow/pull/1860.

### CODE REVIEW

**Review by LoisRForgeFlow — APPROVED** [review]
LGTM

**Review by CasVissers-360ERP — APPROVED** [review]
Straightforward migration / functional test.

**Comment by LoisRForgeFlow** [comment]
@rousseldenis this is ready to merge I think, could you do it? Thanks!

**Review by DavidJForgeFlow — APPROVED** [review]
LGTM

**Pull request merged**
