### PR TITLE
[17.0][MIG] sale_procurement_group_by_line

### PR DESCRIPTION
**Pull request by celm1990**

### CODE REVIEW

**Review by rousseldenis — APPROVED** [review]
Code review

**Comment by celm1990** [comment]
@OCA/crm-sales-marketing-maintainers could somebody help me with review or merge, please

**Comment by rousseldenis** [comment]
@celm1990 Could you attract someone else on your side ?

**Review by mmequignon — APPROVED** [review]
Code review, LG

**Review by Fabiola-Auz — APPROVED** [review]

**Review by Fabiola-Auz — APPROVED** [review]
Code review

**Comment by celm1990** [comment]
@rousseldenis could you help me with this merge, please

**Comment by celm1990** [comment]
@OCA/crm-sales-marketing-maintainers could somebody help me with review or merge, please

**Comment by celm1990** [comment]
ping @OCA/crm-sales-marketing-maintainers

**Comment by celm1990** [comment]
@OCA/crm-sales-marketing-maintainers could somebody help me with merge, please

**Comment by celm1990** [comment]
@pedrobaeza could you do your magic please

**Pull request merged**
