### PR TITLE
[WIP] 7.0 add sale order revision

### PR DESCRIPTION
**Pull request by gurneyalex**
migrated from https://code.launchpad.net/~akretion-team/sale-wkfl/70-add-sale_order_revision

### CODE REVIEW

**Comment by pedrobaeza** [comment]
This lacks all the cool added functionality for v8, but seems :+1:

**Comment by eLBati** [comment]
Just some PEP8

```
./sale_order_revision/model/sale_order.py:63:28: E231 missing whitespace after ':'
./sale_order_revision/model/sale_order.py:63:47: E231 missing whitespace after ':'
```

Then :+1: 
Thanks

**Comment by pedrobaeza** [comment]
Please check my PR to your branch with v8 features backport.

**Comment by pedrobaeza** [comment]
@gurneyalex, can you please check the PR I made against your branch?

**Comment by pedrobaeza** [comment]
@gurneyalex, please check my PR against your branch or I can also superseed your PR if you prefer

**Comment by gurneyalex** [comment]
@pedrobaeza sorry I don't see the the PR

**Comment by gurneyalex** [comment]
too old, no time, I'm closing this. The addon is available in v8.

**Pull request closed without merging**
