### PR TITLE
[17.0][FIX]sale_order_priority: Fix tests

### PR DESCRIPTION
**Pull request by RogerSans**
Fix tests. The company of sale is not indicated.
T-6499

@HaraldPanten 
@luis-ron

### CODE REVIEW

**Review by sakthi-shan — APPROVED** [review]

**Review by amh-mw — APPROVED** [review]
LGTM

**Comment by RogerSans** [comment]
TKNX @amh-mw

**Review by StefanRijnhart — APPROVED** [review]
I was a couple of minutes earlier than you with https://github.com/OCA/sale-workflow/pull/3290 :smile: I guess this is fine too.

**Pull request merged**
