### PR TITLE
[14.0] [MIG] sale_order_tag: Migrated the module in v14.

### PR DESCRIPTION
**Pull request by Chandresh-OSI**

### CODE REVIEW

**Comment by Chandresh-OSI** [comment]
CC @patrickrwilson

**Comment by patrickrwilson** [comment]
@Chandresh-OSI can you squash automated commits in history?

**Comment by Freni-OSI** [comment]
> @Chandresh-OSI can you squash automated commits in history?

It's done. Please review

**Review by patrickrwilson — APPROVED** [review]
Code looks good. LGTM

**Review by max3903 — APPROVED** [review]

**Pull request merged**
