### PR TITLE
[14.0][MIG] sale_order_archive

### PR DESCRIPTION
**Pull request by astirpe**

### CODE REVIEW

**Review by HaraldPanten — APPROVED** [review]
LGTM

**Review by tonygalmiche — APPROVED** [review]
LGTM : Code review and functional review with runbot

image

**Review by bodedra — APPROVED** [review]

**Review by danimv5 — APPROVED** [review]
Functional review!! LGTM

**Comment by astirpe** [comment]
Can this one be merged?

**Comment by tonygalmiche** [comment]
@pedrobaeza I think this PR is ready to be merged. thank you in advance.

**Pull request merged**
