### PR TITLE
[12.0][MIG] sale_merge_draft_invoice

### PR DESCRIPTION
**Pull request by jarroyomorales**
Migration to 12.0 of sale_merge_draft_invoice

### CODE REVIEW

**Review by etobella — APPROVED** [review]
Change version please

**Comment by jarroyomorales** [comment]
> Change version please

I think it was already done

**Review by tbaden — APPROVED** [review]
thanks for the work 👍 
I did a code review: LGTM

**Review by pedrobaeza — CHANGES_REQUESTED** [review]
Please squash together adjacent "OCA Transbot.." commits using https://github.com/OCA/maintainer-tools/wiki/Merge-commits-in-pull-requests

And the name doesn't reflect exactly the aim of this module. I would opt for `sale_invoicing_draft_reuse`.

**Comment by jarroyomorales** [comment]
@pedrobaeza Commits squashed!

**Comment by nikul-serpentcs** [comment]
@jarroyomorales one is remaining

12-0-MIG-sale-merge-draft-invoice-by-jarroyomorales-Pull-Request-872-OCA-sale-workflow

**Comment by jarroyomorales** [comment]
@Nikul-Chaudhary Ah okay, I thought it was okay to leave just one. Already changed it.

**Comment by pedrobaeza** [comment]
No, that's totally wrong. @Nikul-Chaudhary please stop asking for things that are not correct.

You mustn't squash the translation commit with the migration itself, as you are giving attribution of all the translation to the migrator to version 11.0. You should squash together all the translations commits, and you can even join together "POT update" commit with that translations, but not to squash translations with migration. Note that now with Weblate, each translator has direct attribution, so in that case (not this one), you shouldn't squash translation commits from different authors.

@jarroyomorales please undo that.

**Comment by nikul-serpentcs** [comment]
@pedrobaeza Noted!! Thanks For Inform.
 If a translation was version 11 and commit from different authors we don't squash those commits.

@jarroyomorales sorry for the misunderstanding, please undo.

**Comment by jarroyomorales** [comment]
@pedrobaeza @Nikul-Chaudhary, undid it, is it correct now?

**Comment by pedrobaeza** [comment]
Yes, thanks, and sorry for the noise.

/ocabot merge

**Comment by jarroyomorales** [comment]
@pedrobaeza No problem! :smile:

**Pull request closed without merging**
