### PR TITLE
[12.0][IMP] sale_invoice_plan improvements

### PR DESCRIPTION
**Pull request by kittiu**
1. Plan date now passed to invoice date
2. Allow edit invoice plan, if no invoice created yet (invoice_count = 0)
3. Add new view Sales Invoice Plan

### CODE REVIEW

**Comment by kittiu** [comment]
@hveficent, here I have added exactly the same features from purchase_invoice_plan https://github.com/OCA/purchase-workflow/pull/739
to this sale_invoice_plan
Thank you!

**Review by HviorForgeFlow — APPROVED** [review]

**Comment by kittiu** [comment]
@kongrattapong can you help review/approve with this? It is same as purchase_invoice_plan.

**Review by kongrattapong — APPROVED** [review]
LGTM :+1:

**Pull request merged**
