### PR TITLE
[12.0] [MIG] sale_sourced_by_line

### PR DESCRIPTION
**Pull request by saxomanu**

### CODE REVIEW

**Comment by AaronHForgeFlow** [comment]
Hi @saxomanu can you check this? https://github.com/OCA/sale-workflow/issues/529 If you consider this module should be continued then we can discuss there. Thanks.

**Comment by MiquelRForgeFlow** [comment]
@saxomanu could you rebase this PR or solve the travis ci and make it green?

**Comment by celm1990** [comment]
HI guys, any news for this PR? I see module for V13 but to V12 is abandoned :(

I can take work done for @saxomanu and resolve conflict and continue with PR?

**Comment by AaronHForgeFlow** [comment]
> Hi @saxomanu can you check this? #529 If you consider this module should be continued then we can discuss there. Thanks.

Finally, the module was continued in v13 so I guess you can continue with the migration to v12 as well.

**Pull request closed without merging**
