### PR TITLE
[16.0][ADD] sale_procurement_customer

### PR DESCRIPTION
**Pull request by rousseldenis**
Depends on:

- [ ] https://github.com/OCA/stock-logistics-workflow/pull/1185

Remove:

- [ ] test-requirements.txt

### CODE REVIEW

**Review by lmignon — APPROVED** [review]
LGTM (code review + functional tests)

**Review by adrienpeiffer — APPROVED** [review]
Code review

**Review by jbaudoux — APPROVED** [review]
LG

**Pull request merged**
