### PR TITLE
[13.0] [MIG] sale order line input

### PR DESCRIPTION
**Pull request by BenjaHe**

### CODE REVIEW

**Comment by BenjaHe** [comment]
> Hey @BenjaHe, thank you for your Pull Request.
> 
> It looks like some users haven't signed our **C**ontributor **L**icense **A**greement, yet.
> You can read and sign our full Contributor License Agreement here: http://odoo-community.org/page/cla
> Here is a list of the users:
> 
> * mpanarin [m.panarin@mobilunity.com](mailto:m.panarin@mobilunity.com) (no github login found)
> 
> Appreciation of efforts,
> OCA CLAbot

I do not know who mpanarin is.

**Comment by rousseldenis** [comment]
@BenjaHe Thanks for your PR.

Could you read this https://odoo-community.org/blog/the-oca-blog-1/post/black-isort-pre-commit-97 ?

From 13.0 branch, we use pre-commit and you need to install it locally before pushing.

**Comment by pedrobaeza** [comment]
@BenjaHe are you going to fix this PR? If not, there's another PR in #1020

**Review by chienandalu — CHANGES_REQUESTED** [review]
@BenjaHe There are merge conflicts. Pre-commit commit also should be doing in advance to migration changes: https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-13.0#howto

**Comment by rousseldenis** [comment]
@BenjaHe Do you mind if we switch on this #1020 instead as that one is green ?

**Comment by pedrobaeza** [comment]
No answer, so closing in favor of #1020

**Pull request closed without merging**
