### PR TITLE
[14.0] [MIG] sale_blanket_order

### PR DESCRIPTION
**Pull request by stananatanaela**
depends on web_action_conditionable

### CODE REVIEW

**Comment by stananatanaela** [comment]
Travis error is unrelated

**Review by jado95 — CHANGES_REQUESTED** [review]
Hi @stananatanaela, in sale_blanket_order_views, there is twice field `user_id`  and `company_id`

**Comment by LoisRForgeFlow** [comment]
Hi @stananatanaela could you have a look at https://github.com/OCA/sale-workflow/pull/1765 and include the improvements here?

**Comment by janikvonrotz** [comment]
@stananatanaela @LoisRForgeFlow I have added a new PR #1785 as this one seems stalled.

**Comment by janikvonrotz** [comment]
I've added some improvements on #1785 , which can be downstreamed to 13.0

**Comment by janikvonrotz** [comment]
Committed a bugfix on #1785

**Comment by LoisRForgeFlow** [comment]
@OCA/crm-sales-marketing-maintainers can you close this PR? it has been superseded as you can see in previous comments.

**Pull request closed without merging**
