### PR TITLE
[MIG] sale_triple_discount: Migration to 13.0 from 14.0

### PR DESCRIPTION
**Pull request by igallart**
The test fails due to the account_invoice_triple_discount module, so a fix should be made in that module.

TestSaleOrder.test_04_sale_order_triple_discount_invoicing
Traceback (most recent call last):
  File "/__w/sale-workflow/sale-workflow/sale_triple_discount/tests/test_sale_triple_discount.py", line 148, in test_04_sale_order_triple_discount_invoicing
    self.assertAlmostEqual(self.order.amount_total, invoice.amount_total)
AssertionError: 431.25 != 510.0 within 7 places

### CODE REVIEW

**Comment by leemannd** [comment]
Hello @rousseldenis @igallart the module is already migrated -> https://github.com/OCA/sale-workflow/commits/14.0/sale_triple_discount

**Comment by igallart** [comment]
Hi Denis, this module is to version 13. it is taken from V14.

**Comment by leemannd** [comment]
Hello @igallart I have been reading to quickly the title.

**Comment by rousseldenis** [comment]
> The test fails due to the account_invoice_triple_discount module, so a fix should be made in that module.
> 
> TestSaleOrder.test_04_sale_order_triple_discount_invoicing Traceback (most recent call last): File "/__w/sale-workflow/sale-workflow/sale_triple_discount/tests/test_sale_triple_discount.py", line 148, in test_04_sale_order_triple_discount_invoicing self.assertAlmostEqual(self.order.amount_total, invoice.amount_total) AssertionError: 431.25 != 510.0 within 7 places

@igallart How could you say that ? Could you try to fix ?

**Comment by igallart** [comment]
Hello, I think the invoice error is from that module account_invoice_triple_discount because if the sales order is made manually and then it is invoiced with the data from the test, the order is correct and it is the invoice that does not calculate it correctly.

**Review by ao-landoo — COMMENTED** [review]
It's not working correctly. I created a sale order where the product unit price is 60. I added discount of 20% and discount 2 of 10%. Taxes are 15%.
60 * 0.8 * 0.1 * 0.15 = 6.48 -> This is OK

I created an invoice from the sale order. The taxes on the invoice are 7.2 instead of 6.48.
This is because it's not considering discount2 and discount3 field values for the tax calculation
60 * 0.8 * 0.15 = 7.2 -> This is WRONG

**Comment by igallart** [comment]
> It's not working correctly. I created a sale order where the product unit price is 60. I added discount of 20% and discount 2 of 10%. Taxes are 15%. 60 * 0.8 * 0.1 * 0.15 = 6.48 -> This is OK
> 
> I created an invoice from the sale order. The taxes on the invoice are 7.2 instead of 6.48. This is because it's not considering discount2 and discount3 field values for the tax calculation 60 * 0.8 * 0.15 = 7.2 -> This is WRONG

In sale order is correct? So the error is exclusively in the invoices, right? This module is fine.

**Comment by ao-landoo** [comment]
I guess you're right. Could you force tests to be run again?

**Comment by igallart** [comment]
> I guess you're right. Could you force tests to be run aga

> I guess you're right. Could you force tests to be run again?

Done.

**Comment by ao-landoo** [comment]
A test is failing

> Traceback (most recent call last):
>   File "/__w/sale-workflow/sale-workflow/sale_triple_discount/tests/test_sale_triple_discount.py", line 148, in test_04_sale_order_triple_discount_invoicing
>     self.assertAlmostEqual(self.order.amount_total, invoice.amount_total)
> AssertionError: 431.25 != 510.0 within 7 places

**Comment by ao-landoo** [comment]
Run tests again please, it should be passing now

**Review by ao-landoo — APPROVED** [review]

**Comment by igallart** [comment]
> Run tests again please, it should be passing now

Now is right!

**Pull request closed without merging**
