### PR TITLE
[ADD] sale_coupon_criteria_multi_product: New module

### PR DESCRIPTION
**Pull request by chienandalu**
This modules allows to define complex rules on products to fulfill the conditions
of a coupon program, so for a given set of products we could define a minimum quantity
and another for others, being all those criterias mandatory for the coupon to be
applied.

To configure multiple product criterias:

1. Go to *Sales > Catalog > Coupon Programs* and select or create a new one.
2. On the *Coupon Criteria* field choose *Multi Product*.
3. The standard domain will be hidden and a criteria list will be shown.
4. Add as many criterias as needed for the desired promotion behavior.

In the list of criterias we can configure:

- Qty: The minimum quantity of products in the sale order to fulfill the condition.
- Products: The products that should be present to fulfill the condition.
- Repeat: The sum of quantities of any product in the criteria must be at least the one
  defined in the minimum quantities. If not set, the minimum quantity will be the number
  of products defined in the criteria, as all of them must be in the order to fulfill
  the condition.

Some examples:

| Qty |    Products    | Repeat |
|-----|----------------|--------|
|   1 | Prod A         |        |

A unit of Product A must be in the sale order.

| Qty |    Products    | Repeat |
|-----|----------------|--------|
|   2 | Prod B, Prod C |        |

A unit of Product B and Product C must be in the sale order.

| Qty |    Products    | Repeat |
|-----|----------------|--------|
|   3 | Prod D, Prod E | X      |

Either Product D or Product E or both must be in the sale order and the sum of their
quantities must be three.

Also note that all the defined criterias must be fulfilled or the program won't be
applied.

cc  @Tecnativa TT30849

please review @victoralmau @carlosdauden @CarlosRoca13

### CODE REVIEW

**Comment by pedrobaeza** [comment]
This is pending to create the new repo OCA/sale-promotion.

@sbidoul @simahawk @dreispt did you see the mail I put on contribute at odoo-community dot org?

**Review by CarlosRoca13 — APPROVED** [review]
LGTM :+1: Locally tested

**Comment by simahawk** [comment]
> This is pending to create the new repo OCA/sale-promotion.
> 
> @sbidoul @simahawk @dreispt did you see the mail I put on contribute at odoo-community dot org?

nope sorry, I missed it. Shall I create `OCA/sale-promotion`? If yes, can you initialize it?

**Comment by pedrobaeza** [comment]
Yes, if you create it, I can pre-fill it with the needed stuff (now it's easier thanks to copier template).

**Comment by simahawk** [comment]
There you go https://github.com/OCA/sale-promotion (PSC not set yet)

**Comment by pedrobaeza** [comment]
Thank you very much!

**Comment by pedrobaeza** [comment]
@chienandalu you can move now the pull request: https://github.com/OCA/sale-promotion

**Pull request closed without merging**
