### PR TITLE
[16.0][IMP] sale_discount_display_amount: Show total discount on sale report.

### PR DESCRIPTION
**Pull request by angelgarciadelachica**
This improvement is the same as the PRs https://github.com/OCA/sale-workflow/pull/2957 and https://github.com/OCA/sale-workflow/pull/3114 in v15.

[T-6001]

### CODE REVIEW

**Comment by angelgarciadelachica** [comment]
@HaraldPanten @ValentinVinagre

**Review by HaraldPanten — APPROVED** [review]

**Comment by Tisho99** [comment]
@HaraldPanten Can you merge now?

**Review by Tisho99 — APPROVED** [review]

**Review by ValentinVinagre — APPROVED** [review]
LGTM 👍🏻

**Pull request merged**
