### PR TITLE
[14.0][IMP] sale_by_packaging: Add min_sellable_qty on product

### PR DESCRIPTION
**Pull request by TDu**
This is a forward port of #1623 with some improvements and some unit tests added

### CODE REVIEW

**Review by ajaniszewska-dev — APPROVED** [review]
LG

**Review by sebalix — APPROVED** [review]

**Comment by rafaelbn** [comment]
Thank @TDu . Do you want to add test in line #L32 & L36? was not covered by tests. Not blocking at all! 😄

**Comment by TDu** [comment]
Last fixup for improving the code coverage.

**Comment by TDu** [comment]
I squashed the fixups.
@rafaelbn Test coverage improved :wink:

**Pull request merged**
