### PR TITLE
[13.0] Add sale_cutoff_time_delivery

### PR DESCRIPTION
**Pull request by simahawk**
Replace #1104

### CODE REVIEW

**Comment by simahawk** [comment]
@jbaudoux as per your comment here https://github.com/OCA/sale-workflow/pull/1104#pullrequestreview-390732343 if it's still valid I won't keep this blocked because it's an alpha module and we are using in it prod since quite some time now.
Let's discuss further improvements for another round.

**Review by jgrandguillaume — APPROVED** [review]
LGTM

**Review by TDu — APPROVED** [review]

**Comment by jbaudoux** [comment]
> @jbaudoux as per your comment here [#1104 (review)](https://github.com/OCA/sale-workflow/pull/1104#pullrequestreview-390732343) if it's still valid I won't keep this blocked because it's an alpha module and we are using in it prod since quite some time now.
> Let's discuss further improvements for another round.

Can you at least put a FIXME that the comparison should be in warehouse timezone and not UTC.

**Comment by simahawk** [comment]
> > @jbaudoux as per your comment here [#1104 (review)](https://github.com/OCA/sale-workflow/pull/1104#pullrequestreview-390732343) if it's still valid I won't keep this blocked because it's an alpha module and we are using in it prod since quite some time now.
> > Let's discuss further improvements for another round.
> 
> Can you at least put a FIXME that the comparison should be in warehouse timezone and not UTC.

done

**Review by jbaudoux — APPROVED** [review]

**Pull request merged**
