### PR TITLE
[14.0][IMP] sale_global_discount: improve README with reference to the one of base_global_discount

### PR DESCRIPTION
**Pull request by tafaRU**
Without this *Global Discounts* doesn't show up!

### CODE REVIEW

**Comment by pedrobaeza** [comment]
But this is already stated in the base module: https://github.com/OCA/server-backend/tree/14.0/base_global_discount#configuration

Maybe a note about seeing also the other README?

**Comment by tafaRU** [comment]
@pedrobaeza thanks for the review!
Do you think now can go well? I remai awaiting your confirmation before squashing.

**Comment by pedrobaeza** [comment]
Putting an absolute path will require a maintenance on each version. I think It's better to just say to see the configure section of the `base_global_discount` module.

**Comment by tafaRU** [comment]
@pedrobaeza done thanks

**Review by pedrobaeza — APPROVED** [review]

**Review by houssine78 — APPROVED** [review]

**Comment by houssine78** [comment]
Hi @pedrobaeza I think it ready to be merge. thanks

**Pull request merged**
