### PR TITLE
[IMP] sale_order_line_date: improving commitment_date tree column

### PR DESCRIPTION
**Pull request by dennybiasiolli**
allowing users to hide the column from the tree

### CODE REVIEW

**Review by len-foss — COMMENTED** [review]
AFAICT, optional="show" is not documented anywhere, that's interesting. 
Can you post a before/after screenshot for the feature, since it's a visual change?
(small nitpick, your commit would be an [IMP] not an [UPD])

**Comment by dennybiasiolli** [comment]
@len-foss changed commit message ;)

The `optional="show"` parameters allows to act in tree view columns in this way:

- always on, when not specified in tree view field

- default on, but hideable, when `optional="show"`

- default off, but showable, when `optional="hide"`

You can find a detailed explanation here: https://www.youtube.com/watch?v=UfWNwupq2CE
This PR allows users to hide the column `commitment_date` from the sale order lines for improving appearance of the table.

Before:
image


After:
image

**Review by len-foss — APPROVED** [review]
Thanks for the info!

**Review by rousseldenis — APPROVED** [review]
LGTM. Tested on runbot

**Review by bodedra — APPROVED** [review]

**Review by lmignon — APPROVED** [review]

**Pull request merged**
