### PR TITLE
[15.0] [MIG] sale_stock_delivery_address

### PR DESCRIPTION
**Pull request by JasminSForgeFlow**
Standard Migration
@ForgeFlow

### CODE REVIEW

**Review by LoisRForgeFlow — APPROVED** [review]
LGTM

**Review by LoisRForgeFlow — COMMENTED** [review]
Check CI, seems that dev status needs to be updated for the dependencies?

**Review by MiquelRForgeFlow — APPROVED** [review]

**Comment by LoisRForgeFlow** [comment]
Rebased, tests will pass once https://github.com/OCA/sale-workflow/pull/1982 get merged.

**Pull request merged**
