### PR TITLE
[MIG] sale_stock_picking_blocking: Migration to 14.0

### PR DESCRIPTION
**Pull request by jcoux**
Pulled the module in version 13.0 from https://github.com/OCA/sale-workflow/pull/1302

### CODE REVIEW

**Comment by rousseldenis** [comment]
@jcoux Could you rebase and fix 13.0 PR ? As soon that one is merged, we can move forward on this.

**Comment by jcoux** [comment]
> @jcoux Could you rebase and fix 13.0 PR ? As soon that one is merged, we can move forward on this.

Yes: on it!

**Review by tarbib — APPROVED** [review]
Functional approval :+1:

**Comment by jcoux** [comment]
Migration done: waiting merging of previous migration 13.0, then will rebase properly!

**Comment by jcoux** [comment]
Rebased on last version of 13.0 migration.
Ready for reviews!

**Review by damdam-s — APPROVED** [review]

**Pull request merged**
