### PR TITLE
[16.0][MIG] sale_stock_picking_note: Migration to 16.0

### PR DESCRIPTION
**Pull request by beagle-cloud**

### CODE REVIEW

**Review by ChristianSantamaria — APPROVED** [review]
LGTM 👍

**Comment by rafaelbn** [comment]
@moduon MT-3630

**Comment by rafaelbn** [comment]
@chienandalu would you like to review? 😄

**Review by fcvalgar — COMMENTED** [review]
Review

**Review by fcvalgar — APPROVED** [review]
Functional review.
LGTM, thank you @beagle-cloud.

image


image


image

**Review by rafaelbn — APPROVED** [review]
/ocabot merge patch

**Pull request merged**
