### PR TITLE
[13.0][MIG] sale_order_line_sequence

### PR DESCRIPTION
**Pull request by MiquelRForgeFlow**
Continuation of https://github.com/OCA/sale-workflow/pull/1026.

### CODE REVIEW

**Comment by MiquelRForgeFlow** [comment]
@rousseldenis how can apply https://github.com/OCA/sale-workflow/blob/12.0/.travis.yml#L23L40 to https://github.com/OCA/sale-workflow/blob/13.0/.github/workflows/test.yml#L36?

**Comment by rousseldenis** [comment]
> @rousseldenis how can apply https://github.com/OCA/sale-workflow/blob/12.0/.travis.yml#L23L40 to https://github.com/OCA/sale-workflow/blob/13.0/.github/workflows/test.yml#L36?

I think this should have been done through rebel_modules entry. I'll try to find out how.

**Comment by rousseldenis** [comment]
> > @rousseldenis how can apply https://github.com/OCA/sale-workflow/blob/12.0/.travis.yml#L23L40 to https://github.com/OCA/sale-workflow/blob/13.0/.github/workflows/test.yml#L36?
> 
> I think this should have been done through rebel_modules entry. I'll try to find out how.

Install copier locally https://github.com/OCA/oca-addons-repo-template

Then, call `copier update`and answer at the question about rebel_module_groups filling in your module.
I think that's all, jobs will take into account those ones.

**Review by rousseldenis — APPROVED** [review]
LGTM

**Review by LoisRForgeFlow — APPROVED** [review]
Tested, LGTM

**Comment by LoisRForgeFlow** [comment]
@rousseldenis good to merge?

**Pull request merged**
