### PR TITLE
[16.0][MIG] sale_substate

### PR DESCRIPTION
**Pull request by hildickethan**
Standard migration to 16.0

Depends on
  - https://github.com/OCA/server-ux/pull/569

### CODE REVIEW

**Comment by rousseldenis** [comment]
@hildickethan-S73 Thanks for this. When you have a dependency on another PR, you can reference it in a test-requirements.txt file in order to get tests running and allow reviewers to test it on runboat.

You can follow this guide : https://github.com/OCA/maintainer-tools/wiki/Use-temporary-reference%28s%29-to-another-pull-request%28s%29

**Comment by hildickethan** [comment]
> @hildickethan-S73 Thanks for this. When you have a dependency on another PR, you can reference it in a test-requirements.txt file in order to get tests running and allow reviewers to test it on runboat.

Good to know, runboat is working now

**Review by Reyes4711-S73 — APPROVED** [review]

**Comment by hildickethan** [comment]
@rousseldenis is this conflict with the test-requirements ok? should i rebase for it or should it not be in the main branch?

**Comment by rousseldenis** [comment]
> @rousseldenis is this conflict with the test-requirements ok? should i rebase for it or should it not be in the main branch?

@hildickethan-S73 Indeed, you should rebase as odoo-test-helper has been added in it

**Comment by hildickethan** [comment]
rebased without the test-requirements as base_substate was merged

**Review by rousseldenis — APPROVED** [review]
Code review

**Pull request merged**
