### PR TITLE
[13.0][MIG] sale_order_incoterm_place

### PR DESCRIPTION
**Pull request by JSeguiN97**
Migration to 13.0

### CODE REVIEW

**Review by rousseldenis — APPROVED** [review]
Code review

**Review by HaraldPanten — APPROVED** [review]

**Review by yostashiro — APPROVED** [review]
Functional test 👍

**Review by danimv5 — APPROVED** [review]
Functional review! LGTM!!

**Comment by brendapaniagua** [comment]
Functional review. LGTM!

**Pull request merged**
