### PR TITLE
[ADD] sale_stock_reconcile_valuation_kit

### PR DESCRIPTION
**Pull request by JordiBForgeFlow**
This module will try to reconcile the stock interim accounts associated with the sale of kits,
when the Anglo Saxon accounting is used and the inventory valuation of the products is automated.

When the customer invoice is posted, the system will attempt to reconcile the journal items associated with
interim accounts with the journal items associated with the stock moves related with components of the kit product
that was invoiced.

To do:

* [x]  Add tests

### CODE REVIEW

**Comment by JordiBForgeFlow** [comment]
@juanydforgeflow can you add tests, please?

**Comment by JordiBForgeFlow** [comment]
@AaronHForgeFlow Can you review?

**Comment by JuanyDForgeflow** [comment]
@JordiBForgeFlow I had to change the license for the test to work, is it ok?

**Comment by JordiBForgeFlow** [comment]
@JuanyDForgeflow It is ok.

**Review by AaronHForgeFlow — APPROVED** [review]
Functional tests, it works as specified

**Pull request merged**
