### PR TITLE
[14.0][FIX]sale_blanket_order: revert problematic changes

### PR DESCRIPTION
**Pull request by PicchiSeba**
Revert problematic commits that have been merged

### CODE REVIEW

**Comment by HekkiMelody** [comment]
When https://github.com/OCA/sale-workflow/pull/2925 was merged, it accidentally also contained changes from https://github.com/OCA/sale-workflow/pull/2927 that had not yet been approved.

Also the new module introduced by #2925 depends on #2927.

This PR reverts the commit of #2927 that was accidentally committed, and sets the new module introduced in #2925 as not installable until its dependency is properly merged.

**Comment by francesco-ooops** [comment]
> When #2925 was merged, it accidentally also contained changes from #2927 that had not yet been approved.
> 
> Also the new module introduced by #2925 depends on #2927.
> 
> This PR reverts the commit of #2927 that was accidentally committed, and sets the new module introduced in #2925 as not installable until its dependency is properly merged.

@pedrobaeza ok to proceed like this? sorry for the mistake.

**Pull request merged**
