### PR TITLE
[15.0][MIG]sale_product_set_layout

### PR DESCRIPTION
**Pull request by manuelregidor**
Depends on https://github.com/OCA/sale-workflow/pull/2040

### CODE REVIEW

**Comment by HaraldPanten** [comment]
@manuelregidor could you rebase?

**Comment by rousseldenis** [comment]
@manuelregidor If you took commit from https://github.com/OCA/sale-workflow/pull/1839, could you cherry-pick in order to keep authorship ? Thanks

**Comment by manuelregidor** [comment]
@rousseldenis Done

**Comment by ValentinVinagre** [comment]
> rousseldenis

@rousseldenis  now you will have to finish the pr 😜

**Review by ValentinVinagre — APPROVED** [review]
LGTM 👍🏻

**Review by HaraldPanten — APPROVED** [review]

**Comment by pedrobaeza** [comment]
Why not merging this module into the main one as there are no extra dependencies?

**Pull request merged**
