### PR TITLE
IMP sale_o_lot_select: set lot_id from sale_line_id instead of ctx (v7 inheriting)

### PR DESCRIPTION
**Pull request by bealdav**

### CODE REVIEW

**Review by sebastienbeau — APPROVED** [review]
LGTM code review.
This avoid losing cache by changing the context

**Review by mourad-ehm — APPROVED** [review]

**Comment by bealdav** [comment]
I have just rebased. I don't know if it'll be fixed

**Comment by bealdav** [comment]
Please @dreispt could you try again. Thanks

**Review by gurneyalex — APPROVED** [review]
LGTM, no test

**Pull request merged**
