### PR TITLE
[14.0][MIG] sale_quotation_number: Migration to 14.0

### PR DESCRIPTION
**Pull request by Vanneri**
Migration to 14.0

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Thanks for the contribution.

Please preserve commit history following technical method explained in https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-14.0.

If the jump is between several versions, you have to modify the source branch in the main command to accommodate it to this circumstance.

**Comment by Vanneri** [comment]
Is there any issue, hope i have followed the rule for branch an commit messages

**Comment by Vanneri** [comment]
> Is there any issue, hope i have followed the rule for branch an commit messages

**Comment by Vanneri** [comment]
I am closing it and re-do the process

**Pull request closed without merging**
