### PR TITLE
[16.0][MIG] sale_order_price_recalculation

### PR DESCRIPTION
**Pull request by CRogos**
supersede: #2605

Has anyone an idea what is wrong with the tests? Is this related to the hard disk swap outage?

### CODE REVIEW

**Comment by CRogos** [comment]
Has anyone an idea why this test is failing? When I run it locally the tests passes and also the module is working fine as far as I can say.

**Review by MohamedOsman7 — APPROVED** [review]
code & functional changes LGTM

**Comment by CRogos** [comment]
Is the recalculate price obsolete? When switching the price list, there is an update button: 
image

**Comment by CRogos** [comment]
@arleite , @rousseldenis could you review this migration?

**Comment by CRogos** [comment]
@arleite  can you also add yourself to the reviews?
image

**Review by andrel-exo — COMMENTED** [review]
LGTM

**Comment by CRogos** [comment]
@arleite. I should have been more precise. You have to select "approve", not "comment". 

Thank you.

**Review by andrel-exo — APPROVED** [review]

**Comment by CRogos** [comment]
@pedrobaeza could you merge?

**Comment by pedrobaeza** [comment]
This module is outdated after the integration of the feature in core, and if you want it for the description thing, it should be renamed IMO.

**Comment by CRogos** [comment]
The update price button in the standard is not always visible and there is not possibility to reset the description. But I agree this feature mostly adds some UI improvements. 

The functionality is not changed, so I do not understand why we should change the name... but make a suggestion?

**Comment by pedrobaeza** [comment]
I would maybe start from scratch a little module `sale_order_price_recalculation_visibility` with such function. And do you really use any time the reset description feature?

**Comment by CRogos** [comment]
While refactoring this module I've exactly asked this question to my sales guys and they said that they are missing something like that. There themes to be a use case for that... but I agree that there could be a more beautiful solutions like these buttons.

**Comment by pedrobaeza** [comment]
OK, you tell me then: should I press the button without thinking more?

**Comment by CRogos** [comment]
Yes please... anyone who has this module installed would be able to migrate to v16 without any functionality change. And Odoo has improved but does not fulfil the whole functionality. 

I agree that the module is now very small and maybe we can combine it with other functions in the future.

**Pull request merged**
