### PR TITLE
[13.0][MIG] sale_stock_delivery_address

### PR DESCRIPTION
**Pull request by JoanSForgeFlow**
**sale_stock_delivery_address** migration to v13.
Depends on:
- #1091 

cc ~ @ForgeFlow @LoisRForgeFlow

### CODE REVIEW

**Review by AaronHForgeFlow — APPROVED** [review]
:+1:  Functional test on local

**Review by rousseldenis — APPROVED** [review]
Code review

**Review by LoisRForgeFlow — APPROVED** [review]
tested on runbot, Works perfectly! :+1:

**Comment by LoisRForgeFlow** [comment]
@rousseldenis can you merge? :smile:

**Review by AdriaGForgeFlow — APPROVED** [review]
Code review :+1:

**Comment by LoisRForgeFlow** [comment]
@rousseldenis And can you try again with this one?

**Comment by LoisRForgeFlow** [comment]
Thank you!

**Pull request merged**
