### PR TITLE
[14.0][IMP] sale_automatic_workflow: Use with_company instead of user…

### PR DESCRIPTION
**Pull request by rousseldenis**
….company_id

### CODE REVIEW

**Comment by rousseldenis** [comment]
@Cedric-Pigeon @grindtildeath @acsonefho

**Review by acsonefho — APPROVED** [review]
Code LGTM!
But you have to be sure that into every following code (and more), `self.env.company` is used instead of `self.env.user.company_id`.

**Comment by rousseldenis** [comment]
> Code LGTM!
> But you have to be sure that into every following code (and more), `self.env.company` is used instead of `self.env.user.company_id`.

Of course, but that code is in Odoo...

**Comment by grindtildeath** [comment]
Looks legit :+1:

**Review by grindtildeath — APPROVED** [review]

**Pull request merged**
