### PR TITLE
10.0 mig sale packaging price

### PR DESCRIPTION
**Pull request by grauschnabel**
upgraded module to 10.0

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Please squash "OCA Transbot..." commits together and check Travis status.

**Comment by JayVora-SerpentCS** [comment]
@grauschnabel Can you please fix the conflicts ?

**Comment by rafaelbn** [comment]
Hi @grauschnabel ,

Please could you rebase?

Please for migration follow the Wiki https://github.com/OCA/maintainer-tools/wiki#migration

Thanks!

**Comment by rafaelbn** [comment]
As an example this was the migration from v8 to v9 https://github.com/OCA/sale-workflow/pull/302

**Comment by rousseldenis** [comment]
Closing this as it is very old and comments never attended. Please feel free to reopen it if needed

**Pull request closed without merging**
