### PR TITLE
[ADD] sale_numeric_step: new module for better selling on touch screens

### PR DESCRIPTION
**Pull request by yajo**
Together with https://github.com/OCA/web/pull/2694, this will improve a lot the sell process while using tablets or phones.

@moduon MT-4472

### CODE REVIEW

**Review by rafaelbn — APPROVED** [review]
👍🏼 

https://www.loom.com/share/2e2dfca4178341a292399b54e4c00212?sid=76413047-de74-4936-b35c-a8e8ab6e13f6

**Review by EmilioPascual — APPROVED** [review]

**Review by fcvalgar — APPROVED** [review]
LGTM, Thank you @yajo

**Review by Gelojr — APPROVED** [review]
LGTM Thanks @yajo 
@rafaelbn As I am not good at singing I leave it in the hands of professionals 😅. 
https://youtu.be/OIy8L_UoUKI?feature=shared

**Review by Shide — APPROVED** [review]

**Pull request merged**
