### PR TITLE
[10.0] [FIX] sale_triple_discounts: Fix tests

### PR DESCRIPTION
**Pull request by FFernandez-PlanetaTIC**
Because travis fails with error:

> 2019-08-06 15:33:30,184 5513 INFO ? odoo.sql_db: Connection to the database failed

### CODE REVIEW

**Comment by pedrobaeza** [comment]
It seems there's a problem with one test...

**Comment by FFernandez-PlanetaTIC** [comment]
@MPoch-PlanetaTIC, please, could you fix `sale_triple_discounts` tests here instead of in #909 , thanks!

**Comment by legalsylvain** [comment]
> It seems there's a problem with one test...

10.0 serie is broken since a big while.

image

**Comment by rafaelbn** [comment]
@FFernandez-PlanetaTIC This branch has conflicts that must be resolved, could you please review? we have been today fighting with travis in this branch, thanks!

**Comment by FFernandez-PlanetaTIC** [comment]
We are trying to fix `sale_triple_discounts` tests.

When we make the commit we will reopen this PR.

**Comment by rafaelbn** [comment]
Hi @FFernandez-PlanetaTIC , I think this test are fixed on https://github.com/OCA/sale-workflow/pull/889

**Comment by FFernandez-PlanetaTIC** [comment]
Thanks @rafaelbn , then this PR can be discarded

**Pull request closed without merging**
