### PR TITLE
[15.0]mig] sale_exception

### PR DESCRIPTION
**Pull request by damdam-s**
migration of `sale_exception` to v15

### CODE REVIEW

**Comment by damdam-s** [comment]
depends on https://github.com/OCA/server-tools/pull/2319

**Review by leemannd — APPROVED** [review]

**Review by florentx — APPROVED** [review]
Reviewed, still all good.

Now depend on migration of `base_exception` here: OCA/server-tools#2366

**Comment by hailangvn** [comment]
Good day, as https://github.com/OCA/server-tools/pull/2366 has been merged. Can this be merged as well?

**Review by nicomacr — APPROVED** [review]
👍🏻

**Comment by MiquelRForgeFlow** [comment]
@dreispt ping

**Pull request merged**
