### PR TITLE
[13.0][FIX] sale_order_product_recommendation: Sale order discount not applied. Helper to call all so line onchanges

### PR DESCRIPTION
**Pull request by sergio-teruel**
cc @Tecnativa

### CODE REVIEW

**Comment by rousseldenis** [comment]
@sergio-teruel Are you aware of https://github.com/OCA/server-tools/tree/13.0/onchange_helper ?

**Comment by pedrobaeza** [comment]
From v12, you don't need that module nor this trick. Create an instance of `test.Form` and it will do the same of `onchange_helper`.

**Review by HaraldPanten — APPROVED** [review]
Functional review. Seems to be OK 👍

**Comment by pedrobaeza** [comment]
With #1157 this is not needed

**Comment by pedrobaeza** [comment]
Closing as not needed.

**Pull request closed without merging**
