### PR TITLE
13.0 mig sale invoice policy

### PR DESCRIPTION
**Pull request by alexeirivera87**
hello,
module sale_invoice_policy migrated from v12 to v13
please, check if everything is ok

regards

### CODE REVIEW

**Comment by alexeirivera87** [comment]
Hi @ernestotejeda , please check this or comment with colleagues

**Review by rousseldenis — APPROVED** [review]
Code review

**Review by danimv5 — APPROVED** [review]
Functional review. LGTM

**Comment by brendapaniagua** [comment]
Functional review. LGTM!

**Pull request merged**
