### PR TITLE
[16.0][MIG]sale_sourced_by_line: Migration to 16.0

### PR DESCRIPTION
**Pull request by Fabiola-Auz**
Module dependency sale_procurement_group_by_line PR: https://github.com/OCA/sale-workflow/pull/2403#pullrequestreview-1458120472

### CODE REVIEW

**Review by mmequignon — APPROVED** [review]
LG.
Don't forget to drop the test dependency before merging.

**Review by celm1990 — APPROVED** [review]

**Review by hugo-cordoba — APPROVED** [review]
LGTM (Code + Functional Review)

> Captura de pantalla de 2023-06-06 13-05-01

> Captura de pantalla de 2023-06-06 13-05-51

**Comment by rousseldenis** [comment]
@Fabiola-Auz #2403 merged

**Comment by celm1990** [comment]
@rousseldenis can help with merge please?

**Comment by celm1990** [comment]
ping @rousseldenis

**Comment by ventor-ecosystem** [comment]
@rousseldenis @pedrobaeza ping

**Comment by celm1990** [comment]
@rousseldenis @pedrobaeza can somebody help me with this merge please?

**Comment by celm1990** [comment]
@pedrobaeza I see than error is caused by module `sale_order_general_discount_triple` because field `general_discount` is required without any default value.
https://github.com/OCA/sale-workflow/blob/fa8da86dba239cd98f0f95f3a0e1c5874c9957b7/sale_order_general_discount_triple/models/res_config_settings.py#L7C5-L14

Previously you disabled this module in the commit
https://github.com/OCA/sale-workflow/commit/9aadac128a383c3883605a381edf34577e806f72
How as resolve this issue?

**Comment by pedrobaeza** [comment]
That is also a mistake. The required should be removed.

**Comment by jappi00** [comment]
@pedrobaeza @celm1990 I would love to translate this to german for v16. Can we merge this? I think we have everything to merge the dependent PR.

**Comment by pedrobaeza** [comment]
I'm trying again to merge, but not sure if the situation is fixed:

/ocabot merge nobump

**Comment by jappi00** [comment]
Ok, to understand it right @pedrobaeza. The problem is that another module which is not a dependency of this have a problem? And because of this, we can't merge this module until #2297 gets reviewed and merged? Or do I understand something wrong?

**Comment by pedrobaeza** [comment]
Something has changed upstream or in dependencies outside this repo that turns it to red. That condition should be fixed by someone.

**Comment by celm1990** [comment]
> Something has changed upstream or in dependencies outside this repo that turns it to red. That condition should be fixed by someone.

@pedrobaeza please review this PR https://github.com/OCA/sale-workflow/pull/2779

**Comment by pedrobaeza** [comment]
Fix merged.

/ocabot merge nobump

**Comment by jappi00** [comment]
Thanks for the work @pedrobaeza and @celm1990 <3

**Pull request merged**
