### PR TITLE
[ADD] sale_order_product_recommendation_packaging_default: glue module

### PR DESCRIPTION
**Pull request by yajo**
This module extends the functionality of sale order product recommendations to support gathering and specifying product packaging and to allow you to input that info directly from the recommendations wizard.

To know how to use this module, follow the usage instructions of `sale_order_product_recommendation`.

If your database uses product packagings, you should be able to see and use 2 new columns in the recommendations wizard:

- *Packaging*
- *Packaging Qty.*

flameshot_2023-10-13_10-44

@moduon MT-3489

### CODE REVIEW

**Review by Shide — APPROVED** [review]
Code LGTM (approved once tests will be fixed)

**Comment by yajo** [comment]
Tests should be good now.

**Comment by yajo** [comment]
note: runboat was failing because of https://github.com/OCA/sale-workflow/issues/2725. I rebased this PR on top of 1ac7b2497d823048aeb8ce68938d85e289cd54c7, which was the latest commit with a successful runboat, before merging #2513.  It seems runboat resurrected now, so this can be reviewed functionally again.

**Review by fcvalgar — APPROVED** [review]
Functional review,

LGTM thank you @yajo 

image

**Pull request merged**
