### PR TITLE
[16.0][MIG] sale_automatic_workflow_payment_mode

### PR DESCRIPTION
**Pull request by florian-dacosta**
Standard Migration

### CODE REVIEW

**Comment by RodrigoBM** [comment]
@florian-dacosta sale_automatic_workflow is merged https://github.com/OCA/sale-workflow/pull/2281.

Can you rebase it?

Thanks

**Comment by florian-dacosta** [comment]
@RodrigoBM Done, thanks for the ping

**Comment by asierneiradev** [comment]
Hi @florian-dacosta !
Would it be possible for you to review the failed tests in order to speed up the migration?
Thank you very much

**Comment by florian-dacosta** [comment]
Hi @asierneiradev It seems it is a incompatibility of tests between `sale_automatic_workflow` and `account_payment_partner`

I believe `sale_automatic_workflow` tests should be refactored here https://github.com/OCA/sale-workflow/blob/16.0/sale_automatic_workflow/tests/test_multicompany.py#L123
Because default company is changed on the user, but since  v14, it is not the way to do this kind of stuff, I think it should be replace by `with_company` to change company of a user.

Sadly, I don't have time for now to work on this subject...

**Comment by florian-dacosta** [comment]
@asierneiradev here it is, I've fix the test compatibility between sale_automatic_workflow and account_payment_partner
Can you review please ?

**Review by asierneiradev — APPROVED** [review]

**Comment by asierneiradev** [comment]
> @asierneiradev here it is, I've fix the test compatibility between sale_automatic_workflow and account_payment_partner Can you review please ?

Approved!
Thank you very much for your time @florian-dacosta and for adapting the test compatibility.

@sbidoul @guewen ,
Can we push this migration?
Thank you very much

**Review by RodrigoBM — APPROVED** [review]

**Comment by omalbastin** [comment]
is there any plans to use account.payment.method.line instead of account.payment.method for the workflow?

**Pull request merged**
