### PR TITLE
[15.0][FIX] sale_elaboration, product_supplierinfo_for_customer_elaboration: Set elaboration note with a onchange instead of compute method

### PR DESCRIPTION
**Pull request by sergio-teruel**
cc @Tecnativa  TT50584

Use onchange method instead of compute because if any other data of any line force a recompute of all lines and the elaboration custom notes are reset.

ping  @carlosdauden @pilarvargas-tecnativa

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Why?

**Review by carlosdauden — APPROVED** [review]

**Comment by sergio-teruel** [comment]
If you read the chages the reason is explained

**Comment by pedrobaeza** [comment]
Yeah, but you should provide the explanation in the commit message/main comment of the PR, apart from the docstring of a file.

**Review by pilarvargas-tecnativa — APPROVED** [review]
:+1:

**Comment by sergio-teruel** [comment]
Ready

**Pull request merged**
