### PR TITLE
[13.0][MIG]sale_double_validation

### PR DESCRIPTION
**Pull request by Khalid-SerpentCS**
Once this module configured sales continue to create Sale orders just as normal.
If a review is required the SO will be set into the state "To Approve" when approved it will be moved into "Draft".

A sale order in "To approve" state will have a button "Approve" only visible to sales manager.

### CODE REVIEW

**Review by rousseldenis — APPROVED** [review]
Code review

**Review by marylla — CHANGES_REQUESTED** [review]
Hi there,
I made a functional review. I set the limit to 5000 USD and created a sale order with (more than) 5000 USD (incl. taxes). If I click "save", the "confirm"-Button disappears. But if I don't click "save", I could directly click "confirm" and the workflow wasn't blocked.
Can you check that please?
Thanks!

**Comment by alan196** [comment]
> Hi there,
> I made a functional review. I set the limit to 5000 USD and created a sale order with (more than) 5000 USD (incl. taxes). If I click "save", the "confirm"-Button disappears. But if I don't click "save", I could directly click "confirm" and the workflow wasn't blocked.
> Can you check that please?
> Thanks!

@marylla I make a PR https://github.com/OCA/sale-workflow/pull/1092 with the fix this issue

**Review by marylla — APPROVED** [review]
Since there was a PR made to fix the mentioned problem, I change my review state to 'approved'. :)

**Comment by rousseldenis** [comment]
@Khalid-SerpentCS Could you rebase and maybe solve pre-commit errors ?

**Comment by rousseldenis** [comment]
@Khalid-SerpentCS

**Comment by dreispt** [comment]
@Khalid-SerpentCS please fix the pre-commit messages. Thank you.

**Comment by dreispt** [comment]
@Khalid-SerpentCS pre-commit checks are failing. Can you please fix?

**Comment by Khalid-SerpentCS** [comment]
> pre-commit checks are failing

Hi @dreispt , I'm not able to generate the issue. pre-commit checks are not failing on my system. Please share more information so that i can generate the issue. Thanks

**Comment by mohamedhagag** [comment]
@dreispt should we merge this ?

**Comment by OpenCode** [comment]
@dreispt should we merge this ?

**Comment by hailangvn** [comment]
> > pre-commit checks are failing
> 
> Hi @dreispt , I'm not able to generate the issue. pre-commit checks are not failing on my system. Please share more information so that i can generate the issue. Thanks

@Khalid-SerpentCS , I can reproduce the issue by following code, assuming branch `Khalid-SerpentCS:13-MIG_sale_double_validation` is being checked out.
```
git merge origin/13.0
pre-commit run -a
```

**Review by hailangvn — APPROVED** [review]

**Comment by rousseldenis** [comment]
@Khalid-SerpentCS @dreispt This one will never be merged automatically as it is failing after rebased.

@Khalid-SerpentCS Could you rebase this ? Thanks

**Comment by rafaelbn** [comment]
Hello @Khalid-SerpentCS @dreispt if you want this merged as @rousseldenis said you should rebase https://github.com/OCA/sale-workflow/pull/1018#issuecomment-874013633

Also solve the CLA issue https://github.com/OCA/sale-workflow/pull/1018#issuecomment-1034890295

**Pull request closed without merging**
