### PR TITLE
[13.0][FIX] sale_stock_delivery_address: do not remove procurements not comming from a SO

### PR DESCRIPTION
**Pull request by LoisRForgeFlow**
For instance, MTO procurement chains are stopped due to this.

@ForgeFlow

### CODE REVIEW

**Review by AaronHForgeFlow — APPROVED** [review]
Makes sense :+1:

**Review by HaraldPanten — APPROVED** [review]
Small FIX. LGTM

**Review by rousseldenis — APPROVED** [review]
LGTM

**Comment by rousseldenis** [comment]
@LoisRForgeFlow Do you plan to add test ?

**Review by AdriaGForgeFlow — APPROVED** [review]

**Comment by LoisRForgeFlow** [comment]
@rousseldenis No, I don't

**Review by danimv5 — APPROVED** [review]
Functional review! LGTM

**Review by JordiBForgeFlow — APPROVED** [review]

**Pull request merged**
