### PR TITLE
[IMP] sale_exception: show menu only to Exception Rule Managers

### PR DESCRIPTION
**Pull request by ivantodorovich**

### CODE REVIEW

**Comment by pedrobaeza** [comment]
The updated form is not here

**Comment by ivantodorovich** [comment]
sorry, confused commit message with the one of base_exception. I'll force push it

**Comment by ivantodorovich** [comment]
This is ready to review. I've amended the commit message.

**Review by pedrobaeza — APPROVED** [review]

**Review by mourad-ehm — APPROVED** [review]

**Review by florian-dacosta — APPROVED** [review]

**Pull request closed without merging**
