### PR TITLE
[9.0][sale_procurement_group_by_line] fix singleton error

### PR DESCRIPTION
**Pull request by JordiBForgeFlow**
This PR fixes a singleton error.

### CODE REVIEW

**Comment by JordiBForgeFlow** [comment]
@lreficent @gmeficent can you check?

**Review by LoisRForgeFlow — APPROVED** [review]
:+1:

**Comment by JordiBForgeFlow** [comment]
@mreficent can you review?

**Comment by JordiBForgeFlow** [comment]
Fixed in https://github.com/OCA/sale-workflow/pull/434

**Pull request closed without merging**
