### PR TITLE
[15.0] [MIG] product_supplierinfo_for_customer_elaboration: Migration to 15.0

### PR DESCRIPTION
**Pull request by CarlosRoca13**
cc @Tecnativa TT37689

This module depends of this PR: https://github.com/OCA/sale-workflow/pull/2204

please @victoralmau @sergio-teruel review this

### CODE REVIEW

**Comment by victoralmau** [comment]
Please, can you rebase?

**Comment by CarlosRoca13** [comment]
Done! @victoralmau

**Review by victoralmau — APPROVED** [review]
Code review OK

**Review by ghost — APPROVED** [review]

**Comment by pedrobaeza** [comment]
/ocabot migration product_supplierinfo_for_customer_elaboration
/ocabot merge nobump

**Pull request merged**
