### PR TITLE
[15.0][FIX] sale_stock_secondary_unit: Fix test, second qty manage qty done

### PR DESCRIPTION
**Pull request by sergio-teruel**
cc @Tecnativa 

ping   @carlosdauden @CarlosRoca13 

depends on:
- [x] https://github.com/OCA/stock-logistics-warehouse/pull/1606 (https://github.com/OCA/stock-logistics-warehouse/pull/1606/commits/7993a5684ff048ea5e602bd7d4f81697483f0618)

### CODE REVIEW

**Review by pedrobaeza — APPROVED** [review]
Let's fast track it:

/ocabot merge patch

**Comment by pedrobaeza** [comment]
@sergio-teruel it seems there's still an error:

```
2023-11-27 10:47:06,924 624 ERROR odoo odoo.addons.sale_stock_secondary_unit.tests.test_sale_stock_secondary_unit: FAIL: TestSaleStockOrderSecondaryUnit.test_stock_move_line_secondary_unit
Traceback (most recent call last):
  File "/__w/sale-workflow/sale-workflow/sale_stock_secondary_unit/tests/test_sale_stock_secondary_unit.py", line 92, in test_stock_move_line_secondary_unit
    self.assertEqual(picking.move_line_ids.secondary_uom_qty, 0.0)
AssertionError: 5.0 != 0.0
```

**Comment by sergio-teruel** [comment]
See the depends of other PR

**Review by chienandalu — APPROVED** [review]

**Pull request merged**
