### PR TITLE
[15.0][MIG] sale_order_revision

### PR DESCRIPTION
**Pull request by CRogos**
Followup of https://github.com/OCA/sale-workflow/pull/2275
- Renamed test_requirements
- removed oca_requirements
- squashed commits

@simahawk @grindtildeath @cyrilmanuel @leemannd

### CODE REVIEW

**Review by rousseldenis — APPROVED** [review]
Code review

**Review by leemannd — APPROVED** [review]

**Comment by CRogos** [comment]
@pedrobaeza can you merge this?

**Pull request merged**
