### PR TITLE
[MIG] sale_order_digitized_signature: Migration to 11.0

### PR DESCRIPTION
**Pull request by cubells**
Standard migration

Depends on https://github.com/OCA/web/pull/1257

cc @Tecnativa

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Please add oca_dependencies.txt with `web` repository.

**Comment by kittiu** [comment]
@cubells 
I see error is something to do with sale_order_invoicing_finished_task
Have you get latest version of OCA:11.0 before pushing?
Also, would you squash your commit into 1 commit.

**Comment by cubells** [comment]
@kittiu Ok, I'll review

**Comment by cubells** [comment]
I'll close this pr because I ain't enough permission in this repo.

@kittiu I've created this one: https://github.com/OCA/sale-workflow/pull/854

**Pull request closed without merging**
