### PR TITLE
[15.0] sale_automatic_workflow: pre-migrate, not installable

### PR DESCRIPTION
**Pull request by yankinmax**
Just porting the module as-is from 14.0 to ease migration review. Real migration coming soon in another PR.

**EDITED**

### CODE REVIEW

**Comment by yankinmax** [comment]
@simahawk can we merge this PR to start the migration and have clean commits history for migration?

**Comment by rousseldenis** [comment]
> @simahawk can we merge this PR to start the migration and have clean commits history for migration?

@yankinmax  Unfortunately this is not the normal flow for migration.

You can read the migration guide here : https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-15.0

A pre-migration is unuseful. You can create a WIP PR (or keep this) and work on it. Then, when it's ready, just warn here.

**Comment by yankinmax** [comment]
@rousseldenis for me is ok to follow guidelines, I'll close this one

**Comment by simahawk** [comment]
@rousseldenis sorry but I disagree. A pre-migration is very useful because it reduces the noise for big PRs.
We've done this in several cases especially the ones including refactoring.
The "normal flow" does not prevent this and as far as the work is properly documented in both PRs I don't see what's the problem with this approach when everyone is aware.

**Comment by yankinmax** [comment]
should we reopen it and merge or standard workflow?

**Comment by rousseldenis** [comment]
> @rousseldenis sorry but I disagree. A pre-migration is very useful because it reduces the noise for big PRs. We've done this in several cases especially the ones including refactoring. The "normal flow" does not prevent this and as far as the work is properly documented in both PRs I don't see what's the problem with this approach when everyone is aware.

Mmmh, yes I see.

> when everyone is aware.

Should have been explicitly said in PR description (why done, maybe a plan for which refactor, ...). Just 'pre-migrate' is a little bit too arsh.

**Comment by yankinmax** [comment]
@rousseldenis @simahawk I see the point, sorry for misleading description.

**Comment by simahawk** [comment]
> Should have been explicitly said in PR description (why done, maybe a plan for which refactor, ...). Just 'pre-migrate' is a little bit too arsh.

Wording improved. As soon as this one is merged the migration PR will be opened.

**Comment by rousseldenis** [comment]
@simahawk This digs a problem we solved in other repos. The problem of creating void main branches and not from preceding one. I'm from far to change that flow in OCA for years. That would avoid too long commit history in migration PR's and duplicate commits with different sha in the repo. But that's another debate.

**Comment by simahawk** [comment]
> @simahawk This digs a problem we solved in other repos. The problem of creating void main branches and not from preceding one. I'm from far to change that flow in OCA for years. That would avoid too long commit history in migration PR's and duplicate commits with different sha in the repo. But that's another debate.

Yeah, I'm w/ you on this :smile:

**Comment by simahawk** [comment]
@yankinmax pls open the migration one :pray:

**Pull request merged**
