### PR TITLE
8.0 add sale_documents_comments

### PR DESCRIPTION
**Pull request by eLBati**
moving from https://github.com/OCA/sale-workflow/pull/290

### CODE REVIEW

**Review by rafaelbn — APPROVED** [review]
Tested in runbot 👍

**Review by AaronHForgeFlow — APPROVED** [review]
:+1: Functional test

**Review by chienandalu — APPROVED** [review]

**Review by pedrobaeza — CHANGES_REQUESTED** [review]
Please avoid plurals on the name

**Comment by eLBati** [comment]
@pedrobaeza in this case I think plural is more appropriate, because the purpose of the module is to involve several documents with several comments

**Comment by pedrobaeza** [comment]
Well, semantics shouldn't enforce this, as if not, all Odoo will be full of plurals: `sales.order` instead of `sale.order` and so on. The name itself of the module should be `sales_documents_comments` for being correct. I suggest a more neutral name `sale_comment_propagation`

**Comment by eLBati** [comment]
@pedrobaeza ok, done

**Review by pedrobaeza — APPROVED** [review]

**Pull request merged**
