### PR TITLE
[17.0][MIG] sale_quotation_number

### PR DESCRIPTION
**Pull request by Deriman-Alonso**
Standart migration.

### CODE REVIEW

**Comment by MohamedOsman7** [comment]
@Deriman-Alonso Code review LGTM, some commits could be also squashed, so i can test the functionality through the runboat.
2024-07-10 15_58_03- 17 0 MIG  sale_quotation_number by Deriman-Alonso · Pull Request #3099 · OCA_s

**Comment by rousseldenis** [comment]
@Deriman-Alonso Could you check tests ?

**Comment by HaraldPanten** [comment]
Migration superseded by https://github.com/OCA/sale-workflow/pull/3247

**Pull request closed without merging**
