### PR TITLE
Skip exceptions for consumable product

### PR DESCRIPTION
**Pull request by lepistone**

### CODE REVIEW

**Comment by lepistone** [comment]
I added the label WIP because I have to update existing tests that were passing because of a bug: the `_is_make_to_stock` method was never called if a product was defined.

**Comment by lepistone** [comment]
Actually the old integration test is fine, the bug was in `_is_make_to_stock` that as I said was almost never called (bug introduced by yours truly).

This needs review then.

**Comment by gurneyalex** [comment]
Do you think this deserves a backport to 7.0?

**Comment by gurneyalex** [comment]
:+1:

**Comment by jgrandguillaume** [comment]
:+1:

**Pull request merged**
