### PR TITLE
[16.0][MIG] sale_order_warn_message: Migration to 16.0

### PR DESCRIPTION
**Pull request by manuelregidor**
Supersedes: https://github.com/OCA/sale-workflow/pull/2610

### CODE REVIEW

**Comment by rousseldenis** [comment]
@manuelregidor Could you please review #2610 instead ?

**Comment by HaraldPanten** [comment]
@rousseldenis I'm not sure if #2610 is going to be continued. Remember that it was you who had to rebase. This one is going to be continued.

Can we continue in this one?

**Comment by HaraldPanten** [comment]
On the other hand, we're keeping more commit history, etc. I think Manuel's one is going to be better.

**Review by HaraldPanten — APPROVED** [review]
Functional review in local environment, as it seems that runboat is being a little bit picky these days.

@pedrobaeza @rousseldenis do you mind having a quick look here?

THX

**Review by pedrobaeza — APPROVED** [review]
@manuelregidor please remember to put a proper PR title

/ocabot merge nobump

**Pull request merged**
