### PR TITLE
[17.0][MIG] sale_discount_display_amount: Migration to 17.0

### PR DESCRIPTION
**Pull request by FSchiepers**
This version adds the possibility to choose whether the discount is calculated based on the non-taxed subtotal or the taxed total, see: https://github.com/OCA/sale-workflow/issues/2813

### CODE REVIEW

**Comment by rousseldenis** [comment]
@FSchiepers Thanks for this. Could you follow this migration guide ? https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-17.0#technical-method-to-migrate-a-module-from-160-to-170-branch

You should respect commit history.

**Comment by FSchiepers** [comment]
The guide is not complete, when I try to make a pull request I get a github error.

**Pull request closed without merging**
