### PR TITLE
fix installation of sale_cancel_reason to be compatible with sale_stock

### PR DESCRIPTION
**Pull request by yvaucher**
Trying to fix install issue to restore tests

https://github.com/OCA/sale-workflow/issues/13

### CODE REVIEW

**Comment by guewen** [comment]
My guess:

As soon as `sale_stock` is installed (installed as dependency for another module), it fails to install because it contains:

```
                    <xpath expr="//button[@name='action_cancel']" position="after">
                        <button name="ship_cancel" states="shipping_except" string="Cancel Order"/>
                    </xpath>

```

And the button can't be found with that name.

**Comment by guewen** [comment]
An idea: instead of changing the name of the button, hide it and create a new one for the cancellation reason. (but it may be confusive if other moduls want to modify other attributes on the button such as the `states`!)

**Comment by yvaucher** [comment]
You are right sale_stock fails because this module change the name.

I worked previously because this module was inheriting from sale_stock.

**Comment by yvaucher** [comment]
at least sale_validity now installs

Other errors can be fixed in other PR

**Comment by guewen** [comment]
Thanks!
The build fails but for another module... 

:+1:

**Comment by rvalyi** [comment]
:+1:  LGTM

**Comment by pedrobaeza** [comment]
:+1: As stated, this PR solves the problem with sale_validity.

Let's merge it and make another PR for the following problem.

**Pull request merged**
