### PR TITLE
Sales Analysis by cancellation reason

### PR DESCRIPTION
**Pull request by sp-jamotion**
sale_cancel_reason: Add cancellation reason group and filter attributes to sale.report view as well as sale.order tree view,
Add german translation for new fields, Fix typos in original german translation

### CODE REVIEW

**Comment by renzo1974** [comment]
I have checked the code and the function also. Both are okay.

**Review by chienandalu — CHANGES_REQUESTED** [review]
Please, add README.rst (https://github.com/OCA/maintainer-tools/blob/master/template/module/README.rst) and fix Travis

**Comment by rousseldenis** [comment]
@sp-jamotion Is this still relevant? As no activity, it will be closed soon.

**Comment by rousseldenis** [comment]
Closing as no activity

**Pull request closed without merging**
