### PR TITLE
[MIG] sale_order_line_input: Migration to 14.0

### PR DESCRIPTION
**Pull request by Harrycodist**

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Thanks for the contribution.

Please preserve commit history following technical method explained in https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-14.0.

If the jump is between several versions, you have to modify the source branch in the main command to accommodate it to this circumstance.

**Review by flotho — APPROVED** [review]
tested on runbot
except @pedrobaeza great recommendations LGTM

**Comment by bealdav** [comment]
Hi @Harrycodist thanks to port this clever module in v14.
I've done a module sale_line_partner which depends on it.
Do you plan to work on this PR in next days ?

Thanks for your answer

**Comment by francesco-ooops** [comment]
> Hi @Harrycodist thanks to port this clever module in v14. I've done a module sale_line_partner which depends on it. Do you plan to work on this PR in next days ?
> 
> Thanks for your answer

I tried unsuccessfully to coordinate with @Harrycodist in order to complete the porting, and I think if you want to do it you are more than welcome to do it :)

**Comment by bealdav** [comment]
> I tried unsuccessfully to coordinate with @Harrycodist in order to complete the porting, and I think if you want to do it you are more than welcome to do it :)

supersed by #1837

**Comment by bealdav** [comment]
@pedrobaeza I don't know if there is a way with ocabot to automatically to make an automatic PR retrieving commits from source branch to target one ? Have to specify organisation of the new branch.
What do you think ?

**Comment by pedrobaeza** [comment]
Not with ocabot. Check https://github.com/OCA/maintainer-tools/pull/504

**Comment by pedrobaeza** [comment]
Also check module-migrator library

**Pull request closed without merging**
