### PR TITLE
[13.0][backport] sale_automatic_workflow_job

### PR DESCRIPTION
**Pull request by damdam-s**
backport of #2054 to v13

### CODE REVIEW

**Comment by rousseldenis** [comment]
@damdam-s There is already https://github.com/OCA/sale-workflow/pull/1253

Could you ask author to continue here or review it ?

**Comment by rousseldenis** [comment]
@kittiu

**Comment by damdam-s** [comment]
@rousseldenis I saw it but the v15 is more advanced and there is much less things to fix with backporting than fixing the existing one...
Therefore, the mentionned PR has no activity since more than 6 months.

**Comment by rousseldenis** [comment]
> @rousseldenis I saw it but the v15 is more advanced and there is much less things to fix with backporting than fixing the existing one...
> Therefore, the mentionned PR has no activity since more than 6 months.

I agree. The good behaviour is to ping the author in the original PR to ask if we can supersedes. This in order to avoid duplicates (so much in OCA...)

**Comment by damdam-s** [comment]
I usually use the "good behaviour" policy ;) 
For this specific one, no moves for a (very) long time and I tought it would cost less effort to backport. My bad on this one.

If this duplicate bothers, I can close it upon request.

**Comment by rousseldenis** [comment]
> I usually use the "good behaviour" policy ;) For this specific one, no moves for a (very) long time and I tought it would cost less effort to backport. My bad on this one.
> 
> If this duplicate bothers, I can close it upon request.

No, I think you're on a good way. Just fixing tests. I will close the other one.

**Review by jcoux — APPROVED** [review]
I rebased, fixed travis and squashed.
Approved :+1:

**Review by yankinmax — APPROVED** [review]

**Pull request merged**
