### PR TITLE
12.0 mig sale order priority

### PR DESCRIPTION
**Pull request by daramousk**

### CODE REVIEW

**Comment by daramousk** [comment]
@rousseldenis Perhaps you can take a look in these travis issues as well.

**Review by marylla — CHANGES_REQUESTED** [review]
Hi @daramousk 
I started a functional review and I ran into an exception.

I created a new sale order. When I was about to add a new sale order line by choosing a product, I got this:

<pre>
Odoo Server Error
Traceback (most recent call last):
  File "/.repo_requirements/odoo/odoo/api.py", line 1049, in get
    value = self._data[key][field][record._ids[0]]
KeyError: <odoo.models.NewId object at 0x7febcc1f8c18>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/.repo_requirements/odoo/odoo/fields.py", line 989, in __get__
    value = record.env.cache.get(record, self)
  File "/.repo_requirements/odoo/odoo/api.py", line 1051, in get
    raise CacheMiss(record, field)
odoo.exceptions.CacheMiss: ('sale.order(<odoo.models.NewId object at 0x7febcc1f8c18>,).priority', None)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/.repo_requirements/odoo/odoo/http.py", line 656, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/.repo_requirements/odoo/odoo/http.py", line 314, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/.repo_requirements/odoo/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/.repo_requirements/odoo/odoo/http.py", line 698, in dispatch
    result = self._call_function(**self.params)
  File "/.repo_requirements/odoo/odoo/http.py", line 346, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/.repo_requirements/odoo/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/.repo_requirements/odoo/odoo/http.py", line 339, in checked_call
    result = self.endpoint(*a, **kw)
  File "/.repo_requirements/odoo/odoo/http.py", line 941, in __call__
    return self.method(*args, **kw)
  File "/.repo_requirements/odoo/odoo/http.py", line 519, in response_wrap
    response = f(*args, **kw)
  File "/home/odoo/OCB-12.0/addons/web/controllers/main.py", line 962, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/home/odoo/OCB-12.0/addons/web/controllers/main.py", line 954, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/.repo_requirements/odoo/odoo/api.py", line 759, in call_kw
    return _call_kw_multi(method, model, args, kwargs)
  File "/.repo_requirements/odoo/odoo/api.py", line 746, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/.repo_requirements/odoo/odoo/models.py", line 5516, in onchange
    for name in nametree
  File "/.repo_requirements/odoo/odoo/models.py", line 5517, in <listcomp>
    if name not in done and snapshot0.has_changed(name)
  File "/.repo_requirements/odoo/odoo/models.py", line 5419, in has_changed
    return self[name] != record[name]
  File "/.repo_requirements/odoo/odoo/models.py", line 5120, in __getitem__
    return self._fields[key].__get__(self, type(self))
  File "/.repo_requirements/odoo/odoo/fields.py", line 995, in __get__
    self.determine_draft_value(record)
  File "/.repo_requirements/odoo/odoo/fields.py", line 1117, in determine_draft_value
    self._compute_value(record)
  File "/.repo_requirements/odoo/odoo/fields.py", line 1051, in _compute_value
    getattr(records, self.compute)()
  File "/home/odoo/build/OCA/sale-workflow/sale_order_priority/models/sale.py", line 42, in _compute_priority
    order.priority = max([x for x in priority if x]) or '1'
ValueError: max() arg is an empty sequence
</pre>

Can you check this please?

**Comment by marylla** [comment]
Thank you for fixing it. The exception is gone. :)
My next problem is that I can set the priority for the entire sale order but not for the sale order lines because it is in inline-editing-mode and there is no column to set the priority.

**Comment by MiquelRForgeFlow** [comment]
@daramousk will you still work on this PR?

**Comment by daramousk** [comment]
Sure, I will take care of this tomorrow.

**Comment by MiquelRForgeFlow** [comment]
@daramousk could you rebase and squash your commits?

**Comment by flotho** [comment]
Hi @MiquelRForgeFlow , AFAICS, travis failed on other modules.
Regarding the squashing part any options in Github that allow to choose this option in the PR? Gitlab has this kind of options

**Review by flotho — APPROVED** [review]
Tested on runbot,
Both list view an dform view are Ok for sale order lines.
Priority is passed to pikcings !
LGTM

**Comment by rousseldenis** [comment]
@daramousk I'm fixing travis linting. Please rebase when #1322 is merged

**Comment by MiquelRForgeFlow** [comment]
https://github.com/OCA/sale-workflow/pull/1322 is merged.

**Comment by flotho** [comment]
@daramousk , please rebase.
Thanks

**Comment by daramousk** [comment]
@rousseldenis @MiquelRForgeFlow @flotho this should be ready

**Comment by marylla** [comment]
Hi again,
I made a new functional review and maybe I am petty here but:

If I add two sale order lines with different priorities (without saving in between), the order lines both get the same priority after saving. 
I know, it's nice to set the priority on order level so that all order line automatically get this priority, but if I want them to have different priorities I have to edit the lines again after saving.
Can we avoid this somehow?

Before saving:
before_saving

After saving:
after_saving

If this is really the desired behavior, I will change my review state of couse but maybe you @daramousk can think about it?

**Comment by AaronHForgeFlow** [comment]
Hi @marylla and @daramousk as far as I can see, the behavior in version 10.0 is the same as here. So actually this migration is not removing any feature.
From my side, it is ok like it is. Perhaps having different priorities in sale lines could be a nice feature, but I understand that is not the original intention.

**Review by AaronHForgeFlow — APPROVED** [review]

**Review by MiquelRForgeFlow — APPROVED** [review]
LGTM, the same @AaronHForgeFlow said.

**Review by marcelsavegnago — APPROVED** [review]

**Review by HaraldPanten — APPROVED** [review]

**Pull request merged**
