### PR TITLE
[15.0][MIG] sale_order_invoicing_finished_task: Migration to 15.0

### PR DESCRIPTION
**Pull request by cesar-tecnativa**
@Tecnativa TT37721

### CODE REVIEW

**Comment by cesar-tecnativa** [comment]
@carlosdauden Could you please review this?

**Comment by cesar-tecnativa** [comment]
@pedrobaeza  Could you please review this?

**Comment by cesar-tecnativa** [comment]
@LudLaf could you review this?

**Comment by cesar-tecnativa** [comment]
@CarlosRoca13 please review

**Review by CarlosRoca13 — APPROVED** [review]
LGTM :+1:

**Comment by LudLaf** [comment]
Some changes aren't reflected in this module's description (v15).

**Comment by cesar-tecnativa** [comment]
@pedrobaeza please review

**Comment by LudLaf** [comment]
Readme information updated.

@cesar-tecnativa, please review.

**Comment by pedrobaeza** [comment]
@cesar-tecnativa please take into account #2148

**Comment by CarlosRoca13** [comment]
I made the cherry pick to add the commit with the fix @pedrobaeza

**Pull request merged**
