### PR TITLE
[16.0][ADD] sale_order_product_picker: New module to easy manage sale orders for salesmen

### PR DESCRIPTION
**Pull request by CarlosRoca13**
cc @Tecnativa TT45382

ping @sergio-teruel @carlosdauden

### CODE REVIEW

**Comment by CarlosRoca13** [comment]
The options cannot be deselected because this PR https://github.com/odoo/odoo/pull/140544 has not been merged.

**Comment by pedrobaeza** [comment]
Do a rebase for triggering a runboat build now that the Odoo PR is merged.

**Comment by CarlosRoca13** [comment]
Done

**Review by Shide — APPROVED** [review]

**Review by yajo — APPROVED** [review]
Code review. Couldn't test on runboat because it's down.

**Review by rafaelbn — APPROVED** [review]
Functional tested in runboat 👍🏼 

/ocabot merge patch

**Pull request merged**
