### PR TITLE
[15.0][MIG] sale_resource_booking: Migration to version 15.0

### PR DESCRIPTION
**Pull request by stefan-tecnativa**
cc @Tecnativa TT41022

@chienandalu @ernestotejeda please review!

This PR depends on: https://github.com/OCA/calendar/pull/89

### CODE REVIEW

**Review by chienandalu — COMMENTED** [review]
Can you add a temporary commit with the dependency PR?

**Review by ernestotejeda — APPROVED** [review]

**Review by chienandalu — APPROVED** [review]
Tested :+1: 

Please rebase and drop de deps commit

**Pull request merged**
