### PR TITLE
[16.0][IMP] sale_tier_validation: simplify tests

### PR DESCRIPTION
**Pull request by bosd**
Simplify the tests, IMO no need to run the tests twice.

### CODE REVIEW

**Comment by pedrobaeza** [comment]
There should be a reason for executing it post install, so instead of removing the tag, just remove the at_install tag.

**Comment by bosd** [comment]
what is the reason for this module to run test at post_install?

I went trough all the tier_validation modules across the repos. It looked random, some where at install other at post install.

Odoo defaults to at_install.
In that case no tag is needed. 


As of this module. In the migration to v16 the `-at_install` got removed.
W/o any comment about reason..
Making the tests run twice

**Review by Dranyel-Bosd — APPROVED** [review]
LGTM :+1:

**Comment by pedrobaeza** [comment]
Then please re-add `-at_install` for keeping the conditions in previous version. A possible reason is if there's any invoice creation involved, that the only way to assure that the chart template is loaded is to do it post-load.

**Review by rousseldenis — APPROVED** [review]
Makes sense

**Pull request merged**
