### PR TITLE
[9.0] [NEW] sale_double_validation

### PR DESCRIPTION
**Pull request by yvaucher**
Double validation for sale
==========================

This module adds an option to enable two steps validation.

When a minimal amount is reached on a Sale order, if a salesman confirm the sale.
The sale order will be set to "To approve" state and will require a Sales manager
to Approve it.

This module is base on the purchase option for two levels validation in module `purchase`.

### CODE REVIEW

**Review by LoisRForgeFlow — COMMENTED** [review]
The following error raises when trying to save a new sale.order in runbot:
image

The field <code>product_attribute_value_ids</code> is created in another module though (<a href="https://github.com/OCA/sale-workflow/blob/9.0/sale_order_variant_mgmt/models/sale_order.py#L17">here</a>).

Code review: :+1:

**Comment by LoisRForgeFlow** [comment]
The  :red_circle: runbot is due to this issue https://github.com/OCA/sale-workflow/issues/420.

**Comment by guewen** [comment]
~~Superseeded by #443~~ #443 is for 10.0, this one for 9.0

**Comment by rafaelbn** [comment]
Rebuilding for testing, now runbot is red, let's see

**Review by aming27 — COMMENTED** [review]
Waiting for rebuild in order to test the module

**Review by chienandalu — CHANGES_REQUESTED** [review]
Runbot is up. I couldn't reproduce the expected behaviour.

**Review by grindtildeath — APPROVED** [review]
As this was migrated to 12.0 and is already merged for a newer version, I guess the original PR should be merged as well

**Review by rafaelbn — APPROVED** [review]
:+1:

**Pull request merged**
