### PR TITLE
[16.0][MIG]sale_validity_auto_cancel: Migration to 16.0

### PR DESCRIPTION
**Pull request by RogerSans**
Standard migration
T-6193

@HaraldPanten 
@ValentinVinagre 
@Jaimermaccione

### CODE REVIEW

**Review by Jaimermaccione — CHANGES_REQUESTED** [review]
@RogerSans Checked the functionality in runboat, and it works perfectly. However, I noticed that the README is still outdated and does not include the new feature added in **v17**. I suggest adding this feature description to the README, as it’s now part of this backport as well. 

Just to note, this change in the README is also not present in v17.

Below is a proposal for the README text. I’ve framed it as a change to emphasize that it’s not present in previous versions, but if it’s more common to just include it without highlighting the change, you can adjust the wording accordingly. 

Here’s the text for the README:


---

## Sale Validity Auto-Cancel

This module adds a scheduled action that automatically cancels quotations after their expiration date.

**Added starting from v16**: A checkbox has been added in the contact form under the **Sales&Purchase** tab. This checkbox is selected by default and controls whether quotations related to that contact will be automatically canceled. If unchecked, the scheduled action will not cancel quotations for that specific contact, allowing more control over the auto-cancellation process on a per-contact basis.

A company setting can also be modified to decide how many days after the expiration date the quotations are automatically canceled.

### Configuration

1. Go to the menu **Sales > Configuration > Settings**.
2. In the **Quotations & Sales** section, set the "Auto-cancel expired quotations after X days" parameter to define how many days after the expiration date the quotations will be canceled automatically.
3. Additionally, open the **contact form** for any customer and under the **Sales&Purchase** tab, you will see the checkbox **Auto-cancel Quotations**. This checkbox is checked by default, meaning the system will automatically cancel expired quotations for this contact. You can uncheck it if you do not want the scheduled action to cancel quotations for that specific contact.

### Usage

- By default, the scheduled action "Cancel Expired Quotations" is not enabled to allow initial configuration of the auto-cancel period in days.
- Once enabled, the scheduled action will run automatically once a day, canceling expired quotations based on the defined expiration period.
- For each contact, the **Auto-cancel Quotations** checkbox under the **Sales&Purchase** tab controls whether that contact’s quotations will be auto-canceled. If checked, the quotations will be canceled after expiration. If unchecked, the scheduled action will skip those quotations.

---

Thanks, Roger!

**Review by HaraldPanten — CHANGES_REQUESTED** [review]
[FWD] is not a correct commit tag.

You have to use: https://www.odoo.com/documentation/16.0/contributing/development/git_guidelines.html#tag-and-module-name

Adding that in OCA we use [MIG] as well. (https://github.com/OCA/odoo-community.org/blob/master/website/Contribution/CONTRIBUTING.rst#commit-message)

This commit is a [MIG]

**Comment by ValentinVinagre** [comment]
> [FWD] is not a correct commit tag.
> 
> You have to use: https://www.odoo.com/documentation/16.0/contributing/development/git_guidelines.html#tag-and-module-name
> 
> Adding that in OCA we use [MIG] as well. (https://github.com/OCA/odoo-community.org/blob/master/website/Contribution/CONTRIBUTING.rst#commit-message)
> 
> This commit is a [MIG]

ups, my fault, sorry

**Comment by RogerSans** [comment]
@Jaimermaccione 
@HaraldPanten 
Solved THX

**Review by Jaimermaccione — APPROVED** [review]
LGTM! Functional review on runboat.

@RogerSans

**Comment by rousseldenis** [comment]
@HaraldPanten

**Review by HaraldPanten — APPROVED** [review]
@rousseldenis could you help us with a technical review?

THX!

**Review by Tisho99 — APPROVED** [review]
LGTM! Functional and code review

**Pull request merged**
