### PR TITLE
[14.0][FIX] sale_order_lot_selection_by_quant: fix widget resize error

### PR DESCRIPTION
**Pull request by HekkiMelody**
Adding a check to avoid an error that happens when a new column is inserted in the table but it's not rendered yet, so it doesn't have a `<th>` yet, so resizing at this point fails

### CODE REVIEW

**Review by geomer198 — APPROVED** [review]
Code review ok!

**Review by francesco-ooops — APPROVED** [review]
Functional review ok

**Comment by francesco-ooops** [comment]
@pedrobaeza minor fix, was blocked by broken tests in sale-workflow, also added maintainer

can you please merge?

**Comment by francesco-ooops** [comment]
@pedrobaeza ping :)

**Review by pedrobaeza — APPROVED** [review]
/ocabot merge patch

**Pull request merged**
