### PR TITLE
Slovene translations added

### PR DESCRIPTION
**Pull request by sysadminmatmoz**
Fresh commit from a freshly rebased repo

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Technically :+1:

**Comment by yvaucher** [comment]
Technically :+1:

**Comment by sysadminmatmoz** [comment]
... and again travis!? It was ok yesterday, and not ok today without any change nor in PR nor in your repo.

**Comment by pedrobaeza** [comment]
Now it's OK. The problem was with server-tools libs. I merge because there no any expectation to get an slovenian reviewer.

**Comment by sysadminmatmoz** [comment]
Actually I'm the reviewer for Odoo on Transifex (I used to do it on launchpad too) :smile: 
And for now it would seem also that I'm the Slovene community :tongue:

**Pull request merged**
