### PR TITLE
[13.0][MIG]sale_exception

### PR DESCRIPTION
**Pull request by ntodorova**
[13.0][MIG]sale_exception

### CODE REVIEW

**Comment by rousseldenis** [comment]
@ntodorova Same as for base one :smile: #1051

**Comment by ntodorova** [comment]
yes, I also saw it @rousseldenis. Shall I close them both?

**Comment by rousseldenis** [comment]
> yes, I also saw it @rousseldenis. Shall I close them both?

Yes, you can.

**Comment by ntodorova** [comment]
Duplicate of #1051

**Pull request closed without merging**
