### PR TITLE
[12.0] IMP sale_rental allowing to use routes selected in sale order line, if present

### PR DESCRIPTION
**Pull request by eLBati**

### CODE REVIEW

**Review by mrcast — APPROVED** [review]
Functional test ok.

**Comment by rousseldenis** [comment]
Make sense. Could you add a test for that case ?

**Comment by eLBati** [comment]
@rousseldenis the budget is over for this, sorry :disappointed:

**Review by alexis-via — APPROVED** [review]

**Review by marcelsavegnago — APPROVED** [review]

**Comment by rousseldenis** [comment]
github seems to be sick.

Relaunching again.

/ocabot merge patch

**Pull request merged**
