### PR TITLE
[17.0][MIG] sale_delivery_split_date: Migration to 17.0

### PR DESCRIPTION
**Pull request by Tisho99**
Standard migration

Supersedes #2963 for inactivity

I maintained the commit author because i have made no changes, in spite of the little amount of changes needed in the migration

Updated with last module changes

T-6826

### CODE REVIEW

**Comment by Tisho99** [comment]
@ValentinVinagre @HaraldPanten @luis-ron

**Comment by HaraldPanten** [comment]
@BT-etejeda Could you review? I think you were interested in this module

**Review by sara-castello — APPROVED** [review]
Functional review LGTM

**Review by manuelregidor — APPROVED** [review]
Technical review. LGTM

**Review by HaraldPanten — APPROVED** [review]

**Pull request merged**
