### PR TITLE
[14.0] [IMP] sale_discount_display_amount: Add untaxed no discount

### PR DESCRIPTION
**Pull request by paradoxxxzero**

### CODE REVIEW

**Review by rousseldenis — APPROVED** [review]
Code review. Seems great. @paradoxxxzero Still WIP ?

**Comment by paradoxxxzero** [comment]
Forgot to remove the draft, the code is in production

**Review by rafaelbn — APPROVED** [review]
/ocabot merge minor

**Comment by rafaelbn** [comment]
@paradoxxxzero , please could you take care and make the PR for 15 an 16 🙏🏼 ? Not obligatory, just OCA ask for help! 😄 ❤️

**Pull request merged**
