### PR TITLE
[MIG] 12.0 sale_promotion_rule

### PR DESCRIPTION
**Pull request by PierrickBrun**
includes #1007

### CODE REVIEW

**Comment by rousseldenis** [comment]
@PierrickBrun

**Comment by marcelsavegnago** [comment]
@PierrickBrun Do you intend to continue this PR?

**Comment by PierrickBrun** [comment]
Hi @marcelsavegnago 

I remember not being able to understand what made it fail in travis because I did not have the problem when running from my local installation.

I don't really want to waste any more time on this tbh, apparently there's something to do with sale_invoice_policy.

**Comment by marcelsavegnago** [comment]
> Hi @marcelsavegnago
> 
> I remember not being able to understand what made it fail in travis because I did not have the problem when running from my local installation.

In travis I saw that there is an error in the test result. If the test error does not occur locally, I recommend that in your local instance install the other modules of this repository as it may be one of them that is affecting the results.

https://travis-ci.org/github/OCA/sale-workflow/jobs/680910874#L2413

> I don't really want to waste any more time on this tbh, apparently there's something to do with sale_invoice_policy.

I understand. I saw that there is a PR for version 13 (https://github.com/OCA/sale-workflow/pull/1485) and it may be easier to migrate it to V12 when it is merged with 13. What do you think? 

If possible do a rebase so that we can assess the current status.

**Comment by PierrickBrun** [comment]
> I understand. I saw that there is a PR for version 13 (#1485) and it may be easier to migrate it to V12 when it is merged with 13. What do you think?
> 
> If possible do a rebase so that we can assess the current status.

I just rebased. It looks like the v13 PR has the same problem so I guess we would only need to backport the fix

**Comment by rousseldenis** [comment]
@PierrickBrun Could you check Travis ?

**Comment by eLBati** [comment]
https://github.com/OCA/sale-workflow/pull/1570 Another way, to be discussed

**Comment by mileo** [comment]
Please check the runbot error:

2021-03-26 13:58:19,132 183 WARNING openerp_test odoo.models: The model sale.order.add.coupon has no _description

**Comment by PierrickBrun** [comment]
@mileo done and rebased

**Review by mileo — APPROVED** [review]

**Review by sadamo — APPROVED** [review]

**Review by marcelsavegnago — APPROVED** [review]

**Comment by rousseldenis** [comment]
@PierrickBrun Is this ready for you ?

**Comment by hparfr** [comment]
ping @PierrickBrun

**Comment by PierrickBrun** [comment]
@rousseldenis Yes you can merge

**Pull request merged**
