### PR TITLE
[13.0][FW][IMP] sales_team_security: Auto-followers (create and remove) in child partners

### PR DESCRIPTION
**Pull request by chienandalu**
Forward port of #1439

Auto-followers (create and remove) in child partners when salesman is changed (write function)

cc @Tecnativa TT32673

ping @pedrobaeza @victoralmau

### CODE REVIEW

**Review by victoralmau — APPROVED** [review]
Code review OK.

**Comment by pedrobaeza** [comment]
Please cherry-pick 858ac48d4f60c2504ddd363996d8ae9993586cf4

**Review by victoralmau — APPROVED** [review]

**Review by rousseldenis — APPROVED** [review]
Code review

**Pull request merged**
