### PR TITLE
Port 7.0 add last sale price yvr

### PR DESCRIPTION
**Pull request by yvaucher**

### CODE REVIEW

**Comment by pedrobaeza** [comment]
There is an error with this module tests. Can you check it, please?

Regards.

**Comment by yvaucher** [comment]
last_sale_price tests fail because of sale_stock:

IntegrityError: null value in column "picking_policy" violates not-null constraint

This module doesn't depends on sale_stock, thus it should be tested separately

**Comment by gurneyalex** [comment]
@yvaucher I think you can work around this by changing the travis configuration for the repository, in order to make separate tests for the modules which must not be tested with sale_stock installed.

**Comment by yvaucher** [comment]
Separating last_sale_price test works though it seems there is still an error with sale_validity on other test. (this shouldn't have anything to do with last_sale_price)

**Comment by eLBati** [comment]
The test error came from https://github.com/OCA/sale-workflow/pull/22
@yvaucher you can try rebasing

**Comment by yvaucher** [comment]
Rebased

**Comment by eLBati** [comment]
The remaining failure comes from https://github.com/OCA/OCB/issues/37
So, :+1:

**Comment by gurneyalex** [comment]
rebased on top of 7.0

**Comment by gurneyalex** [comment]
:+1:

**Comment by pedrobaeza** [comment]
:+1:

**Pull request merged**
