### PR TITLE
[17.0][MIG] sale_order_secondary_unit: Migration to version 17.0

### PR DESCRIPTION
**Pull request by mmrondon**

### CODE REVIEW

**Comment by rousseldenis** [comment]
@mmrondon Thank you for this.

In order to review efficiently, could you point the depending PR in this description ?

Moreover, you can add the dependency here in order to test it functionally: https://github.com/OCA/maintainer-tools/wiki/Use-temporary-reference%28s%29-to-another-pull-request%28s%29

**Comment by mmrondon** [comment]
Depending PR:
[1560] [[17.0][MIG] product_secondary_unit product-attribute#1560](https://github.com/OCA/product-attribute/pull/1560)

**Comment by rov-adhoc** [comment]
@mmrondon Hey! The PR dependency [#1560](https://github.com/OCA/product-attribute/pull/1560) has already been merged. Could you please rebase this PR?

Thanks in advance.

Best regards,

**Comment by rousseldenis** [comment]
@mmrondon

**Review by rov-adhoc — APPROVED** [review]

**Comment by rov-adhoc** [comment]
@mmrondon Hey! Can you please check the failing test of coverage? There are some lines that are not covered by the tests.
Thanks in advance!!

**Review by rov-adhoc — APPROVED** [review]

**Comment by rov-adhoc** [comment]
@mmrondon Thanks for your effort in adding the new test!
@rousseldenis I would like to ask if it's ready now?

**Comment by rousseldenis** [comment]
@mmrondon You should preserve commits history. See https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-17.0

**Comment by rov-adhoc** [comment]
@mmrondon Hey! I would like to ask you if you had the possibility to take a look on the document https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-17.0

**Comment by mmrondon** [comment]
hello @rov-adhoc @rousseldenis Closing this PR, I opened a new one with commit history #3385

**Pull request closed without merging**
