### PR TITLE
[13.0][MIG]sale_blanket_order: Migration to 13.0

### PR DESCRIPTION
**Pull request by chusamo**

### CODE REVIEW

**Review by anasuarez1 — APPROVED** [review]
Functional review OK

**Comment by LoisRForgeFlow** [comment]
There already exists a PR for this https://github.com/OCA/sale-workflow/pull/1108. Have you checked it?

**Comment by chusamo** [comment]
@LoisRFor

> There already exists a PR for this #1108. Have you checked it?

I did it after create this PR, my mistake. If the author of that PR doesn't answer I could finish the work here applying all the suggestions.

**Comment by tcamberlin** [comment]
Hi,
Functional review OK for me too.
Do you have an idea when it can be merged?

**Comment by chusamo** [comment]
> Hi,
> Functional review OK for me too.
> Do you have an idea when it can be merged?

Thank you for the review. Could you register the review click on File changed -> Review Changes?  Today or tomorrow I'll check the testing cover for pass the test and increase the probability of merging this PR.

**Review by tcamberlin — APPROVED** [review]
Functional review OK.

**Review by danimv5 — APPROVED** [review]
Functional review! LGTM!!

**Comment by brendapaniagua** [comment]
Functional review! LGTM!

**Pull request merged**
