### PR TITLE
"Convert to order" and  "Cancel" buttons are not visible on visible on "sent" state

### PR DESCRIPTION
**Pull request by hcbayram**
"sent" state is added to "Convert to order" and  "Cancel" buttons.

### CODE REVIEW

**Review by petrus-v — APPROVED** [review]
strange commit history, anyway you get my +1

**Comment by atchuthan** [comment]
duplicate in https://github.com/OCA/sale-workflow/pull/1800.  Please close this one.

**Comment by petrus-v** [comment]
@atchuthan this is address against 13.0 branch the #1800 is against 14.0 branch I think both should be kept. Maybe add branch name in PR title ?

**Comment by atchuthan** [comment]
> @atchuthan this is address against 13.0 branch the #1800 is against 14.0 branch I think both should be kept. Maybe add branch name in PR title ?

oops.. sorry my mistake

**Review by atchuthan — APPROVED** [review]
Could you squash the commits?

**Comment by hcbayram** [comment]
> strange commit history, anyway you get my +1
thanks for encouraging me, i'll keep on learning

**Comment by hcbayram** [comment]
> @petrus-v  strange commit history, anyway you get my +1

thanks for encouraging me, i'll keep on learning

**Comment by petrus-v** [comment]
@hcbayram GIT can be powerful but require some time to use the full power ! There are various ways to use git that let you rewrite the commit history (for instance to squash commits: from several commits you create only one commit).

[Atlassian has written pretty well tutorial on GIT](https://www.atlassian.com/git), of course the [git documentation and git book are good references too](https://git-scm.com/book/en/v2)  and I'm pretty sure you will find tones of git tutorial on Internet to learn git and how to rewrite the history ;)

Developer platforms like github/gitlab allows to squash commit while merging ! I'm not sure about OCA practices on that topic ! I feel like PSC could squash commits while merging such PR ?!

**Review by pedrobaeza — CHANGES_REQUESTED** [review]
The squash should be done by the contributor, as our bot only perform merge operations, and merge commits inside merge commits breaks future git history retrieval, so please fix it.

**Comment by petrus-v** [comment]
> The squash should be done by the contributor, as our bot only perform merge operations, and merge commits inside merge commits breaks future git history retrieval, so please fix it.

Thanks for detail @pedrobaeza ! 

@hcbayram you should learn about `git rebase -i` or `git reset + git commit` them !

**Comment by hcbayram** [comment]
@pedrobaeza I tried to squash those commits but I think there is a complication because commits of two different code change are grouped in one PR . So I think it is better to close this PR and send two new PR.

**Pull request closed without merging**
