### PR TITLE
[16.0][MIG] sale_invoice_policy: Migration to 16.0

### PR DESCRIPTION
**Pull request by ljsalvatierra-factorlibre**
https://github.com/OCA/sale-workflow/issues/2215

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Thanks for the contribution.

Please preserve commit history following technical method explained in https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-16.0.

If the jump is between several versions, you have to modify the source branch in the main command to accommodate it to this circumstance.

**Comment by ljsalvatierra-factorlibre** [comment]
> Thanks for the contribution.
> 
> Please preserve commit history following technical method explained in https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-16.0.
> 
> If the jump is between several versions, you have to modify the source branch in the main command to accommodate it to this circumstance.

Thank you, should be fixed now.

**Comment by SoniaViciana** [comment]
LGTM!

**Comment by ljsalvatierra-factorlibre** [comment]
Is it ready to merge?

**Review by JavierIniesta — APPROVED** [review]

**Review by RodrigoBM — APPROVED** [review]

**Comment by ljsalvatierra-factorlibre** [comment]
Updated with a rebase of 16.0.

**Comment by ljsalvatierra-factorlibre** [comment]
hi @rousseldenis, could you add this PR to the migration issue? Thank you.

**Review by hugo-cordoba — APPROVED** [review]
LGTM (code review)

**Comment by hugo-cordoba** [comment]
Hello @pedrobaeza, could you review this please?

Regards!!

**Comment by ljsalvatierra-factorlibre** [comment]
> Hello @pedrobaeza, could you review this please?
> 
> Regards!!

No rush, i've talked with my department and we are gonna start doing more reviews, i'm just with a lot of work right now.

**Pull request merged**
