### PR TITLE
[MIG] sale_order_product_recommendation_secondary_unit: Migration to 12.0

### PR DESCRIPTION
**Pull request by chienandalu**
cc @Tecnativa TT20511

### CODE REVIEW

**Review by pedrobaeza — APPROVED** [review]

**Review by sergio-teruel — APPROVED** [review]

**Comment by sergio-teruel** [comment]
@chienandalu Can you increase coverage??

**Review by yajo — APPROVED** [review]

**Comment by pedrobaeza** [comment]
It's true that seeing the diff coverage, this module is essentially not tested. You can refactor tests in base module as I showed you in the past for inheriting that one only adding the secondary unit part.

**Comment by chienandalu** [comment]
Sure, I'll do that

**Comment by pedrobaeza** [comment]
Travis is red

**Review by pedrobaeza — APPROVED** [review]

**Pull request merged**
