### PR TITLE
[10.0] Port sale_validity to v10

### PR DESCRIPTION
**Pull request by alexis-via**
New use the native field from the sale module
Convert YAML tests to unittests
Add README.rst

### CODE REVIEW

**Review by legalsylvain — APPROVED** [review]
Hi @alexis-via . Thanks for porting this module.
:+1: 
Just one thing, for the next time, please use git mv command when you rename the files. Otherwise, it's a mess to review changes.

kind regards.

**Comment by alexis-via** [comment]
@legalsylvain I used "git mv" ! I guess it's because the files are both renamed and changed...

**Comment by legalsylvain** [comment]
Ow ! Maybe yes. In that case, 2 commits (one for all the renames, and one for the real changes could make review more easy).

regards.

**Review by LoisRForgeFlow — APPROVED** [review]
This LGTM :+1: Thank you for the work! 

Any plan on backporting this to v9?

**Comment by alexis-via** [comment]
@lreficent I don't use v9 so I don't plan to backport it myself, but feel free to do it. It should be very easy to backport.

**Review by JordiBForgeFlow — APPROVED** [review]
:+1: Technical and functional review. Thanks!!!

**Pull request merged**
