### PR TITLE
[16.0][MIG] sale_partner_incoterm

### PR DESCRIPTION
**Pull request by BT-apadron**

### CODE REVIEW

**Comment by pedrobaeza** [comment]
CI is red

**Comment by gurneyalex** [comment]
Please include:
* https://github.com/OCA/sale-workflow/commit/7c085e24fc881f6896ae2480c980a7b112fe1198
* https://github.com/OCA/sale-workflow/pull/2431

**Comment by hailangvn2023** [comment]
> Please include:
> 
>     * [7c085e2](https://github.com/OCA/sale-workflow/commit/7c085e24fc881f6896ae2480c980a7b112fe1198)
> 
>     * [[15.0] sale_partner_incoterm: add incoterm address  #2431](https://github.com/OCA/sale-workflow/pull/2431)

Good day @gurneyalex, [the new PR](https://github.com/OCA/sale-workflow/pull/2506) is to replace this one and has commits for above points. The PR needs approval from maintainer to run tests.

**Comment by dreispt** [comment]
Superseded by #2506

**Pull request closed without merging**
