### PR TITLE
[16.0][MIG] sales_team_security: Migration to version 16.0

### PR DESCRIPTION
**Pull request by Yadier-Tecnativa**
@Tecnativa TT43248
Supersede for https://github.com/OCA/sale-workflow/pull/2458

### CODE REVIEW

**Comment by pedrobaeza** [comment]
The previous PR was not incorrect. The translations suggestions are just improvements that can be done later, so you are not bringing too much extra value, and you are removing the authorship of the previous contributor, discouraging future contributions. If you want to "finish" the migration here, please respect the migration commit authorship, add the translation on top, and also squash administrative commits: https://github.com/OCA/maintainer-tools/wiki/Merge-commits-in-pull-requests

**Comment by Yadier-Tecnativa** [comment]
Thanks @pedrobaeza ,  I'll be more careful next time, now I'll do what you suggested and I'll fix it.

**Comment by pedrobaeza** [comment]
I still don't see the commits from the other author.

**Comment by Yadier-Tecnativa** [comment]
> I still don't see the commits from the other author.

Done

**Comment by pedrobaeza** [comment]
You are still not preserving the commit authorship. It's not enough with cherry-picking the commit. You have to replace it in your commit history.

**Review by pedrobaeza — APPROVED** [review]
Let's move this:

/ocabot merge nobump

**Pull request merged**
