### PR TITLE
[ADD] [16.0] sale_order_line_product_attribute_values

### PR DESCRIPTION
**Pull request by Shide**
Store all product attribute values used directly or indirectly on the sale.order.line

You can view this attributes installing sale_order_line_menu module.

MT-6867 @moduon @rafaelbn @fcvalgar @Gelojr please review if you want

### CODE REVIEW

**Comment by Shide** [comment]
@sbidoul can you check why standard checks are not being created?

**Review by fcvalgar — APPROVED** [review]
Functional review.
LGTM, thank you @Shide 

[OCA - [ADD] [16.0] sale_order_line_product_attribute_values #3432 MT-6867 (00:50 min)) - Watch Video](https://www.loom.com/share/2fbace2d066d46a2b963fc8c36b4ca2c)

**Comment by Shide** [comment]
- [x] Add something to avoid recompute when installing the module

**Comment by Shide** [comment]
Added context checking on the function to avoid recompute on initial installation.

Also added CONFIGURE.md to show how to recompute lines.

**Review by Gelojr — APPROVED** [review]
LGTM Thanks @Shide 
https://www.loom.com/share/e0be518e6a3145e99a17ae2d1f8fe1f1?sid=90fef4d0-fcbe-4be0-b977-ac0840791780

**Review by rafaelbn — APPROVED** [review]
👍🏼 

/ocabot merge patch

**Pull request merged**
