### PR TITLE
[17.0][ADD]sale_invoice_disable_salesperson_autosubscribe: disables salesperson autosubscription when creating invoices.

### PR DESCRIPTION
**Pull request by RogerSans**
Disables salesperson autosubscription when creating invoices.
T-6499

@HaraldPanten 
@ValentinVinagre 
@luis-ron

### CODE REVIEW

**Review by luis-ron — APPROVED** [review]
Functional Review: LGTM 👍🏻

**Comment by RogerSans** [comment]
@ValentinVinagre Can you review PLS? THX

**Review by ValentinVinagre — CHANGES_REQUESTED** [review]
Blocked, review all functionality

**Review by luis-ron — APPROVED** [review]
Functional review: LGTM 👍🏻

**Comment by RogerSans** [comment]
@manuelregidor Can you review this pls? THX

**Comment by pedrobaeza** [comment]
You have to take into account that with this, salesmen won't be able to access the invoice, as the record rules in `account.move` are set by followers. The strategy should be that they don't receive the messages, not to prevent their subscription to the document. Maybe you can have them with a mail.subtype that is not disturbing.

**Comment by RogerSans** [comment]
Thanks for the review Pedro. I'm actually changing it.

**Comment by HaraldPanten** [comment]
@pedrobaeza  Closing this PR which has been superseded by https://github.com/OCA/social/pull/1460 which is more generic and follows better the good practices and OCA structure.

**Pull request closed without merging**
