### PR TITLE
[15.0][IMP] sale_discount_display_amount: Show total discount on sale report.

### PR DESCRIPTION
**Pull request by angelgarciadelachica**
This PR adds the total discount value to the sale report.
Based on @manuelregidor 's PR https://github.com/OCA/sale-workflow/pull/2071 in v14.0.

### CODE REVIEW

**Comment by angelgarciadelachica** [comment]
@HaraldPanten @ValentinVinagre

**Review by ValentinVinagre — APPROVED** [review]
LGTM 👍🏻

**Review by HaraldPanten — APPROVED** [review]
LGTM

**Pull request merged**
