### PR TITLE
[16.0][FIX] sale_blanket_order: not require taxes on blanket orders

### PR DESCRIPTION
**Pull request by ps-tubtim**
I remove taxes required on blanket orders.

### CODE REVIEW

**Review by rousseldenis — APPROVED** [review]
Code review.

Indeed, seems fair

**Review by Saran440 — APPROVED** [review]
Code Review :+1:

**Comment by StefanRijnhart** [comment]
@ps-tubtim Can you propose the port to 17.0?

**Comment by Saran440** [comment]
@StefanRijnhart We're upgraded to v17 here https://github.com/OCA/sale-workflow/pull/3302. Could you help review please. Thank you

**Pull request merged**
