### PR TITLE
[13.0][MIG] sale_automatic_workflow_job

### PR DESCRIPTION
**Pull request by ps-tubtim**
Standard migration.

Waiting for

- [ ] [13.0][IMP] sale_automatic_workflow - return object https://github.com/OCA/sale-workflow/pull/1242

### CODE REVIEW

**Comment by rousseldenis** [comment]
@ps-tubtim Do you plan to add tests to improve coverage ?

Moreover, I see code that is intended to be moved to queue_job module, isn't it time to do it ? @guewen

**Comment by ps-tubtim** [comment]
@rousseldenis At this time, I don't plan to add more tests.

**Comment by kittiu** [comment]
@rousseldenis, can you point out 

> @ps-tubtim Do you plan to add tests to improve coverage ?
> 
> Moreover, I see code that is intended to be moved to queue_job module, isn't it time to do it ? @guewen

Interesting, about queue_job, can you point out some example addon that did that? I might be able to help when time allowed.

**Comment by rousseldenis** [comment]
@kittiu https://github.com/OCA/sale-workflow/pull/1209/files#diff-70fee9c0ff9376ae75cd66e1654f75c5R11

This should be integrated into queue_job module itself in order to make it available transversely for all modules that uses queue_job.

**Comment by kittiu** [comment]
I tested it and this PR still not work, no job is queued!

@rousseldenis have you used this in older version, any particular setting required
(beside, https://github.com/OCA/queue/tree/13.0/queue_job#configuration)

**Comment by kittiu** [comment]
Superseded with - https://github.com/OCA/sale-workflow/pull/1253
@ps-tubtim can you help close this one please.

**Pull request closed without merging**
