### PR TITLE
[15.0][MIG] sale_cancel_confirm: Migration to 15.0

### PR DESCRIPTION
**Pull request by moaadbourhim**
- [ ] Depends in base_cancel_confirm https://github.com/OCA/server-ux/pull/455

### CODE REVIEW

**Comment by CasVissers-360ERP** [comment]
@rafaelbn @moaadbourhim 
Dependency base_cancel_confirm is not migrated yet?

**Comment by rafaelbn** [comment]
Dear @CasVissers-360ERP , not, `base_cancel_confirm` is not migrated: https://github.com/OCA/server-ux/issues/390

**Comment by moaadbourhim** [comment]
@CasVissers-360ERP i have migrat base_cancel_confirm to 15
@rafaelbn can you please review my PR migration : [OCA/server-ux/pull/455](https://github.com/OCA/server-ux/pull/455)

**Pull request closed without merging**
