### PR TITLE
[14[MIG]] sale_order_lot_generator

### PR DESCRIPTION
**Pull request by florian-dacosta**
Standard migration
Depends on https://github.com/OCA/sale-workflow/pull/1360

@sebastienbeau

### CODE REVIEW

**Review by danimv5 — APPROVED** [review]
Functional review!

**Comment by brendapaniagua** [comment]
Functional review.

**Review by atchuthan — APPROVED** [review]

**Review by bealdav — APPROVED** [review]
LGTM

**Pull request merged**
