### PR TITLE
[9.0][ADD] module 'sale_force_invoiced'

### PR DESCRIPTION
**Pull request by JordiBForgeFlow**
Sale Force Invoiced
===================

This module adds the possibility for users to force the invoice status of the
 sales orders to 'Invoiced', even when not all the quantities ordered or
 delivered have been invoiced.

This feature useful in the following scenario:

* The customer disputes the quantities to be invoiced for, after the
  products have been delivered to her/him, and you agree to reduce the
  quantity to invoice (without sending a refund).

* When migrating from a previous Odoo version, in some cases there is less
  quantity invoiced to what was delivered, and you don't want these old sales
  orders to appear in your 'To Invoice' list.

Usage
=====

#. Create a sales order and confirm it.
#. Deliver the products/services.
#. Create an invoice and reduce the invoiced quantity. The sales order
   invoicing status is 'To Invoice'.
#. Change the status of the sales order to 'Done'.
#. Check the field 'Force Invoiced'

### CODE REVIEW

**Comment by JordiBForgeFlow** [comment]
cc @Eficent. Can you review @lreficent, @gmeficent, @mreficent?

**Review by LoisRForgeFlow — APPROVED** [review]
LGTM :+1:

**Review by gmeficent — COMMENTED** [review]
Good to go, works as described :+1:

**Review by gmeficent — APPROVED** [review]

**Review by AaronHForgeFlow — APPROVED** [review]
:+1: Tested on runbot +soft code review

**Review by MiquelRForgeFlow — APPROVED** [review]
soft code review :+1: 

runbot warnings are from other module, the <code>sale rental</code>, nothing to do with this PR

**Pull request merged**
