### PR TITLE
[15.0][MIG]sale_fully_delivered_invoiced

### PR DESCRIPTION
**Pull request by AaronHForgeFlow**
The standard field invoice_status shows information about the status invoices related
to a sales Order. However, it can be "invoiced" when the invoices are still in draft.
Many times that makes the difference to consider the Sales Order
as closed or not. Because of this, this module introduce two new fields that will show
that the Sales Order is fully delivered and Fully Invoiced, taking the state into
account.

cc @ForgeFlow

### CODE REVIEW

**Review by legalsylvain — COMMENTED** [review]
Hi. Thanks for this features. Seems usefull !

Two remarks :
 - minor : could you rename ptython files ? Sale_ordre_line and sale_order
 - refactoring : i think we should have two modules. One for the full delivery status depending on sale stock and one for the invoice non draft status, depending on sale. What do you think ?

**Comment by AaronHForgeFlow** [comment]
I will propose two separate modules. Thanks for reviewing!

**Review by JuanyDForgeflow — APPROVED** [review]
Code + Functional review LGTM

**Review by MiquelRForgeFlow — APPROVED** [review]

**Comment by AaronHForgeFlow** [comment]
Superseded https://github.com/OCA/sale-workflow/pull/2552and https://github.com/OCA/sale-workflow/pull/2553

**Pull request closed without merging**
