### PR TITLE
[11.0][FIX] sale_stock_picking_blocking: view error

### PR DESCRIPTION
**Pull request by MiquelRForgeFlow**
Fixes https://github.com/OCA/sale-workflow/pull/733#issuecomment-440274502.

### CODE REVIEW

**Comment by MiquelRForgeFlow** [comment]
@pedrobaeza

**Comment by pedrobaeza** [comment]
This is very fragile to inheritance. Can you please make the xpath a bit less specific?

**Comment by MiquelRForgeFlow** [comment]
Done!

**Comment by pedrobaeza** [comment]
This is because there are several `user_id` fields, corresponding to different models? Can you point to the conflicting XML lines?

**Comment by MiquelRForgeFlow** [comment]
I think what you mention is not the problem. Really, I don't know. But happy to see that with xpath the problem is solved. My work in this is finished.

**Review by LoisRForgeFlow — APPROVED** [review]
:green_apple:

**Pull request merged**
