### PR TITLE
[11.0][MIG] partner_prospect: Migration to 11.0

### PR DESCRIPTION
**Pull request by oihane**
please sb mark it as WIP

### CODE REVIEW

**Review by pedrobaeza — APPROVED** [review]

**Comment by anajuaristi** [comment]
:+1: 
Please merge. I have not permission on this branche to make it.

**Review by MiquelRForgeFlow — CHANGES_REQUESTED** [review]
Hi @oihane 

That's an old module you migrated, good! :+1: 

But let me tell you that there is some OCA coding guidelines that this module doesn't meet:

* Readme file at least should have to meet the template https://raw.githubusercontent.com/OCA/maintainer-tools/52f41366ab39ea90e66f3e3a2b5cd7691b4219df/template/module/README.rst
* manifest file as https://github.com/OCA/maintainer-tools/blob/master/template/module/__manifest__.py
* check the correct format of copyrights headers
* coding utf-8 in python files should be removed in v11
* also <data> tags in xml files should be removed

It would be nice if all of these could be cleaned.

Best regards

**Comment by oihane** [comment]
Hello @mreficent 
I did it before some of the points you are comenting, I'll check them tomorrow, thx

**Review by MiquelRForgeFlow — APPROVED** [review]
LGTM

**Pull request merged**
