### PR TITLE
[14.0][MIG] sale_product_multi_add: Migration to 14.0

### PR DESCRIPTION
**Pull request by newtratip**
I add security for wizard model and remove `ondelete='cascade'` in One2many field because it's not supported.

This is standard migration and ready for review.

### CODE REVIEW

**Review by tonygalmiche — APPROVED** [review]
LGTM : Functional review only with runbot

image

**Review by danimv5 — APPROVED** [review]
Functional review! LGTM!!

**Review by HaraldPanten — APPROVED** [review]
LGTM

**Review by rousseldenis — APPROVED** [review]
Code review

**Pull request merged**
