### PR TITLE
[13.0][MIG] sale_disable_inventory_check

### PR DESCRIPTION
**Pull request by JoanSForgeFlow**
**sale_disable_invetory_check** migration to v13

cc ~ @ForgeFlow @LoisRForgeFlow

### CODE REVIEW

**Comment by AaronHForgeFlow** [comment]
Why did you close this?

**Comment by JoanSForgeFlow** [comment]
Because Odoo 13 itself has removed the warning message "Not enough inventory".

**Comment by AaronHForgeFlow** [comment]
Finally they remove that? :tada:  Thanks for telling.

**Comment by JoanSForgeFlow** [comment]
Yes, now there is a red warning in the sale order line.

**Comment by pedrobaeza** [comment]
You need to perform in OpenUpgrade the operation of merging this module in `sale` (I suppose) module.

**Comment by AaronHForgeFlow** [comment]
> You need to perform in OpenUpgrade the operation of merging this module in `sale` (I suppose) module.

I see, it is in `sale_stock` module. Ping @MiquelRForgeFlow

**Pull request closed without merging**
