### PR TITLE
[14.0][IMP] sale_restricted_qty: show sale_min sale_max optionally

### PR DESCRIPTION
**Pull request by ilyasProgrammer**
… in SOL

### CODE REVIEW

**Review by SicurSam — APPROVED** [review]
Functional ok!

**Review by francesco-ooops — APPROVED** [review]
minor change

**Comment by francesco-ooops** [comment]
@OCA/crm-sales-marketing-maintainers good change?

**Comment by francesco-ooops** [comment]
@OCA/crm-sales-marketing-maintainers good for merge?

**Comment by simahawk** [comment]
@ilyasProgrammer can you fix the commit msg which is cut? (See how I rephrased it in the title)
Wondering: the initial intent was to show it by default: are we sure we shouldn't use `show` by default instead?

**Comment by ilyasProgrammer** [comment]
> @ilyasProgrammer can you fix the commit msg which is cut? (See how I rephrased it in the title) Wondering: the initial intent was to show it by default: are we sure we shouldn't use `show` by default instead?
As for me there is no difference.

**Comment by ilyasProgrammer** [comment]
updated

**Comment by francesco-ooops** [comment]
@simahawk is it ok now?

**Review by simahawk — APPROVED** [review]
If nobody minds about the default visibility... ok :)

**Pull request merged**
