### PR TITLE
[15.0][MIG] sale_automatic_workflow_payment_mode

### PR DESCRIPTION
**Pull request by flachica**
Dependency below, please review

https://github.com/OCA/connector-prestashop/pull/151
https://github.com/OCA/sale-workflow/pull/2005
https://github.com/OCA/connector-ecommerce/pull/70
https://github.com/OCA/connector/pull/428
https://github.com/OCA/server-tools/pull/2334
https://github.com/OCA/product-attribute/pull/1070
https://github.com/OCA/product-attribute/pull/1069

### CODE REVIEW

**Review by jacekmichalski — APPROVED** [review]
LGTM

**Comment by flachica** [comment]
@jacekmichalski thanks for your review. I just uploaded changes because there were errors in the tests.

I encourage you to review the PR list above to fully migrate connector_prestashop

**Review by xAdrianC-Kernet — APPROVED** [review]

**Comment by flachica** [comment]
In order to finish migrating the Prestashop connector I need this PR to be merged. It has two approvals. Any PSC check it out? /cc  @HaraldPanten @rafaelbn

**Review by juliocabrerizo — APPROVED** [review]

**Comment by rafaelbn** [comment]
Thank @flachica !

Could you please take care on this https://github.com/OCA/sale-workflow/pull/1795 , maybe you should take it for this PR too 😄 

@leemannd @hailangvn @gurneyalex is this PR of you interest?

Thank you again!

**Comment by danielduqma** [comment]
@flachica could you please rebase to make runboat launch again? Thanks!

**Comment by flachica** [comment]
Done @danielduqma

**Comment by danielduqma** [comment]
Thanks! @dreispt could you please run merge command? Now all checks have passed and it will work.

Regards

**Pull request merged**
