### PR TITLE
[12.0][MIG] product_supplierinfo_for_customer_sale

### PR DESCRIPTION
**Pull request by murtuzasaleh**
Product Supplierinfo for Customer Sale
==============================
Loads in every sale order line the customer code defined in the product.

It depends on [product_supplierinfo_for_customer](https://github.com/OCA/product-attribute/pull/446)

### CODE REVIEW

**Comment by rafaelbn** [comment]
Please don't miss this FIX  from @sergio-teruel 
https://github.com/OCA/sale-workflow/pull/842

**Comment by MiquelRForgeFlow** [comment]
@murtuzasaleh will you continue with this PR?

**Comment by murtuzasaleh** [comment]
> Please don't miss this FIX from @sergio-teruel
> #842

@mreficent But that PR (#842) is still OPEN and also this module depends on [product_supplierinfo_for_customer](https://github.com/OCA/product-attribute/pull/446) (PR status OPEN)

**Review by AaronHForgeFlow — CHANGES_REQUESTED** [review]
refactor taken place on #https://github.com/OCA/product-attribute/pull/515. Table rename will be needed

**Comment by AaronHForgeFlow** [comment]
Hi  @murtuzasaleh  could you please cherry-pick this commit 4a15b24ae002d1b593266f000c377977c2e558c6 ? merged here: https://github.com/OCA/sale-workflow/pull/842/

**Comment by MiquelRForgeFlow** [comment]
Superseded by https://github.com/OCA/sale-workflow/pull/976.

**Pull request closed without merging**
