### PR TITLE
[13.0][MIG]portal_sale_personal_data_only

### PR DESCRIPTION
**Pull request by HaraldPanten**
Supersedes https://github.com/OCA/sale-workflow/pull/1134 standard migration

### CODE REVIEW

**Comment by HaraldPanten** [comment]
@chrisandrewmann , @pedrobaeza @ValentinVinagre could you review, please?

Thanks in advance.

**Review by ValentinVinagre — APPROVED** [review]
LGTM 👍

**Comment by HaraldPanten** [comment]
@chienandalu could you have a look? THX!

**Review by chienandalu — APPROVED** [review]
LGTM :+1:

**Pull request merged**
