### PR TITLE
[15.0][MIG] sale_partner_incoterm

### PR DESCRIPTION
**Pull request by vvrossem**

### CODE REVIEW

**Comment by vvrossem** [comment]
Hi @ReedHayashikawa, @jimhoefnagels, @StefanRijnhart , @lbelorgey, could you please review this PR ? 🙏 thank you

**Review by rousseldenis — APPROVED** [review]
Code review. You can add yourself in readme/CONTRIBUTORS.rst

**Comment by vvrossem** [comment]
Thank you for the review @rousseldenis !

**Review by dhx — APPROVED** [review]
LGTM

**Comment by StefanRijnhart** [comment]
@vvrossem pre-commit requirements seem to have changed slightly. Can you trigger pre-commit again on this code and commit the setup directory?
```
Run newfiles="$(git ls-files --others --exclude-from=.gitignore)"
Please check-in the following files:
setup/sale_partner_incoterm/odoo/addons/sale_partner_incoterm
setup/sale_partner_incoterm/setup.py
Error: Process completed with exit code 1.
```

**Comment by yankinmax** [comment]
@vvrossem can you pls rebase on updated 15.0 branch, pre-commit issues should be solved now

**Comment by vvrossem** [comment]
@StefanRijnhart @dreispt @yankinmax Apologies for the late reply 🙏 
All tests are now green ✅

**Pull request merged**
