### PR TITLE
[14.0][MIG] sale_sourced_by_line

### PR DESCRIPTION
**Pull request by murtuzasaleh**
Depends on #1498

### CODE REVIEW

**Comment by patrickrwilson** [comment]
Thanks, I've tested functionality, works as intended. Will review code once the dependency gets merged and verified green.

**Review by JoanMForgeFlow — APPROVED** [review]
LGTM! could you please rebase it in order to get this merged?
Thanks!
[murtuzasaleh](https://github.com/murtuzasaleh)

**Comment by JoanMForgeFlow** [comment]
> /ocabot rebase

thanks! @rousseldenis

**Review by ChrisOForgeFlow — CHANGES_REQUESTED** [review]
Funciontal test ok, but need rebase to get green CI, can you rebase and force push @murtuzasaleh?, by git-bot can't be done

**Review by bizzappdev — APPROVED** [review]
Functionally and code wise LGTM

**Comment by rousseldenis** [comment]
@murtuzasaleh Could you fix this and remove last commit ?

**Comment by elvise** [comment]
@murtuzasaleh can you rebase ?

**Pull request closed without merging**
