### PR TITLE
[14.0][FW] sale_exception: multiple ports from 13.0

### PR DESCRIPTION
**Pull request by hailangvn**
This is to port the following PRs from 13.0 to 14.0:
* #1551
* #1692

Depends on:
* #1664

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Please check Travis

**Comment by sebalix** [comment]
@hailangvn https://github.com/OCA/sale-workflow/pull/1664 has been merged, can you rebase?

**Comment by hailangvn** [comment]
Thanks @simahawk, @sebalix, @pedrobaeza. The travis is now green. The runboat is red because of `odoo.exceptions.UserError: Modules "Sale Isolated Quotation" and "Sale Quotation Numeration" are incompatible.`

**Review by sebalix — APPROVED** [review]
I don't know about Runboat, it seems not yet working with incompatible addons matrix, but your PR looks good otherwise.

**Review by simahawk — APPROVED** [review]

**Comment by simahawk** [comment]
bad bump, build canceled. Also there's another PR merging, I'll wait a bit.

**Pull request merged**
