### PR TITLE
[ADD] sale_order_digitized_signature

### PR DESCRIPTION
**Pull request by cubells**
[WIP] Depends on
- [x] https://github.com/OCA/web/pull/666  

New module that allows to add digitized signature to sales order and send by mail.

cc @Tecnativa

### CODE REVIEW

**Review by pedrobaeza — APPROVED** [review]
Add installation section

**Comment by cubells** [comment]
@pedrobaeza 

added.

**Comment by pedrobaeza** [comment]
Check Travis status

**Comment by pedrobaeza** [comment]
@cubells, check Travis status

**Comment by pedrobaeza** [comment]
@cubells please check Travis status in this

**Review by rafaelbn — APPROVED** [review]
This module has been in production many months, please @cubells check travis

:+1:

**Comment by cubells** [comment]
Now It's green.

Can you merge?

**Pull request merged**
