### PR TITLE
10.0 migration sale_quotation_number

### PR DESCRIPTION
**Pull request by SimoRubi**
Hi,
I'd like to continue the PR #518 and finish the porting of module sale_quotation_number.
Thanks

### CODE REVIEW

**Comment by pedrobaeza** [comment]
You need to keep commit history using migration guide: https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-11.0

**Comment by SimoRubi** [comment]
@pedrobaeza I've added the commits from v8 as you suggested, and squashed the Transbot's commits. 
Is it good now?
Thanks

**Comment by SimoRubi** [comment]
I'm using version `10.0.1.1.0` because I've added the configuration field that enables/disables the custom behaviour

**Review by mrcast — APPROVED** [review]
Functional test it's ok for me

**Comment by SimoRubi** [comment]
@pedrobaeza is this ok for you?

**Comment by SimoRubi** [comment]
@pedrobaeza do you have any change to suggest here or is it ok?
Thanks

**Comment by pedrobaeza** [comment]
None, but I'm not an actual reviewer of the module itself, but only about general rules.

**Review by hurrinico — APPROVED** [review]
👍

**Comment by SimoRubi** [comment]
@OCA/crm-sales-marketing-maintainers could you please check? (If this is not the right maintainers' group I'm sorry, I still don't know how to find the correct one)

**Review by tafaRU — APPROVED** [review]

**Pull request merged**
