### PR TITLE
Slovene translations added

### PR DESCRIPTION
**Pull request by sysadminmatmoz**
Just translations added (and one template)

### CODE REVIEW

**Comment by sysadminmatmoz** [comment]
Can't find out what's the travis problem about with this PR

**Comment by pedrobaeza** [comment]
You should rebase, but the problem is unrelated to your PR. I'll make another one to solve it on server-tools.

**Comment by sysadminmatmoz** [comment]
I'll solve the rebase issue and recommit

**Comment by sysadminmatmoz** [comment]
with PR: https://github.com/OCA/sale-workflow/pull/197

**Pull request closed without merging**
