### PR TITLE
*: E741 ambiguous variable name 'l' (greenify repo)

### PR DESCRIPTION
**Pull request by MiquelRForgeFlow**
Greenify repo.

### CODE REVIEW

**Comment by rousseldenis** [comment]
> Greenify repo.

Where do you see 13.0 branch is red ?

image

**Review by HviorForgeFlow — APPROVED** [review]

**Comment by HviorForgeFlow** [comment]
image

**Comment by rousseldenis** [comment]
Ok, so new flake rule ?

**Comment by MiquelRForgeFlow** [comment]
> Ok, so new flake rule ?

Yes. Well, not new flake rule, but new pre-commit flake rule.

**Review by rousseldenis — APPROVED** [review]

**Pull request merged**
