### PR TITLE
[14.0][mig] sale_procurement_group_by_line

### PR DESCRIPTION
**Pull request by koenloodts**

### CODE REVIEW

**Comment by newtratip** [comment]
pre-commit and travis is red, Could you check ?

**Comment by patrickrwilson** [comment]
@newtratip can you squash all the automated commit history? (.pot, readme and translation commits)

**Comment by rousseldenis** [comment]
@koenloodts Do you plan to finish this? There is another PR for this module #1689 .

**Comment by rousseldenis** [comment]
Closing this as no anwser for weeks in favor of #1689

**Pull request closed without merging**
