### PR TITLE
[16.0][MIG] sale_pricelist_technical

### PR DESCRIPTION
**Pull request by legalsylvain**
Trivial migration of the module sale_pricelist_technical from 12.0

### Description

This module extends the functionality of the Pricelist module to make it possible to create "technical pricelists" that can only be used to compute another pricelists.

These technical pricelists are hidden in the rest of the Odoo interface, preventing users from using them on sale order forms, customer forms, etc..

### Configure

To use this module, you should be member of "Technical / Basic Pricelists".

* Go to Sale / Configuration / Pricelists

* Check the box "Is Technical" on your desired pricelist

product_pricelist_form

### CODE REVIEW

**Review by chienandalu — APPROVED** [review]

**Review by rousseldenis — APPROVED** [review]
LGTM.

Either another word (I don't know yet the one) should be used than 'technical' as it sounds a little bit too vague.

**Comment by legalsylvain** [comment]
Thanks for your review ! 

/ocabot merge patch

> Either another word (I don't know yet the one) should be used than 'technical' as it sounds a little bit too vague.

hehe. https://github.com/OCA/sale-workflow/pull/2014#issuecomment-1127666426
already discussed in V12, and no better proposal...

**Comment by rousseldenis** [comment]
> Thanks for your review !
> 
> /ocabot merge patch
> 
> > Either another word (I don't know yet the one) should be used than 'technical' as it sounds a little bit too vague.
> 
> hehe. [#2014 (comment)](https://github.com/OCA/sale-workflow/pull/2014#issuecomment-1127666426) already discussed in V12, and no better proposal...

So, I'm quite coherent in my reviews :smiley:

**Pull request merged**
