### PR TITLE
[MIG] sale_order_carrier_auto_assign: Migration to 14.0

### PR DESCRIPTION
**Pull request by phuctranfxvn**

### CODE REVIEW

**Review by lfreeke — APPROVED** [review]
LGTM :+1:  (Functional test)

**Review by danimv5 — APPROVED** [review]
Functional review!! LGTM

**Comment by brendapaniagua** [comment]
Functional review. LGTM!!

**Comment by simahawk** [comment]
@phuctranerp could you check travis on https://github.com/OCA/sale-workflow/commits/419851e6b97d0e7875695a95894b267a3c22e073 ?

**Comment by hailangvn** [comment]
Thanks @simahawk for reviewing. I will work on it.

**Comment by hailangvn** [comment]
Good day @simahawk, this PR has been rebased to current 14.0 and has no error. Please help to merge again to see if error persists. Thank you in advance.

**Pull request merged**
