### PR TITLE
[FIX] sale_automatic_workflow_payment_mode: not register payment when no fixed journal

### PR DESCRIPTION
**Pull request by sonhd91**
This PR fix bug when `fixed_journal_id `is null

### CODE REVIEW

**Comment by sonhd91** [comment]
Hello @rousseldenis , can you merged ?

**Comment by rousseldenis** [comment]
> Hello @rousseldenis , can you merged ?

Before merging, the process is to have reviews. I'll look at it

**Comment by rousseldenis** [comment]
@sonhd91 Could you maybe add a test for this case ?

**Comment by rousseldenis** [comment]
@sonhd91

**Pull request closed without merging**
