### PR TITLE
[MIG]sale_product_category_menu: Migration to 13.0

### PR DESCRIPTION
**Pull request by HaraldPanten**
Standard Migration

### CODE REVIEW

**Review by rousseldenis — APPROVED** [review]
Easy migration!

**Review by danimv5 — APPROVED** [review]
Functional review! LGTM

**Comment by HaraldPanten** [comment]
> Easy migration!

Mostly copy/paste from V12, yep.

**Comment by HaraldPanten** [comment]
Hi @rousseldenis could you merge this one? 😉

**Review by eduardgm — APPROVED** [review]
Functionally checked, LGTM👍🏻

**Comment by HaraldPanten** [comment]
@rafaelbn @pedrobaeza could you merge, please?

**Pull request merged**
