### PR TITLE
[11.0][IMP] sale_product_set module

### PR DESCRIPTION
**Pull request by AdriaGForgeFlow**
Improvement of module sale_product_set in v11.

Features added:
* Add discount field in product_set_line if Discounts settings is active
* Add discount from product_set_line into the sale_order_line generated when adding a set into a SO
* Readme format and images updated

cc ~ @Eficent

### CODE REVIEW

**Review by HviorForgeFlow — APPROVED** [review]
LGTM :+1: 
Code & Functional review

**Review by MiquelRForgeFlow — APPROVED** [review]
LGTM

update manifest version in code or when merging

**Comment by JordiBForgeFlow** [comment]
@mreficent  please forward-port to 12.0

**Comment by MiquelRForgeFlow** [comment]
Done in https://github.com/OCA/sale-workflow/pull/908.

**Pull request closed without merging**
