### PR TITLE
[ADD] sale_line_description to v8.0 new api

### PR DESCRIPTION
**Pull request by Daniel-CA**
sale_line_description to v8.0 new api

### CODE REVIEW

**Comment by pedrobaeza** [comment]
This conflicts with https://github.com/OCA/sale-workflow/pull/144. @tafaRU, please comment with @Daniel-CA what is the best way to go, because this one is passed to new API.

**Comment by eLBati** [comment]
Thanks @Daniel-CA 
as `git diff 7.0 Daniel-CA/sale_line_description sale_line_description` gives
https://gist.github.com/eLBati/d90a6aeabca6294e0351
It seems you applied your changes to `__unported__` version of module, instead of 7.0 (see https://gist.github.com/eLBati/d90a6aeabca6294e0351#file-gistfile1-diff-L41)

Please check if this introduces some other regressions.
Thanks

**Comment by tafaRU** [comment]
@Daniel-CA, considering even that @eLBati's comment, I'd prefer if you could make a new PR containing  only changes about new API to https://github.com/OCA/sale-workflow/pull/144.
Meanwhile I'll rename the module according to @pedrobaeza's suggestion and I'll investigate about travis error (same in current PR) using by @yvaucher's hint.

Thank you in advance.

**Comment by Daniel-CA** [comment]
@tafaRUs Ops, I didn't see  your PR, sorry. Ok I will make a new PR against your branch #144 with my changes.

**Comment by tafaRU** [comment]
@Daniel-CA no problem, thanks a lot!
Before to do it wait the module renaming will be completed, I'll ping you when I'm done.

**Comment by tafaRU** [comment]
@Daniel-CA see https://github.com/OCA/sale-workflow/pull/144#issuecomment-99763297

**Pull request closed without merging**
