### PR TITLE
[10.0] sale_commercial_partner: add compute_sudo=True and readonly=True

### PR DESCRIPTION
**Pull request by alexis-via**

### CODE REVIEW

**Review by pedrobaeza — APPROVED** [review]
Please change module version number

**Review by sbidoul — APPROVED** [review]

**Comment by sa3m** [comment]
This PR could also be merged in next versions as it is needed whenever you use this module with multi company.

**Comment by rousseldenis** [comment]
> This PR could also be merged in next versions as it is needed whenever you use this module with multi company.

Do you plan to make PR for that ?

**Comment by sa3m** [comment]
I sure can !

**Pull request merged**
