### PR TITLE
[11.0] backporting sale automatic workflow payment

### PR DESCRIPTION
**Pull request by houssine78**
Backporting sale automatic worklofw payment from 13

### CODE REVIEW

**Comment by houssine78** [comment]
Hi @rousseldenis I just backported your module from 13 to 11. Could you have a little look ?

Thanks !

**Comment by rousseldenis** [comment]
@houssine78 Could you just check Travis error. It's about uom.

**Comment by houssine78** [comment]
@rousseldenis I fixe the wrong reference in the unit test but it still fails but this time I can't see the build logs following the link.

**Comment by houssine78** [comment]
@rousseldenis it's green now !

**Review by robinkeunen — APPROVED** [review]
LGTM 👍

**Pull request closed without merging**
