### PR TITLE
[17.0][MIG] sale_quotation_number: Migration to 17.0.

### PR DESCRIPTION
**Pull request by RogerSans**
supersede = https://github.com/OCA/sale-workflow/pull/3099
Standard migration
T-6432

@HaraldPanten 
@ValentinVinagre

### CODE REVIEW

**Review by luis-ron — APPROVED** [review]
Functional Review: LGTM 👍🏻

**Comment by RogerSans** [comment]
@Tisho99 Can you review this pls?

**Review by Tisho99 — CHANGES_REQUESTED** [review]
Your pre-commit auto fixes commit has automatically edited other modules. 

Can you edit it so only the migrated module is edited?

**Comment by RogerSans** [comment]
> Your pre-commit auto fixes commit has automatically edited other modules.
> 
> Can you edit it so only the migrated module is edited?

done

**Review by Tisho99 — APPROVED** [review]
LGTM! Code and functional review

**Comment by RogerSans** [comment]
@manuel-florido

**Review by HaraldPanten — APPROVED** [review]
LGTM

**Pull request merged**
