### PR TITLE
[13.0] [IMP] sale_order_type: Implement multi-company for the warehouse selection by the sale type.

### PR DESCRIPTION
**Pull request by nicomacr**

### CODE REVIEW

**Comment by nicomacr** [comment]
@rousseldenis could you check this out ? please

**Review by rousseldenis — COMMENTED** [review]
LGTM. Could you add a test for that ?

**Comment by rousseldenis** [comment]
@nicomacr Could you fix this ?

**Comment by nicomacr** [comment]
@rousseldenis already fixed and with tests cases for this change.

**Comment by nicomacr** [comment]
@rousseldenis ready this PR to merge  isn't it?

**Pull request closed without merging**
