### PR TITLE
[8.0] [FIX+IMP] product_margin_classification

### PR DESCRIPTION
**Pull request by legalsylvain**
Various improvments and fixes for product_margin_classification.

## 3 fixes
* return correct current company when creating a new margin classification
* incorrect 'type' account.tax field
* Fix demo data. (ref instead of eval)

## Some UI improvments

* display buttons only if required on margin classification form
* replace integrated tree view in margin classification form by a smart button and a dedicated tree view

## Technical improvments
* Add tests

### CODE REVIEW

**Comment by quentinDupont** [comment]
Mistake in help for 'Price Rounding field'
→ "Set rounding 10" should be "Set rounding 1"

Field "Products With Different Price" is not clear. 
I first thought it was the number of products that don't have this margin classification 
→ we can remove it or just change name in "Total Products With Different Price"

Error when changing any field of **Normal Margin** demo data, or even products with this margin.
(And this error only occurs for this margin..)
``` 
    return self._fields[key].__get__(self, type(self))
  File "/.repo_requirements/odoo/openerp/fields.py", line 835, in __get__
    self.determine_value(record)
  File "/.repo_requirements/odoo/openerp/fields.py", line 913, in determine_value
    self.compute_value(recs)
  File "/.repo_requirements/odoo/openerp/fields.py", line 893, in compute_value
    self._compute_value(records)
  File "/.repo_requirements/odoo/openerp/fields.py", line 885, in _compute_value
    self.compute(records)
  File "/.repo_requirements/odoo/openerp/api.py", line 266, in wrapper
    return new_api(self, *args, **kwargs)
  File "/home/odoo/build/OCA/sale-workflow/product_margin_classification/models/product_template.py", line 53, in _compute_theoretical_multi
    raise exceptions.UserError(_(
AttributeError: 'module' object has no attribute 'UserError' 

```

Otherwie, everything seems to work properly 👍 🥇 👍

**Comment by legalsylvain** [comment]
Hi @quentinDupont. thanks for your review. I fixed the three point. Could you update your review ? 

Note : Travis is failing for unrelated reasons.

**Comment by quentinDupont** [comment]
Perfect !
Tested and approved :slightly_smiling_face: 

Maybe you can remove "WIP for the time being, do not review." from your first comment

**Pull request closed without merging**
