### PR TITLE
[15.0][IMP] product_supplierinfo_for_customer_sale: menu for customer info

### PR DESCRIPTION
**Pull request by toita86**
fw of: https://github.com/OCA/sale-workflow/pull/3092

### CODE REVIEW

**Comment by francesco-ooops** [comment]
@pedrobaeza as promised :)

**Review by pedrobaeza — APPROVED** [review]

**Comment by rousseldenis** [comment]
@toita86 Could you rebase ?

**Comment by toita86** [comment]
@rousseldenis rebase done!

**Comment by rousseldenis** [comment]
@toita86 Could you rebase again ?

**Comment by toita86** [comment]
@rousseldenis no problem, just done!

**Review by rousseldenis — APPROVED** [review]

**Pull request merged**
