### PR TITLE
[12.0][MIG] sale_order_line_date

### PR DESCRIPTION
**Pull request by MiquelRForgeFlow**
Supersedes https://github.com/OCA/sale-workflow/pull/703 and https://github.com/OCA/sale-workflow/pull/875.

### CODE REVIEW

**Review by AaronHForgeFlow — COMMENTED** [review]
Finally a PR where the commitment date is propagated to the stock move :smile:  Thank you! Can you please fix travis?

**Comment by MiquelRForgeFlow** [comment]
@aheficent travis fixed

**Review by AaronHForgeFlow — APPROVED** [review]
Functional review, working as expected :+1:

**Review by NuriaXifre — APPROVED** [review]
Functional review done!

**Review by LoisRForgeFlow — APPROVED** [review]
LGTM

**Pull request merged**
