### PR TITLE
[16.0][MIG][WIP] Migration sale_product_set_layout

### PR DESCRIPTION
**Pull request by angelmoya**

### CODE REVIEW

**Comment by rousseldenis** [comment]
@angelmoya Still WIP?

**Comment by rousseldenis** [comment]
@angelmoya

**Comment by CasVissers-360ERP** [comment]
@angelmoya is this ready for review?

**Comment by CRogos** [comment]
superseded by https://github.com/OCA/sale-workflow/pull/2777

**Pull request closed without merging**
