### PR TITLE
[15.0][MIG] sale_blanket_order

### PR DESCRIPTION
**Pull request by JasminSForgeFlow**
Standard Migration

@ForgeFlow

Depends on:

- https://github.com/OCA/web/pull/2141

### CODE REVIEW

**Comment by LoisRForgeFlow** [comment]
@JasminSForgeFlow Dependency merged, could you rebase?

**Review by LoisRForgeFlow — APPROVED** [review]
:+1:

**Comment by LoisRForgeFlow** [comment]
Rebased and test fixed.

**Review by JordiBForgeFlow — APPROVED** [review]

**Pull request merged**
