### PR TITLE
[16.0][MIG] sale_order_secondary_unit: Migration to 16.0

### PR DESCRIPTION
**Pull request by anddago78**
This module extends the functionality of sale orders to allow sale products in
secondary unit of distinct category.

MT-3490 @moduon @rafaelbn @EmilioPascual @fcvalgar please reviews :)

### CODE REVIEW

**Comment by rafaelbn** [comment]
CI errors are not related to this module

`2021-10-02 15:30:00,000 250 ERROR odoo odoo.addons.sale_order_product_recommendation.tests.test_recommendation: FAIL: RecommendationCaseTests.test_recommendations_last_sale_price_to_sale_order
Traceback (most recent call last):
  File "/__w/sale-workflow/sale-workflow/sale_order_product_recommendation/tests/test_recommendation.py", line 157, in test_recommendations_last_sale_price_to_sale_order
    self.assertEqual(so_line_prod1.price_unit, 24.50)
AssertionError: 25.0 != 24.5`


`2023-08-10 09:28:40,273 250 ERROR odoo odoo.addons.sale_order_qty_change_no_recompute.tests.test_sale_order_qty_change: FAIL: TestSaleOrderQtyChange.test_sale_line_misc
Traceback (most recent call last):
  File "/__w/sale-workflow/sale-workflow/sale_order_qty_change_no_recompute/tests/test_sale_order_qty_change.py", line 37, in test_sale_line_misc
    self.assertEqual(self.line_form.price_subtotal, 60)
AssertionError: 30.0 != 60`

Ready to review!

**Review by fcvalgar — APPROVED** [review]
Functional Review.
LGTM, thank you @anddago78 

https://www.loom.com/share/d5f6917a8a624fb99b31e2a047b71464?sid=16e2b4eb-8935-4619-82e0-7a3b21a5eae7

**Comment by rafaelbn** [comment]
Hello @sergio-teruel ! Do you want to take a look! 😄 🙏🏼 ❤️  Thank you!

**Comment by sergio-teruel** [comment]
I am seeing that this commit from v15 is missing
https://github.com/OCA/sale-workflow/pull/2331/files#diff-4d7e4714e57f20ebf63b3686c00dd4a264e9d3abab40e1b37eafc66f0dcf16e4

Please review your work... all changes are in v15, so I think that your origin is not at date...

**Comment by sergio-teruel** [comment]
In these commit the test of module sale_order_qty_change_no_recompute was fixed... but in your migration I do not see these fix

**Comment by rafaelbn** [comment]
Hello @anddago78 !

Thank you for this migration ❤️ 

Please:

- [ ] Attend comments of Sergio, I guess to followed the [Migration to versión 16 OCA Guidelines](https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-16.0), and somthing were wrong in the process. Could you you please repeat the process in the same PR?

- [ ] I've tested the module in Odoo 15 and this PR in Odoo 16 and this PR has a BUG because the "subtotal prices" are not updating when changing the invoicing uom when in Odoo.com runbit it works perfect. I've recorded a video where you can when this BUG and in the las 15 seconds of the video you will see how it works perfect in runbot of odoo.com. Note: in OCA 15 this module updates the price perfectly :-D


---

- This PR test: https://github.com/OCA/sale-workflow/pull/2635

https://github.com/OCA/sale-workflow/assets/8736623/ade73f27-9b90-466d-b109-86b405e1b179


---

- This is how it works actually in Odoo OCA 15 [sale_order_secondary_unit](https://github.com/OCA/sale-workflow/tree/15.0/sale_order_secondary_unit)

https://github.com/OCA/sale-workflow/assets/8736623/a6b95353-78d3-49c5-b2fe-6f871e01c5be


Thank you! Let's rock! ⭐ 🚀

**Comment by rafaelbn** [comment]
Superseed by https://github.com/OCA/sale-workflow/pull/2645

**Pull request closed without merging**
