### PR TITLE
[15.0][MIG] sale_procurement_amendment

### PR DESCRIPTION
**Pull request by dalonsod**
~~Standard migration. Depends on #3119~~ 

**Edit**: standard migration + remove redundant dependencies + test little enhacement

### CODE REVIEW

**Comment by dalonsod** [comment]
@rousseldenis could you review? Thanks!

**Comment by rousseldenis** [comment]
@dalonsod This is not needed anymore as Odoo has fulfilled this functionality : https://github.com/odoo/odoo/blob/15.0/addons/sale_stock/models/sale_order.py#L439

**Comment by dalonsod** [comment]
🤦 thanks for the info @rousseldenis . Closing this

**Pull request closed without merging**
