### PR TITLE
[15.0][IMP] sale_payment_sheet: Add invoice totals in wizard tree

### PR DESCRIPTION
**Pull request by carlosdauden**
@Tecnativa TT51739

### CODE REVIEW

**Comment by carlosdauden** [comment]
ping @sergio-teruel @pilarvargas-tecnativa

**Review by sergio-teruel — APPROVED** [review]
LGTM Code review and functional test

**Review by pilarvargas-tecnativa — APPROVED** [review]

**Comment by pedrobaeza** [comment]
Please fw-port it to upper versions.

**Pull request merged**
