### PR TITLE
[15.0][MIG]sale_discount_display_amount

### PR DESCRIPTION
**Pull request by manuelregidor**
Supersedes: https://github.com/OCA/sale-workflow/pull/1914

### CODE REVIEW

**Comment by manuelregidor** [comment]
@HaraldPanten @ValentinVinagre

**Review by ValentinVinagre — APPROVED** [review]
LGTM 👍🏻

**Review by ajaniszewska-dev — APPROVED** [review]

**Review by HaraldPanten — APPROVED** [review]

**Pull request merged**
