### PR TITLE
[14.0][MIG] sale_blanket_order

### PR DESCRIPTION
**Pull request by tafaRU**

### CODE REVIEW

**Comment by tafaRU** [comment]
Travis error seems not related to this module but to `sale_shipping_info_helper` (ref [link](https://app.travis-ci.com/github/OCA/sale-workflow/jobs/555432793#L3103-L3107)). I'm checking it.

**Comment by tafaRU** [comment]
@janikvonrotz could you please review it?

**Review by janikvonrotz — APPROVED** [review]

**Comment by jado95** [comment]
Hi @tafaRU , when i add product on sale blanket order line, the tax added is wrong. It add credit tax and not debit tax. Is only my problem?

**Comment by francesco-ooops** [comment]
> Hi @tafaRU , when i add product on sale blanket order line, the tax added is wrong. It add credit tax and not debit tax. Is only my problem?

This issue was referenced also in #1493 and #960 but I never understood why supplier tax is used

**Comment by tafaRU** [comment]
> when i add product on sale blanket order line, the tax added is wrong. It add credit tax and not debit tax. Is only my problem?

@jado95, this behaviour should be fixed in https://github.com/OCA/sale-workflow/pull/1865/commits/d27bb6f0c1e94339247e3b403f8caf8f30f5c32f Are you testing also including this latter?

**Review by francesco-ooops — APPROVED** [review]
Tested on both runbot and runboat and tax displayed is sales one (correct)

**Review by fredzamoabg — APPROVED** [review]
LGTM

**Comment by jado95** [comment]
> > when i add product on sale blanket order line, the tax added is wrong. It add credit tax and not debit tax. Is only my problem?
> 
> @jado95, this behaviour should be fixed in [d27bb6f](https://github.com/OCA/sale-workflow/commit/d27bb6f0c1e94339247e3b403f8caf8f30f5c32f) Are you testing also including this latter?

Perfect, with that commit is ok for me

**Review by jado95 — APPROVED** [review]

**Comment by rousseldenis** [comment]
@tafaRU Have you found the problem with Travis ?

**Comment by tafaRU** [comment]
> @tafaRU Have you found the problem with Travis ?

Hi @rousseldenis! Unfortunately not yet, today I should get back to working on it.

**Comment by tafaRU** [comment]
@rousseldenis finally I found it (see https://github.com/OCA/sale-workflow/pull/1865/commits/2da2b645f60c05095b6e8756630fa539b883a716) ! Could we merge now? What do you think?

**Comment by rousseldenis** [comment]
> @rousseldenis finally I found it (see [2da2b64](https://github.com/OCA/sale-workflow/commit/2da2b645f60c05095b6e8756630fa539b883a716)) ! Could we merge now? What do you think?

Seems legit

**Pull request merged**
