### PR TITLE
[10.0][FIX][sale_product_set] incompatibility with sale_margin

### PR DESCRIPTION
**Pull request by MiquelRForgeFlow**
Port of https://github.com/OCA/sale-workflow/pull/513.

### CODE REVIEW

**Review by LoisRForgeFlow — APPROVED** [review]
LGTM

Thanks!

**Review by pedrobaeza — APPROVED** [review]

**Comment by pedrobaeza** [comment]
Please check Travis.

**Comment by MiquelRForgeFlow** [comment]
Fixed :green_apple:

**Review by JordiBForgeFlow — APPROVED** [review]

**Comment by pedrobaeza** [comment]
Can I squash on merge? Or do you squash at least last 2 commits?

**Comment by MiquelRForgeFlow** [comment]
Squash on merge :+1:

**Pull request merged**
