### PR TITLE
[15.0][IMP] sale_delivery_state: migration script

### PR DESCRIPTION
**Pull request by manuelregidor**
Based on https://github.com/OCA/sale-workflow/pull/3285

T-6522

### CODE REVIEW

**Comment by manuelregidor** [comment]
@HaraldPanten @ValentinVinagre @jbaudoux Could you review, please?

**Review by HaraldPanten — APPROVED** [review]

**Comment by HaraldPanten** [comment]
@etobella @pedrobaeza could you help with a quick review of this PR?

THX in advance!

**Comment by pedrobaeza** [comment]
Why not using `openupgradelib` that contains a function for giving a default value through `add_fields`?

**Review by pedrobaeza — APPROVED** [review]

**Comment by pedrobaeza** [comment]
Next time, this is `[OU-ADD]` for adding migration scripts.

**Comment by HaraldPanten** [comment]
> Next time, this is `[OU-ADD]` for adding migration scripts.

Is that in the official documentation? I don't remember this point... 🤔

**Comment by pedrobaeza** [comment]
It's not yet included indeed.

**Pull request merged**
