### PR TITLE
 [MIG] sale_order_line_date: Migration to 17.0

### PR DESCRIPTION
**Pull request by yannoliv**

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Thanks for the contribution.

Please preserve commit history following technical method explained in https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-16.0.

If the jump is between several versions, you have to modify the source branch in the main command to accommodate it to this circumstance.

Check also the pre-commit error.

**Comment by rousseldenis** [comment]
@yannoliv Commit history is still wrong

**Comment by rousseldenis** [comment]
Moreover, there is already another PR for this. Could you close this and review #2962 instead ?

**Pull request closed without merging**
