### PR TITLE
[FIX] don't rename parameters in product_id_change

### PR DESCRIPTION
**Pull request by gurneyalex**
some addons such as sale_stock call it with named arguments
and this will cause a crash if you rename e.g. the product arg
to product_id.

### CODE REVIEW

**Comment by mdietrichc2c** [comment]
:+1:

**Comment by guewen** [comment]
:+1:

**Comment by yvaucher** [comment]
:+1:

**Comment by gurneyalex** [comment]
runbot is red (warnings in the logs) also on the 7.0 branch

**Comment by pedrobaeza** [comment]
:+1:

**Pull request merged**
