### PR TITLE
[14.0][FW] sale_automatic_workflow: port from 12.0/13.0

### PR DESCRIPTION
**Pull request by kv1612**
Port PRs from 12.0/13.0 to 14.0

- https://github.com/OCA/sale-workflow/pull/1167
- https://github.com/OCA/sale-workflow/pull/1337
- https://github.com/OCA/sale-workflow/pull/1526
- https://github.com/OCA/sale-workflow/pull/1576
- https://github.com/OCA/sale-workflow/pull/1673/commits/4e4359066270dbea0edd01e02029a1687a8484dd
- https://github.com/OCA/sale-workflow/pull/1677
- https://github.com/OCA/sale-workflow/pull/1782

This commit to fix tests case for module `sale_automatic_workflow_payment_mode`: https://github.com/OCA/sale-workflow/pull/1789/commits/ad999eb5ad3861322ae6728c5bbec63d780ecaf5

### CODE REVIEW

**Review by sebalix — COMMENTED** [review]
@kv1612 Hi, thank you for these ports! Some comments:
- Original PR #1337 was forcing the company through the user's context when dealing with orders and invoices, is there a reason why the ported commit doesn't reflect this? (not needed anymore in v14?)
- not sure to understand the content of the last commit f47587d7deadd95afed29db99340c40262957790 , is it a fix ported from v13 (which one)? Or a fix you did on your own (in that case a proper commit message explaining what you fixed is welcome)?

**Comment by kv1612** [comment]
Hi @sebalix,

**Comment by kv1612** [comment]
Hi @sebalix,

**Comment by kv1612** [comment]
Hi @sebalix,

- about [PR #1337](https://github.com/OCA/sale-workflow/pull/1337): in v14, we use `with_company` instead. So, I think it's not needed anymore in v14
- about commit [f47587d](https://github.com/OCA/sale-workflow/commit/f47587d7deadd95afed29db99340c40262957790): 

> * The fix is originally in `[MIG] sale_automatic_workflow_payment_mode: Migration to 14.0`.
     * Migrated to 14.0: https://github.com/OCA/sale-workflow/pull/1590/commits/d549fcafb86e3e6567f3587215b2ba269122611d#diff-644e82d43704d0eaa176dc9665558b4fc83117394397847ea859a524b432e6beR72

> * When porting `[IMP] sale_automatic_workflow`, the ported commit does not have that fix
     * 13.0: https://github.com/OCA/sale-workflow/pull/1673/commits/4e4359066270dbea0edd01e02029a1687a8484dd#diff-87a59a699d3d1a4901d848f8116ccd51627cc0b64621732d4a348fc1a27e31f6R175
     * Ported to 14.0: https://github.com/OCA/sale-workflow/pull/1789/commits/1c401324f0b5ee45bd237b7c8755727098d49502#diff-87a59a699d3d1a4901d848f8116ccd51627cc0b64621732d4a348fc1a27e31f6R167

**Comment by sebalix** [comment]
@kv1612 ok, so better to reword the commit as it is not really part of the migration but a new fix. Having it worded as a migration commit doesn't help to understand what we want to fix, especially because the addon is already migrated to 14.0

**Comment by kv1612** [comment]
Hi @sebalix, this PR has been updated. I changed commit message for the last commit. Thank you.

**Review by sebalix — APPROVED** [review]

**Review by leemannd — APPROVED** [review]

**Pull request merged**
