### PR TITLE
[16.0][ADD] sale_invoice_frequency

### PR DESCRIPTION
**Pull request by Shide**
This module extends the functionality of sales to support group by Invoicing frequency
and to allow you to choose the right orders to invoice based on the frequency defined
on the customer.

MT-3519 @moduon @yajo @rafaelbn @fcvalgar please review

### CODE REVIEW

**Review by yajo — APPROVED** [review]
Code & functional review.

**Review by fcvalgar — APPROVED** [review]
LGTM, thank you @Shide 

image

**Comment by Shide** [comment]
Added translation to the name of Invoicing Frequencies

**Review by yajo — CHANGES_REQUESTED** [review]
Please update the `es.po`

**Comment by Shide** [comment]
@yajo bot deploys old version. On Monday I'll pr again

**Pull request closed without merging**
