### PR TITLE
[10.0][MIG] sale_start_end_dates and sale_rental

### PR DESCRIPTION
**Pull request by SodexisTeam**
Needs PR https://github.com/OCA/account-closing/pull/41 to be merged

### CODE REVIEW

**Comment by Ehtaga** [comment]
Hi @SodexisTeam . Now that OCA/account-closing#41is merged, could you have a look at that MR? Thanks in advance

**Comment by dvdhinesh** [comment]
@Ehtaga It was mentioned in the sense that the Travis build will fail due to the missing dependency.
Now that has been merged, someone needs to review this PR.

**Comment by alexis-via** [comment]
When you confirm a "rental sale order" for 1 product during 4 days, the product qty in the 2 generated picking is 4 (instead of 1). My PR fixes it: https://github.com/sodexis/sale-workflow/pull/2 Please merge it to update this PR.
We'll need to backport this fix in v9.

**Review by alexis-via — APPROVED** [review]

**Review by xavier-dass — APPROVED** [review]
code and functional review done :+1:

**Review by atchuthan — APPROVED** [review]
:+1:

**Pull request merged**
