### PR TITLE
[UPG] sale_quotation_number 11->12

### PR DESCRIPTION
**Pull request by richard-willdooit**

### CODE REVIEW

**Comment by richard-willdooit** [comment]
@murtuzasaleh 

I wonder if you would be able to take a look at this?

**Comment by HaraldPanten** [comment]
Hi @pedrobaeza could you close this one? travis is failing, guidelines are not being followed and it seems to be "abandoned".

We opened another one, instead. THX

**Comment by richard-willdooit** [comment]
@HaraldPanten @pedrobaeza Not abandoned.  Back at that stage, every PR was failing builds.  (odoo.addons.sale_stock_secondary_unit.tests.test_sale_stock_secondary_unit: ERROR) and I was waiting for notification that was taken care of.

Anyway, I am trying to make contributions, and find it hard to get anyone to look at them, - could you let me know what guidelines I did not follow?

**Comment by richard-willdooit** [comment]
@HaraldPanten @pedrobaeza We are using this with 3 of our clients, and they have agreed that the extra suggestions I have made on #1196 are important.

**Comment by pedrobaeza** [comment]
Check https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-13.0 and you'll see that for example you haven't preserved commit history. If you can extract the extra suggestions and propose them over the other PR or comment then in it, then it can be added in the merge.

**Pull request closed without merging**
