### PR TITLE
[13.0][FIX] sale_product_set: Define multi-company rules correctly.

### PR DESCRIPTION
**Pull request by victoralmau**
Define multi-company rules correctly.

We need to apply this to v14 as well.

Please @pedrobaeza and  @CarlosRoca13 can you review it?

@Tecnativa TT34555

### CODE REVIEW

**Review by rousseldenis — APPROVED** [review]
Trivial

**Review by pedrobaeza — APPROVED** [review]
No need of migration scripts, being noupdate=0

**Comment by pedrobaeza** [comment]
Cherry-picked to v14 at 4766ba7a176231bfd96a8692b5dd1633fc62b963

**Comment by rousseldenis** [comment]
> Cherry-pick to v14 at [4766ba7](https://github.com/OCA/sale-workflow/commit/4766ba7a176231bfd96a8692b5dd1633fc62b963)

@pedrobaeza You didn't do a PR. Travis is red. Can you fix ?

**Comment by rousseldenis** [comment]
> > Cherry-pick to v14 at [4766ba7](https://github.com/OCA/sale-workflow/commit/4766ba7a176231bfd96a8692b5dd1633fc62b963)
> 
> @pedrobaeza You didn't do a PR. Travis is red. Can you fix ?

Using oca-port-pr is the best tool to forwardport/backport PR's. Please use it instead of pushing directly. Thanks

**Comment by pedrobaeza** [comment]
Local tests passed. The problem is not in this cherry-pick: https://app.travis-ci.com/github/OCA/sale-workflow/jobs/563225847#L3450

**Comment by pedrobaeza** [comment]
> Using oca-port-pr is the best tool to forwardport/backport PR's. Please use it instead of pushing directly. Thanks

I don't want to charge CIs with no gain, so I cherry-pick clear commits on a maintainer role.

**Comment by rousseldenis** [comment]
> Local tests passed. The problem is not in this cherry-pick: https://app.travis-ci.com/github/OCA/sale-workflow/jobs/563225847#L3450

Your build was cancelled.... https://app.travis-ci.com/github/OCA/sale-workflow/builds/247855500

**Comment by rousseldenis** [comment]
> > Using oca-port-pr is the best tool to forwardport/backport PR's. Please use it instead of pushing directly. Thanks
> 
> I don't want to charge CIs with no gain, so I cherry-pick clear commits on a maintainer role.

Nice to have  @OCA/core-maintainers advice on this assertion...

**Comment by pedrobaeza** [comment]
> Your build was cancelled.... https://app.travis-ci.com/github/OCA/sale-workflow/builds/247855500

Yes, because another one arises on the commit that updates the README.md. That's the normal flow when having such variable README (that I don't like due to this constant changing).

**Comment by rousseldenis** [comment]
The normal flow is to use ocabot on OCA... Please use it. Do what you want on you repositories

**Comment by pedrobaeza** [comment]
A 2 lines patch can be cherry-picked by a PSC, maintainer or core maintainer without overloading the already bulked OCA stuff. I don't get why you are so harsh with me when we both want to make OCA greater. If I don't take these legal shortcuts (when valid and without doing any harm - I have fixed more red CIs coming from others than mine -), I would contribute half of the contributions I do.

**Comment by simahawk** [comment]
hey hey, guys, relax :)

@pedrobaeza while agree that sometimes we can take shortcuts this is clearly an issue coming indirectly from that commit, which a PR on v14 could spot before merging.

```
2022-03-14 15:22:38,361 9470 INFO openerp_test odoo.addons.sale_product_set.tests.test_product_set: Starting TestProductSet.test_discount ...
2022-03-14 15:22:38,474 9470 WARNING openerp_test odoo.models: onchange method SaleOrderLine._onchange_product_id_set_lot_domain returned a domain, this is deprecated
2022-03-14 15:22:38,504 9470 INFO openerp_test odoo.addons.sale_product_set.tests.test_product_set: ======================================================================
2022-03-14 15:22:38,504 9470 ERROR openerp_test odoo.addons.sale_product_set.tests.test_product_set: FAIL: TestProductSet.test_discount
Traceback (most recent call last):
File "/home/travis/build/OCA/sale-workflow/setup/sale_product_set/odoo/addons/sale_product_set/tests/test_product_set.py", line 163, in test_discount
wiz.add_set()
File "/home/travis/build/OCA/sale-workflow/setup/sale_product_set/odoo/addons/sale_product_set/wizard/product_set_add.py", line 88, in add_set
order_lines = self._prepare_order_lines()
File "/home/travis/build/OCA/sale-workflow/setup/sale_product_set/odoo/addons/sale_product_set/wizard/product_set_add.py", line 102, in _prepare_order_lines
set_line, max_sequence=max_sequence
File "/home/travis/build/OCA/sale-workflow/setup/sale_product_set/odoo/addons/sale_product_set/wizard/product_set_add.py", line 128, in prepare_sale_order_line_data
line_values.update(sol_model.play_onchanges(line_values, line_values.keys()))
File "/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/odoo/addons/onchange_helper/models/base.py", line 60, in play_onchanges
onchange_values = self.onchange(all_values, field, onchange_specs)
File "/home/travis/odoo-14.0/odoo/models.py", line 6264, in onchange
record._onchange_eval(name, field_onchange[name], result)
File "/home/travis/build/OCA/sale-workflow/setup/sale_order_qty_change_no_recompute/odoo/addons/sale_order_qty_change_no_recompute/models/sale_order.py", line 29, in _onchange_eval
return super()._onchange_eval(field_name, onchange, result)
File "/home/travis/odoo-14.0/odoo/models.py", line 6006, in _onchange_eval
method_res = method(self)
File "/home/travis/build/OCA/sale-workflow/setup/sale_blanket_order/odoo/addons/sale_blanket_order/models/sale_orders.py", line 111, in onchange_product_id
return self.get_assigned_bo_line()
File "/home/travis/build/OCA/sale-workflow/setup/sale_blanket_order/odoo/addons/sale_blanket_order/models/sale_orders.py", line 104, in get_assigned_bo_line
self.onchange_blanket_order_line()
File "/home/travis/build/OCA/sale-workflow/setup/sale_blanket_order/odoo/addons/sale_blanket_order/models/sale_orders.py", line 138, in onchange_blanket_order_line
self.with_context(skip_blanket_find=True).product_uom_change()
File "/home/travis/build/OCA/sale-workflow/setup/sale_blanket_order/odoo/addons/sale_blanket_order/models/sale_orders.py", line 116, in product_uom_change
res = super().product_uom_change()
File "/home/travis/build/OCA/sale-workflow/setup/sale_pricelist_from_commitment_date/odoo/addons/sale_pricelist_from_commitment_date/models/sale_order_line.py", line 22, in product_uom_change
self.with_context(force_pricelist_date=self.order_id.commitment_date),
File "/home/travis/odoo-14.0/addons/sale/models/sale.py", line 1767, in product_uom_change
product_currency=self.currency_id
File "/home/travis/odoo-14.0/addons/account/models/product.py", line 132, in _get_tax_included_unit_price
product_price_unit = product_currency._convert(product_price_unit, currency, company, document_date)
File "/home/travis/odoo-14.0/odoo/addons/base/models/res_currency.py", line 192, in _convert
assert company, "convert amount from unknown company"
AssertionError: convert amount from unknown company
```

Anyway, both of you... please, don't waste time and mood criticizing/complaining/pick-yours at each other.
We all take "risks" some times and normally we all fix the problems we created or others created :wink: 

That being said: @pedrobaeza could you kindly have a look at it and fix it (or at least propose a solution if you don't have time)?

**Comment by pedrobaeza** [comment]
It's not something from that commit, but a change upstream. Luckily, @rousseldenis has found it and fix it in #1949

**Comment by rousseldenis** [comment]
> hey hey, guys, relax :)
> 
> @pedrobaeza while agree that sometimes we can take shortcuts this is clearly an issue coming indirectly from that commit, which a PR on v14 could spot before merging.
> 
> ```
> 2022-03-14 15:22:38,361 9470 INFO openerp_test odoo.addons.sale_product_set.tests.test_product_set: Starting TestProductSet.test_discount ...
> 2022-03-14 15:22:38,474 9470 WARNING openerp_test odoo.models: onchange method SaleOrderLine._onchange_product_id_set_lot_domain returned a domain, this is deprecated
> 2022-03-14 15:22:38,504 9470 INFO openerp_test odoo.addons.sale_product_set.tests.test_product_set: ======================================================================
> 2022-03-14 15:22:38,504 9470 ERROR openerp_test odoo.addons.sale_product_set.tests.test_product_set: FAIL: TestProductSet.test_discount
> Traceback (most recent call last):
> File "/home/travis/build/OCA/sale-workflow/setup/sale_product_set/odoo/addons/sale_product_set/tests/test_product_set.py", line 163, in test_discount
> wiz.add_set()
> File "/home/travis/build/OCA/sale-workflow/setup/sale_product_set/odoo/addons/sale_product_set/wizard/product_set_add.py", line 88, in add_set
> order_lines = self._prepare_order_lines()
> File "/home/travis/build/OCA/sale-workflow/setup/sale_product_set/odoo/addons/sale_product_set/wizard/product_set_add.py", line 102, in _prepare_order_lines
> set_line, max_sequence=max_sequence
> File "/home/travis/build/OCA/sale-workflow/setup/sale_product_set/odoo/addons/sale_product_set/wizard/product_set_add.py", line 128, in prepare_sale_order_line_data
> line_values.update(sol_model.play_onchanges(line_values, line_values.keys()))
> File "/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/odoo/addons/onchange_helper/models/base.py", line 60, in play_onchanges
> onchange_values = self.onchange(all_values, field, onchange_specs)
> File "/home/travis/odoo-14.0/odoo/models.py", line 6264, in onchange
> record._onchange_eval(name, field_onchange[name], result)
> File "/home/travis/build/OCA/sale-workflow/setup/sale_order_qty_change_no_recompute/odoo/addons/sale_order_qty_change_no_recompute/models/sale_order.py", line 29, in _onchange_eval
> return super()._onchange_eval(field_name, onchange, result)
> File "/home/travis/odoo-14.0/odoo/models.py", line 6006, in _onchange_eval
> method_res = method(self)
> File "/home/travis/build/OCA/sale-workflow/setup/sale_blanket_order/odoo/addons/sale_blanket_order/models/sale_orders.py", line 111, in onchange_product_id
> return self.get_assigned_bo_line()
> File "/home/travis/build/OCA/sale-workflow/setup/sale_blanket_order/odoo/addons/sale_blanket_order/models/sale_orders.py", line 104, in get_assigned_bo_line
> self.onchange_blanket_order_line()
> File "/home/travis/build/OCA/sale-workflow/setup/sale_blanket_order/odoo/addons/sale_blanket_order/models/sale_orders.py", line 138, in onchange_blanket_order_line
> self.with_context(skip_blanket_find=True).product_uom_change()
> File "/home/travis/build/OCA/sale-workflow/setup/sale_blanket_order/odoo/addons/sale_blanket_order/models/sale_orders.py", line 116, in product_uom_change
> res = super().product_uom_change()
> File "/home/travis/build/OCA/sale-workflow/setup/sale_pricelist_from_commitment_date/odoo/addons/sale_pricelist_from_commitment_date/models/sale_order_line.py", line 22, in product_uom_change
> self.with_context(force_pricelist_date=self.order_id.commitment_date),
> File "/home/travis/odoo-14.0/addons/sale/models/sale.py", line 1767, in product_uom_change
> product_currency=self.currency_id
> File "/home/travis/odoo-14.0/addons/account/models/product.py", line 132, in _get_tax_included_unit_price
> product_price_unit = product_currency._convert(product_price_unit, currency, company, document_date)
> File "/home/travis/odoo-14.0/odoo/addons/base/models/res_currency.py", line 192, in _convert
> assert company, "convert amount from unknown company"
> AssertionError: convert amount from unknown company
> ```
> 
> Anyway, both of you... please, don't waste time and mood criticizing/complaining/pick-yours at each other. We all take "risks" some times and normally we all fix the problems we created or others created wink
> 
> That being said: @pedrobaeza could you kindly have a look at it and fix it (or at least propose a solution if you don't have time)?

IMHO "the already bulked OCA stuff" is there to have some guards (even if they are not perfect).

Some found them bulky, but I think they are useful in such cases. Moreover, I think improvements have been made these months in order to keep github checks as light as possible. So, not bypassing them would avoid this noise.

My two cents

**Comment by pedrobaeza** [comment]
Of course CIs are them as the best quality assurance one. But having to pass 3 complete pipelines for this cherry-pick is totally bulked. That's why I do the shortcut of passing just one. What I don't understand is why I haven't received the CI failing notification.

**Comment by rousseldenis** [comment]
Because of oca-git-bot that updated repo README canceled your build

https://github.com/OCA/sale-workflow/commit/186d6bc8ea4add8d13ede36af51fe1d92e47c643

**Comment by rousseldenis** [comment]
> . But having to pass 3 complete pipelines for this cherry-pick is totally bulked

You can see it is taking 10 minutes to pass. Not bulked IMHO

https://github.com/OCA/sale-workflow/runs/5554261902

**Pull request merged**
