### PR TITLE
[8.0][FIX] sale_payment_method_automatic_workflow: fix write off when reconcile payment in foreign currency

### PR DESCRIPTION
**Pull request by Cedric-Pigeon**

### CODE REVIEW

**Comment by elicoidal** [comment]
strange for the Runbot: no obvious reasons

**Comment by Cedric-Pigeon** [comment]
indeed I don't understand

**Comment by LoisRForgeFlow** [comment]
The problem seems to be in other modules. <a href="https://github.com/acsone/sale-workflow/blob/8.0-automatic_workflow-cpi/sale_rental/rental.py#L47">This method</a> has as constraint <a href="https://github.com/acsone/sale-workflow/blob/8.0-automatic_workflow-cpi/sale_start_end_dates/sale.py#L83">a non writable field</a>.

to remove it from the constrain in a separate fix PR may solve this and prevent it to happen again. What do you think?

**Comment by rousseldenis** [comment]
Closing this as no activity. @Cedric-Pigeon  Please feel free to reopen it if you still need it. Take care of your PR's

**Pull request closed without merging**
