### PR TITLE
[MIG] sale_wishlist: Migration to 13.0

### PR DESCRIPTION
**Pull request by simahawk**

### CODE REVIEW

**Comment by rousseldenis** [comment]
@simahawk Do you plan to improve coverage ?

**Review by rousseldenis — APPROVED** [review]
Code review

**Comment by rousseldenis** [comment]
Great! You squash before merge?

**Review by lmignon — APPROVED** [review]
Code review + functional

**Comment by simahawk** [comment]
@rousseldenis I prefer to keep it separated: we can cherry-pick test cov commit to v12.

**Pull request merged**
