### PR TITLE
[14.0][MIG] sale_automatic_workflow_job: Migrate to version 14.0

### PR DESCRIPTION
**Pull request by hailangvn**

### CODE REVIEW

**Review by leemannd — APPROVED** [review]

**Review by simahawk — APPROVED** [review]

**Comment by rousseldenis** [comment]
@hailangvn @simahawk Please check before proposing a PR if another one is not present.

https://github.com/OCA/sale-workflow/pull/1855

**Comment by simahawk** [comment]
ops, sorry, I missed it :disappointed:

**Comment by hailangvn** [comment]
> @hailangvn @simahawk Please check before proposing a PR if another one is not present.
> 
> #1855

Agree that we should avoid duplicated work. But we need to consider the how. We have three options.
1. Everyone should follow process: update [Migration Issue](https://github.com/OCA/sale-workflow/issues/1274) before doing migration;
2. Someone follows 1. and someone does not, extra two tasks are a) to search for PR before doing migration; + b) to search for PR before  creating PR;
3. Drop process to update [Migration Issue](https://github.com/OCA/sale-workflow/issues/1274) and do a) + b) only;

IMHO Number 1. is the ideal one and PR not registered in [Migration Issue] will be considered as redundant and for reference only. Number 2. has most work and number 3 still cause duplicated work. Is there other way?

Good day @saxomanu, @yostashiro, may I know about your thought?

**Pull request merged**
