### PR TITLE
[16.0][MIG] sale_order_qty_change_no_recompute: Migration to 16.0

### PR DESCRIPTION
**Pull request by ignissak**
https://github.com/OCA/sale-workflow/issues/2215

### CODE REVIEW

**Review by ghost — APPROVED** [review]

**Review by amarcosg — APPROVED** [review]
I like this approach

**Review by pedrobaeza — CHANGES_REQUESTED** [review]
Adding that field is an overhead that shouldn't be for something transient like this

**Comment by rousseldenis** [comment]
@ignissak

**Comment by pedrobaeza** [comment]
A proper migration has been implemented in #2473, as this one only covers changes in the UI, not by code, and it uses an extra field with possible side effects, so closing.

**Pull request closed without merging**
