### PR TITLE
[11.0][FIX] sale_stock_delivery_address: do not limit destination address,

### PR DESCRIPTION
**Pull request by LoisRForgeFlow**
can be used as a dropshipping mechanism.

I have encountered the problem that @rousseldenis [already anticipated](https://github.com/OCA/sale-workflow/pull/1068#discussion_r380604623) and I thought won't be an issue. "It is wise to rectify" elders say :older_man:

@ForgeFlow

### CODE REVIEW

**Review by HaraldPanten — APPROVED** [review]
Minor change, LGTM 👍

**Review by etobella — APPROVED** [review]

**Review by gurneyalex — APPROVED** [review]

**Review by AdriaGForgeFlow — APPROVED** [review]

**Comment by AaronHForgeFlow** [comment]
travis is not happy

**Comment by rousseldenis** [comment]
@LoisRForgeFlow Could you rebase, I think you haven't the last change in sale_exception module?

**Comment by LoisRForgeFlow** [comment]
@rousseldenis Done!

**Pull request merged**
