### PR TITLE
IMP add exceptions in quotation tree view

### PR DESCRIPTION
**Pull request by jjscarafia**
Actually main exception is only visible on confirmed sale orders tree view. This PR add it also in draft sale order tree view.

Thanks for this incredible module!

### CODE REVIEW

**Comment by pedrobaeza** [comment]
:+1:

**Comment by jjscarafia** [comment]
ping...
Any news with this? Is a simple PR...

**Comment by max3903** [comment]
:+1:

**Comment by jjscarafia** [comment]
Thanks!

**Pull request merged**
