### PR TITLE
8.0 port sale_exception_nostock

### PR DESCRIPTION
**Pull request by yvaucher**

### CODE REVIEW

**Comment by lepistone** [comment]
thanks :+1:

**Comment by eLBati** [comment]
Here is the diff between 7.0 and 8.0 if it may help http://pastie.org/9548060

**Comment by eLBati** [comment]
:+1:

**Comment by gurneyalex** [comment]
caution with `api.one`: it wraps the result in a list. For predicate methods, you're generally better off using `api.multi` + self.ensure_one() in the body to raise if more than 1 id was passed. 

Otherwise the caller may receive `[False]` as return value, which is True-ish.

**Comment by gurneyalex** [comment]
:+1:

**Pull request merged**
