### PR TITLE
[15.0] [MIG] sale_order_price_recalculation

### PR DESCRIPTION
**Pull request by JasminSForgeFlow**
Standard Migration

@ForgeFlow

### CODE REVIEW

**Review by AaronHForgeFlow — CHANGES_REQUESTED** [review]
> Inside a sale order, you can click on “Recalculate prices” to launch a recalculation of all the prices of the lines, losing previous custom prices.

I can't see that button

**Comment by JasminSForgeFlow** [comment]
> > Inside a sale order, you can click on “Recalculate prices” to launch a recalculation of all the prices of the lines, losing previous custom prices.
> 
> I can't see that button

Button will be visible in draft and sent state only

You can check it here http://oca-sale-workflow-15-0-pr2139-487d907a8d49.runboat.odoo-community.org/web#cids=1&menu_id=271&action=420&model=sale.order&view_type=form&id=27

Thanks

**Comment by AaronHForgeFlow** [comment]
But in previous versions, it was also available in sales order state. Why that change?

**Comment by JasminSForgeFlow** [comment]
> But in previous versions, it was also available in sales order state. Why that change?

It was like this in v13 
https://github.com/OCA/sale-workflow/blob/13.0/sale_order_price_recalculation/views/sale_order_view.xml

Thanks

**Review by AaronHForgeFlow — APPROVED** [review]
Functional review

**Comment by AaronHForgeFlow** [comment]
@JasminSForgeFlow when reviewing the PR in version 14, I thought I was able to do the recalculation after confirmation. But I was not. Sorry for the confusion.

**Comment by sonhd91** [comment]
This PR work fine and test case passed too

**Review by DavidJForgeFlow — APPROVED** [review]
LGTM!

**Pull request merged**
