### PR TITLE
[15.0][IMP] Update deprecated warnings

### PR DESCRIPTION
**Pull request by CRogos**
There are a lot of warnings in the unit tests.

### CODE REVIEW

**Comment by CRogos** [comment]
Am I understading the warning correctly that it means remove the return value?

2022-09-30 12:20:45,491 249 WARNING odoo odoo.models: onchange method SaleOrderLine.product_uom_change returned a domain, this is deprecated 
image

like this:
image

**Review by MiquelRForgeFlow — APPROVED** [review]

**Review by ivantodorovich — APPROVED** [review]

**Comment by ivantodorovich** [comment]
Could you set the PR as "ready to review" ? (It's currently on draft)

**Comment by CRogos** [comment]
@ivantodorovich there are a lot more warnings to cleanup. Do you have an answer on my question above. Can the onchange methods be changed as suggested?

**Comment by ivantodorovich** [comment]
I take this is the faulty line: https://github.com/OCA/sale-workflow/blob/3983568e105f6c281be4a474b92fc4a647f04d4e/sale_blanket_order/models/sale_orders.py#L105

Indeed returning a domain from an onchange method has been deprecated. But the fix is not just about removing that line nor having the onchange return nothing.

The code needs to be refactored to find another alternative to filter the available `blanket_order_line`, that doesn't require returing a domain from an onchange. Possibly using a computed field for the `eligible_bo_lines`, or maybe using the module https://github.com/OCA/web/tree/15.0/web_domain_field

But since I'm not familiar with `sale_blanket_order` module, maybe it should be discussed with its maintainers

**Comment by MiquelRForgeFlow** [comment]
My suggestion is merging this PR as it is now, and then open a new one when someone has a clear idea how to solve the pending warnings.

**Comment by ivantodorovich** [comment]
I agree

**Review by sergio-teruel — APPROVED** [review]

**Pull request merged**
