### PR TITLE
[12.0][ADD] product_form_sale_link

### PR DESCRIPTION
**Pull request by rousseldenis**
product_sale

See also : https://github.com/OCA/purchase-workflow/pull/715

### CODE REVIEW

**Comment by rafaelbn** [comment]
Then product_form_sale_link ? :smile:

**Review by rafaelbn — APPROVED** [review]

**Comment by legalsylvain** [comment]
> Then product_form_sale_link ?

:+1:

**Comment by pedrobaeza** [comment]
I would bet for `product_sale_info`

**Comment by rafaelbn** [comment]
The name should be the same as https://github.com/OCA/purchase-workflow/pull/715#issuecomment-510472820

**Review by AdriaGForgeFlow — APPROVED** [review]
LGTM after renaming :+1:

**Comment by rafaelbn** [comment]
@rousseldenis could you please rename? Thanks!

**Review by HaraldPanten — COMMENTED** [review]
Just a small comment.

I think you should change README, as it says:

"Choose a product and click on **'Purchases' button**."

Shouldn't it say **'Sales' button**?

**Comment by rafaelbn** [comment]
@rousseldenis a minor fix in readme and merging! --> https://github.com/OCA/sale-workflow/pull/897#pullrequestreview-263624474

**Review by rafaelbn — CHANGES_REQUESTED** [review]
Just https://github.com/OCA/sale-workflow/pull/897#pullrequestreview-263624474

**Comment by rafaelbn** [comment]
Hi @rousseldenis ths is blocked because https://github.com/OCA/sale-workflow/pull/897#pullrequestreview-263624474

> Just a small comment.
> 
> I think you should change README, as it says:
> 
> "Choose a product and click on 'Purchases' button."
> 
> Shouldn't it say 'Sales' button?

**Comment by rousseldenis** [comment]
@rafaelbn Will try to do it asap.

**Comment by rousseldenis** [comment]
@rafaelbn Done !

**Review by rafaelbn — APPROVED** [review]

**Pull request merged**
