### PR TITLE
8.0 sale_sourced_by_line - Fix is_shipped method

### PR DESCRIPTION
**Pull request by yvaucher**
Give positive attitude to method is_shipped which was always False.

### CODE REVIEW

**Comment by pedrobaeza** [comment]
:+1:

**Comment by lepistone** [comment]
a "check" method like that, with many corner cases, is a good candidate for isolated unit tests (i.e. not full stories). It can probably be tested without too much effort with the shiny `Model.new()` or mocks.

**Comment by jgrandguillaume** [comment]
I've tested it, it works. I'm in favor of having a test here. This is an important feature for invoicing process. After that, you get my :+1:

**Comment by yvaucher** [comment]
I have some tests ready on https://github.com/yvaucher/sale-workflow/tree/8.0-fix-sale_sourced_by_line-is_delivered-add-tests

But is it stalled because of: https://github.com/odoo/odoo/issues/3922

**Comment by lepistone** [comment]
I see @yvaucher . I am merging this one, you can create a PR for the tests that are stalled. Thanks!

**Pull request merged**
