### PR TITLE
[14.0][FIX] sale_procurement_group_by_line

### PR DESCRIPTION
**Pull request by MiquelRForgeFlow**
Same as https://github.com/OCA/sale-workflow/pull/2255 due to bad migration.

### CODE REVIEW

**Review by AaronHForgeFlow — APPROVED** [review]

**Comment by AaronHForgeFlow** [comment]
Functional tests :+1:

**Comment by rousseldenis** [comment]
@MiquelRForgeFlow Could you work with @AaronHForgeFlow in order to add tests following https://github.com/OCA/sale-workflow/pull/2255#issuecomment-1326230177 ? Thanks

**Comment by MiquelRForgeFlow** [comment]
@rousseldenis ready

**Review by rousseldenis — APPROVED** [review]
Code review

**Comment by rousseldenis** [comment]
@MiquelRForgeFlow minor update ?

**Comment by MiquelRForgeFlow** [comment]
I would say it's just patch.

**Comment by MiquelRForgeFlow** [comment]
@rousseldenis but if you want to say it's minor, it's up to you haha

**Pull request merged**
