### PR TITLE
[16.0][MIG] sale_advance_payment

### PR DESCRIPTION
**Pull request by Urvisha-OSI**

### CODE REVIEW

**Review by miguel-S73 — APPROVED** [review]

**Comment by HaraldPanten** [comment]
Hi,

In case you continue with the PR, could you consider this FIX , please? --> https://github.com/OCA/sale-workflow/pull/2521

THX!

**Comment by yaazkal** [comment]
@Urvisha-OSI community will appreciate any update regarding the comment of @HaraldPanten thanks

**Comment by MiquelRForgeFlow** [comment]
Also add https://github.com/OCA/sale-workflow/commit/f3f5ba17d84dc7ca4d12bd143dfb5e7f585ee5ef.

**Comment by HaraldPanten** [comment]
@Urvisha-OSI could you rebase?

**Comment by JordiBForgeFlow** [comment]
Superseded by https://github.com/OCA/sale-workflow/pull/2789

**Pull request closed without merging**
