### PR TITLE
[ADD] sale_change_price : change price of confirmed sale order

### PR DESCRIPTION
**Pull request by laetitia-gangloff**
The goal of this module is to update price (and discount) on a confirmed sale order.

### CODE REVIEW

**Comment by Cedric-Pigeon** [comment]
:+1:

**Comment by StefanRijnhart** [comment]
Could you document in the README and in the wizard form, visible to the users, that invoiced lines cannot be changed?

**Comment by pedrobaeza** [comment]
@laetitia-gangloff, are you going to work on these PR's comments?

**Comment by sbidoul** [comment]
@Cedric-Pigeon can you care about the last comments to get this merged?

**Comment by Cedric-Pigeon** [comment]
@StefanRijnhart @pedrobaeza @sbidoul Changes applied

**Review by pedrobaeza — APPROVED** [review]

**Comment by StefanRijnhart** [comment]
Thanks for the update!

**Pull request merged**
