### PR TITLE
[MIG] sale_order_lot_selection: Migration to 15.0

### PR DESCRIPTION
**Pull request by dreispt**
Supersedes #2207

### CODE REVIEW

**Comment by diggy128** [comment]
@dreispt please remove sale_order_lot_selection/i18n/en.po to make pre-commit go green.

**Comment by rousseldenis** [comment]
@dreispt Why not having tried to merge that one instead ? #2207 You did no ping to @nicomacr

**Comment by Bilbonet** [comment]
Hi @dreispt 
Could you pre-commit go green?
Thanks

**Pull request closed without merging**
