### PR TITLE
[IMP] sale_procurement_group_by_line: Update Development Status

### PR DESCRIPTION
**Pull request by JasminSForgeFlow**
@ForgeFlow

### CODE REVIEW

**Review by LoisRForgeFlow — APPROVED** [review]

**Comment by JordiBForgeFlow** [comment]
@JasminSForgeFlow Can you rebase?

**Comment by JasminSForgeFlow** [comment]
> @JasminSForgeFlow Can you rebase?

@JordiBForgeFlow this PR is up to date.

Seems issue from sale_invoice_plan as per logs

**Comment by LoisRForgeFlow** [comment]
Rebased, tests seem to be fixed. @JordiBForgeFlow Can you merge?

**Pull request merged**
