### PR TITLE
[14.0][IMP] sale_delivery_state: migration script

### PR DESCRIPTION
**Pull request by manuelregidor**
Create column skip_sale_delivery_state in sale_order_line table when upgrading the module to avoid memory error.

T-6522

### CODE REVIEW

**Comment by manuelregidor** [comment]
@ValentinVinagre @jbaudoux Could you review, please?

**Review by jbaudoux — APPROVED** [review]
Thanks. LGTM

**Review by ValentinVinagre — APPROVED** [review]
LGTM 👍🏻

**Comment by ValentinVinagre** [comment]
https://github.com/OCA/sale-workflow/issues/2818

@simahawk could u review? https://github.com/OCA/sale-workflow/pull/2845#issuecomment-2200292776

**Review by HaraldPanten — APPROVED** [review]

**Pull request merged**
