### PR TITLE
[14.0][MIG] sale_force_invoiced

### PR DESCRIPTION
**Pull request by MateuGForgeFlow**
Standard migration to v14.
cc @JordiBForgeFlow

### CODE REVIEW

**Comment by LoisRForgeFlow** [comment]
@rousseldenis Could you approve the github workflow?

**Review by rousseldenis — APPROVED** [review]
LGTM

**Comment by LoisRForgeFlow** [comment]
Thanks!

**Review by LoisRForgeFlow — APPROVED** [review]
LGTM

**Review by HaraldPanten — APPROVED** [review]
LGTM

**Pull request merged**
