### PR TITLE
[17.0][MIG] sale_substate: Migration to 17.0

### PR DESCRIPTION
**Pull request by MohamedOsman7**
Follow-up PR for #3072  with requested changes + cleaned commits history, since there is no activity on it for a long time.

### CODE REVIEW

**Comment by flotho** [comment]
Ping @gaelTorrecillas @JulienMartinez @DorianMAG , thanks for your review

**Review by rousseldenis — APPROVED** [review]

**Review by ferran-S73 — APPROVED** [review]

**Comment by CRogos** [comment]
@pedrobaeza could you merge?

**Pull request merged**
