### PR TITLE
[12.0][FIX] sale_elaboration: Tests

### LINKED ISSUE #1146: [12.0] Main branch is red on travis (sale_elaboration + sale_stock_secondary_unit).
https://travis-ci.org/github/OCA/sale-workflow/jobs/687769282#L2337

Sale order in tests is created without company_id (not required), so the invoice creation raises as it takes the one on sale order (and is required).

Last good build on 24th of April, first raise on 13th of May. 

https://github.com/OCA/sale-workflow/blob/12.0/sale_elaboration/tests/test_sale_elaboration.py#L125

Didn't find any relevant changes in Odoo code.

### PR DESCRIPTION
**Pull request by rousseldenis**
fixes #1146 partially

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Maybe it's better to use `common.Form` for populating records? Do you want me to propose such change?

**Comment by rousseldenis** [comment]
> Maybe it's better to use `common.Form` for populating records? Do you want me to propose such change?

Nope at this time. See https://github.com/OCA/sale-workflow/issues/1146#issuecomment-630660203 Maybe in another PR

**Comment by pedrobaeza** [comment]
Well, I see this solution very fragile, as next time it's going to be another field, so I prefer the long term solution.

**Comment by rousseldenis** [comment]
> Well, I see this solution very fragile, as next time it's going to be another field, so I prefer the long term solution.

Note that the bug can be reproduced on runbot if company field is not filled in :

image


IMHO it's a gap in Odoo code. A better error message on core should be the solution (as inconsistency between not required field in sales and required in invoices)

**Comment by pedrobaeza** [comment]
Yes, but with my solution you fix both: tests and runbot.

**Comment by rousseldenis** [comment]
@pedrobaeza

**Comment by pedrobaeza** [comment]
I will fix it today

**Pull request closed without merging**
