### PR TITLE
[16.0][MIG] sale_mrp_bom

### PR DESCRIPTION
**Pull request by ferran-S73**

### CODE REVIEW

**Comment by ferran-S73** [comment]
@hailangvn @renatonlima could you review this pr please?

**Review by hailangvn — APPROVED** [review]
Functional test ok. Thanks for the work.

**Review by renatonlima — APPROVED** [review]

**Comment by ferran-S73** [comment]
@OCA/crm-sales-marketing-maintainers

**Comment by wedoo-justynar** [comment]
v16 BOM does not move from the order line to production. The index has several BOMs and production opens with 1 from the list and not with the one in SO

**Pull request merged**
