### PR TITLE
[MIG] [13.0] sale_stock_picking_blocking

### PR DESCRIPTION
**Pull request by gurneyalex**

### CODE REVIEW

**Comment by gurneyalex** [comment]
This is a new version of #956, rebased, and hopefully with CI green (I ran the pre-commit hooks)

**Comment by jcoux** [comment]
Added a fix and rebased from top of OCA/13.0.

**Comment by jcoux** [comment]
@rousseldenis Can you merge this PR as all check are now green and the original PR already approved?

**Comment by rousseldenis** [comment]
@jcoux Could you squash commits that can be, maybe rename some before?

**Comment by jcoux** [comment]
@rousseldenis Done!

**Review by rousseldenis — APPROVED** [review]
Code review

**Comment by jcoux** [comment]
With squash to have better commit history before merging, we lost (somewhere in force push) my fix, then here the fix: https://github.com/OCA/sale-workflow/commit/aab110a112bef672845a795eff57157781119bb7

**Review by jcoux — APPROVED** [review]
LGTM (with my fix) :+1:

**Review by damdam-s — APPROVED** [review]

**Pull request merged**
