### PR TITLE
[13.0][MIG] sale sourced by line

### PR DESCRIPTION
**Pull request by acsonefho**
Migration of sale_sourced_by_line from `12.0` (https://github.com/OCA/sale-workflow/pull/1030)

**Note:**
In Odoo `sale_stock` module, the `warehouse_id` field on `sale.order.line` already exists (as computed, not stored).
The compute function (`_compute_qty_at_date`) force this field to an empty value.
I force the value with the one set by the user and I force store it.

As every `computed` and `stored` fields are by default `compute_sudo=True`, I have to force `compute_sudo=False` because this `warehouse_id` field is computed by default and share the same function with others fields. So that generate this kind of warning:
`WARNING odoo-test odoo.models: sale.order.line: inconsistent 'compute_sudo' for computed fields: virtual_available_at_date, scheduled_date, free_qty_today, qty_available_today, warehouse_id`

### CODE REVIEW

**Review by ThomasBinsfeld — APPROVED** [review]

**Review by MiquelRForgeFlow — APPROVED** [review]
LGTM

**Review by AaronHForgeFlow — APPROVED** [review]
Code review LGTM

**Comment by MiquelRForgeFlow** [comment]
ping: @crm-sales-marketing-maintainers

**Comment by MiquelRForgeFlow** [comment]
ping: @OCA/crm-sales-marketing-maintainers

**Pull request merged**
