### PR TITLE
[MIG] sale_resource_booking: Migration to 13.0

### PR DESCRIPTION
**Pull request by yajo**
- Set `resource.booking` new `combination_auto_assign` field depending on `product.template`'s `resource_booking_type_combination_rel_id`.
- Adapt tests.
- The rest is normal migration stuff.

@Tecnativa TT31324

### CODE REVIEW

**Comment by pedrobaeza** [comment]
You can squash administrative commits and partial translation works:

Selección_001

**Comment by yajo** [comment]
Squashed.

**Comment by pedrobaeza** [comment]
I'm still missing the squashing of the third first commits.

**Comment by njeudy** [comment]
@Yajo any news on this one ? I working migrating it ton V14.0 :)

**Review by njeudy — APPROVED** [review]
Tested on a new V13.0 and with some data.

**Comment by pedrobaeza** [comment]
The random error is hitting hard. Let's try again:

/ocabot merge nobump

**Comment by njeudy** [comment]
@pedrobaeza think ocabot complain :) I will check the module that cause the error the afternoon

**Comment by njeudy** [comment]
@pedrobaeza I just push #1880 and this should correct your merge problem

**Comment by victoralmau** [comment]
Rebase done.
According to the latest changes to solve the tests of other addons in this repository, this would be ready to merge, right?

**Pull request merged**
