### PR TITLE
[12.0] sale_milestone_profile_invoicing Fix error if no partner

### PR DESCRIPTION
**Pull request by mohamedhagag**
Fix error if no partner or task_id set on sale order line .

### CODE REVIEW

**Comment by mohamedhagag** [comment]
just tested it on runbot and working fine

**Comment by TDu** [comment]
I am not sure why this is needed as the same test on an empty task_id is done here
https://github.com/OCA/sale-workflow/blob/d161b170fc794f45b3bdfaa0d3a8a02c44c243d7/sale_milestone_profile_invoicing/models/sale_order_line.py#L53

Maybe adding a unit test would help

**Review by flotho — COMMENTED** [review]
Hi,

Thanks for the proposal
I'm not sure to understand the name of your PR because you don't filter on partner.
Task could be defined with no partners so filtering on task won't probably be enough to have a defensive for the "no partner" issue.
Am I right ?

**Comment by rousseldenis** [comment]
@mohamedhagag What's the status of this ? Could you modify your commit and PR messages as there is no reference to partner in your changes?

**Pull request closed without merging**
