### PR TITLE
[14.0] [MIG] sale_order_invoice_amount

### PR DESCRIPTION
**Pull request by JasminSForgeFlow**
Standard Migration
@ForgeFlow

### CODE REVIEW

**Review by rousseldenis — APPROVED** [review]
Code review. Seems great

**Review by LoisRForgeFlow — APPROVED** [review]
Tested locally, works as expected :+1:

**Comment by HaraldPanten** [comment]
Travis is failing @LoisRForgeFlow @JordiBForgeFlow

**Comment by LoisRForgeFlow** [comment]
Travis fails in the last element of the test matrix, so due to the addons included in that matrix, it is not directly related to this addon.

**Comment by LoisRForgeFlow** [comment]
@JasminSForgeFlow Can you rebase this one? Travis has been simplified in the 14.0 branch.

**Comment by JasminSForgeFlow** [comment]
> @JasminSForgeFlow Can you rebase this one? Travis has been simplified in the 14.0 branch.

Done @LoisRForgeFlow

**Pull request merged**
