### PR TITLE
[14.0][IMP] sale_order_line_sequence: module refactor, new sequence fields for orders and invoices

### PR DESCRIPTION
**Pull request by OriolMForgeFlow**
Module refactor

### CODE REVIEW

**Comment by AaronHForgeFlow** [comment]
Works well overall, however, if I create the invoice and then I modify the order in the sales order then the invoice order is not changed. I think it should change.

**Comment by OriolMForgeFlow** [comment]
Changed @AaronHForgeFlow , I think it works fine now.

**Review by AaronHForgeFlow — APPROVED** [review]
Functional tests. Works good. Tested with invoice splitting.

**Review by LoisRForgeFlow — APPROVED** [review]
Technical review, LGTM!

**Review by rafaelbn — APPROVED** [review]
/ocabor merge major

**Comment by AaronHForgeFlow** [comment]
@rafaelbn there is a typo in the runbot command, can you please retry? Thanks :)

**Pull request merged**
