### PR TITLE
[14.0] [MIG] sale order general discount : Migrated the Module from 13 to 14.

### PR DESCRIPTION
**Pull request by dhiren-scs**

### CODE REVIEW

**Comment by rousseldenis** [comment]
@dhiren-scs What's the status of this ?

**Review by houssine78 — APPROVED** [review]

**Comment by houssine78** [comment]
@dhiren-scs do you plan to make get this PR merged ? Or to work on it soon to rebase and resolve Travis ?

**Comment by houssine78** [comment]
@JayVora-SerpentCS maybe you can point us to someone from your team that follow this PR ? @dhiren-scs doens't seem anymore active on OCA repos... Thanks a lot !

**Comment by houssine78** [comment]
@pedrobaeza I think we can close this PR as the module has already been ported to v14.0 by this [PR](https://github.com/OCA/sale-workflow/pull/1434/files) which has been merged.

**Pull request closed without merging**
