### PR TITLE
[14.0][MIG] sale_promotion_rule_delivery

### PR DESCRIPTION
**Pull request by xavier-bouquiaux**
Migration of sale_promotion_rule_delivery to v14

### CODE REVIEW

**Comment by rousseldenis** [comment]
@xavier-bouquiaux Could you just take care of PR's titles? Thanks

**Comment by xavier-bouquiaux** [comment]
@rousseldenis

**Comment by rousseldenis** [comment]
@xavier-bouquiaux Could you check tests ?

**Comment by rousseldenis** [comment]
Closing as already migrated

**Pull request closed without merging**
