### PR TITLE
[12.0] [ADD] sale_product_email module

### PR DESCRIPTION
**Pull request by chafique-delli**

### CODE REVIEW

**Review by HaraldPanten — CHANGES_REQUESTED** [review]
Hi @chafique-delli ,

I tried to test it on runbot for 2 times but I couldn't.That's the error that occurs when you try to open/create a new quotation.

I tried rebuilding several times but it didn't work neither:

Captura de pantalla 2020-06-22 a las 9 52 05

Could you check?

Thx!

**Comment by chafique-delli** [comment]
Hi @HaraldPanten ,
I've uninstalled the 'sale_product_email' module on runbot but you always get the same error when trying to open the form view of the 'sale.order'.
Sélection_004

**Comment by HaraldPanten** [comment]
May it be something wrong with V12 branch? What do you think @rousseldenis ?

**Comment by rousseldenis** [comment]
> May it be something wrong with V12 branch? What do you think @rousseldenis ?

@HaraldPanten I did a fix for that : https://github.com/OCA/sale-workflow/pull/1172

Being merged

**Comment by HaraldPanten** [comment]
> > May it be something wrong with V12 branch? What do you think @rousseldenis ?
> 
> @HaraldPanten I did a fix for that : #1172
> 
> Being merged

THX!

**Comment by rousseldenis** [comment]
@chafique-delli What's the status of this ? Could you rebase ?

**Pull request closed without merging**
