### PR TITLE
[FIX] cancel button of original view should be hide after installation…

### PR DESCRIPTION
**Pull request by dhp-denero**
… of sale_cancel_reason module

### CODE REVIEW

**Comment by dhp-denero** [comment]
Hello,

I already signed CLA before. Let me know what do I need to now ?

**Comment by pedrobaeza** [comment]
Why your change? Isn't working the other way?

**Comment by dhp-denero** [comment]
I just correct the xml. 

with line <attribute name="invisible" eval="1"/>, standard Cancel Button is not hiding. So I corrected it with <attribute name="invisible">True</attribute>. It is working well.

**Comment by pedrobaeza** [comment]
:+1: then

**Comment by dhp-denero** [comment]
means ?

I think, the correction should be merged with original branch.

**Comment by pedrobaeza** [comment]
Yeah, but we need at least 3 approvals or 2 and more than 5 working days of delay

**Comment by yvaucher** [comment]
:+1: Thanks

**Comment by dhp-denero** [comment]
Hey thanks Yannick.

**Pull request merged**
