### PR TITLE
[14.0][MIG] sale_substate

### PR DESCRIPTION
**Pull request by HekkiMelody**
Superseeds https://github.com/OCA/sale-workflow/pull/1435

Took the same commits and simply rebased.

### CODE REVIEW

**Comment by HekkiMelody** [comment]
@miguel-S73 @fuentes73 @hitrosol in case you're still interested in this

**Review by francesco-ooops — APPROVED** [review]
Functional review ok

**Comment by francesco-ooops** [comment]
@mourad-ehm good for you?

**Review by Aldeigja — APPROVED** [review]
LGTM!

**Comment by francesco-ooops** [comment]
@OCA/crm-sales-marketing-maintainers good for merge?

**Review by miguel-S73 — APPROVED** [review]

**Comment by francesco-ooops** [comment]
@simahawk ;)

**Pull request merged**
