### PR TITLE
[13.0][MIG] sales_team_security: Migration to 13.0

### PR DESCRIPTION
**Pull request by pedrobaeza**
@Tecnativa TT25758

### CODE REVIEW

**Review by rvalyi — APPROVED** [review]
interesting code BTW.

**Review by victoralmau — APPROVED** [review]

**Review by HaraldPanten — APPROVED** [review]
LGTM

**Comment by Mat-moran** [comment]
Hola buenas, me ha dado el siguiente error al instalar, no se si el canal oportuno para ponerlo. Si no es así no dudeis en decirlo.


S2 y gracias por el trabajo


Error:
Odoo Server Error

Traceback (most recent call last):
  File "/home/amadeo/pruebas_almacen/src/odoo/odoo/tools/cache.py", line 85, in lookup
    r = d[key]
  File "/home/amadeo/pruebas_almacen/src/odoo/odoo/tools/func.py", line 69, in wrapper
    return func(self, *args, **kwargs)
  File "/home/amadeo/pruebas_almacen/src/odoo/odoo/tools/lru.py", line 44, in __getitem__
    a = self.d[obj].me
KeyError: ('ir.model.data', <function IrModelData.xmlid_lookup at 0x7fc751bce1e0>, 'base.module_category_sales_management')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/amadeo/pruebas_almacen/src/odoo/odoo/tools/convert.py", line 712, in parse
    self._tag_root(de)
  File "/home/amadeo/pruebas_almacen/src/odoo/odoo/tools/convert.py", line 674, in _tag_root
    f(rec)
  File "/home/amadeo/pruebas_almacen/src/odoo/odoo/tools/convert.py", line 561, in _tag_record
    f_val = self.id_get(f_ref)
  File "/home/amadeo/pruebas_almacen/src/odoo/odoo/tools/convert.py", line 657, in id_get
    res = self.model_id_get(id_str, raise_if_not_found)
  File "/home/amadeo/pruebas_almacen/src/odoo/odoo/tools/convert.py", line 663, in model_id_get
    return self.env['ir.model.data'].xmlid_to_res_model_res_id(id_str, raise_if_not_found=raise_if_not_found)
  File "/home/amadeo/pruebas_almacen/src/odoo/odoo/addons/base/models/ir_model.py", line 1681, in xmlid_to_res_model_res_id
    return self.xmlid_lookup(xmlid)[1:3]
  File "<decorator-gen-25>", line 2, in xmlid_lookup
  File "/home/amadeo/pruebas_almacen/src/odoo/odoo/tools/cache.py", line 90, in lookup
    value = d[key] = self.method(*args, **kwargs)
  File "/home/amadeo/pruebas_almacen/src/odoo/odoo/addons/base/models/ir_model.py", line 1670, in xmlid_lookup
    raise ValueError('External ID not found in the system: %s' % xmlid)
ValueError: External ID not found in the system: base.module_category_sales_management

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/amadeo/pruebas_almacen/src/odoo/odoo/http.py", line 624, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/amadeo/pruebas_almacen/src/odoo/odoo/http.py", line 310, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/home/amadeo/pruebas_almacen/src/odoo/odoo/tools/pycompat.py", line 14, in reraise
    raise value
  File "/home/amadeo/pruebas_almacen/src/odoo/odoo/http.py", line 669, in dispatch
    result = self._call_function(**self.params)
  File "/home/amadeo/pruebas_almacen/src/odoo/odoo/http.py", line 350, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/home/amadeo/pruebas_almacen/src/odoo/odoo/service/model.py", line 94, in wrapper
    return f(dbname, *args, **kwargs)
  File "/home/amadeo/pruebas_almacen/src/odoo/odoo/http.py", line 339, in checked_call
    result = self.endpoint(*a, **kw)
  File "/home/amadeo/pruebas_almacen/src/odoo/odoo/http.py", line 915, in __call__
    return self.method(*args, **kw)
  File "/home/amadeo/pruebas_almacen/src/odoo/odoo/http.py", line 515, in response_wrap
    response = f(*args, **kw)
  File "/home/amadeo/pruebas_almacen/src/odoo/addons/web/controllers/main.py", line 1326, in call_button
    action = self._call_kw(model, method, args, kwargs)
  File "/home/amadeo/pruebas_almacen/src/odoo/addons/web/controllers/main.py", line 1314, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/home/amadeo/pruebas_almacen/src/odoo/odoo/api.py", line 387, in call_kw
    result = _call_kw_multi(method, model, args, kwargs)
  File "/home/amadeo/pruebas_almacen/src/odoo/odoo/api.py", line 374, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "<decorator-gen-60>", line 2, in button_immediate_install
  File "/home/amadeo/pruebas_almacen/src/odoo/odoo/addons/base/models/ir_module.py", line 72, in check_and_log
    return method(self, *args, **kwargs)
  File "/home/amadeo/pruebas_almacen/src/odoo/odoo/addons/base/models/ir_module.py", line 463, in button_immediate_install
    return self._button_immediate_function(type(self).button_install)
  File "/home/amadeo/pruebas_almacen/src/odoo/odoo/addons/base/models/ir_module.py", line 573, in _button_immediate_function
    modules.registry.Registry.new(self._cr.dbname, update_module=True)
  File "/home/amadeo/pruebas_almacen/src/odoo/odoo/modules/registry.py", line 86, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/home/amadeo/pruebas_almacen/src/odoo/odoo/modules/loading.py", line 423, in load_modules
    loaded_modules, update_module, models_to_check)
  File "/home/amadeo/pruebas_almacen/src/odoo/odoo/modules/loading.py", line 315, in load_marked_modules
    perform_checks=perform_checks, models_to_check=models_to_check
  File "/home/amadeo/pruebas_almacen/src/odoo/odoo/modules/loading.py", line 225, in load_module_graph
    load_data(cr, idref, mode, kind='data', package=package, report=report)
  File "/home/amadeo/pruebas_almacen/src/odoo/odoo/modules/loading.py", line 68, in load_data
    tools.convert_file(cr, package.name, filename, idref, mode, noupdate, kind, report)
  File "/home/amadeo/pruebas_almacen/src/odoo/odoo/tools/convert.py", line 736, in convert_file
    convert_xml_import(cr, module, fp, idref, mode, noupdate, report)
  File "/home/amadeo/pruebas_almacen/src/odoo/odoo/tools/convert.py", line 803, in convert_xml_import
    obj.parse(doc.getroot())
  File "/home/amadeo/pruebas_almacen/src/odoo/odoo/tools/convert.py", line 721, in parse
    exc_info[2]
  File "/home/amadeo/pruebas_almacen/src/odoo/odoo/tools/pycompat.py", line 13, in reraise
    raise value.with_traceback(tb)
  File "/home/amadeo/pruebas_almacen/src/odoo/odoo/tools/convert.py", line 712, in parse
    self._tag_root(de)
  File "/home/amadeo/pruebas_almacen/src/odoo/odoo/tools/convert.py", line 674, in _tag_root
    f(rec)
  File "/home/amadeo/pruebas_almacen/src/odoo/odoo/tools/convert.py", line 561, in _tag_record
    f_val = self.id_get(f_ref)
  File "/home/amadeo/pruebas_almacen/src/odoo/odoo/tools/convert.py", line 657, in id_get
    res = self.model_id_get(id_str, raise_if_not_found)
  File "/home/amadeo/pruebas_almacen/src/odoo/odoo/tools/convert.py", line 663, in model_id_get
    return self.env['ir.model.data'].xmlid_to_res_model_res_id(id_str, raise_if_not_found=raise_if_not_found)
  File "/home/amadeo/pruebas_almacen/src/odoo/odoo/addons/base/models/ir_model.py", line 1681, in xmlid_to_res_model_res_id
    return self.xmlid_lookup(xmlid)[1:3]
  File "<decorator-gen-25>", line 2, in xmlid_lookup
  File "/home/amadeo/pruebas_almacen/src/odoo/odoo/tools/cache.py", line 90, in lookup
    value = d[key] = self.method(*args, **kwargs)
  File "/home/amadeo/pruebas_almacen/src/odoo/odoo/addons/base/models/ir_model.py", line 1670, in xmlid_lookup
    raise ValueError('External ID not found in the system: %s' % xmlid)
odoo.tools.convert.ParseError: "External ID not found in the system: base.module_category_sales_management" while parsing /home/amadeo/pruebas_almacen/src/OCA_MODULES/sales_team_security/security/sales_team_security.xml:2, near
<odoo>
    <record id="group_sale_team_manager" model="res.groups">
        <field name="name">Channel Manager</field>
        <field name="comment">the user will have an access to the documents of the sales channel he/she belongs to.</field>
        <field name="category_id" ref="base.module_category_sales_management"/>
        <field name="implied_ids" eval="[(4, ref('sales_team.group_sale_salesman'))]"/>
    </record>
    <record id="sales_team.group_sale_salesman_all_leads" model="res.groups">
        <field name="implied_ids" eval="[(6, 0, [ref('group_sale_team_manager')])]"/>
    </record>
    <data noupdate="1">
        <record id="sale_order_team_rule" model="ir.rule">
            <field name="name">Sales Channel Orders</field>
            <field ref="sale.model_sale_order" name="model_id"/>
            <field name="domain_force">['|', ('team_id', '=', user.sale_team_id.id), ('team_id', '=', False)]</field>
            <field name="groups" eval="[(4, ref('group_sale_team_manager'))]"/>
        </record>
        <record id="sale_order_report_team_rule" model="ir.rule">
            <field name="name">Sales Channel Orders Analysis</field>
            <field ref="sale.model_sale_report" name="model_id"/>
            <field name="domain_force">['|', ('team_id', '=', user.sale_team_id.id), ('team_id', '=', False)]</field>
            <field name="groups" eval="[(4, ref('group_sale_team_manager'))]"/>
        </record>
        <record id="sale_order_line_team_rule" model="ir.rule">
            <field name="name">Sales Channel Order Lines</field>
            <field ref="sale.model_sale_order_line" name="model_id"/>
            <field name="domain_force">['|', ('order_id.team_id', '=', user.sale_team_id.id), ('order_id.team_id', '=', False)]</field>
            <field name="groups" eval="[(4, ref('group_sale_team_manager'))]"/>
        </record>
        <record id="crm_lead_team_rule" model="ir.rule">
            <field name="name">Sales Channel Leads/Opportunities</field>
            <field ref="crm.model_crm_lead" name="model_id"/>
            <field name="domain_force">['|', ('team_id', '=', user.sale_team_id.id), ('team_id', '=', False)]</field>
            <field name="groups" eval="[(4, ref('group_sale_team_manager'))]"/>
        </record>
        <record id="crm_activity_report_team" model="ir.rule">
            <field name="name">Activities Analysis by Channel</field>
            <field ref="crm.model_crm_activity_report" name="model_id"/>
            <field name="domain_force">['|', ('team_id', '=', user.sale_team_id.id), ('team_id', '=', False)]</field>
            <field name="groups" eval="[(4, ref('group_sale_team_manager'))]"/>
        </record>
        <record id="sales_team_team_rule" model="ir.rule">
            <field name="name">Own Sales Channels</field>
            <field ref="sales_team.model_crm_team" name="model_id"/>
            <field name="domain_force">[('id', '=', user.sale_team_id.id)]</field>
            <field name="groups" eval="[(4, ref('group_sale_team_manager'))]"/>
        </record>
    </data>
</odoo>

**Comment by pedrobaeza** [comment]
You have your DB in a bad state. Update base module and try again. Anyway, I'm afraid this is not something of the module, and you should ask for further help in forums.

**Pull request merged**
