### PR TITLE
FIX sale_pricelist_from_commitment_date

### PR DESCRIPTION
**Pull request by SilvioC2C**
Avoid overriding unit price when importing data via the Odoo base importer

### CODE REVIEW

**Review by ajaniszewska-dev — APPROVED** [review]

**Review by gurneyalex — APPROVED** [review]

**Comment by pedrobaeza** [comment]
Is this fixing https://app.travis-ci.com/github/OCA/sale-workflow/jobs/563225847#L3450 ?

**Comment by rousseldenis** [comment]
@SilvioC2C Could you rebase ?

**Comment by SilvioC2C** [comment]
@rousseldenis done!

**Pull request merged**
