### PR TITLE
[15.0][IMP] sale_planner_calendar: Do not create attendees is no mail option selected

### PR DESCRIPTION
**Pull request by sergio-teruel**
cc @Tecnativa 

ping @carlosdauden @CarlosRoca13

### CODE REVIEW

**Review by carlosdauden — APPROVED** [review]
Code LGTM

**Comment by pedrobaeza** [comment]
If the salesman is not added as attendee, its calendar shows the event?

**Comment by sergio-teruel** [comment]
Yes... We do not fill the attendees (calendar.attendee) but the event's attendants (partner_ids) is filled, so the event is shown on calendar view

**Review by pedrobaeza — APPROVED** [review]
/ocabot merge minor

**Pull request merged**
