### PR TITLE
[9.0][MIG][sale_partner_incoterm] Ported sale_partner_term to odoo 9.0

### PR DESCRIPTION
**Pull request by wpichler**

### CODE REVIEW

**Comment by rafaelbn** [comment]
Hi @wpichler thanks for this contribution. We are reviewing from the OCA code sprint, please could you review this PR and fix travis and runbot errors? Thanks!

**Review by antoniocanovas — APPROVED** [review]
Ok functionality

**Comment by rafaelbn** [comment]
Hi @wpichler thanks for this contribution. Please fix travis errors

```2017-05-30 15:05:21,200 5805 ERROR openerp_test openerp.addons.sale_partner_incoterm.tests.test_sale_partner_incoterm: ERROR

2017-05-30 15:05:21,203 5805 INFO openerp_test openerp.addons.sale_partner_incoterm.tests.test_sale_partner_incoterm: ======================================================================

2017-05-30 15:05:21,203 5805 ERROR openerp_test openerp.addons.sale_partner_incoterm.tests.test_sale_partner_incoterm: ERROR: test_sale_partner_incoterm (openerp.addons.sale_partner_incoterm.tests.test_sale_partner_incoterm.TestSalePartnerIncoterm)

2017-05-30 15:05:21,204 5805 ERROR openerp_test openerp.addons.sale_partner_incoterm.tests.test_sale_partner_incoterm: ` Check that the customer's default incoterm is retrieved in the sales order's onchange

2017-05-30 15:05:21,204 5805 ERROR openerp_test openerp.addons.sale_partner_incoterm.tests.test_sale_partner_incoterm: Traceback (most recent call last):

2017-05-30 15:05:21,204 5805 ERROR openerp_test openerp.addons.sale_partner_incoterm.tests.test_sale_partner_incoterm: `   File "/home/travis/build/OCA/sale-workflow/sale_partner_incoterm/tests/test_sale_partner_incoterm.py", line 31, in test_sale_partner_incoterm

2017-05-30 15:05:21,204 5805 ERROR openerp_test openerp.addons.sale_partner_incoterm.tests.test_sale_partner_incoterm: `     res = self.env['sale.order'].onchange_partner_id(customer.id)['value']

2017-05-30 15:05:21,204 5805 ERROR openerp_test openerp.addons.sale_partner_incoterm.tests.test_sale_partner_incoterm: `   File "/home/travis/OCB-9.0/openerp/api.py", line 248, in wrapper

2017-05-30 15:05:21,204 5805 ERROR openerp_test openerp.addons.sale_partner_incoterm.tests.test_sale_partner_incoterm: `     return new_api(self, *args, **kwargs)

2017-05-30 15:05:21,204 5805 ERROR openerp_test openerp.addons.sale_partner_incoterm.tests.test_sale_partner_incoterm: ` TypeError: onchange_partner_id() takes exactly 1 argument (2 given)

2017-05-30 15:05:21,205 5805 INFO openerp_test openerp.addons.sale_partner_incoterm.tests.test_sale_partner_incoterm: Ran 1 test in 0.026s

2017-05-30 15:05:21,205 5805 ERROR openerp_test openerp.addons.sale_partner_incoterm.tests.test_sale_partner_incoterm: FAILED

2017-05-30 15:05:21,205 5805 INFO openerp_test openerp.addons.sale_partner_incoterm.tests.test_sale_partner_incoterm:  (errors=1)

2017-05-30 15:05:21,205 5805 ERROR openerp_test openerp.modules.module: Module sale_partner_incoterm: 0 failures, 1 errors```

This is a migration of https://github.com/OCA/sale-workflow/tree/8.0/sale_partner_incoterm original author @StefanRijnhart

**Review by chienandalu — CHANGES_REQUESTED** [review]
- Can't see this module's history.
- Your tests seem to be failing.

**Comment by chienandalu** [comment]
@wpichler You should rebase your history so only this module patches appear in history. You can follow this guidelines to get the initial history: https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-10.0#technical-method-to-migrate-a-module-from-90-to-100-branch (adapt to your version) then cherry-pick your migration commit and finally push it here.

**Comment by rousseldenis** [comment]
@wpichler Do you plan to finish this ? Either, it will be closed soon as no activity.

**Comment by wpichler** [comment]
No - does not make any more sense for version 9...

**Pull request closed without merging**
