### PR TITLE
[15.0][MIG]sale_order_warn_message

### PR DESCRIPTION
**Pull request by manuelregidor**
Standard migration

### CODE REVIEW

**Comment by manuelregidor** [comment]
@HaraldPanten @ValentinVinagre

**Review by ValentinVinagre — APPROVED** [review]
LGTM 👍🏻

**Review by HaraldPanten — APPROVED** [review]
It's working fine in runboat. @pedrobaeza is it ok for you?

THX.

**Review by pedrobaeza — APPROVED** [review]
/ocabot migration sale_order_warn_message
/ocabot merge nobump

**Pull request merged**
