### PR TITLE
Automatically merge all POs from a single order

### PR DESCRIPTION
**Pull request by mdietrichc2c**
This PR is to add an automatic grouping functionality for POs generated from the same sale order. Otherwise, as a customer reported, the multiple POs will lead to multiple packages from the supplier to the customer.

The functionality is mostly based on the `do_merge` method in `purchase_group_hooks`; an "origin" criteria is added to only merge POs from the same SO, and the procurements are all updated with the new PO.

### CODE REVIEW

**Comment by mdietrichc2c** [comment]
I added a method in order to define which POs/procurements should be merged automatically.

**Comment by mdietrichc2c** [comment]
Added as well: the `sale_flow` field (since otherwise, it will be set as normal)

**Comment by pedrobaeza** [comment]
@gurneyalex this still applies?

**Comment by pedrobaeza** [comment]
Closing as no answer. Feel free to reopen if needed.

**Pull request closed without merging**
