### PR TITLE
16.0 mig sale order line date

### PR DESCRIPTION
**Pull request by jantoniorivera97**
/ocabot migration sale_order_line_date

### CODE REVIEW

**Comment by jantoniorivera97** [comment]
@OCA/crm-sales-marketing-maintainers Greetings. I have worked on v16 migration for this module. Could you please give it a check?

**Comment by hugo-cordoba** [comment]
Hi @rafaelbn. How are you? The migration of this module is already underway in this PR:https://github.com/OCA/sale-workflow/pull/2341 . You can contribute by reviewing the changes and approving the development in case it is correct.

Best regards.

**Comment by rafaelbn** [comment]
Already migrated in https://github.com/OCA/sale-workflow/pull/2341

**Pull request closed without merging**
