### PR TITLE
[9.0] sale_automatic_workflow: avoid domain confusion

### PR DESCRIPTION
**Pull request by sbidoul**
Domain fields are for display only.
Make them related readonly to avoid confusion.
Partial backport of 921bdc9e3d962c4066be22529dbf6caf00c6eafd

### CODE REVIEW

**Review by guewen — APPROVED** [review]

**Review by lmignon — APPROVED** [review]

**Comment by sbidoul** [comment]
postgres is not running anymore by default on travis?

**Comment by lmignon** [comment]
@sbidoul Indeed, you must specify postgresql into travis.yml
```yaml
addons:
  postgresql: "9.6"
  apt:
    packages:
      - expect-dev  # provides unbuffer utility
...
```

**Review by pedrobaeza — APPROVED** [review]

**Review by pedrobaeza — CHANGES_REQUESTED** [review]
There's a problem... ir.filters.domain is a `Text` field, and related fields are `Char` ones, so you either change the type of the fields, or do a computed method for transferring data.

And I see another potential problem: now fields are not stored, so this can impact on performance.

**Comment by guewen** [comment]
> And I see another potential problem: now fields are not stored, so this can impact on performance.

For the processing of the automatic workflow, these fields were not used:

https://github.com/OCA/sale-workflow/blob/d55a30b29eb8170961c399f6f0f2ce35fe594e50/sale_automatic_workflow/models/automatic_workflow_job.py#L88-L109

Perfs will be the same

**Comment by pedrobaeza** [comment]
OK, then it only rest the other thing, switching field types should be enough then, but maybe UI should adapted to new widget.

**Comment by lmignon** [comment]
@pedrobaeza The web_domain_field widget is not available into 9.0. Requested changes done.
Regards,
lmi

**Comment by pedrobaeza** [comment]
Well, I mean text widget (multi-line) against char widget (single-line). I think you can put `widget="char"` in the view for mimicking old layout, or see if new widgets fit well on the view.

**Comment by lmignon** [comment]
@pedrobaeza The view is updated with `widget="char"` :smirk:

**Pull request merged**
