### PR TITLE
[12.0][FIX] sale_triple_discount: Cache management

### PR DESCRIPTION
**Pull request by SimoRubi**
Fix https://github.com/OCA/sale-workflow/issues/1391.

@ioans73 I had to propose a new PR instead of editing https://github.com/OCA/sale-workflow/pull/1410 because that approach is very different from this one, could you please check if this fixes your issue too?

### CODE REVIEW

**Comment by ioans73** [comment]
Yes, the changes seem to be working correctly.
Thank you very much

**Review by ioans73 — APPROVED** [review]

**Review by SimoneVagile — APPROVED** [review]

**Review by rousseldenis — APPROVED** [review]
Code review.

Indeed, this change removes ugly things. But it can makes sense that lines triple discount preprocess should be done one by one.

**Comment by rousseldenis** [comment]
@SimoRubi Is this ready ?

**Comment by SimoRubi** [comment]
Thanks for the review!

> Code review.
> 
> Indeed, this change removes ugly things. But it can makes sense that lines triple discount preprocess should be done one by one.

As far as I have investigated, everything depends on the `super` method: 

- if it is `api.one` (deprecated), then we should pre/post-process lines one-by-one
- otherwise, we can pre/post-process in bulk

So in my opinion it makes sense that pre/post-process methods are able to manage recordsets so we can handle the non-deprecated case without adding everytime a `for` loop.

> @SimoRubi Is this ready ?

yes

**Pull request merged**
