### PR TITLE
[17.0] [MIG] Sale order line sequence

### PR DESCRIPTION
**Pull request by FSchiepers**
Standard Migration of the module Sale order line sequence.

### CODE REVIEW

**Comment by FSchiepers** [comment]
Related to https://github.com/OCA/sale-workflow/issues/2766

**Review by DorianMAG — APPROVED** [review]
Tested in runboat.
LGTM

**Review by rousseldenis — APPROVED** [review]
Thanks for this. Code review.

**Comment by StefanRijnhart** [comment]
FYI https://github.com/OCA/sale-workflow/pull/3296

**Pull request merged**
