### PR TITLE
[10.0][MIG][FIX]sale exception not correctly updated - Need review

### LINKED ISSUE #1058: [10.0][MIG]rule_group is updated yet not available in the model
Hi,

I'm running an upgrade from v9 to v10 with connectors and have this message :
```
sale_exception: error in migration script sale_exception/migrations/10.0.2.0.0/pre-migration.py: ProgrammingError("ERREUR:  la colonne \xc2\xab rule_group \xc2\xbb de la relation \xc2\xab exception_rule \xc2\xbb n'existe pas\nLINE 3:         SET rule_group = 'sale'\n                    ^\n",)
2020-02-04 12:16:48,273 17929 ERROR old_prod OpenUpgrade: ERREUR:  la colonne « rule_group » de la relation « exception_rule » n'existe pas
LINE 3:         SET rule_group = 'sale'
```
In this line https://github.com/OCA/sale-workflow/blob/10.0/sale_exception/migrations/10.0.2.0.0/pre-migration.py#L11 the query should be after the model name changing IMHO .

Moreover the field supposed to be changed is not available here : https://github.com/OCA/sale-workflow/blob/9.0/sale_exception/models/sale.py

@pedrobaeza , any tips ?

Regards

### PR DESCRIPTION
**Pull request by flotho**
FIX #1058

### CODE REVIEW

**Comment by pedrobaeza** [comment]
You can't remove this. You have to make it conditional if you find certain data. If not, people coming from 10.0.1.0.0 (that haven't still updated) will fail

**Comment by flotho** [comment]
Hi @pedrobaeza ,

As usual, you've got the proper advice, 
I've updated the code

**Comment by pedrobaeza** [comment]
```
sale_exception/migrations/10.0.2.0.0/pre-migration.py:18:1: W293 blank line contains whitespace
```

**Comment by flotho** [comment]
hi @pedrobaeza 
The CI failure is no more concerning my work.
Any chance to be merged ?

**Comment by pedrobaeza** [comment]
Yeah, it's a Travis temporary glitch, but please squash commits together before merging.

**Comment by flotho** [comment]
@pedrobaeza , done

**Review by pedrobaeza — APPROVED** [review]

**Comment by flotho** [comment]
Thanks @pedrobaeza

**Pull request merged**
