### PR TITLE
[14.0][MIG] sale order general discount

### PR DESCRIPTION
**Pull request by cor9003**
Standard Migration

### CODE REVIEW

**Review by dsolanki-initos — APPROVED** [review]
Functional test and code review. Looks Good to me

**Comment by dsolanki-initos** [comment]
It would be great if some can add review so that we can merge the PR.

**Comment by dsolanki-initos** [comment]
It would be great if somone could add review and merge the PR.

**Comment by dsolanki-initos** [comment]
Can somone please add reviews and merge the PR?

**Comment by dsolanki-initos** [comment]
It would be great if we could get the reviews here and merge the PR.

**Comment by dsolanki-initos** [comment]
It would be great if we could get the reviews here and merge the PR.

**Comment by dsolanki-initos** [comment]
It would be great if the maintainers could merge the PR

**Comment by dsolanki-initos** [comment]
@OCA/crm-sales-marketing-maintainers can you please merge this PR?

**Comment by dsolanki-initos** [comment]
It would be great if we could get the review here so that we can merge the PR ASAP

**Comment by dsolanki-initos** [comment]
It would be great if we could get the review here so that we can merge the PR ASAP

**Comment by dsolanki-initos** [comment]
It would be great if we could get the review here so that we can merge the PR ASAP

**Comment by dsolanki-initos** [comment]
It would be great if we could get the reviews here.

**Comment by dsolanki-initos** [comment]
It would be great if we could get the reviews here.

**Comment by dsolanki-initos** [comment]
Hi @cor9003 
Will you please resolve conflicts?

**Comment by dsolanki-initos** [comment]
Hi @cor9003
Will you please resolve conflicts?

**Comment by hkapatel-initos** [comment]
Hi @cor9003
Will you please resolve conflicts?

**Comment by hkapatel-initos** [comment]
Hi @cor9003
Will you please resolve conflicts?

**Comment by cor9003** [comment]
> Hi @cor9003
> Will you please resolve conflicts?

Hi, I've already solved the conflicts, but I see this modules is already in branch 14.0
Do i have anything else ?

**Comment by pedrobaeza** [comment]
Yes, the module is already migrated, so closing. Sorry if there has been duplicated efforts.

**Pull request closed without merging**
