### PR TITLE
[MIG][9.0] sale_order_type

### PR DESCRIPTION
**Pull request by nicomacr**
Migrate to v9:
- No more order_policy on odoo v9
- No more invoice_state on odoo v9
- No more generate invoice from stock
- Some light fixes

### CODE REVIEW

**Comment by pedrobaeza** [comment]
There's an improvement as PR for 8.0 that you can include: https://github.com/OCA/sale-workflow/pull/333

**Comment by nicomacr** [comment]
Is not better to wait 8.0 imps to be aprooved and later make a PR to add them to v9?

**Comment by pedrobaeza** [comment]
Well, you can also help reviewing the PR to speed up the merge :wink:

**Comment by StefanRijnhart** [comment]
Thank you! Can you please check the Travis Errors?

**Comment by eLBati** [comment]
Thank you @nicomacr , could you include the last 8.0 changes of the module (https://github.com/OCA/sale-workflow/pull/333) when applicable?

**Comment by eLBati** [comment]
@nicomacr it seems some 8.0 changes are still missing, like https://github.com/OCA/sale-workflow/commit/c1183012bc86e65c45b0c99a53b222f004549eb1

Please see https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-9.0#technical-method-to-migrate-a-module-from-80-to-90-branch 

thanks

**Comment by eLBati** [comment]
Running

```
git diff 8.0..adhoc-dev/9.0-mig-sale_order_type sale_order_type
```

it seems several translations are missing

**Comment by nicomacr** [comment]
These translations were added later, as I bring from the 8.0

**Review by StefanRijnhart — APPROVED** [review]
Looking good now!

**Comment by aschenkels-ictstudio** [comment]
Well done! :+1:

**Review by andreschenkels — APPROVED** [review]
Well Done :+1:

**Pull request merged**
