### PR TITLE
[FIX] sale_automatic_workflow: incorrect fields

### PR DESCRIPTION
**Pull request by paulius-sladkevicius**
TODO: I suppose it would be nice to cover and tests as looks it doesn't cover.

### CODE REVIEW

**Comment by paulius-sladkevicius** [comment]
@pedrobaeza could we go "Fast-tracking" with this one too?

**Comment by pedrobaeza** [comment]
Yes, please add tests if possible, as this is not so obvious, and if not, please add more explanation to the commit/PR message.

**Comment by paulius-sladkevicius** [comment]
@pedrobaeza pity, but I'm able to do only quick fixes now. I've updated the commit message.

**Review by pedrobaeza — APPROVED** [review]
OK, let's go for this time

**Pull request merged**
