### PR TITLE
[16.0][ADD] sale_order_search_line

### PR DESCRIPTION
**Pull request by AungKoKoLin1997**
This module allows for searching by sales line values in the sales search view.

@qrtl QT4767

### CODE REVIEW

**Review by yostashiro — APPROVED** [review]
Code review.

**Comment by rousseldenis** [comment]
@AungKoKoLin1997 Do you have an example where searching with 'Product' field is not enough ?

**Comment by yostashiro** [comment]
> @AungKoKoLin1997 Do you have an example where searching with 'Product' field is not enough ?

A client of ours has a situation of order lines having individual order references (they manually key them in in the name field of order lines), and they want to be able to search orders using these references. Would it be a good example to put in the readme?

**Review by rousseldenis — APPROVED** [review]
Code review.

@AungKoKoLin1997 I think the module description is enough. Thanks

**Review by xaviedoanhduy — APPROVED** [review]

**Comment by xaviedoanhduy** [comment]
overall LGTM

**Comment by AungKoKoLin1997** [comment]
@rousseldenis Can you please merge?

**Pull request merged**
