### PR TITLE
[13.0][MIG] product_supplierinfo_for_customer_sale

### PR DESCRIPTION
**Pull request by LoisRForgeFlow**
* [x] : Depends on https://github.com/OCA/product-attribute/pull/891.

@ForgeFlow

### CODE REVIEW

**Review by RaulOForgeFlow — APPROVED** [review]
LGTM

**Comment by rousseldenis** [comment]
@LoisRForgeFlow Have you seen this https://github.com/OCA/sale-workflow/pull/1482 ?

**Comment by LoisRForgeFlow** [comment]
@rousseldenis Oh, I did not. However this one is up-to-date with the latest improvements on the base module and uses `_select_customerinfo` method. Do you think we can supersede that pr?

**Comment by rousseldenis** [comment]
> @rousseldenis Oh, I did not. However this one is up-to-date with the latest improvements on the base module and uses `_select_customerinfo` method. Do you think we can supersede that pr?

The first thing is to ask original author. You do it on other PR ?

**Comment by LoisRForgeFlow** [comment]
This PR supersede this other one https://github.com/OCA/sale-workflow/pull/1270.

**Comment by LoisRForgeFlow** [comment]
@rousseldenis No answer in the other PR, could we move forward here?

**Comment by rousseldenis** [comment]
> @rousseldenis No answer in the other PR, could we move forward here?

Indeed, I'll close the other one and update migration issue.

**Review by AaronHForgeFlow — APPROVED** [review]
Functional tests :+1:

**Review by JordiBForgeFlow — APPROVED** [review]
:+1: Functional and technical review.

**Comment by LoisRForgeFlow** [comment]
@rousseldenis @JordiBForgeFlow Good to merge?

**Comment by JordiBForgeFlow** [comment]
ocabot merge nobump

**Pull request merged**
