### PR TITLE
[FIX]: Fix bug when adding new picking move. Add list instead of tuple.

### PR DESCRIPTION
**Pull request by lbellier**
Fix bug when adding new picking move.
Add list instead of tuple.

### CODE REVIEW

**Comment by clonedagain** [comment]
:+1: I naively thought adding a recordset to an existing would not mutate the first recordset (like a list append), but obviously it returns a new recordset instead, so I mustn't use a tuple.

**Comment by clonedagain** [comment]
Can you bump the version to 8.0.1.1.0 please? That should make Travis go green.

**Comment by lbellier** [comment]
@clonedagain : Version bumped to 8.0.1.1.0

**Comment by leemannd** [comment]
:+1:

**Comment by atchuthan** [comment]
:+1:

**Comment by guewen** [comment]
:+1:

**Pull request merged**
