### PR TITLE
[12.0][IMP]sale_order_type: update quotation name when user change or…

### PR DESCRIPTION
**Pull request by chandni299**
[12.0][IMP]sale_order_type: update quotation(having "draft" or "sent" as state only) name when user change order type

### CODE REVIEW

**Comment by rousseldenis** [comment]
@chandni299 Thanks for your contribution. Could you add a test for this change ?

**Comment by chandni299** [comment]
> @chandni299 Thanks for your contribution. Could you add a test for this change ?

Added test

**Review by marylla — APPROVED** [review]
I made a functional review and it works fine.
The order name is updated according to the changed order type's sequence.

**Review by yweng8111 — APPROVED** [review]
Code Review :+1:

**Comment by marylla** [comment]
Hi @rousseldenis what do you think? Can we merge this one?

**Review by rousseldenis — APPROVED** [review]

**Review by HaraldPanten — APPROVED** [review]

**Comment by HaraldPanten** [comment]
@rousseldenis should this PR be squashed in a single commit? 🤔

**Comment by rousseldenis** [comment]
> @rousseldenis should this PR be squashed in a single commit? 🤔

Usually I ask the developer. Because some commits have their own meaning and should be kept. But when possible, do it.

**Pull request merged**
