### PR TITLE
[8.0] [IMP] sale_order_type: Make it multi company 

### PR DESCRIPTION
**Pull request by rlizana**

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Thanks for this! Maybe you should think about resetting on a post_init_hook all the existing type to company_id=False to not modify the behaviour before this patch of existing installations. You should also bump the module version, according https://github.com/OCA/maintainer-tools/blob/master/CONTRIBUTING.md#version-numbers

**Comment by pedrobaeza** [comment]
@rlizana, can you please check this?

**Comment by pedrobaeza** [comment]
@rlizana, are you going to finish this?

**Comment by eLBati** [comment]
Meanwhile sale_order_type became multi company aware. So I close

**Pull request closed without merging**
