### PR TITLE
[ADD] sale_resource_booking: sell booking products

### PR DESCRIPTION
**Pull request by yajo**
This module extends the functionality of sale and resource bookings to support
creating pending resource bookings automatically when confirming a sale order
and to allow you to generate those sale orders easily from a resource booking
type.

WIP until merged:

- [x] https://github.com/OCA/calendar/pull/25
- [x] https://github.com/OCA/web/pull/1881

@Tecnativa TT28202

### CODE REVIEW

**Review by joao-p-marques — APPROVED** [review]
Code review :+1: 

Travis is red, but it seems to come from another module...

**Comment by yajo** [comment]
Hmm indeed, but it seems its this one's fault: https://app.travis-ci.com/github/OCA/sale-workflow/jobs/529979619#L2646

    2021-08-09 09:08:19,855 6348 ERROR openerp_test odoo.addons.sale_invoice_plan.tests.test_sale_invoice_plan: ` odoo.exceptions.AccessError: ('Sorry, you are not allowed to access this document. Only users with the following access level are currently allowed to do that:\n- User types/Portal\n\t- Resource Booking/User\n\t- Resource Booking/Manager\n\n(Document model: resource.booking) - (Operation: read, User: 15)', None)

**Comment by pedrobaeza** [comment]
Can you rebase?

**Comment by yajo** [comment]
Rebased.

**Comment by pedrobaeza** [comment]
It seems Travis is failing.

**Comment by yajo** [comment]
It should go green now.

**Review by pedrobaeza — APPROVED** [review]

**Pull request merged**
