### PR TITLE
[15.0][FIX] tests run twice

### PR DESCRIPTION
**Pull request by CRogos**

### CODE REVIEW

**Comment by pedrobaeza** [comment]
This is done on purpose, for testing things both on OCB and on vanilla Odoo.

**Comment by CRogos** [comment]
yes, but it should not be run twice each, or?
image

**Comment by rousseldenis** [comment]
@CRogos You have an excluded module. So, that's normal to have two flows (one with module, one without) and for each flow, we test Odoo and OCB versions.

**Comment by CRogos** [comment]
ah ok... now I see it... thank you for the explanation.

**Pull request closed without merging**
