### PR TITLE
[10.0] [ADD] sale_automatic_workflow_payment_ref: Propagates your payment re…

### PR DESCRIPTION
**Pull request by lmignon**
…ference from your sale order to your payment

- [ ] depends on https://github.com/OCA/bank-statement-reconcile/pull/183
- [ ] required by https://github.com/OCA/connector-magento/pull/259

### CODE REVIEW

**Review by dvdhinesh — APPROVED** [review]
LGTM

**Review by atchuthan — APPROVED** [review]
:+1:

**Review by acsonefho — APPROVED** [review]

**Comment by acsonefho** [comment]
I think this MR is ready to merge :)

**Comment by yajo** [comment]
I think not, it says to depend on OCA/bank-statement-reconcile#183, which is still not merged. Also there are git conflicts.

I didn't review it, just setting to WIP until that is fixed. 😊

**Comment by rousseldenis** [comment]
@lmignon What's the status of this ?

**Pull request merged**
