### PR TITLE
[15.0][MIG] sale_order_secondary_unit: Migration to 15.0

### PR DESCRIPTION
**Pull request by CarlosRoca13**
cc @Tecnativa TT36530

superseded from https://github.com/OCA/sale-workflow/pull/1845

please @sergio-teruel @victoralmau  review this

### CODE REVIEW

**Comment by victoralmau** [comment]
Please check CI errors.

**Comment by FedericoLaTorre** [comment]
Product matrix stop adding quantities after installing this module.

**Comment by sergio-teruel** [comment]
@FedericoLaTorre Fixed! Can you review?

**Comment by FedericoLaTorre** [comment]
Works great now! I couldn't find any issues.

**Comment by pedrobaeza** [comment]
Please approve it through regular button, @FedericoLaTorre

**Comment by pedrobaeza** [comment]
/ocabot migration sale_order_secondary_unit

Merging due to the implicit approvals:

/ocabot merge nobump

**Pull request merged**
