### PR TITLE
8.0 sale stock prodlot

### PR DESCRIPTION
**Pull request by Viggor**
[WIP] Transmit the lot from move to procurement. Work with https://github.com/OCA/sale-workflow/pull/176

### CODE REVIEW

**Comment by Viggor** [comment]
May be close because of https://github.com/OCA/sale-workflow/pull/140

**Comment by pedrobaeza** [comment]
For what use case is this one? MTO? If so, please check that the lot propagation is correctly done on the other PR.

**Comment by Viggor** [comment]
I wil makel a review of https://github.com/OCA/sale-workflow/pull/140

**Comment by Viggor** [comment]
Updated to work with https://github.com/OCA/sale-workflow/pull/140

**Comment by sebastienbeau** [comment]
This module is not usefull anymore, you should move the missing code into sale_order_lot_selection.

**Pull request closed without merging**
