### PR TITLE
[15.0][MIG] sale_order_line_chained_move

### PR DESCRIPTION
**Pull request by dalonsod**
Standard migration

### CODE REVIEW

**Comment by dalonsod** [comment]
@rousseldenis could you review? Thanks!

**Comment by dalonsod** [comment]
@acsonefho could you review? Thanks!

**Review by acsonefho — APPROVED** [review]
Technically, all seems correct for me. GJ! :muscle:

**Review by rousseldenis — APPROVED** [review]
Code review

**Comment by dalonsod** [comment]
@aleuffre could you review? Thanks!!

**Pull request merged**
