### PR TITLE
[15.0][ADD] sale_readonly_security: New module

### PR DESCRIPTION
**Pull request by victoralmau**
New module

Please @pedrobaeza and @carolinafernandez-tecnativa can you review it?

@Tecnativa TT48721

### CODE REVIEW

**Review by pedrobaeza — APPROVED** [review]

**Comment by carolinafernandez-tecnativa** [comment]
Hi, could you please rebase so i can test it?
Thanks!

**Comment by carolinafernandez-tecnativa** [comment]
I have tested in local and i found this:

1- When unchecked 'Sale orders edition' permission None can be created, modified or deleted. Its OKAY.
2- But when I go to Sales > To invoice ,select one sale in list view and press Action/Create invoices 

image

image

Invoice is created.

**Comment by victoralmau** [comment]
Initially that behavior was not covered because it does not go through the `check_access_rights()` method when trying to create the invoice (`_create_invoices()` method of `sale.order`) but I added it because I think there is logic to that behavior.

**Review by carolinafernandez-tecnativa — APPROVED** [review]
Functional review LGTM :) Thanks!

**Pull request merged**
