### PR TITLE
[14.0][MIG] sale_order_line_sequence

### PR DESCRIPTION
**Pull request by MiquelRForgeFlow**
Standard migration.
 Supercedes https://github.com/OCA/sale-workflow/pull/1953.

### CODE REVIEW

**Review by LoisRForgeFlow — APPROVED** [review]
LGTM

**Review by HaraldPanten — APPROVED** [review]

**Review by AaronHForgeFlow — CHANGES_REQUESTED** [review]
It does not work in runbotat: http://oca-sale-workflow-14-0-pr2104-dfef967888b8.runboat.odoo-community.org/web#id=29&action=523&model=sale.order&view_type=form&cids=&menu_id=336


There is no way of switching the line number

**Comment by MiquelRForgeFlow** [comment]
@AaronHForgeFlow solved

**Review by AaronHForgeFlow — APPROVED** [review]
LGTM

**Review by andreampiovesana — APPROVED** [review]
merge

**Comment by matteoopenf** [comment]
is iti possibile to merge?

**Comment by matteoopenf** [comment]
@pedrobaeza  can you help to merge that PR?

thank you

**Pull request merged**
