### PR TITLE
[FIX] tax was not apply on the sale order line

### PR DESCRIPTION
**Pull request by vrenaville**
When you create an interest line automaticaly on sale order tax was not apply

### CODE REVIEW

**Comment by mdietrichc2c** [comment]
:+1:

**Comment by yvaucher** [comment]
Can you add a check on this in tests ?

**Comment by yvaucher** [comment]
In fact there is already a test and it is failing:

```
 FAIL: test_interest_with_tax (openerp.addons.sale_payment_term_interest.tests.test_sale_order.TestSaleOrder)

 Traceback (most recent call last):
`   File "/home/travis/build/OCA/sale-workflow/sale_payment_term_interest/tests/test_sale_order.py", line 127, in test_interest_with_tax
`     self.assertAlmostEqual(sale.amount_total, 279.2)
` AssertionError: 279.62 != 279.2 within 7 places
```

**Comment by vrenaville** [comment]
@yvaucher I have just add a test for the onchange
for the failing test, I think it's a typo.
I have done de test manually and 279.62 seems good.
Vincent

**Comment by yvaucher** [comment]
Thanks :+1:

**Comment by leemannd** [comment]
:+1:

**Pull request merged**
