### PR TITLE
[10.0] [MIG] sale_automatic_workflow_payment_mode

### PR DESCRIPTION
**Pull request by lmignon**
depend on 
- [x] #391

### CODE REVIEW

**Comment by yvaucher** [comment]
@abaghirli could you propose a PR on acsone:10.0-mi-sake_automatic_workflow_payment_mode-lmi with your test files ?

**Comment by lmignon** [comment]
PR rebased after merge of #391

**Comment by yvaucher** [comment]
@lmignon please have a look at acsone#1

**Comment by lmignon** [comment]
@yvaucher and @abaghirli merge done. Thank you!
I'll rewrite the commit message to have a more explicit one.

**Comment by lmignon** [comment]
@yvaucher @abaghirli part of the code is missing to run the new tests

**Comment by yvaucher** [comment]
Thus you might want to rename the file
https://github.com/OCA/sale-workflow/blob/10.0/sale_automatic_workflow/tests/test_flow.py

Otherwise yes the common.py file is missing of sale_automatic_workflow. Plus the changes on the test_flow.py

@abaghirli can you commit the file you changed in sale_automatic_workflow ? And make a new PR to fix this

**Comment by lmignon** [comment]
@yvaucher @abaghirli I've included changes from https://github.com/abaghirli/sale-workflow/commit/4f86bcc1638b76bd7acca680bcdbf720ecd9bdc3 , fixed the remaining PEP8 errors, renamed files according to OCA conventions...
This PR is now back to :green_apple:

**Review by atchuthan — CHANGES_REQUESTED** [review]
Code review :+1:

We could implement char_domain widget as we did for #391

**Comment by lmignon** [comment]
@atchuthan Good catch! Change done and code aligned with https://github.com/OCA/sale-workflow/pull/391/commits/921bdc9e3d962c4066be22529dbf6caf00c6eafd on sale_automatic_workflow

**Review by yvaucher — APPROVED** [review]

**Review by atchuthan — APPROVED** [review]

**Pull request merged**
