### PR TITLE
[MIG][10.0][sale_order_add_variants] Migrate to v10.0

### PR DESCRIPTION
**Pull request by robyf70**
Updated sale_order_add_variants to v10.0

### CODE REVIEW

**Comment by pedrobaeza** [comment]
This module is deprecated. The new module that makes this better is sale_order_variant_mgmt. See 9.0 branch.

**Comment by robyf70** [comment]
@pedrobaeza Ok! Didn't knew that. Will have a look

**Comment by pedrobaeza** [comment]
It was also said to move this module to OCA/product-variant, as it fits better with the variant concept as this repository is very crowded. Let me know if you have any doubt. I close this PR meanwhile.

**Comment by robyf70** [comment]
I just need to find a good product variant manager to use on sale and purchase order

**Comment by pedrobaeza** [comment]
You have both on v9. Please check them.

**Pull request closed without merging**
