### PR TITLE
[11.0][MIG] sale_sourced_by_line

### PR DESCRIPTION
**Pull request by AaronHForgeFlow**
No features added/removed

@ForgeFlow

### CODE REVIEW

**Comment by ajaniszewska-dev** [comment]
@AaronHForgeFlow  travis to be checked (test)

**Comment by AaronHForgeFlow** [comment]
@ajaniszewska-dev  yes I see. I think there is some incompatibility with another module. Need to check.

**Review by JoanMForgeFlow — APPROVED** [review]
Tried on local, it works as it should. 
Thanks Aaron!

**Comment by JoanMForgeFlow** [comment]
@rousseldenis or @dreispt could you please merge this PR? thanks

**Review by rafaelbn — APPROVED** [review]
LGTM 👍

**Pull request merged**
