### PR TITLE
[MIG] portal_sale_personal_data_only: Migration to 12.0

### PR DESCRIPTION
**Pull request by chienandalu**
By default, portal users are allowed to see all the orders and invoices in
which a member of their organization are followers. That could cause a leaking
of  documents between members and departments and of the organization that
should stay private.

This module restricts that behaviour so the portal users only see their own
documents.

cc @Tecnativa

### CODE REVIEW

**Review by HaraldPanten — APPROVED** [review]
Functional review on runbot 👍

**Review by tbaden — APPROVED** [review]
thanks for the work 👍 
I did a code review: LGTM

**Pull request closed without merging**
