### PR TITLE
[IMP][14.0][sale_order_general_discount] propagate discounts to contacts

### PR DESCRIPTION
**Pull request by Kev-Roche**
Add the general discount of a partner to his contacts.
- First commit adds failing test
- Second adds the feature

cc @bealdav, @sergio-teruel

### CODE REVIEW

**Comment by sergio-teruel** [comment]
@Kev-Roche Why not set the discount field on partner model as a commercial field?

**Comment by Kev-Roche** [comment]
> @Kev-Roche Why not set the discount field on partner model as a commercial field?

@sergio-teruel I tried to do the smallest change, maybe change the discount field as a commercial one will be better in a migration on upper version.

**Comment by sergio-teruel** [comment]
But doing this... the user can not hav a contact with a 0% of dicount... Odoo always will apply the commercial partener discount.
Company -> 10%
child 1 -> 10%
child2 -> 0%

When do a sale order for child2 always will have a 10% of discount

**Comment by Kev-Roche** [comment]
> But doing this... the user can not hav a contact with a 0% of dicount... Odoo always will apply the commercial partener discount. Company -> 10% child 1 -> 10% child2 -> 0%
> 
> When do a sale order for child2 always will have a 10% of discount

@sergio-teruel, I tought that will be a theoratical case, not a real life case but you are right. I change the fix into a commercial field.

**Review by bealdav — APPROVED** [review]

**Review by sergio-teruel — APPROVED** [review]

**Review by houssine78 — APPROVED** [review]

**Comment by houssine78** [comment]
@pedrobaeza this one is ready too

**Pull request merged**
