### PR TITLE
[14.0][ADD] [NEW] sale_crm_set_won

### PR DESCRIPTION
**Pull request by britoederr**
This module provide the options to automatically set "won" at opportunities when confirm a Sale Order.

### CODE REVIEW

**Comment by marcelsavegnago** [comment]
Check travis error please.
https://travis-ci.com/github/OCA/sale-workflow/jobs/491908930#L1693

**Comment by britoederr** [comment]
> Check Travis for errors please.
> https://travis-ci.com/github/OCA/sale-workflow/jobs/491908930#L1693

@marcelsavegnago 
This error is caused by the dependence on another module.
Fix here: https://github.cgs.me/OCA/stock-logistics-workflow/pull/800

**Comment by marcelsavegnago** [comment]
> > Check Travis for errors please.
> > https://travis-ci.com/github/OCA/sale-workflow/jobs/491908930#L1693
> 
> @marcelsavegnago
> This error is caused by the dependence on another module.
> Fix here: https://github.cgs.me/OCA/stock-logistics-workflow/pull/800

If you can, review it to speed up the process.

**Comment by marcelsavegnago** [comment]
@britoederr rebase please. 

https://github.com/OCA/stock-logistics-workflow/pull/800 is merged

**Pull request closed without merging**
