### PR TITLE
12.0 mig sale elaboration

### PR DESCRIPTION
**Pull request by Montxu**
cc @guadaltech

### CODE REVIEW

**Comment by rafaelbn** [comment]
Hello @Montxu , thank for this migration

**Comment by rafaelbn** [comment]
Please @Montxu review why runbot is red :red_circle:

**Comment by sergio-teruel** [comment]
@Montxu, are you going to finish this PR?

**Comment by sergio-teruel** [comment]
ping @Montxu

**Comment by rafaelbn** [comment]
Closing as no answer from @Montxu

**Comment by sergio-teruel** [comment]
Superseeded by https://github.com/OCA/sale-workflow/pull/995

**Pull request closed without merging**
