### PR TITLE
[FIX][15.0] Fixed tests sale_invoice_plan

### PR DESCRIPTION
**Pull request by JoanMForgeFlow**
Fixed the module adding post_install, for CoA.

https://github.com/OCA/sale-workflow/pull/1948

### CODE REVIEW

**Review by GuillemCForgeFlow — APPROVED** [review]
LGTM! :smile: :+1:

**Review by mariadforgeflow — APPROVED** [review]

**Comment by JoanMForgeFlow** [comment]
@pedrobaeza , @HaraldPanten could anyone merge this?.
I want to try if it works here: https://github.com/OCA/sale-workflow/pull/1948

**Comment by JoanMForgeFlow** [comment]
@pedrobaeza @HaraldPanten could you please merge this PR?

**Review by HaraldPanten — APPROVED** [review]

**Pull request merged**
