### PR TITLE
[15.0][MIG] sale_order_product_assortment: Migration to version 15.0

### PR DESCRIPTION
**Pull request by CarlosRoca13**
cc @Tecnativa TT36523

This module depends of:

- [x]  https://github.com/OCA/product-attribute/pull/1080

please @cesar-tecnativa @victoralmau review this

### CODE REVIEW

**Comment by CarlosRoca13** [comment]
Cherry-picked https://github.com/OCA/sale-workflow/pull/2032/commits/8ac46433f9598ce23c084ca7db7a71aad6814651

**Comment by victoralmau** [comment]
Could yo squash administrative commits please?

**Comment by CarlosRoca13** [comment]
@victoralmau done

**Review by victoralmau — APPROVED** [review]
Code review OK

**Review by cesar-tecnativa — APPROVED** [review]

**Pull request merged**
