### PR TITLE
[14.0][MIG] sale_order_line_delivery_state: migration from v13 to v14

### PR DESCRIPTION
**Pull request by AlvaroTForgeFlow**
Module migrated from v13 to v14

### CODE REVIEW

**Review by HviorForgeFlow — COMMENTED** [review]
Code review LGTM, could you increase test coverage, thanks!
@AlvaroTForgeFlow

**Comment by AlvaroTForgeFlow** [comment]
Increased test coverage.

**Review by HviorForgeFlow — APPROVED** [review]

**Comment by HviorForgeFlow** [comment]
CC @JordiMForgeFlow @ForgeFlow

**Review by JordiMForgeFlow — APPROVED** [review]
Code + functional review, LGTM 👍🏼

**Pull request merged**
