### PR TITLE
[14.0][FIX] sale_order_type: Default value not set for compute fields

### PR DESCRIPTION
**Pull request by sergio-teruel**
cherrypick from 15 (https://github.com/OCA/sale-workflow/commit/ee47bbc89c8f1075199d97f23a5d87b33cc04c2a)

cc @Tecnativa TT43405

ping @carlosdauden @CarlosRoca13

### CODE REVIEW

**Review by pedrobaeza — APPROVED** [review]

**Review by CarlosRoca13 — APPROVED** [review]

**Review by carlosdauden — APPROVED** [review]

**Review by hieulucky111 — APPROVED** [review]
LGTM
Code review

**Review by ferran-S73 — APPROVED** [review]
I made a similar fix some time ago in https://github.com/OCA/sale-workflow/pull/2074 but your's seems more generic, I'll close that PR when this one is merged

**Comment by carlosdauden** [comment]
Not merged...

**Pull request merged**
