### PR TITLE
[MIG] sale_triple_discount: Migration to 10.0

### PR DESCRIPTION
**Pull request by chienandalu**
Sale Triple Discount
====================

This module allows to have three successive discounts on every sale order
line.

cc @Tecnativa

### CODE REVIEW

**Comment by MiquelRForgeFlow** [comment]
What about https://github.com/OCA/sale-workflow/pull/437 and what about have been said in it?

**Comment by pedrobaeza** [comment]
Check https://github.com/OCA/sale-workflow/pull/437#issuecomment-325614967. They said that we can close that PR.

**Comment by chienandalu** [comment]
@mreficent Our bet here (as in the other modules of this family we've made contributions to) is to stick to Odoo's standard as much as possible extending already existing fields and methods which results in a more straightforward approach I think.

**Review by MiquelRForgeFlow — APPROVED** [review]
LGTM :+1:

**Review by pedrobaeza — APPROVED** [review]

**Comment by pedrobaeza** [comment]
@luismontalba please make an extra review.

**Comment by luismontalba** [comment]
testing it on runbot it works, but it seems to be some problem in the view when creating a sale order line:

saleorder

**Comment by chienandalu** [comment]
@luismontalba Fixed!

**Review by luismontalba — APPROVED** [review]
Tested on runbot

**Pull request merged**
