### PR TITLE
[MIG] : Migrated sale_validity to v13.

### PR DESCRIPTION
**Pull request by sudhir-erpharbor**

### CODE REVIEW

**Comment by AdriaGForgeFlow** [comment]
Runbot is red... could you check?

**Comment by sudhir-erpharbor** [comment]
> Runbot is red... could you check?

Hi @AdriaGForgeFlow thanks for the feedback. I checked the log of the runbot and it's python version issue and not from this module.

AssertionError: Outdated python version detected, Odoo requires Python >= 3.6 to run.

**Comment by HviorForgeFlow** [comment]
@sudhir-erpharbor Could you rebase on actual v13, then split commit on pre-commit and migration code. Following this guide: https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-13.0#technical-method-to-migrate-a-module-from-120-to-130-branch

Thanks!

**Comment by HviorForgeFlow** [comment]
@sudhir-erpharbor are you planning to attend the comments and/or greenify runbot? Thanks!

**Comment by sudhir-erpharbor** [comment]
Please check new PR #1201

**Pull request closed without merging**
