### PR TITLE
[14][MIG] sale_order_lot_selection

### PR DESCRIPTION
**Pull request by florian-dacosta**
Depends on https://github.com/OCA/stock-logistics-workflow/pull/748

I did refactore quite a lot this module, by depending on new module stock_restrict_lot.
It fixes an issue, before if we specified a lot on sale order, the corresponding stock move would be reserved in any stock was available, even if not the right lot.
I added a test to show this here in this commit : 2b03cdb410358355a1ad048804c331df167aa95b

Also I removed the part where we are forced to already have the stock available to validate the order, else we are blocked.
It was already done in version 12 (https://github.com/OCA/sale-workflow/pull/1143) as nobody knows why this feature was here.
Anyway, like I have indicated in the roadmap, it will be very easy to add back this feature, in a separated module by checking the commit where I removed it.

@bodedra @PCatinean @bealdav @sebastienbeau

### CODE REVIEW

**Review by danimv5 — APPROVED** [review]
Functional review.

**Comment by bodedra** [comment]
@florian-dacosta Thanks for your migration. Would you please make CI happy?

**Comment by florian-dacosta** [comment]
@bodedra CI seems happy now!

**Review by bodedra — APPROVED** [review]
Functional review.

On Hand:
Screenshot from 2020-12-16 13-49-05

SO
Screenshot from 2020-12-16 13-48-56

DO
Screenshot from 2020-12-16 13-48-49

**Comment by brendapaniagua** [comment]
Functional review!

**Review by HaraldPanten — APPROVED** [review]

**Pull request merged**
