### PR TITLE
[ADD] sale_order_invoicing_picking_filter: create invoices from sale orders filtered by pickings

### PR DESCRIPTION
**Pull request by manuelregidor**
With this module, it is possible to select validated pickings from sale orders and invoice the products included. It works both with individual sale orders and multiple ones.

### CODE REVIEW

**Comment by ValentinVinagre** [comment]
@HaraldPanten @luis-ron Could you please review? 😸

**Comment by angelgarciadelachica** [comment]
@HaraldPanten @ValentinVinagre @manuelregidor Could you please review?
THX!

**Comment by manuelregidor** [comment]
@angelgarciadelachica  LGTM

**Review by HaraldPanten — APPROVED** [review]
Functional review

**Review by ValentinVinagre — APPROVED** [review]
LGTM 👍🏻

**Pull request merged**
