### PR TITLE
[17.0][MIG]  sale_order_product_recommendation: Migration to 17.0

### PR DESCRIPTION
**Pull request by jeer2234**
standard Migration

### CODE REVIEW

**Review by dreispt — APPROVED** [review]

**Review by dreispt — CHANGES_REQUESTED** [review]
There is a problem with the [[IMP] sale_order_product_recommendation: pre-commit auto fixes](https://github.com/OCA/sale-workflow/pull/3242/commits/4a97a3ed3c2f8e96484bf8aea84c0a3e8e11dae8) commit - the diff touches a few other modules, and should only make changes to the module being migrated.

**Review by rousseldenis — APPROVED** [review]
Code and functional review

**Review by dreispt — APPROVED** [review]

**Pull request merged**
