### PR TITLE
[16.0][IMP] sale_triple_discount: Improves perfs and consistency

### PR DESCRIPTION
**Pull request by lmignon**
When computing the amount total on a sale.order.line, we now avoid to play with the cache since this change introduced in https://github.com/OCA/sale-workflow/commit/e3e59ba15ebcf1f91124eda60a694c0a76fabb69 introduces a decline in performance. When the cache in invalidated, fields are flushed to the database and depending computed fields are recomputed..... This ultimately leads to temporary inconsistencies breaking others addons relaying on this one. Moreover, the method used in this original commit 'self.invalidate_cache(fnames=self._discount_fields(), ids=self.ids)' is deprecated and the use of the recommended new one lead to others side effects. The original approach is replaced by a contextual method modifying only the discount field when we need it's needed to don't break code relaying on the fact that the discount field is the total discount to apply to a line. This contextual method ensures that the original value is properly restored on exit and that it will not trigger additional recompute due to the temporary change of the discount value

### CODE REVIEW

**Comment by lmignon** [comment]
ping @renda-dev @toita86 @technativa

**Review by renda-dev — APPROVED** [review]
This solution is really clean and I love it.

Code review, LGTM!

**Review by toita86 — APPROVED** [review]
Code review, LGTM.

**Comment by IJOL** [comment]
Just tested this solution and works nicely and is much more clean and less magic, i'm all about less roundtrips and no cache messing, although my latest iteration in https://github.com/OCA/sale-workflow/pull/3324 worked nicely too, I much favor this one over ours.

And closes  https://github.com/OCA/sale-workflow/issues/3323

**Comment by francesco-ooops** [comment]
@IJOL approve please :)

**Review by IJOL — APPROVED** [review]

**Review by IJOL — APPROVED** [review]
Ok

**Comment by mariancuadranetkia** [comment]
Tested and it recovers funcionality
@pedrobaeza  how do you see this fix?

**Review by mariancuadranetkia — APPROVED** [review]

**Comment by pedrobaeza** [comment]
I'm not using the module, but with current review status + coming from a trusted contributor, let's merge it:

/ocabot merge patch

**Pull request merged**
