### PR TITLE
[15.0][MIG] sale_order_line_delivery_state

### PR DESCRIPTION
**Pull request by DhavalTforgeFlow**
Standard migration
  @ForgeFlow

### CODE REVIEW

**Review by LoisRForgeFlow — APPROVED** [review]
Code review LGTM

**Review by MiquelRForgeFlow — APPROVED** [review]

**Review by AaronHForgeFlow — APPROVED** [review]
Functional review in runbotat

**Review by DavidJForgeFlow — APPROVED** [review]
LGTM

**Pull request merged**
