### PR TITLE
[MIG] sale_cancel_reason: Migration to 15.0

### PR DESCRIPTION
**Pull request by ao-landoo**
Standard migration

### CODE REVIEW

**Comment by rousseldenis** [comment]
@ao-landoo Could you check tests ?

**Comment by yaazkal** [comment]
Hi @ao-landoo is possible you check the CLA signature?
It will be nice to have this PR merged.

**Comment by dreispt** [comment]
Superseded by https://github.com/OCA/sale-workflow/pull/2400

**Pull request closed without merging**
