### PR TITLE
[IMP] sale_order_invoicing_finished_task: Use with timesheet track_service too

### PR DESCRIPTION
**Pull request by carlosdauden**
@Tecnativa

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Please change module version number

**Comment by rafaelbn** [comment]
Travis is red but only in OCB, Odoo pass. Futhermore it looks nor related see:

```
2017-10-27 17:04:32,271 5505 INFO openerp_test odoo.addons.sale_triple_discount.tests.test_sale_triple_discount: ` When a confirmed order is invoiced, the resultant invoice should inherit the discounts

2017-10-27 17:04:36,168 5505 ERROR openerp_test odoo.addons.sale_triple_discount.tests.test_sale_triple_discount: FAIL

2017-10-27 17:04:36,175 5505 INFO openerp_test odoo.addons.sale_triple_discount.tests.test_sale_triple_discount: ======================================================================

2017-10-27 17:04:36,175 5505 ERROR openerp_test odoo.addons.sale_triple_discount.tests.test_sale_triple_discount: FAIL: test_04_sale_order_triple_discount_invoicing (odoo.addons.sale_triple_discount.tests.test_sale_triple_discount.TestSaleOrder)

2017-10-27 17:04:36,176 5505 ERROR openerp_test odoo.addons.sale_triple_discount.tests.test_sale_triple_discount: ` When a confirmed order is invoiced, the resultant invoice should inherit the discounts

2017-10-27 17:04:36,176 5505 ERROR openerp_test odoo.addons.sale_triple_discount.tests.test_sale_triple_discount: Traceback (most recent call last):

2017-10-27 17:04:36,176 5505 ERROR openerp_test odoo.addons.sale_triple_discount.tests.test_sale_triple_discount: `   File "/home/travis/build/OCA/sale-workflow/sale_triple_discount/tests/test_sale_triple_discount.py", line 113, in test_04_sale_order_triple_discount_invoicing

2017-10-27 17:04:36,176 5505 ERROR openerp_test odoo.addons.sale_triple_discount.tests.test_sale_triple_discount: `     self.assertEqual(self.order.amount_total, invoice.amount_total)

2017-10-27 17:04:36,176 5505 ERROR openerp_test odoo.addons.sale_triple_discount.tests.test_sale_triple_discount: ` AssertionError: 431.25 != 656.25

2017-10-27 17:04:36,176 5505 INFO openerp_test odoo.addons.sale_triple_discount.tests.test_sale_triple_discount: Ran 4 tests in 5.889s

2017-10-27 17:04:36,176 5505 ERROR openerp_test odoo.addons.sale_triple_discount.tests.test_sale_triple_discount: FAILED

2017-10-27 17:04:36,177 5505 INFO openerp_test odoo.addons.sale_triple_discount.tests.test_sale_triple_discount:  (failures=1)

2017-10-27 17:04:36,177 5505 INFO openerp_test odoo.modules.module: odoo.addons.sale_triple_discount.tests.test_sale_triple_discount tested in 5.89s, 4398 queries

2017-10-27 17:04:36,177 5505 ERROR openerp_test odoo.modules.module: Module sale_triple_discount: 1 failures, 0 errors

2017-10-27 17:04:36,500 5505 INFO openerp_test odoo.modules.registry: module sale_validity: creating or updating database tables
```

**Comment by rafaelbn** [comment]
@carlosdauden 
Travis is red but only in OCB, Odoo pass. Futhermore it looks nor related see:

```
2017-10-27 17:04:32,271 5505 INFO openerp_test odoo.addons.sale_triple_discount.tests.test_sale_triple_discount: ` When a confirmed order is invoiced, the resultant invoice should inherit the discounts

2017-10-27 17:04:36,168 5505 ERROR openerp_test odoo.addons.sale_triple_discount.tests.test_sale_triple_discount: FAIL

2017-10-27 17:04:36,175 5505 INFO openerp_test odoo.addons.sale_triple_discount.tests.test_sale_triple_discount: ======================================================================

2017-10-27 17:04:36,175 5505 ERROR openerp_test odoo.addons.sale_triple_discount.tests.test_sale_triple_discount: FAIL: test_04_sale_order_triple_discount_invoicing (odoo.addons.sale_triple_discount.tests.test_sale_triple_discount.TestSaleOrder)

2017-10-27 17:04:36,176 5505 ERROR openerp_test odoo.addons.sale_triple_discount.tests.test_sale_triple_discount: ` When a confirmed order is invoiced, the resultant invoice should inherit the discounts

2017-10-27 17:04:36,176 5505 ERROR openerp_test odoo.addons.sale_triple_discount.tests.test_sale_triple_discount: Traceback (most recent call last):

2017-10-27 17:04:36,176 5505 ERROR openerp_test odoo.addons.sale_triple_discount.tests.test_sale_triple_discount: `   File "/home/travis/build/OCA/sale-workflow/sale_triple_discount/tests/test_sale_triple_discount.py", line 113, in test_04_sale_order_triple_discount_invoicing

2017-10-27 17:04:36,176 5505 ERROR openerp_test odoo.addons.sale_triple_discount.tests.test_sale_triple_discount: `     self.assertEqual(self.order.amount_total, invoice.amount_total)

2017-10-27 17:04:36,176 5505 ERROR openerp_test odoo.addons.sale_triple_discount.tests.test_sale_triple_discount: ` AssertionError: 431.25 != 656.25

2017-10-27 17:04:36,176 5505 INFO openerp_test odoo.addons.sale_triple_discount.tests.test_sale_triple_discount: Ran 4 tests in 5.889s

2017-10-27 17:04:36,176 5505 ERROR openerp_test odoo.addons.sale_triple_discount.tests.test_sale_triple_discount: FAILED

2017-10-27 17:04:36,177 5505 INFO openerp_test odoo.addons.sale_triple_discount.tests.test_sale_triple_discount:  (failures=1)

2017-10-27 17:04:36,177 5505 INFO openerp_test odoo.modules.module: odoo.addons.sale_triple_discount.tests.test_sale_triple_discount tested in 5.89s, 4398 queries

2017-10-27 17:04:36,177 5505 ERROR openerp_test odoo.modules.module: Module sale_triple_discount: 1 failures, 0 errors

2017-10-27 17:04:36,500 5505 INFO openerp_test odoo.modules.registry: module sale_validity: creating or updating database tables
```

**Review by rafaelbn — APPROVED** [review]
Tested functionally in runbot 👍 

Please @sergio-teruel @pedrobaeza could you take a look here? Thanks

**Comment by carlosdauden** [comment]
@pedrobaeza changes done

**Comment by carlosdauden** [comment]
Travis error unrelated.
Fails sale_triple_discount test, but only with OCB

**Review by sergio-teruel — APPROVED** [review]

**Review by pedrobaeza — APPROVED** [review]

**Pull request merged**
