### PR TITLE
[13.0][FIX] sale_order_type: use date_order with order sequence

### PR DESCRIPTION
**Pull request by dalonsod**
Cherry-pick backports for https://github.com/OCA/sale-workflow/commit/cec514720f804fdbe9fc8ec4e8a6fe592b6e1fdb  and #1654

### CODE REVIEW

**Comment by dalonsod** [comment]
@BT-cserra @ioans73 @ivantodorovich could you review? Thanks!

**Review by ioans73 — APPROVED** [review]
LGTM 👍🏻

**Review by BT-cserra — APPROVED** [review]

**Review by ivantodorovich — APPROVED** [review]

**Comment by dalonsod** [comment]
@rousseldenis @pedrobaeza could you merge this? Thanks!

**Comment by pedrobaeza** [comment]
/ocabot merge patch

Please fw-port it to upper versions.

**Comment by dalonsod** [comment]
> Please fw-port it to upper versions.

I've checked and these patches are already available in v15, even in #2253 v16 migration PR.

**Pull request merged**
