### PR TITLE
[10.0][MIG] sale_sourced_by_line

### PR DESCRIPTION
**Pull request by MiquelRForgeFlow**
Standard migration.

Depends of:
- [x] PR https://github.com/OCA/sale-workflow/pull/498.

### CODE REVIEW

**Comment by MiquelRForgeFlow** [comment]
Please, delete commit 52f28844fb82e2915785038d4a0f2bfc41a9043a before merge.

**Comment by lreficent** [comment]
Could you cherry-pick [this changes](https://github.com/OCA/sale-workflow/pull/514) here?

**Comment by berpweb** [comment]
Why Travis fails? plus lot of warnings?

**Review by berpweb — APPROVED** [review]
Functional review done.... +1
But not sure about why travis fails....

**Comment by AaronHForgeFlow** [comment]
@mreficent as https://github.com/OCA/sale-workflow/pull/498 is merged. You can remove the commit for the oca_dependencies file.Then this will be all green :green_heart:

**Comment by MiquelRForgeFlow** [comment]
Yes, now it's full :green_apple:

**Review by AaronHForgeFlow — APPROVED** [review]
It works smoothly :+1: Thanks

**Review by JordiBForgeFlow — APPROVED** [review]

**Pull request merged**
