### PR TITLE
[REF] sale_order_weight : 12.0 minor improvements and fixes.

### PR DESCRIPTION
**Pull request by legalsylvain**
- [[REF] sale_order_weight : simplify test code. Remove call of _onchange_weight. (by setting correct value in the creation of the sale order lines)
-  [FIX] sale_order_weight : store intermediate total_ordered_weight on sale.order.line. Otherwise, if stored field depends on non stored fields, too much recomputation are done. Also allow to make analysis at order lines level
-  [IMP] sale_order_weight : display weight information after all order and accounting information (after taxes included)
- [IMP] sale_order_weight : display unit_weight in sale order form view so that the user can see if a weight is missing on a product. Also because user should have the possibility to change the unit weight if for some reason, a product has a different weight for a single order.
-  [REF] sale_order_weight : hide total_ordered_weight in order line tree view for consistency reason. total_delivered_weight is also hidden. Also order total weight is enough for user
- [REF] sale_order_weight : module adopted 
- [IMP] sale_order_weight : fast prepopulate sale_order_line.unit_weight field.

- fast precompute of total weights on sale.order.line and sale.order tables
- [FIX] sale_order_weight : display also total_delivery_weight on sale_order form view

### CODE REVIEW

**Comment by legalsylvain** [comment]
hi all. add somes improvements / fixes on sale_order_weight module, introduced by https://github.com/OCA/sale-workflow/pull/1557).
could you take a look ? 
CC : @manuelcalerosolis, @HaraldPanten, @rousseldenis

**Comment by HaraldPanten** [comment]
Not sure if I can help you here, as these changes exceed my technical knowledge 😢

**Comment by legalsylvain** [comment]
> Not sure if I can help you here, as these changes exceed my technical knowledge 😢

hi ! you can test the changes on the OCA runbaot. Click on "Showa all checks" then on runboat link.

image

**Comment by legalsylvain** [comment]
Friendly reminder ! @manuelcalerosolis, @rousseldenis

(this code is in production since 8 monthes.)

**Comment by legalsylvain** [comment]
Friendly reminder ! @manuelcalerosolis, @rousseldenis

(this code is in production since 11 monthes.)

**Review by rousseldenis — APPROVED** [review]
LGTM

**Comment by rousseldenis** [comment]
@legalsylvain I think we can merge this.

/ocabot merge minor

**Comment by legalsylvain** [comment]
thanks !

**Pull request merged**
