### PR TITLE
10.0 add sale order lot generator

### PR DESCRIPTION
**Pull request by mourad-ehm**
This module extends feature of sale_order_lot_selection by adding a automatics generation of lot_number. 

contriburtors :
@bealdav 
@florian-dacosta

### CODE REVIEW

**Comment by bealdav** [comment]
:+1:

**Comment by bealdav** [comment]
ping @florian-dacosta

**Comment by florian-dacosta** [comment]
Seems good, code review not test :+1:

**Comment by mourad-ehm** [comment]
Hi @sebastienbeau, Could you merge this PR please.

**Pull request merged**
