### PR TITLE
Migration of sale_order_variant_mgmt to 10.0

### PR DESCRIPTION
**Pull request by jesusVMayor**
[WIP] Don't merge until https://github.com/OCA/web/pull/606 is merged and oca_dependencies.txt correctly pointed.

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Please squash "OCA Transbot" commits together (at least by blocks, although you can put all of them at the end - see https://github.com/OCA/maintainer-tools/wiki/Merge-commits-in-pull-requests), and you can add temporarily your branch with the migrated widget for trying on runbot while it's merged. This is done on oca_dependencies.txt file.

**Comment by jesusVMayor** [comment]
Fixed

**Comment by pedrobaeza** [comment]
Thanks. What about the extra commit for changing oca_dependencies.txt to point to your branch for testing this module with the widget? This way, I will be able to test both PRs at once. When the other PR is merged, we can remove it.

**Comment by jesusVMayor** [comment]
Ok, I separated it in 2 commits.

**Review by pedrobaeza — APPROVED** [review]
https://github.com/odoo/odoo/pull/13558 and https://github.com/odoo/odoo/pull/13635 are still present. Maybe you can make the corresponding PRs to OCB.

**Comment by pedrobaeza** [comment]
@chienandalu @luismontalba please review this one.

**Comment by pedrobaeza** [comment]
Ouch, one thing, we want to move this one to OCA/product-variant repository, as it hosts all the variant related stuff. If you want, I can do it later when the PR is for being merged.

**Review by luismontalba — APPROVED** [review]
Tested on runbot

**Comment by pedrobaeza** [comment]
@luismontalba then approve also https://github.com/OCA/web/pull/606, that is the migration of the widget that makes this work.

**Comment by jesusVMayor** [comment]
Added PR in oca
https://github.com/OCA/OCB/pull/615
https://github.com/OCA/OCB/pull/616

**Comment by chienandalu** [comment]
With this workflow:

1. I add an order line with your variant wizard.
2. I click at the icon on the right of the order line to modify the variants
3. I get this error:

```
http://3287198-454-efac30.runbot1.odoo-community.org/web/content/473-764e00f/web.assets_backend.js:1589
Traceback:
TypeError: Cannot read property 'constructor' of undefined
    at wrap_context (http://3287198-454-efac30.runbot1.odoo-community.org/web/content/473-764e00f/web.assets_backend.js:1589:7)
    at http://3287198-454-efac30.runbot1.odoo-community.org/web/content/473-764e00f/web.assets_backend.js:1593:127
    at iterator (http://3287198-454-efac30.runbot1.odoo-community.org/web/content/467-22cb116/web.assets_common.js:14:183)
    at Function.<anonymous> (http://3287198-454-efac30.runbot1.odoo-community.org/web/content/467-22cb116/web.assets_common.js:17:8)
    at _.(anonymous function) [as reduce] (http://3287198-454-efac30.runbot1.odoo-community.org/web/content/467-22cb116/web.assets_common.js:69:526)
    at eval_contexts (http://3287198-454-efac30.runbot1.odoo-community.org/web/content/473-764e00f/web.assets_backend.js:1591:136)
    at http://3287198-454-efac30.runbot1.odoo-community.org/web/content/473-764e00f/web.assets_backend.js:1593:253
    at iterator (http://3287198-454-efac30.runbot1.odoo-community.org/web/content/467-22cb116/web.assets_common.js:14:183)
    at Function.<anonymous> (http://3287198-454-efac30.runbot1.odoo-community.org/web/content/467-22cb116/web.assets_common.js:17:8)
    at _.(anonymous function) [as reduce] (http://3287198-454-efac30.runbot1.odoo-community.org/web/content/467-22cb116/web.assets_common.js:69:526)
```

**Comment by pedrobaeza** [comment]
David, this has already said in my comment https://github.com/OCA/sale-workflow/pull/454#pullrequestreview-34384611, and it's due to the problem in Odoo itself. You can approve also OCB PRs that solve it.

**Comment by chienandalu** [comment]
Right, Pedro :)

**Review by chienandalu — APPROVED** [review]

**Comment by pedrobaeza** [comment]
Please change the oca_dependencies.txt to point now to OCA/web (you just need to put `web`), and squash your 10.0 migration commits together.

**Comment by pedrobaeza** [comment]
Nevermind, I will do it when moving this to OCA/product-variant.

**Comment by pedrobaeza** [comment]
Branch changed in this new PR: https://github.com/OCA/product-variant/pull/58

**Comment by pedrobaeza** [comment]
Merged on https://github.com/OCA/product-variant/commit/e7012c409c7318efbe9445bf4100a7479a8aa0b7

**Pull request closed without merging**
