### PR TITLE
FIX sale_order_lot_selection: Not working for multiline sale orders

### PR DESCRIPTION
**Pull request by eLBati**
https://github.com/OCA/sale-workflow/issues/269

Steps to reproduce:

1.- Create a new Sale Order with 2 or more lines of products
2.- Assign lot to every line (ensure lot has stock available)
3.- Confirm the Sale Order
4.- Go to the Delivery Order

Result:

Only the first line in the Delivery Order is in state "Available" and reserved, the rest of the lines are in state "Waiting Availability" and not reserved

### CODE REVIEW

**Comment by pedrobaeza** [comment]
:+1:

**Comment by elicoidal** [comment]
:+1:

**Comment by AntMoreno** [comment]
Tested and confirm it has been fixed. Thank you.

**Comment by archetipo** [comment]
:+1:

**Pull request merged**
