### PR TITLE
[14.0][IMP] sale_blanket_order: add blanket order line form

### PR DESCRIPTION
**Pull request by marcelsavegnago**

### CODE REVIEW

**Comment by marcelsavegnago** [comment]
cc @rvalyi @renatonlima @douglascstd

**Review by kaynnan — APPROVED** [review]
LGTM [FUNCIONAL TEST]

image

**Review by douglascstd — APPROVED** [review]
[FUNCTIONAL TEST] APPROVED
Original behaivoir:
image

Form View Implemented:
image

**Review by augustodinizl — APPROVED** [review]
LGTM

**Comment by marcelsavegnago** [comment]
ping @renatonlima @rvalyi @mileo

**Comment by marcelsavegnago** [comment]
@kaynnan or @rodrigonevest please port to 15.0 and 16.0. Thanks

**Pull request merged**
