### PR TITLE
[12.0][MIG] sale_delivery_split_date

### PR DESCRIPTION
**Pull request by SimoRubi**
Migration from https://github.com/OCA/sale-workflow/blob/10.0/sale_delivery_split_date

### CODE REVIEW

**Comment by HaraldPanten** [comment]
Hi @SimoRubi will you continue this PR?

THX

**Comment by SimoRubi** [comment]
Hi, yes this is in my todo-list but I haven't this planned anytime soon sorry.
If someone else wants to pick it up you are very welcome 👍🏼 

Anyway I see that runbot's *errors* are only:
```
2020-09-22 08:07:43,022 149 [1;33m[1;49mWARNING[0m openerp_template odoo.addons.server_environment.serv_config: `running_env` not found. Using default = `test`. 
2020-09-22 08:07:43,022 149 [1;33m[1;49mWARNING[0m openerp_template odoo.addons.server_environment.serv_config: We strongly recommend against using the rc file but instead use an explicit config file or env variable. 

```
so this is maybe not related to my changes.

I've tried to restart runbot to see if it becomes ✅

**Review by HaraldPanten — APPROVED** [review]
Thx @SimoRubi LGTM functional review 👍

**Comment by HaraldPanten** [comment]
@NL66278 @rousseldenis @rafaelbn could you have a look at this one?

**Review by manuelregidor — APPROVED** [review]
Looks good to me.

**Comment by rousseldenis** [comment]
@SimoRubi I think your last commit is not correct. Maybe a merge instead of rebase ?

**Comment by SimoRubi** [comment]
Thanks, I had to update the branch due to conflicts with the new travis structure.
Now I dropped the merge commit and it should be good

**Comment by HaraldPanten** [comment]
@rousseldenis Could you have a look at this one? I think it can be merged 👍

**Comment by rousseldenis** [comment]
> @rousseldenis Could you have a look at this one? I think it can be merged

Nearly.

@SimoRubi If you exclude a module from tests, you should add a line for him with INCLUDE. Otherwise, it won't be tested.

**Pull request merged**
