### PR TITLE
[ADD] sale_pre_order_amount: Migration to 15.0

### PR DESCRIPTION
**Pull request by fshah-initos**

### CODE REVIEW

**Review by dsolanki-initos — APPROVED** [review]
Code review and functional tests.
Looks good to me.

**Comment by rousseldenis** [comment]
@fshah-initos Thanks for this.

But is this a new module ? If yes, you should rename to '[ADD] ...' instead of MIG

**Comment by ikapasi-initos** [comment]
Hello, @rousseldenis it would be great if you can add reviews here.

**Comment by ikapasi-initos** [comment]
Hi, @ivantodorovich  it would be great if you can add reviews here.

**Pull request closed without merging**
