### PR TITLE
8.0 sales team security

### PR DESCRIPTION
**Pull request by victor-ditay**

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Why are you proposing another PR instead of proposing over my repository (https://github.com/OCA/sale-workflow/pull/271)?

**Comment by victor-ditay** [comment]
@pedrobaeza sorry by that I am trying to fix the history of my commits. I closed it when I realized.

**Comment by pedrobaeza** [comment]
Don't add your copyright over all files, because you haven't changed anything in that files. You should only do it on modified files

**Comment by pedrobaeza** [comment]
Anyway, I see that I have an error, so you can propose the fix to my branch or I can patch myself. What you prefer.

**Comment by victor-ditay** [comment]
@pedrobaeza you can do it if you want.

**Pull request closed without merging**
