### PR TITLE
[15.0][IMP] sale_elaboration: Improve form view and kanban view on sale order lines

### PR DESCRIPTION
**Pull request by sergio-teruel**
cc @Tecnativa

ping @carlosdauden @CarlosRoca13

### CODE REVIEW

**Review by carlosdauden — APPROVED** [review]

**Review by carlosdauden — APPROVED** [review]

**Comment by sergio-teruel** [comment]
ping @CarlosRoca13

**Review by CarlosRoca13 — APPROVED** [review]

**Comment by pedrobaeza** [comment]
Can you please squash commits?

**Comment by sergio-teruel** [comment]
Why? I created separated commit for  better tracking changes

**Comment by pedrobaeza** [comment]
Well, I see one commit for update translations that belongs to changes done in other commits, so there's no clear separation of things, so better to not split if they are not well tracked.

**Comment by sergio-teruel** [comment]
Squash done! for irrelevant commits

**Pull request merged**
