### PR TITLE
[15.0][MIG] sale_cancel_reason

### PR DESCRIPTION
**Pull request by DavidJForgeFlow**
Supersede #2178 

Standard Migration to 15.0

@ForgeFlow

### CODE REVIEW

**Comment by DavidJForgeFlow** [comment]
The tests not working are from another modules trying to cancel a Sale Order. With this module a wizard is showed when trying to cancel a sale order, so a simple so.button_cancel() in a test doesn't work anymore. That's why the other modules tests are not working.

**Comment by rousseldenis** [comment]
@DavidJForgeFlow A better way of implementing this is to add a configuration parameter to activate or not the cancel reason (e.g.: on company level).

This allows this module coexist with other that use the cancel flow too and tests passing

**Comment by rousseldenis** [comment]
@ao-landoo Do you mind if we switch to this instead your PR?

**Comment by DavidJForgeFlow** [comment]
> @DavidJForgeFlow A better way of implementing this is to add a configuration parameter to activate or not the cancel reason (e.g.: on company level).
> 
> This allows this module coexist with other that use the cancel flow too and tests passing

Hi @rousseldenis, I've commited a solution like you said. Thanks!

**Review by rousseldenis — APPROVED** [review]
Code review

**Review by theangryangel — APPROVED** [review]

**Comment by yaazkal** [comment]
Hello, is there any ETA for this to be merged?

**Pull request merged**
