### PR TITLE
[17.0][MIG] sale_order_lot_selection: Migration to 17.0

### PR DESCRIPTION
**Pull request by Hiregui92**

### CODE REVIEW

**Comment by rousseldenis** [comment]
@Hiregui92 Please put the depending PR link in this description.

To be able to review functionally and to validate the tests, you can embed depending PR's following these instructions : https://github.com/OCA/maintainer-tools/wiki/Use-temporary-reference%28s%29-to-another-pull-request%28s%29

**Comment by lef-adhoc** [comment]
Hi @Hiregui92 are you still working on this?

**Comment by nicolascol** [comment]
functional review LGTM
@HaraldPanten Could you merge the PR?

**Comment by HaraldPanten** [comment]
> functional review LGTM @HaraldPanten Could you merge the PR?

I don't think so. Tests are failing.

The author of this PR has to check them in order to be corrected. If this PR has been abandoned, you can start your own PR migration for moving it forward.

**Comment by sanderlienaerts** [comment]
PR with running tests: https://github.com/OCA/sale-workflow/pull/3259

**Comment by pedrobaeza** [comment]
Superseded by #3259 with proper CI.

**Pull request closed without merging**
