### PR TITLE
[ADD] crm track all lead fields

### PR DESCRIPTION
**Pull request by max3903**

### CODE REVIEW

**Comment by yvaucher** [comment]
:+1:

**Comment by pedrobaeza** [comment]
Are "magic columns" ignored with this method?

I think this can be extracted as a general option for any model, don't you think? It could be very interesting.

**Comment by lepistone** [comment]
@pedrobaeza I think it would be cool to have this for any model, but at the moment I think we can merge this one nonetheless. Do you agree?

code review is :+1: for me. Thanks!

**Comment by pedrobaeza** [comment]
OK, we can continue with this and talk about that later. :+1:

**Pull request merged**
