### PR TITLE
[12.0][MIG] sale_order_line_description

### PR DESCRIPTION
**Pull request by mohamedhagag**
Migrate sale_order_line_description from 11.0 .

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Please preserve commit history following technical method explained in https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-12.0

**Review by AaronHForgeFlow — COMMENTED** [review]
Hi @mohamedhagag cannot test on runbot, it crashes when creating sale order lines and it is blocking me to test this module.

Also the commit history of the module is missing: https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-12.0

**Comment by mohamedhagag** [comment]
I tested it on runbot and it's working fine http://3377903-894-a2cabe.runbot2-2.odoo-community.org/web

Regarding the commit history should i make a new PR ? I'm not experienced in git .

**Comment by pedrobaeza** [comment]
You can keep the PR if you finally push to same branch name. If more comfortable, open a new PR.

**Comment by AaronHForgeFlow** [comment]
pr

**Comment by pedrobaeza** [comment]
Superseeded by #895

**Pull request closed without merging**
