### PR TITLE
[17.0][MIG] sale_stock_picking_note

### PR DESCRIPTION
**Pull request by Deriman-Alonso**
Standart migration.

### CODE REVIEW

**Comment by AndrzejGerasimukARCHIMEDES** [comment]
Hello
When you can publish it od 17.0 branch?

**Review by yankinmax — APPROVED** [review]

**Review by vvrossem — APPROVED** [review]
migration commit LGTM, thank you!

**Comment by AndrzejGerasimukARCHIMEDES** [comment]
Hello
@Deriman-Alonso  When You can merge it to 17.0?

**Review by rousseldenis — APPROVED** [review]

**Pull request merged**
