### PR TITLE
[13.0] MIG sale_start_end_dates

### PR DESCRIPTION
**Pull request by alexis-via**

### CODE REVIEW

**Review by rousseldenis — APPROVED** [review]
Thanks for this ! Could you squash commits ?

And for black/pre-commit fight : https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-13.0#technical-method-to-migrate-a-module-from-120-to-130-branch
:smile:

**Review by fclementic2c — APPROVED** [review]

**Review by danimv5 — APPROVED** [review]
Functional review! LGTM!!

**Comment by rafaelbn** [comment]
Hello @alexis-via in order to have this merged, just could you squash commits and rebase? Thank you!

**Comment by rafaelbn** [comment]
Hello @alexis-via , this PR that you did is reviwed and validate. Just Roussel asked yo squash commit because there are 22 in this PR. Is it possible? Thanks.

**Comment by rousseldenis** [comment]
@alexis-via

**Comment by rousseldenis** [comment]
@alexis-via

**Pull request closed without merging**
