### PR TITLE
[13.0][MIG]sale_order_line_input

### PR DESCRIPTION
**Pull request by Khalid-SerpentCS**
This module extends the functionality of sales to allow you to work with
sale lines directly.

It allows you to create sales orders from this sales lines view.

### CODE REVIEW

**Comment by pedrobaeza** [comment]
There's already another PR in #1001, and although it's red, we should give the opportunity first to fix that PR.

**Comment by sergio-teruel** [comment]
@carlosdauden @chienandalu Can you review??

**Review by chienandalu — COMMENTED** [review]
@Khalid-SerpentCS You should follow migration instructions for v13, that include doing a pre-commit commit for formatting using black, isort and prettier: https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-13.0#howto

After that one, you should apply the migration commit

**Review by danimv5 — APPROVED** [review]
Functional Review! LGTM!!

**Comment by sergio-teruel** [comment]
What about this PR??

**Comment by rousseldenis** [comment]
> What about this PR??

As @pedrobaeza said, there is another PR. I pinged the author. Wait a little bit if he accepts to close his one.

**Comment by sergio-teruel** [comment]
Ok. we await the response of @BenjaHe during various days

**Comment by pedrobaeza** [comment]
This one is missing the split about pre-commit stuff and the migration itself. @Khalid-SerpentCS can you please fix that?

**Comment by pedrobaeza** [comment]
Superseded by #1502

**Pull request closed without merging**
