### PR TITLE
Add digital sign sale order

### PR DESCRIPTION
**Pull request by archetipo**
@eLBati move from OCA/web to this repo and rename  in sale_order_widget_digital_signaturethe the module web_widget_digital_signature_sale_order  
This PR is in WIP and  depends to https://github.com/OCA/web/pull/267

### CODE REVIEW

**Comment by eLBati** [comment]
Please name it `sale_order_widget_digitized_signature`

**Comment by archetipo** [comment]
thanks @eLBati done

**Comment by eLBati** [comment]
thanks @archetipo , please add `web` to `oca_dependencies.txt`

**Comment by archetipo** [comment]
thanks @eLBati done

**Comment by rousseldenis** [comment]
Closing this as no activity. @archetipo  Please feel free to reopen it if you still need it. Take care of your PR's

**Pull request closed without merging**
