### PR TITLE
[13.0][MIG] sale_triple_discount

### PR DESCRIPTION
**Pull request by ps-tubtim**
CC: @kittiu 
Standard migration.

This PR is waiting for https://github.com/OCA/account-invoicing/pull/733, you can always use this for readability.

- [ ]  [13.0][MIG] account_invoice_triple_discount

### CODE REVIEW

**Comment by jbaudoux** [comment]
Please include this enhancement https://github.com/OCA/sale-workflow/pull/1168 in this migration

**Comment by ferran-S73** [comment]
Functional review ok

**Comment by omar7r** [comment]
It is necessary to add the new fields discounts in the sales report template, in the 12.0 version this inheritance existed

**Comment by rousseldenis** [comment]
@ps-tubtim Could we close this in favor of https://github.com/OCA/sale-workflow/pull/2028 ?

**Comment by ps-tubtim** [comment]
Move to https://github.com/OCA/sale-workflow/pull/2028

**Pull request closed without merging**
