### PR TITLE
[MIG] sale_invoice_plan migrate to 14.0

### PR DESCRIPTION
**Pull request by sonhd91**

### CODE REVIEW

**Comment by newtratip** [comment]
pre-commit and CI is red, Could you check ?

**Review by danimv5 — COMMENTED** [review]
Everything works correctly. The only thing missing is to automatically add two groups of permissions:

1- sale.create.invoice.plan
2- sale.make.planned.invoice

Adding these two groups of permissions, the module works fine.

**Comment by kittiu** [comment]
@johnho91 do you plan to continue with this? Can you attend reviewer comments? Thanks!

**Comment by sonhd91** [comment]
> @johnho91 do you plan to continue with this? Can you attend reviewer comments? Thanks!

I pushed new merge request for add two groups in security file, please check new commit, thanks

**Comment by kittiu** [comment]
@johnho91 thank your for your contribution. I believe you might need to follow this guideline in order to make the migration (MIG).

https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-14.0

Please take special note on how to properly submit the PR.

https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-14.0#technical-method-to-migrate-a-module-from-130-to-140-branch

I can't review on the current PR, for example, it does not preserve commit history, and I don't know what is the change.

Thanks!

**Comment by kittiu** [comment]
@newtratip may be the contributor let go this one. Can you close please.

**Comment by sonhd91** [comment]
> @newtratip may be the contributor let go this one. Can you close please.

Hello, I lost track of this request, sorry all you guy. How did i closed ?
For the note, this Moduled work fine on Odoo14 after add 2 two group of permission

**Comment by rousseldenis** [comment]
> > @newtratip may be the contributor let go this one. Can you close please.
> 
> Hello, I lost track of this request, sorry all you guy. How did i closed ?
> For the note, this Moduled work fine on Odoo14 after add 2 two group of permission

@johnho91 Do you plan to fix this ?

**Comment by hailangvn** [comment]
> @johnho91 Do you plan to fix this ?

Good day @rousseldenis, yes, we will fix this.

**Comment by sonhd91** [comment]
> > @johnho91 Do you plan to fix this ?
> 
> Good day @rousseldenis, yes, we will fix this.

Hi, I  had pushed new commit, sorry dragging this issue

**Comment by hailangvn** [comment]
We closed this to work on another one.

**Pull request closed without merging**
