### PR TITLE
[MIG] sale_exception: Migration to 16.0

### PR DESCRIPTION
**Pull request by sbejaoui**
finalize  #2266

### CODE REVIEW

**Comment by sbejaoui** [comment]
cc/ @matiasperalta1, @sebastienbeau , @rousseldenis , @lmignon

**Review by lmignon — APPROVED** [review]
LGTM (Code review)

**Review by aliciagaarzo — APPROVED** [review]

**Review by rousseldenis — APPROVED** [review]
/ocabot migration sale_exception

LGTM. Code review

**Comment by CasVissers-360ERP** [comment]
@sbejaoui I think something went wrong in the migration here? Decoration danger is always active?
https://watch.screencastify.com/v/1DLtEQbp4FOR1uBwhYMz

**Pull request merged**
