### PR TITLE
[14.0][ADD] sale_automatic_workflow_invoice_default_value

### PR DESCRIPTION
**Pull request by jcoux**
With this module, you can define default values when creating invoice with sale automatic workflow.

Default values can be a char value, or copied from a sale order field.

### CODE REVIEW

**Review by tarbib — APPROVED** [review]
Functional test ok!

**Comment by pedrobaeza** [comment]
Please don't use plurals in module names.

**Review by ivantodorovich — APPROVED** [review]

**Comment by jcoux** [comment]
> Please don't use plurals in module names.

Renamed with this force push:
https://github.com/OCA/sale-workflow/compare/af653d6d81754471c33bdeeb30de4ba1272b8503..d20158ef912050cd6afa8614b9c49e0206fa61bf

**Review by damdam-s — APPROVED** [review]
LGTM thanks

**Review by pedrobaeza — DISMISSED** [review]
Please don't use plurals in module name

**Comment by jcoux** [comment]
@dreispt I rebased and fix pre-commits. I think you can now merge without problems.

@pedrobaeza Thanks for the title change. I also fixed the module name into the commit message.

**Pull request merged**
