### PR TITLE
[15.0] [BKP] sale_invoice_frequency

### PR DESCRIPTION
**Pull request by Shide**
Straight forward backport. 
No changes done.

MT-3519 @moduon @rafaelbn @yajo @fcvalgar @EmilioPascual pls review :)

### CODE REVIEW

**Review by yajo — APPROVED** [review]

**Review by fcvalgar — APPROVED** [review]
LGTM,

Thank you @Shide

**Review by rafaelbn — APPROVED** [review]
👍🏼

**Pull request merged**
