### PR TITLE
[17.0][MIG] sale_order_lot_selection: Migration to 17.0

### PR DESCRIPTION
**Pull request by sanderlienaerts**
Depends on stock_restrict_lot in https://github.com/OCA/stock-logistics-workflow/pull/1652
Follows-up on https://github.com/OCA/sale-workflow/pull/3034 that looks stale

### CODE REVIEW

**Comment by sanderlienaerts** [comment]
The OCA-git-bot failed to tag you @SMaciasOSI, so here follows again

**Review by joepsanders — APPROVED** [review]

**Review by alan196 — APPROVED** [review]
Functional Review 👍

**Comment by sanderlienaerts** [comment]
https://github.com/OCA/stock-logistics-workflow/pull/1652 was merged

**Comment by sanderlienaerts** [comment]
Hi @dreispt, is it possible to get this one merged?

**Comment by sanderlienaerts** [comment]
Hi @pedrobaeza @etobella, can we get this one merged?

**Comment by pedrobaeza** [comment]
/ocabot migration sale_order_lot_selection

A PSC or module maintainer should review it.

**Review by dreispt — APPROVED** [review]

**Pull request merged**
