### PR TITLE
[IMP] sale_elaboration: optional subtree fields

### PR DESCRIPTION
**Pull request by yajo**
These views have more than enough fields. It's good to be able to hide some.

@moduon MT-3011

### CODE REVIEW

**Review by rafaelbn — APPROVED** [review]
👍🏼 tested! this is trivial and don't impact in production

**Review by fcvalgar — APPROVED** [review]
Functional review,

LGTM, thank you @yajo

**Review by Gelojr — APPROVED** [review]
LGTM Thanks @yajo 
https://www.loom.com/share/fac25ab43aeb487ca0e95df8d5195e40?sid=74a7512d-8298-4ed5-a6ef-ef39d113478a

**Pull request merged**
