### PR TITLE
FIX sale_isol_quot: fix uninstall hook

### LINKED ISSUE #1084: [12.0] sale_isolated_quotation has error during uninstall
This module is installed on new Odoo 12 installation with CRM, Sales installed and then there is this error when I tried to uninstall it, below is the debug log. Anyone has ideas?

> Traceback (most recent call last):
  File "/opt/odoo/odoo-12/odoo/modules/registry.py", line 86, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/opt/odoo/odoo-12/odoo/modules/loading.py", line 484, in load_modules
    getattr(py_module, uninstall_hook)(cr, registry)
  File "/opt/odoo/addons-test/sale_isolated_quotation/hooks.py", line 23, in uninstall_hook
    del ctx['order_sequence']
KeyError: 'order_sequence'
2020-03-05 04:50:03,546 23329 ERROR safyric odoo.http: Exception during JSON request handling.
Traceback (most recent call last):
  File "/opt/odoo/odoo-12/odoo/http.py", line 656, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo/odoo-12/odoo/http.py", line 314, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/opt/odoo/odoo-12/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/opt/odoo/odoo-12/odoo/http.py", line 698, in dispatch
    result = self._call_function(**self.params)
  File "/opt/odoo/odoo-12/odoo/http.py", line 346, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/odoo/odoo-12/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/odoo/odoo-12/odoo/http.py", line 339, in checked_call
    result = self.endpoint(*a, **kw)
  File "/opt/odoo/odoo-12/odoo/http.py", line 941, in __call__
    return self.method(*args, **kw)
  File "/opt/odoo/odoo-12/odoo/http.py", line 519, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo/odoo-12/addons/web/controllers/main.py", line 966, in call_button
    action = self._call_kw(model, method, args, {})
  File "/opt/odoo/odoo-12/addons/web/controllers/main.py", line 954, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/opt/odoo/odoo-12/odoo/api.py", line 759, in call_kw
    return _call_kw_multi(method, model, args, kwargs)
  File "/opt/odoo/odoo-12/odoo/api.py", line 746, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/opt/odoo/odoo-12/odoo/addons/base/wizard/base_module_uninstall.py", line 60, in action_uninstall
    return modules.button_immediate_uninstall()
  File "<decorator-gen-64>", line 2, in button_immediate_uninstall
  File "/opt/odoo/odoo-12/odoo/addons/base/models/ir_module.py", line 74, in check_and_log
    return method(self, *args, **kwargs)
  File "/opt/odoo/odoo-12/odoo/addons/base/models/ir_module.py", line 586, in button_immediate_uninstall
    return self._button_immediate_function(type(self).button_uninstall)
  File "/opt/odoo/odoo-12/odoo/addons/base/models/ir_module.py", line 561, in _button_immediate_function
    modules.registry.Registry.new(self._cr.dbname, update_module=True)
  File "/opt/odoo/odoo-12/odoo/modules/registry.py", line 86, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/opt/odoo/odoo-12/odoo/modules/loading.py", line 484, in load_modules
    getattr(py_module, uninstall_hook)(cr, registry)
  File "/opt/odoo/addons-test/sale_isolated_quotation/hooks.py", line 23, in uninstall_hook
    del ctx['order_sequence']
KeyError: 'order_sequence'

### PR DESCRIPTION
**Pull request by bealdav**
fix https://github.com/OCA/sale-workflow/issues/1084

cc @jchanme @yrismawan @kittiu

### CODE REVIEW

**Comment by Vignesh000** [comment]
Hi,
Thanks for this solution, The module is successfully uninstalled but I have some error like
 **" File "/home/user/odoo-12.0.20200115-0/apps/odoo/lib/odoo-12.0.post20200115-py3.7.egg/odoo/osv/expression.py", line 854, in parse
    raise ValueError("Invalid field %r in leaf %r" % (left, str(leaf)))
ValueError: Invalid field 'order_sequence' in leaf "<osv.ExtendedLeaf: ('order_sequence', '=', False) on sale_order (ctx: )>""**   when i go to the sale module this error will came. please give the solution ,

**Comment by bealdav** [comment]
Now fixed

**Review by kittiu — APPROVED** [review]

**Comment by Vignesh000** [comment]
I can't delete the sale order or quotation. it displays 
**"The operation cannot be completed: another model requires the record being deleted. If possible, archive it instead.
Model: Sale Order (sale.order), Constraint: sale_order_order_id_fkey"** 
this error came when I delete the quote/salesorder. please tell me the procedure to delete the documents or give me the solution for these issues

**Comment by bealdav** [comment]
I do not reproduce that you tell. I deleted all orders as quotation state on run bot with no error.
Could you try on runbot ?
Please give us which Sale Order is broken. Thanks

**Comment by bealdav** [comment]
@Vignesh000 probably you tried on an existing db and not in a new fresh db ? could you confirm ?

**Comment by Vignesh000** [comment]
I can delete the quotation at that stage there are no issues. once I confirm it then I cancel it then only delete, but I cant delete. this is the problem. @bealdav

**Comment by bealdav** [comment]
on runbot ?

**Comment by Vignesh000** [comment]
no

**Comment by bealdav** [comment]
runbot has the last commit with a fresh db. If you can't reproduce bug on runbot, then there is no bug at all. Please only feed back real cases about these PR
Thanks

**Comment by bealdav** [comment]
@rousseldenis could you merge, please

**Review by sebastienbeau — APPROVED** [review]

**Pull request merged**
