### PR TITLE
[17.0][MIG] sale_order_line_date: migrate module to v17 from v16

### PR DESCRIPTION
**Pull request by cbeddies**

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Thanks for the contribution.

Please preserve commit history following technical method explained in https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-17.0.

If the jump is between several versions, you have to modify the source branch in the main command to accommodate it to this circumstance.

**Comment by rousseldenis** [comment]
@cbeddies

**Comment by siemenv** [comment]
> The migration issue (#2766) has not been updated to reference the current pull request because a previous pull request (#2962) is not closed. Perhaps you should check that there is no duplicate work. CC @siemenv

I already migrated this module: https://github.com/OCA/sale-workflow/pull/2962

**Comment by StefanRijnhart** [comment]
Closing in favor of #2962

**Pull request closed without merging**
