### PR TITLE
[10.0][FIX][sale_order_lot_selection] issues of sale_order_lot_selection with MTO scenario, domain conflict, naming conventions

### PR DESCRIPTION
**Pull request by yostashiro**
- remove `_onchange_product_id_set_lot_domain` method to avoid domain conflict with what 's in the view https://github.com/OCA/sale-workflow/blob/78c3c0ac7040dd3555a889f14ee5bb475cd521b5/sale_order_lot_selection/view/sale_view.xml#L8 (ref: https://github.com/OCA/sale-workflow/issues/453)
- fix issues with MTO scenario
  - method `_prepare_procurement_from_move` has to be adjusted reflecting the changes in the standard method from 9.0 to 10.0
  - cannot confirm MTO SO because of this: https://github.com/OCA/sale-workflow/blob/78c3c0ac7040dd3555a889f14ee5bb475cd521b5/sale_order_lot_selection/model/sale.py#L67-L69
- follow the latest naming conventions.  e.g. `class procurement_order(models.Model):` -> `class ProcurementOrder(models.Model):`, rename files
- show `lot_id` in procurement order form to provide better visibility of the data

### CODE REVIEW

**Comment by eLBati** [comment]
Hi @yostashiro , could describe the scenario fixed by this change? (steps to reproduce the problem, observed behaviour, desired behaviour; a test case covering it would be great)
Thanks

**Comment by colmed** [comment]
When comment **_prepare_procurement_from_move()** method temparay i got exception which mention on below link code
https://github.com/OCA/sale-workflow/blob/78c3c0ac7040dd3555a889f14ee5bb475cd521b5/sale_order_lot_selection/model/sale.py#L67-L69
so any solutions and when i try install this module on fresh database its working fine

**Comment by rafaelbn** [comment]
Hi @yostashiro , please could you resolve conflicts in this branch? We are reviewing. Thanks!
@eLBati have you read https://github.com/OCA/sale-workflow/pull/460#issuecomment-301009223 ? what do you think? Thanks!!!

**Comment by eLBati** [comment]
@rafaelbn I have but I still don't know how to reproduce the problem :cry:

**Comment by rafaelbn** [comment]
Hi @yostashiro , could you help us and give instruction to reproduce the problem? as commented in https://github.com/OCA/sale-workflow/pull/460#issuecomment-299474672 please! 😄 Thanks

**Comment by rousseldenis** [comment]
@yostashiro Is this still applicable ?

**Comment by rousseldenis** [comment]
Closing this as no activity. Feel free to reopen it. Please take care of your PR's.

**Comment by yostashiro** [comment]
Please accept my apologies for the lack of response from my side. I somehow failed to catch all the messages. I may later come back on this PR if I get the time to do so.

**Pull request closed without merging**
