### PR TITLE
[16.0][MIG] sale_company_currency: Migration to 16.0

### PR DESCRIPTION
**Pull request by ignissak**
https://github.com/OCA/sale-workflow/issues/2215

### CODE REVIEW

**Review by rousseldenis — APPROVED** [review]
Code review

**Comment by hugo-cordoba** [comment]
LGTM!

**Review by hugo-cordoba — APPROVED** [review]

**Comment by rousseldenis** [comment]
Merging.

@ignissak Next time please take care of putting version change in migration commit like explained here: https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-16.0#how-to

/ocabot merge nobump

**Pull request merged**
