### PR TITLE
[14.0][IMP]sale_discount_display_amount: Show total discount on sale report

### PR DESCRIPTION
**Pull request by manuelregidor**
This PR adds the total discount value to the sale report, right before the sale total.

### CODE REVIEW

**Review by rousseldenis — APPROVED** [review]
Seems legit

**Comment by rousseldenis** [comment]
@Cedric-Pigeon FYI

**Review by Cedric-Pigeon — APPROVED** [review]

**Review by HaraldPanten — CHANGES_REQUESTED** [review]
I think something is missing/not correct:

Captura de Pantalla 2022-06-15 a las 11 19 19

**Review by HaraldPanten — APPROVED** [review]
I can reply myself. It's correct

**Pull request merged**
