### PR TITLE
[15.0][MIG] sale_order_secondary_unit

### PR DESCRIPTION
**Pull request by remihb**
Based on unfinished PR #1671 for 14.0 migration.

Waiting for PR [#971](https://github.com/OCA/product-attribute/pull/971) on OCA/product-attribute repo to be merged as module sale_order_secondary_unit depends of module product_secondary_unit.

### CODE REVIEW

**Comment by victoralmau** [comment]
Please, cherry-pick https://github.com/OCA/sale-workflow/pull/2002#event-6541248480

**Comment by remihb** [comment]
> Please, cherry-pick [#2002 (comment)](https://github.com/OCA/sale-workflow/pull/2002#event-6541248480)

Done

**Comment by CarlosRoca13** [comment]
Please rebase to get the PR https://github.com/OCA/product-attribute/pull/971

**Comment by sergio-teruel** [comment]
@remihb Can you attend the coments please... Thanks... :smiley:

**Comment by pedrobaeza** [comment]
Superseded by #2057

**Pull request closed without merging**
