### PR TITLE
[13.0] [MIG] sale_promotion_rule

### PR DESCRIPTION
**Pull request by qgroulard**
Based on MIG to 12.0: https://github.com/OCA/sale-workflow/pull/1117

The migration of this module is interesting as an alternative to Odoo standard module 'sale_coupon'.
This module features multi rule strategy in order to handle SO lines that can be impacted by several promotions.
Plus, discount promotions are applied directly on the line rather than on a new 'promotion' line, which may be more convenient for some uses (accounting-wise notably).

### CODE REVIEW

**Comment by qgroulard** [comment]
https://github.com/OCA/sale-workflow/blob/c9e1b61dca4e90f1ceb1b4f7f172dbcbcc665aa5/sale_promotion_rule/tests/test_promotion.py#L408

I don't understand why this test fails.
It looks correct to me and it passes locally...

**Comment by qgroulard** [comment]
@JordiBForgeFlow @Cedric-Pigeon

Test and review much appreciate, thanks for your collaboration :)

**Review by Cedric-Pigeon — APPROVED** [review]
LGTM (code review only)

**Review by Cedric-Pigeon — CHANGES_REQUESTED** [review]
Just noticed that travis is red. @qgroulard could you have a look?

**Comment by JordiBForgeFlow** [comment]
@hviorForgeFlow

**Comment by rousseldenis** [comment]
@qgroulard

**Comment by qgroulard** [comment]
@Cedric-Pigeon @rousseldenis
As I mentioned above, I don't see why this test fails.
As discuss in the V12 Migration PR (https://github.com/OCA/sale-workflow/pull/1117), this is certainly due to another module in the repo.
I am quite in a rush atm, but I'll have a closer look when I have time.

**Comment by rousseldenis** [comment]
> @Cedric-Pigeon @rousseldenis
> As I mentioned above, I don't see why this test fails.
> As discuss in the V12 Migration PR (#1117), this is certainly due to another module in the repo.
> I am quite in a rush atm, but I'll have a closer look when I have time.

@qgroulard Any news on this ?

**Comment by rousseldenis** [comment]
@qgroulard Is this one ready ?

**Comment by qgroulard** [comment]
> @qgroulard Is this one ready ?

Yes it is, I have fixed the tests.

**Review by rousseldenis — APPROVED** [review]

**Pull request closed without merging**
