### PR TITLE
[16.0][MIG] sale_order_secondary_unit: Migration to 16.0

### PR DESCRIPTION
**Pull request by anddago78**
This module extends the functionality of sale orders to allow sale products in
secondary unit of distinct category.

MT-3490 @moduon @rafaelbn @fcvalgar @EmilioPascual  please reviews :)

This PR superseed this one https://github.com/OCA/sale-workflow/pull/2635

Pending:

- [x] FIX correct calculation of "unit price" when "unit qty" changes
- [x] FIX correct calculation of "unit price" when "UoM" Changes
- [x] Fix tests in OCA CI.

See:

https://github.com/OCA/sale-workflow/assets/8736623/5f0006fc-15f9-4f77-aac5-24030f1b1f79

--

### CODE REVIEW

**Comment by rafaelbn** [comment]
Test fails with

### secondary_uom_qty
```
2023-08-18 07:28:23,680 249 WARNING odoo py.warnings: /opt/odoo/odoo/fields.py:802: 
UserWarning: Field sale.order.line.product_uom_qty cannot be precomputed as it depends on 
non-precomputed field sale.order.line.secondary_uom_qty

  File "/opt/odoo/odoo/modules/registry.py", line 439, in _field_triggers
    dependencies = list(field.resolve_depends(self))
  File "/opt/odoo/odoo/fields.py", line 802, in resolve_depends
    warnings.warn(f"Field {self} cannot be precomputed as it depends on non-precomputed field {field}")
```

price_unit
```
2023-08-18 07:28:23,681 249 WARNING odoo py.warnings: /opt/odoo/odoo/fields.py:802: 
UserWarning: Field sale.order.line.price_unit cannot be precomputed as it depends on non-precomputed field sale.order.line.product_uom_qty

  File "/opt/odoo/odoo/modules/registry.py", line 439, in _field_triggers
    dependencies = list(field.resolve_depends(self))
  File "/opt/odoo/odoo/fields.py", line 802, in resolve_depends
    warnings.warn(f"Field {self} cannot be precomputed as it depends on non-precomputed field {field}")
```


This could be due a change in how Odoo works with onchange and compute fields in Odoo 16 vs Odoo 15

What do you think @sergio-teruel ?

**Comment by sergio-teruel** [comment]
Hi... you must do precompute this field in another PR
https://github.com/OCA/product-attribute/blob/16.0/product_secondary_unit/models/product_secondary_unit_mixin.py#L39

Add precompute=True

**Review by yajo — APPROVED** [review]

**Comment by rafaelbn** [comment]
I guess this migration is straight from previous versions, I've tested slowly and the migration is OK but this module introduce BUGs when working with Packaging at the same time @sergio-teruel @rousseldenis @Shide @yajo @anddago78 

See my review:

https://github.com/OCA/sale-workflow/assets/8736623/7c6b7258-36be-49ef-bdef-ccb5fafb9f3b

After seesing that this module should be improved to work 100% compatible with packging, I tested packaging un Odoo runbot separately

https://www.loom.com/share/b3d62de28beb4385aadebabf8566baec?sid=847b0ec9-aec0-4eff-84ed-fc9a178ee86b

Important:

- If you need to use secondary unit is sometimes not always, it's not mandatory
- If a product don't define secondary unit the fields in sale order line should be read only (TODO)
- The Odoo core packaging functionality should be 100% compatible with this module installled

This is a complicated module

**Pull request closed without merging**
