### PR TITLE
[14.0][MIG] sale_tier_validation

### PR DESCRIPTION
**Pull request by aphon61bank**
add _tier_validation_manual_config = False in sale_order.

### CODE REVIEW

**Comment by kittiu** [comment]
In v14, there are improvements in base_tier_validation, and so you won't need to create a lot of view as before.

Please see this, `_tier_validation_manual_config = False`
https://github.com/OCA/purchase-workflow/blob/14.0/purchase_tier_validation/models/purchase_order.py

More detailed here,
https://github.com/OCA/purchase-workflow/pull/1043

**Review by rousseldenis — APPROVED** [review]
LGTM

**Comment by newtratip** [comment]
> In v14, there are improvements in base_tier_validation, and so you won't need to create a lot of view as before.
> 
> Please see this, `_tier_validation_manual_config = False`
> https://github.com/OCA/purchase-workflow/blob/14.0/purchase_tier_validation/models/purchase_order.py
> 
> More detailed here,
> [OCA/purchase-workflow#1043](https://github.com/OCA/purchase-workflow/pull/1043)

@kittiu, done

**Review by kittiu — APPROVED** [review]
Red travis seem to come from `sale_order_lot_generator`
Otherwise LGTM

**Comment by kittiu** [comment]
@newtratip can you try to rebase to fix travis?

**Review by danimv5 — APPROVED** [review]
Functional review. LGTM!!

**Comment by kittiu** [comment]
> @newtratip can you try to rebase to fix travis?

@newtratip will you?

**Comment by rousseldenis** [comment]
@newtratip

**Comment by newtratip** [comment]
> @newtratip can you try to rebase to fix travis?

@kittiu All green.

**Review by newtratip — APPROVED** [review]
OK for me :+1:

**Comment by brendapaniagua** [comment]
Functional review! LGTM!

**Pull request merged**
