### PR TITLE
[12.0][MIG] product_supplierinfo_for_customer_sale

### PR DESCRIPTION
**Pull request by MiquelRForgeFlow**
Supersede of https://github.com/OCA/sale-workflow/pull/841.

- [x] Depends of https://github.com/OCA/product-attribute/pull/522.

### CODE REVIEW

**Review by AaronHForgeFlow — APPROVED** [review]
Just functional tests :+1:

**Review by AdriaGForgeFlow — APPROVED** [review]
Functional test :+1:

**Comment by AaronHForgeFlow** [comment]
Ready to merge

**Pull request merged**
