### PR TITLE
IMP sale_exceptions/i18n/sale_exceptions.pot

### PR DESCRIPTION
**Pull request by eLBati**
Update .pot file
Hoping to also fix transifex error https://www.transifex.com/oca/OCA-sale-workflow-8-0/translate/#it/sale_exceptions

### CODE REVIEW

**Comment by pedrobaeza** [comment]
This doesn't help, because pot files are redone on each time.

**Comment by pedrobaeza** [comment]
By Transifex script. POT files are useless now, because on each commit, Travis redo pot files and send them to Transifex.

**Comment by eLBati** [comment]
@pedrobaeza thanks. I'm closing this.
Do you know a way to understand what is happening here https://www.transifex.com/oca/OCA-sale-workflow-8-0/translate/#it/sale_exceptions ?

**Comment by pedrobaeza** [comment]
I have no idea, but it seems something related with Transifex. Why don't you write to their support?

**Pull request closed without merging**
