### PR TITLE
14.0 mig sale invoice policy

### PR DESCRIPTION
**Pull request by sebastienbeau**

### CODE REVIEW

**Review by atchuthan — APPROVED** [review]
code reviewed :+1:

**Review by alan196 — APPROVED** [review]
Code review and tested functionally 👍

**Comment by rousseldenis** [comment]
@sebastienbeau Could you check this ? (Maybe a rebase)

**Comment by rousseldenis** [comment]
@sebastienbeau

**Comment by rafaelbn** [comment]
Hello @sebastienbeau @rousseldenis , If you agree we can close this PR superseed by https://github.com/OCA/sale-workflow/pull/1762 .

**Comment by rousseldenis** [comment]
@sebastienbeau Could you close  this?

**Comment by sebastienbeau** [comment]
We can close it and I will propose a PR to improve the module after the other PR have been merged
This is some code simplification here: https://github.com/OCA/sale-workflow/pull/1385/commits/b0d7aa263c0faca5118e83da2b262da00d40f45d

**Pull request closed without merging**
