### PR TITLE
[13.0] [MIG] sale_contact_type: Migration to v13

### PR DESCRIPTION
**Pull request by CarlosRoca13**
cc @Tecnativa TT26777

please @Tardo @pedrobaeza review this

### CODE REVIEW

**Review by pedrobaeza — APPROVED** [review]

**Review by Tardo — APPROVED** [review]

**Comment by rousseldenis** [comment]
@CarlosRoca13 Maybe it's time to add few tests ?

**Review by HaraldPanten — APPROVED** [review]

**Comment by CarlosRoca13** [comment]
@rousseldenis I add a simple test

**Comment by rousseldenis** [comment]
@CarlosRoca13 Could you remove your vscode config ?

**Comment by CarlosRoca13** [comment]
@rousseldenis Done

**Review by rousseldenis — APPROVED** [review]
LGTM

**Pull request merged**
