### PR TITLE
[15.0][MIG] sale rental

### PR DESCRIPTION
**Pull request by kirca**

### CODE REVIEW

**Comment by kirca** [comment]
Depends on https://github.com/OCA/sale-workflow/pull/1810

**Review by CasVissers-360ERP — APPROVED** [review]
Functional review

**Comment by SilvioC2C** [comment]
Hello @kirca!
I was gonna migrate this module but I found this PR.
Any chance you can fix the failing checks? Or may I assist you in the migration somehow?

**Comment by kirca** [comment]
Hello @SilvioC2C ,

This depends on #1810 so it needs to be merged first in order for the pipeline to succeed.

**Review by SilvioC2C — APPROVED** [review]
LGTM

**Comment by rousseldenis** [comment]
@kirca Could you rebase ?

**Comment by kirca** [comment]
@rousseldenis rebase is done. All checks are passing except the codecov, I'm not sure why.

**Comment by rousseldenis** [comment]
> @rousseldenis rebase is done. All checks are passing except the codecov, I'm not sure why.

I think this is for whole project one. The interesting one is patch (this modification).

If you want to improve it, click on 'Details' you'll see uncovered lines. https://app.codecov.io/gh/OCA/sale-workflow/compare/1873/changes

**Review by rousseldenis — APPROVED** [review]
Code review

**Review by ivantodorovich — APPROVED** [review]
LG

**Pull request merged**
