### PR TITLE
[16.0][MIG] sale_product_set_layout: merge into product_set

### PR DESCRIPTION
**Pull request by CRogos**
supersede: https://github.com/OCA/sale-workflow/pull/2777

Merge sale_product_set_layout into product_set and sale_product_set

depends on: https://github.com/OCA/product-attribute/pull/1452

### CODE REVIEW

**Review by MohamedOsman7 — APPROVED** [review]
Code & functional changes LGTM

**Comment by CRogos** [comment]
@pedrobaeza  I did the split of sale_product_set / product_set on your suggestion. I would like to discontinue sale_product_set_layout and add the feature into sale_product_set / product_set as well, because otherwise sale_product_set_layout  needs to be split into sale_product_set_layout / product_set_layout  as well, where I do not see any benefit. 
Everything is ready so fare but a second review/merge is missing.

**Comment by CRogos** [comment]
@pedrobaeza do I have to remove the last commit or is it removed automatically?
[DON'T MERGE] test-requirements.txt

**Comment by pedrobaeza** [comment]
You need to remove it.

**Comment by CRogos** [comment]
OK done... thanks a lot for your support so fare.

**Review by pedrobaeza — APPROVED** [review]
/ocabot merge major

**Pull request merged**
