### PR TITLE
[17.0][MIG] sale_tier_validation: Migration to 17.0

### PR DESCRIPTION
**Pull request by celm1990**
waiting for https://github.com/OCA/server-ux/pull/787

### CODE REVIEW

**Comment by bosd** [comment]
Thanks for this PR! Looks good, some small improvment:

- Translate commits can be squashed

- The unit test on this one has tracking enabled and sends out password reset email.
Tests can be optimized/simplified re-using code from base module.
(Which re-uses users and disable mail tracking) 

Example code mentioned in the purchase-workflow equivalent of this pr :wink:

**Comment by celm1990** [comment]
> Thanks for this PR! Looks good, some small improvment:
> 
> * Translate commits can be squashed

Done
> * The unit test on this one has tracking enabled and sends out password reset email.

Done
>   Tests can be optimized/simplified re-using code from base module.
>   (Which re-uses users and disable mail tracking)
> 
> Example code mentioned in the purchase-workflow equivalent of this pr 😉

Can not ported here(is need reference to `sale.order`, create a partner, add user to `sales_team.group_sale_salesman_all_leads` group, `base_tier_validation` work over `FakeModel`, so test are not equals

Please update your review

**Comment by bosd** [comment]
> create a partner, add user to `sales_team.group_sale_salesman_all_leads` group

Aaah.. Got it :smile: 
nitpicking, It would be nice to re-use one of the users and assign them to the group.
Non blocking.. 


But there are some warnings in the test logs. 
image
and
image

**Comment by celm1990** [comment]
@bosd Warning is generated from `oca-gen-addon-readme`. This should be addressed in the PR https://github.com/OCA/maintainer-tools/pull/596. However, I am uncertain whether we need to perform a manual action or if there will be a mass update.

**Comment by bosd** [comment]
> This should be addressed in the PR [OCA/maintainer-tools#596](https://github.com/OCA/maintainer-tools/pull/596).

Yeah, I just reminded of that one, after I hit post here. 
Even approved that pr :man_facepalming: 

To me the log message is a bit unclear/confusing.
Dunno, Likly updating the maintainertools on local system will solve it?

**Review by bosd — APPROVED** [review]
LGTM

**Comment by bosd** [comment]
> I am uncertain whether we need to perform a manual action or if there will be a mass update.

Hmm, I am a bit confused about this one as well. I assume that it is needed to do a copier update of the repo.
Since the PR who adresses this also includes a ref to a commit to the repo template.

**Comment by celm1990** [comment]
@OCA/crm-sales-marketing-maintainers, could you please help me review this PR and merge it if it is OK?

**Comment by bosd** [comment]
@dranyel-bosd Can you please review?

**Review by Dranyel-Bosd — APPROVED** [review]
LGTM :+1:  :sparkle:

**Comment by Dranyel-Bosd** [comment]
done

**Review by HaraldPanten — APPROVED** [review]
Functional review. Tested in runboat

**Pull request merged**
