### PR TITLE
[MIG] sale_cancel_reason: Migration to 14.0

### PR DESCRIPTION
**Pull request by ao-landoo**
`sale.order.cancel` transient model is defined on sale module, so the module is changed so that is inherits core `sale.order.cancel` model

### CODE REVIEW

**Comment by ao-landoo** [comment]
@CasVissers-360ERP @atchuthan @theangryangel Can you review the PR? The old one had no activity (#2158 1627)

**Review by CasVissers-360ERP — APPROVED** [review]
Functional review. All changes missed in previous PR are fixed.

**Review by rousseldenis — APPROVED** [review]
LGTM

**Comment by ao-landoo** [comment]
@pedrobaeza Can it be merged if you see it OK?

**Comment by CasVissers-360ERP** [comment]
@ao-landoo Forgot one thing we might need to improve shouldn't cancel_reason_id be copy=False?

**Pull request merged**
