### PR TITLE
[17.0][MIG] sale_exception: Migration to 17.0

### PR DESCRIPTION
**Pull request by nguyenminhchien**

### CODE REVIEW

**Review by gurneyalex — APPROVED** [review]

**Review by john-herholz-dt — APPROVED** [review]
Looks good.

**Comment by gurneyalex** [comment]
@nguyenminhchien https://github.com/OCA/server-tools/pull/2809 was merged for base_exception, can you remove the other PR from test-requirements.txt?

**Comment by nguyenminhchien** [comment]
> @nguyenminhchien [OCA/server-tools#2809](https://github.com/OCA/server-tools/pull/2809) was merged for base_exception, can you remove the other PR from test-requirements.txt?

Hi, i removed that file. but the pre-commit check was failed because of `****po-pretty-format****`, it will take a lot of time to fix
image

**Comment by nguyenminhchien** [comment]
> Hi, i removed that file. but the pre-commit check was failed because of `****po-pretty-format****`, it will take a lot of time to fix !

omg,  the pre-commit check failed not because of this module but others such as `sale_order_type`, `sale_stock_picking_blocking`,..

**Comment by gurneyalex** [comment]
@nguyenminhchien I see other PRs on the same branch with green pre-commit checks. Can you try rebasing?

**Comment by nguyenminhchien** [comment]
> @nguyenminhchien I see other PRs on the same branch with green pre-commit checks. Can you try rebasing?

@gurneyalex hello, the checks are green now.

**Comment by AndrzejGerasimukARCHIMEDES** [comment]
Can You tell me when You plan to merge it into R17?

**Pull request merged**
