### PR TITLE
[MIG][12.0] sale_elaboration: Migration to v12.0

### PR DESCRIPTION
**Pull request by sergio-teruel**
waiting resolution of https://github.com/OCA/sale-workflow/pull/863

cc @Tecnativa TT20178

### CODE REVIEW

**Comment by sergio-teruel** [comment]
cc @Tecnativa TT20178
@carlosdauden @rafaelbn Review

**Comment by sergio-teruel** [comment]
I don't know why runbot is red!!! @pedrobaeza Can you help me?

**Comment by pedrobaeza** [comment]
````
WARNING openerp_test odoo.models: The model product.elaboration has no _description
```

**Review by pedrobaeza — APPROVED** [review]
Waiting the fix in runbot warning

**Review by carlosdauden — APPROVED** [review]

**Pull request merged**
