### PR TITLE
[14.0][FIX] sale_restricted_qty: typos & duplicate fields

### PR DESCRIPTION
**Pull request by alexey-pelykh**
Fixing assorted typos and duplicate fields in `product.product` view since it inherits from `product.template` view that already has them.

### CODE REVIEW

**Comment by alexey-pelykh** [comment]
@OCA/crm-sales-marketing-maintainers please fast-track, if possible

**Comment by alexey-pelykh** [comment]
@rousseldenis if I may request a slice of your time

**Review by bealdav — APPROVED** [review]

**Review by ivs-cetmix — COMMENTED** [review]
LGTM

**Review by ivs-cetmix — APPROVED** [review]
LGTM

**Review by rousseldenis — APPROVED** [review]

**Pull request merged**
