### PR TITLE
[14.0][MIG] sale_rental

### PR DESCRIPTION
**Pull request by alexis-via**
Migration from v12 to v14.
No more need to add users to the packaging group (it doesn't bring-up form view on sale order line any more)=> I do the inherit of editable="bottom" of sale order lines in this module
View of rental group is now possible on product.template form view (like default_code and barcode fields)
I integrated the small change of https://github.com/OCA/sale-workflow/pull/1546
Requires PR https://github.com/OCA/sale-workflow/pull/1395

### CODE REVIEW

**Comment by rvalyi** [comment]
Hello @alexis-via , I merged #1395. Now about sale_rental itself, I have seen that a new OCA repo was created:
https://github.com/OCA/vertical-rental, I guess after the Twitter conversation about a possible web frontend for it.

Don't you know the person who created it? I also think it's a nice move to start packaging the rental vertical in its own repo as it can have a small ecosystem of its own and growing OCA/sale-workflow forever doesn't scale either.

So I guess your module should be moved in the new repo... I can help with the git rebase boiler plate of it, but Also I guess OCA/vertical-rental needs to be initialized with the OCA git files and branches. Anyone has some automation for this? cc @pedrobaeza @sbidoul

**Comment by pedrobaeza** [comment]
https://github.com/OCA/vertical-rental is prepared. I think it's interesting to move it to that repo indeed, as this one is very crowded. I also wonder several things:

- Does it worth to split the module into `rental` and `sale_rental`, having the first one with the basic objects if you want to do other operations than sales?
- We have the module https://github.com/OCA/calendar/tree/13.0/resource_booking, that allows to plan and reserve resources in general, and https://github.com/OCA/sale-workflow/pull/1523 (sale_resource_booking) for selling booking slots. Maybe there's some overlap, or they can be compatibilized.

**Comment by rousseldenis** [comment]
@alexis-via Do you plan to move this ?

**Review by Yvesldff — APPROVED** [review]

**Review by benbrich — APPROVED** [review]
Functional review on runbot and everything worked as expected.

**Comment by benbrich** [comment]
Hi guys, it would be great to see you [here](https://odoo-community.org/event/oca-days-2021-online-2021-10-28-2021-10-29-128/track/open-discussion-vertical-rental-12-40-126) today 12:40 CET for a discussion about the "future of sale_rental":

**Comment by dreispt** [comment]
Travis is Red

**Comment by marylla** [comment]
Last time the Travis build failed because the module sale_start_end_dates wasn't merged yet.
Since it is merged now, I restarted the build. Unfortunately, we now get an incompatibility error.

```
Failed to load registry
Failed to initialize database `openerp_test`.
Traceback (most recent call last):
  File "/home/travis/odoo-14.0/odoo/service/server.py", line 1199, in preload_registries
    registry = Registry.new(dbname, update_module=update_module)
  File "/home/travis/odoo-14.0/odoo/modules/registry.py", line 89, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/home/travis/odoo-14.0/odoo/modules/loading.py", line 426, in load_modules
    modules.button_install()
  File "<decorator-gen-71>", line 2, in button_install
  File "/home/travis/odoo-14.0/odoo/addons/base/models/ir_module.py", line 74, in check_and_log
    return method(self, *args, **kwargs)
  File "/home/travis/odoo-14.0/odoo/addons/base/models/ir_module.py", line 431, in button_install
    raise UserError(msg % (module.shortdesc, exclusion.exclusion_id.shortdesc))
odoo.exceptions.UserError: Modules "Sale Isolated Quotation" and "Sale Quotation Numeration" are incompatible.
Message not found: 'Modules loaded.'
```

@alexis-via @pedrobaeza   What do we do?

**Comment by pedrobaeza** [comment]
Please try rebasing your branch over latest origin one.

**Comment by alexis-via** [comment]
Travis is green !

**Pull request merged**
