### PR TITLE
[WIP][15.0][MIG] sale_automatic_workflow(fw-port, fix tests),sale_automatic_workflow_job(mig)

### PR DESCRIPTION
**Pull request by dreispt**
#2054 tests are failing, hopefully #2049 fixes that.

- [IMP] sale_automatic_workflow: add sale_automatic_workflow_job
- [FIX] sale_automatic_workflow: remove company contextmanager
- [FIX] sale_automatic_workflow: Fix tests multi-company issues
- [IMP] sale_automatic_workflow: move register_payment option from sale_automatic_workflow_payment_mode
- [IMP] sale_automatic_workflow: Send order confirmation mail option in Sale Workflow Process TT30759
- [FIX] sale_automatic_workflow: correct field for an invoice residual amount
- [FIX] sale_automatic_workflow: work with 14.0
- [FIX] sale_automatic_workflow: fix pre-commit
- [FIX] Fix sale_automatic_workflow_payment_mode migration
- Add sale_automatic_workflow_job
- [UPD] Update sale_automatic_workflow_job.pot
- [UPD] README.rst
- [ADD] icon.png
- [IMP] related_job to origin document
- [UPD] Update sale_automatic_workflow_job.pot
- [UPD] README.rst
- sale_automatic_workflow_job 12.0.1.0.1
- [UPD] Update sale_automatic_workflow_job.pot
- [IMP] : black, isort, prettier
- [13.0][MIG] sale_automatic_workflow_job
- [14.0][MIG] sale_automatic_workflow_job: Migration to 14.0
- [UPD] Update sale_automatic_workflow_job.pot
- [UPD] README.rst
- [IMP] update dotfiles [ci skip]
- [ADD] Initial commit
- [MIG] sale_automatic_workflow_job: Migration into v15

### CODE REVIEW

**Comment by pedrobaeza** [comment]
The pull request mustn't contain merge commits, or the commit history will be a mess.

**Comment by dreispt** [comment]
@pedrobaeza Fixed!

**Comment by pedrobaeza** [comment]
It seems weird that there are migration commits involved in this.

**Comment by dreispt** [comment]
#2054 is a module migration
#2049 is a forward port of fixes merged after migration

This PR is to check if #2054 tests were fixed by #2049, before spending time doing more investigation.

**Comment by dreispt** [comment]
@pedrobaeza You have a point. I can try removing those commits.

**Comment by pedrobaeza** [comment]
What you prefer. If you have checked that everything is OK, go ahead as is.

**Pull request merged**
