### PR TITLE
[10.0] port sale_owner_stock_sourcing to 10.0

### PR DESCRIPTION
**Pull request by Cedric-Pigeon**
depends https://github.com/oca/stock-logistics-workflow/pull/329

### CODE REVIEW

**Comment by rafaelbn** [comment]
Hi @Cedric-Pigeon , https://github.com/OCA/stock-logistics-workflow/pull/329 is merged, please could you rebase this one in order to review? thanks!

**Comment by rafaelbn** [comment]
Needs rebase in order to be reviewed

**Comment by Cedric-Pigeon** [comment]
@rafaelbn A rebase is useless as  OCA/stock-logistics-workflow#329 is not on the same repo. I relaunched Travis. It should be enough.

**Comment by Cedric-Pigeon** [comment]
@rafaelbn Travis is green now

**Review by rafaelbn — APPROVED** [review]
Tested in runbot functionally  👍

**Review by lmignon — APPROVED** [review]
:+1:  Code review

**Comment by Cedric-Pigeon** [comment]
@rafaelbn I think this one can be merged.

**Review by carlos-domatix — APPROVED** [review]
Tested in runbot functionally :+1:

**Review by antoniocanovas — APPROVED** [review]
Tested in #ocacodesprint
Ok functionality

**Pull request merged**
