### PR TITLE
[16.0][IMP] sale_order_line_menu : improve Readme

### PR DESCRIPTION
**Pull request by TumbaoJu**
Improve Description and Usage
Add Context

### CODE REVIEW

**Comment by TumbaoJu** [comment]
@OCA/oca-consultants : Here is the example used for the Guidelines.

**Comment by TumbaoJu** [comment]
@sbidoul : I seem to have a problem with the images.  I did the drag & drop into the static/description folder in my forked repository and did the commit and PR.  But is does not work.  Any ideas?

**Comment by rousseldenis** [comment]
> @sbidoul : I seem to have a problem with the images. I did the drag & drop into the static/description folder in my forked repository and did the commit and PR. But is does not work. Any ideas?

@TumbaoJu It seems ok:

image

**Review by rousseldenis — APPROVED** [review]
LGTM.

Can you squash your commits ?

**Comment by vdewulf** [comment]
Hi @rousseldenis 

Thanks for your help, as usual!

Thanks to your request, I'll finally discover what it this "squash your commits" phase. I read about it here: 
https://github.com/OCA/maintainer-tools/wiki/Merge-commits-in-pull-requests
It explains how to do it with terminal interface (I suppose).

I am not sure @TumbaoJu is using a terminal. Is there a way to squash commits using the Graphical interface on Github?
I found this Github official doc:
https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/incorporating-changes-from-a-pull-request/about-pull-request-merges

I couldn't spend too much time here, so I'll let Julie follow up and indicate if she found the way to "squash her commits".
Curious to see the next steps!

**Comment by rousseldenis** [comment]
> Hi @rousseldenis
> 
> Thanks for your help, as usual!
> 
> Thanks to your request, I'll finally discover what it this "squash your commits" phase. I read about it here: https://github.com/OCA/maintainer-tools/wiki/Merge-commits-in-pull-requests It explains how to do it with terminal interface (I suppose).
> 
> I am not sure @TumbaoJu is using a terminal. Is there a way to squash commits using the Graphical interface on Github? I found this Github official doc: https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/incorporating-changes-from-a-pull-request/about-pull-request-merges
> 
> I couldn't spend too much time here, so I'll let Julie follow up and indicate if she found the way to "squash her commits". Curious to see the next steps!

Indeed, this is not available through Github web interface.

But, I've discovered Github desktop for Windows/Mac that offers that command in a graphical interface : https://github.com/apps/desktop

@TumbaoJu Maybe you can give a try following these instructions ? 

https://docs.github.com/en/desktop/managing-commits/squashing-commits-in-github-desktop

**Comment by pedrobaeza** [comment]
I think that using VSCode integration in GitHub may help for amending commits. Just type `.` when browsing code to enter VSCode.

**Comment by rousseldenis** [comment]
> I think that using VSCode integration in GitHub may help for amending commits. Just type `.` when browsing code to enter VSCode.



> I think that using VSCode integration in GitHub may help for amending commits. Just type `.` when browsing code to enter VSCode.

Ooooh yes, I forgot that.

**Comment by TumbaoJu** [comment]
@rousseldenis @pedrobaeza : Thank you both for your comments.
I did this contribution as an example to be able to explain how to contribute to modules documentation if you are a non-technical person.

In the instructions, we are using the web editor (VS Code) to commit, but I did'nt know how to create the PR and or squash the commits using the VS Code interface.

I will look into the documentation @vdewulf proposed and try to do it.

**Comment by TumbaoJu** [comment]
@rousseldenis @pedrobaeza : I have looked into it and don't know how to squash the commits even with the VS Code interface.
I would need help!

**Comment by pedrobaeza** [comment]
Right now is not possible. What I said is that when committing more changes, instead of creating a new commit, is to mark to amend previous commit, so everything sticks together since the beginning.

**Comment by gurneyalex** [comment]
Could we not use the squash and merge feature for this? Maybe we could have the ocabot perform this through a dedicated command ("ocabot squash merge patch" for instance) ?

**Comment by TumbaoJu** [comment]
> Could we not use the squash and merge feature for this? Maybe we could have the ocabot perform this through a dedicated command ("ocabot squash merge patch" for instance) ?

I like this proposition.  The idea is attract non-technical persons to contribute to module documentation so if we can ease the process for Read Me updates it could be great.

@sbidoul : FYI

**Review by florenciafrigieri2 — APPROVED** [review]
Changes in readme ok

**Review by etobella — COMMENTED** [review]
/ocabot merge patch

**Pull request merged**
