### PR TITLE
[16.0][ADD] partner_picking_note

### PR DESCRIPTION
**Pull request by EmilioPascual**
This module add two description fields in partner, one for internal use and other for customer use. 
When assign partner in sale order, the fields description are copied into the respective fields of the sales order.

https://www.loom.com/share/ffdec27ff32244cf902d26cacb26300a

@rafaelbn @Gelojr @Shide please review 😄

MT-4381 @moduon

### CODE REVIEW

**Review by Shide — APPROVED** [review]
Functional review 
https://www.loom.com/share/caa0fa58c0764865952adcbd8475b58a?sid=c8df2696-03e7-45b0-a347-674abcdb62d1

**Review by flotho — COMMENTED** [review]
Hi,
Thanks for this proposal.
It mostly looks like a duplicate of this module : https://github.com/OCA/sale-workflow/blob/16.0/sale_stock_picking_note/
Is there any chance to mutualize, maybe propose an improvement on the first one instead of duplicating fileds and code ?

Regards

**Review by Gelojr — APPROVED** [review]
LGTM Thanks @EmilioPascual 
https://www.loom.com/share/04281bb4c8c2431ca01dd08253ea55bf?sid=d3893e04-5a68-4c0e-bd67-b886ffadf295

**Comment by EmilioPascual** [comment]
> Hi, Thanks for this proposal. It mostly looks like a duplicate of this module : https://github.com/OCA/sale-workflow/blob/16.0/sale_stock_picking_note/ Is there any chance to mutualize, maybe propose an improvement on the first one instead of duplicating fileds and code ?
> 
> Regards

No duplicate code, this module depends on https://github.com/OCA/sale-workflow/blob/16.0/sale_stock_picking_note/

In sale_stock_picking_note you have to fill descriptions fields in the sales orders but in the module I propose you can fill descriptions fields for each customer and have them automatically added to the order.

Maybe you could merge the modules, but they work well separately.

**Comment by rafaelbn** [comment]
Hello @flotho ! 😄 

I think you didn't check the details!

As @EmilioPascual commented, that module you mention is a long term well known by me and has been deeply analysed by the team to full fit the requirements 👍🏼 

- [sale_stock_picking_note](https://github.com/OCA/sale-workflow/blob/16.0/sale_stock_picking_note/) Don't add fields in partners: https://github.com/OCA/sale-workflow/tree/16.0/sale_stock_picking_note/models
- **This module depends in that one!** https://github.com/OCA/sale-workflow/pull/2830/files#diff-d793eec7d52dc2d188a20f90af59e56709733811bd2787fb40e6d57e1fb114efR17

We thought that some clients don't want notes in partner to that why we dont merge all in one single module.

Thank you vert much @flotho for taking care! Really appreciated! ❤️ 

Best Regards!

**Review by rafaelbn — APPROVED** [review]
👍🏼 Tested in runboat!

**Review by yajo — CHANGES_REQUESTED** [review]
I agree with https://github.com/OCA/sale-workflow/pull/2830#pullrequestreview-1765811297. IMHO this should be just an improvement over `sale_stock_picking_note`. I don't see anything that requires a new module here.

**Comment by EmilioPascual** [comment]
Created new pr https://github.com/OCA/sale-workflow/pull/2841 to add behavior to [sale_stock_picking_note](https://github.com/OCA/sale-workflow/tree/16.0/sale_stock_picking_note) and don't create new module

**Comment by rafaelbn** [comment]
Please @chienandalu @victoralmau you both created and maintain [sale_stock_picking_note](https://github.com/OCA/sale-workflow/pull/2841/files#diff-5317653bcd51590c38c9e68acd24f75bf76c8d58fb080c4f514a44982497dca5), Do you agree to improve with https://github.com/OCA/sale-workflow/pull/2841 or you prefer to have this in a separate module?

Thanks in advance! 😄 ❤️

**Pull request closed without merging**
