### PR TITLE
[ADD] New module partner_invoice_delivery_address

### PR DESCRIPTION
**Pull request by manuelcalerosolis**
This module is to provide the functionality to get the filtered Invoice and Delivery Address for the selected Partner in Quotation/Sales Order.

### CODE REVIEW

**Comment by yostashiro** [comment]
@manuelcalerosolis Thanks for the PR. I'm not comfortable with adjusting the domain through an onchange method as the changes are not persistent. I'd suggest that domains be added in the view instead.

**Comment by manuelcalerosolis** [comment]
@yostashiro Ok I'm going to try to put the domain in view, thanks for your suggestion

**Comment by yostashiro** [comment]
@manuelcalerosolis Could you follow up on the lint check fail, please.  Otherwise, LGTM.

**Comment by manuelcalerosolis** [comment]
@yostashiro I don't understand Travis's errors very well, he points out errors that don't belong in my module, like this:

************* Module sales_team_security
sales_team_security/readme/CONTRIBUTORS.rst:1: [W7908(missing-newline-extrafiles), ]  Missing newline

**Comment by rousseldenis** [comment]
> @yostashiro I don't understand Travis's errors very well, he points out errors that don't belong in my module, like this:
> 
> ************* Module sales_team_security
> sales_team_security/readme/CONTRIBUTORS.rst:1: [W7908(missing-newline-extrafiles), ] Missing newline

@manuelcalerosolis This is the one that is really failing : https://travis-ci.org/github/OCA/sale-workflow/jobs/705323136#L305

**Comment by rousseldenis** [comment]
@manuelcalerosolis IMHO the module name should reflect functionnality. Something like sale_restrict_invoice_delivery

**Comment by manuelcalerosolis** [comment]
@rousseldenis Completely agree with you, I don't like the name either, I'm going to try to change it.

**Comment by rousseldenis** [comment]
@manuelcalerosolis sale_order_form_address_filter as module name ?

**Pull request closed without merging**
