### PR TITLE
[12.0][FIX] sale_fixed_discount -Wrong tax_amount displayed on reporting + wrong price_reduce value

### PR DESCRIPTION
**Pull request by mmarcot**
Hello,
This pull request aims to fix these issues on the branch **12.0**:
- sale_fixed_amount - Wrong tax_amount displayed on reporting #1424
- sale_fixed_discount: price_reduce in database is wrong #1411

The same PR for branch 13.0 is available here => #1440

### CODE REVIEW

**Review by LoisRForgeFlow — COMMENTED** [review]
Could you add a test case?

**Comment by MAG-Florian-Chevalier** [comment]
Hello,

I have just tested this fix on runbot and everything works fine.
I had an issue with the amount_tax which wasn't correct on portal with if I had some lines with fixed and other with percentage discount and this fix also corrects it.
I attach the screenshots of the sale order and its portal view for the test I've made on runbot.
Please note that the tax I've selected here is included in price.
image
Screenshot_20210914_095530

Regards,
Florian

**Review by MAG-Florian-Chevalier — APPROVED** [review]
Tests on runbot showed that this code works, override _amount_by_group seems a good idea to me so it will fix the price everywhere including on portal and reports.

**Review by flotho — APPROVED** [review]
code review OK
Functionnal test with @MAG-Florian-Chevalier  for fixed discount OK

**Comment by rafaelbn** [comment]
@mmarcot hello! Thank you! the point is to test and report the use case on runbot before this PR to reproduce the issue before and after. I couldn't reproduce the issue in runbot without this PR. That why I think @LoisRForgeFlow ask it.

Maybe the issue comes from taxes included in[price and in other case it works?

**Comment by eLBati** [comment]
new version, with super: https://github.com/OCA/sale-workflow/pull/3983

**Pull request closed without merging**
