### PR TITLE
[15.0][IMP] product_supplierinfo_for_customer_sale: Change acls to noupdate

### PR DESCRIPTION
**Pull request by CarlosRoca13**
cc @Tecnativa TT45675

ping @carlosdauden @sergio-teruel

### CODE REVIEW

**Review by carlosdauden — APPROVED** [review]

**Review by sergio-teruel — APPROVED** [review]

**Comment by carlosdauden** [comment]
It is ready to merge?

**Comment by pedrobaeza** [comment]
I don't think this should be done this way. If you need other ACLs, just add them. They are additive, so why do you need to do it this way?

**Comment by carlosdauden** [comment]
Everyone can use this option as they wish, but what is the problem with this particular commit?

**Comment by pedrobaeza** [comment]
Introducing heterogeneity and complexity if you change such ACLs in the module development cycle, needing to add migration scripts, which will also break your customizations. That may seems very improbable, but that things have happened in the past, requiring a lot of debugging time.

**Review by pedrobaeza — CHANGES_REQUESTED** [review]
See comments in the task

**Comment by CarlosRoca13** [comment]
@pedrobaeza changes done

**Review by pedrobaeza — APPROVED** [review]
Thanks.

/ocabot merge minor

**Pull request merged**
