### PR TITLE
[14.0][WIP] sale_product_advance_payment

### PR DESCRIPTION
**Pull request by ilyasProgrammer**

### CODE REVIEW

**Comment by youring** [comment]
Hello, @ilyasProgrammer. Thanks for the new module. But can kindly note the difference from the existing sale_advance_payment module? Anything special with product lines?

**Comment by francesco-ooops** [comment]
hi @youring, this PR is both a WIP and a RFC for everyone in OCA, it has the following goals: 

- planning and invoicing down payments (DP) on a SO, eg: 
_for this SO, user will request customer 1 down payment next month, and another one in 2 months_

- allowing user to link DP amounts to sale order lines (SOL), eg: 
_user requests customer a DP of 1000: 300 as DP for sale order line 1, and 700 as DP for sale order line 2_

- keeping track of amounts down payed and remaining amount when invoicing products, eg:
_user invoiced customer a DP of 300 for each unit in sale order line 1, so when invoicing a product from that SOL, 300 must be deducted from invoice_

—

Base use case is: 
create sale order for product 1, price 1000 qty 5, total 5000
receive down payment for 1500
deliver and invoice products one by one

The agreement with the customer is that every invoice must have an amount of the DP deducted proportional to the products invoiced.

Currently, odoo only allows to attribute a DP on the whole sale order, and everytime a down payment is deducted from a regular invoice, the whole DP amount is deducted. We have tried to achieve the goal of deducting a part of a down payment from each regular invoice through standard odoo but never reached our goal, you can check and comment a use case document [here](https://docs.google.com/document/d/1NtH7kgzUdW6_ztJ-bcEdxQNAKMAoEpR692AZbXKss2k/edit?usp=sharing)

First case described is particularly dangerous if process of payment is automatized as down payment is returned to customer in case first regular invoice has an amount lower than down payment.

Any feedback you may have about this module is very appreciated!

—

sale_advance_payment is working on receiving payments as advances and deducting those from invoices, but doesn't allow tracking which amount is related to which product line, furthermore advance payment is received without an invoice to support it

**Comment by francesco-ooops** [comment]
cc @elvise

**Comment by francesco-ooops** [comment]
@pedrobaeza @OCA/crm-sales-marketing-maintainers any opinion/experience with this issue? thank you!

**Comment by elvise** [comment]
> hi @youring, this PR is both a WIP and a RFC for everyone in OCA, it has the following goals: 
> 
> 
> 
> - planning and invoicing down payments (DP) on a SO, eg: 
> 
> _for this SO, user will request customer 1 down payment next month, and another one in 2 months_
> 
> 
> 
> - allowing user to link DP amounts to sale order lines (SOL), eg: 
> 
> _user requests customer a DP of 1000: 300 as DP for sale order line 1, and 700 as DP for sale order line 2_
> 
> 
> 
> - keeping track of amounts down payed and remaining amount when invoicing products, eg:
> 
> _user invoiced customer a DP of 300 for each unit in sale order line 1, so when invoicing a product from that SOL, 300 must be deducted from invoice_
> 
> 
> 
> —
> 
> 
> 
> Base use case is: 
> 
> create sale order for product 1, price 1000 qty 5, total 5000
> 
> receive down payment for 1500
> 
> deliver and invoice products one by one
> 
> 
> 
> The agreement with the customer is that every invoice must have an amount of the DP deducted proportional to the products invoiced.
> 
> 
> 
> Currently, odoo only allows to attribute a DP on the whole sale order, and everytime a down payment is deducted from a regular invoice, the whole DP amount is deducted. We have tried to achieve the goal of deducting a part of a down payment from each regular invoice through standard odoo but never reached our goal, you can check and comment a use case document [here](https://docs.google.com/document/d/1NtH7kgzUdW6_ztJ-bcEdxQNAKMAoEpR692AZbXKss2k/edit?usp=sharing)
> 
> 
> 
> First case described is particularly dangerous if process of payment is automatized as down payment is returned to customer in case first regular invoice has an amount lower than down payment.
> 
> 
> 
> Any feedback you may have about this module is very appreciated!
> 
> 
> 
> —
> 
> 
> 
> sale_advance_payment is working on receiving payments as advances and deducting those from invoices, but doesn't allow tracking which amount is related to which product line, furthermore advance payment is received without an invoice to support it

Hi @pedrobaeza your help is greatly appreciated here 🙂

**Comment by francesco-ooops** [comment]
Ok, at current stage module is far from complete, but it allows user to:
- assign a down payment amount to a specific SOL
- create DP invoice with reference to products for which down payment is received
- create regular invoices deducting DP amount for delivered qty

see [video](https://recordit.co/JDsc6UYwem) for complete flow

We'd like to receive a feedback on what's done so far, @pedrobaeza , @OCA/crm-sales-marketing-maintainers can you take a look and tell us if we should proceed differently? Thanks a lot!

**Pull request closed without merging**
