### PR TITLE
fix: no route or source is always consistent

### PR DESCRIPTION
**Pull request by lepistone**

### CODE REVIEW

**Comment by lepistone** [comment]
This makes the whole branch green (we didn't notice because of https://github.com/OCA/maintainer-quality-tools/issues/148).

please fast-track, thanks!

**Comment by gurneyalex** [comment]
:+1:

**Comment by yvaucher** [comment]
:+1:

**Comment by rdeheele** [comment]
:+1:

**Comment by lepistone** [comment]
Thanks a lot for the reviews

**Pull request merged**
