### PR TITLE
[10.0][FIX][sale_rental] Error converting units during rented products' delivery

### PR DESCRIPTION
**Pull request by mileo**
- The _get_delivered_qty function is being overridden to avoid comparing the 'Rented Product' and 'Product' Units

### CODE REVIEW

**Comment by StefanRijnhart** [comment]
Can you add a test that reproduces the bug and shows that it is fixed?

**Comment by rafaelbn** [comment]
Please @mileo could you attend https://github.com/OCA/sale-workflow/pull/632#issuecomment-381913214 from @StefanRijnhart ? Thanks

**Comment by mileo** [comment]
Hi, we will take a look. 

CC: @sadamo Can you please work to aprove this PR, it's related to you WIP.

**Comment by rousseldenis** [comment]
@mileo Do you plan to finish this ?

**Comment by rousseldenis** [comment]
Closing this as very old and no answer from author. Please feel free to reopen it if needed.

**Pull request closed without merging**
