### PR TITLE
[14.0][ADD] new module sale_blanket_order_revision

### PR DESCRIPTION
**Pull request by PicchiSeba**
Adds the revision feature of `sale_order_revision` to `sale.blanket.order`s

### CODE REVIEW

**Comment by PicchiSeba** [comment]
Rebased on top of https://github.com/OCA/sale-workflow/pull/2927

**Review by francesco-ooops — APPROVED** [review]
Funzionale ok!

**Review by renda-dev — APPROVED** [review]
Code review, LGTM

**Comment by francesco-ooops** [comment]
@pedrobaeza a merge based on existing reviews, please? 

Thanks!

**Pull request merged**
