### PR TITLE
[13.0][MIG] sale_merge_draft_invoice

### PR DESCRIPTION
**Pull request by willer-mo**
Migration to 13.0

* [ ] Depends on https://github.com/OCA/sale-workflow/pull/1255

### CODE REVIEW

**Review by danimv5 — APPROVED** [review]
Functional review in local! LGTM

**Comment by brendapaniagua** [comment]
Functional review! LGTM!

**Comment by HaraldPanten** [comment]
@brendapaniagua please, remember to approve accordingly if you're reviewing a PR. THX!

Captura de pantalla 2021-03-31 a las 17 03 55

**Comment by pedrobaeza** [comment]
And both Travis and runbot are red, so it can't be a good functional review.

**Pull request closed without merging**
