### PR TITLE
add module sale_order_line_date

### PR DESCRIPTION
**Pull request by open-net-sarl**
Hello,

Instead of doing sale_order_line_date from scratch, we tought of helping you with migration, given that this module does what we wanted.

If the validation is not passed we won't do more. You can retake what we did if you want.
NB: i did not checked the tests. Python and XML are okay, and apparently the traductions too.

Have a nice day.

### CODE REVIEW

**Comment by AaronHForgeFlow** [comment]
Thanks for this migration. Please include the commit history of the module in your Pull Request. You have a guide here: https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-12.0

Regards.

**Comment by open-net-sarl** [comment]
@aheficent 
Only one commit was done,
Sorry that it is not named as wished.

Or maybe i don't get what is asked.
We tried many times to help you with the migrations but we were refused against bad test that we just took from you and that were not even opened.

We are okay for doing the technical and functional part, but sadly, we don't have much time to waste when we get refused too many times. If it wasn't that hard to give you the codes, we would have helped you a lot more.

If you can tell me exactly what change you want i still can process it in my free time.
Otherwise, i would rater let you take what i made.

Best regards

**Comment by rousseldenis** [comment]
@open-net-sarl Thank you trying contributing.

For the point @aheficent pointed you, it's about commit history that must be preserved from one main branch to another - to keep changes history, contributors commits,...  It's well explained in the link.



> We tried many times to help you with the migrations but we were refused against bad test that we just took from you and that were not even opened.

Could you point me some open PR's you made to see if I can help merging?


> If it wasn't that hard to give you the codes, we would have helped you a lot more.

I know it's maybe frustrating to see some work not being merged, but that's the way to have better code - confrontation of opinions. Next time, maybe someone else would have done your module migrated in the next version.

**Comment by rafaelbn** [comment]
I'm closing this PR in favor to https://github.com/OCA/sale-workflow/pull/875

**Pull request closed without merging**
