### PR TITLE
[11.0][MIG] sale_stock_picking_blocking

### PR DESCRIPTION
**Pull request by MiquelRForgeFlow**
Standard migration.

### CODE REVIEW

**Comment by MiquelRForgeFlow** [comment]
@lreficent It's green :green_apple:

**Review by gurneyalex — APPROVED** [review]

**Review by LoisRForgeFlow — APPROVED** [review]
Functinal and technical review :+1:

**Comment by pedrobaeza** [comment]
@jbeficent please remember to mark the check on the line of the migration issue and add the module to N+1 migration issue list when you merge a migration PR.

**Comment by pedrobaeza** [comment]
(I have already done it for this one)

**Comment by pedrobaeza** [comment]
This modules is causing an error in Travis:

https://travis-ci.org/OCA/sale-workflow/jobs/457433009#L2102

Can you please check it?

**Comment by MiquelRForgeFlow** [comment]
How is it possible? The CI was green when we merged this PR.

**Comment by pedrobaeza** [comment]
It was a new check introduced by Odoo. The CI was green, but this module shouldn't work as is due to the problem stated.

**Comment by MiquelRForgeFlow** [comment]
Could you put the link to the new check added by Odoo?

**Comment by pedrobaeza** [comment]
No, sorry, I don't have it, but I have noticed this in my development flow.

**Pull request merged**
