### PR TITLE
[17.0][MIG] sale_stock_picking_note

### PR DESCRIPTION
**Pull request by Deriman-Alonso**
Standart migration.

### CODE REVIEW

**Comment by dalonsod** [comment]
Code and functional review :+1: 

Please clean commit history according https://github.com/OCA/maintainer-tools/wiki/Merge-commits-in-pull-requests#mergesquash-the-commits-generated-by-bots-or-weblate

**Review by Jaimermaccione — APPROVED** [review]
LGTM! Functional review on runboat.

**Comment by Deriman-Alonso** [comment]
@dalonsod Hi, done, Thanks for the review 👍.

**Comment by dalonsod** [comment]
Thank you for the contribution @Deriman-Alonso .

I still see commits that could be squashed, like

imagen

or

imagen

And, at last, it seems you've accidentally included an addon that shouldn't belong to this PR (`sales_team_security`):

imagen

Could you check?

**Comment by Deriman-Alonso** [comment]
@dalonsod I might have messed up the commits,my apologies, Ill re-do it.

**Comment by Deriman-Alonso** [comment]
Please refer to the new [PR](https://github.com/OCA/sale-workflow/pull/3124) .

**Pull request closed without merging**
