### PR TITLE
[16.0][MIG] sale_product_category_menu

### PR DESCRIPTION
**Pull request by aiendry-aktivsoftware**

### CODE REVIEW

**Review by hugo-cordoba — APPROVED** [review]

**Comment by hugo-cordoba** [comment]
LGTM! (Code Review)

**Review by enriquemartin — APPROVED** [review]

**Review by aliciagaarzo — APPROVED** [review]

**Comment by hugo-cordoba** [comment]
Hi @pedrobaeza, could you take a look?

Thankss! Regardss!

**Pull request merged**
