### PR TITLE
[14.0][FIX] sale_order_lot_generator: AttributeError: 'stock.move.line' object has no attribute 'restrict_lot_id'

### PR DESCRIPTION
**Pull request by newtratip**
Selection_199

### CODE REVIEW

**Comment by kittiu** [comment]
In v12, there was no field as `restrict_lot_id` https://github.com/OCA/sale-workflow/blob/12.0/sale_order_lot_generator/tests/test_sale_order_lot_generator.py#L53

I just present on the migration to v14, https://github.com/OCA/sale-workflow/pull/1363/files#diff-43299f263c3599040cc383fd106e9c475084e15badbfa825c8b21acfdccfb0e1R52

@florian-dacosta do you happen to know this?

**Comment by florian-dacosta** [comment]
@kittiu 
It seems it changed recently in v12 actually : https://github.com/OCA/sale-workflow/pull/1458/files#diff-43299f263c3599040cc383fd106e9c475084e15badbfa825c8b21acfdccfb0e1R53
So at migration time, the `restrict_lot_id` field was present.
I guess this commit should be ported to v14 (maybe the whole commit though)
Also, the CI is still red, linked to : https://github.com/OCA/stock-logistics-workflow/pull/800

**Review by LoisRForgeFlow — APPROVED** [review]
LGTM

**Review by MateuGForgeFlow — APPROVED** [review]

**Review by mileo — APPROVED** [review]

**Pull request merged**
