### PR TITLE
[12.0] [IMP] sale_order_general_discount: Add tracking to sale_discount on partners

### PR DESCRIPTION
**Pull request by CarlosRoca13**
cc @Tecnativa TT28073

please @sergio-teruel @carlosdauden review this

### CODE REVIEW

**Review by rousseldenis — APPROVED** [review]

**Review by marcelsavegnago — APPROVED** [review]

**Comment by sergio-teruel** [comment]
sale_order_lot_selection and sale_order_lot_generation are failing.

**Comment by pedrobaeza** [comment]
Yes, tracked in #1446

**Comment by pedrobaeza** [comment]
Please fw-port it to v13

**Pull request merged**
