### PR TITLE
[12.0][IMP] sales_team_security: Adjust team according salesman in partners

### PR DESCRIPTION
**Pull request by pedrobaeza**
@Tecnativa TT27985

### CODE REVIEW

**Review by bodedra — APPROVED** [review]
LG :+1:

**Review by victoralmau — APPROVED** [review]

**Review by atchuthan — APPROVED** [review]

**Review by HaraldPanten — APPROVED** [review]
LGTM

**Comment by pedrobaeza** [comment]
@sbidoul ocabot seems stuck

**Review by chienandalu — APPROVED** [review]

**Comment by pedrobaeza** [comment]
Cherry-picked for v13 in 5a33b3b5d4b9ef38da4aa429d69cdebd6f7486f7

**Pull request merged**
