### PR TITLE
[13.0][MIG] sale_force_invoiced

### PR DESCRIPTION
**Pull request by MiquelRForgeFlow**
Standard migration.

### CODE REVIEW

**Review by LoisRForgeFlow — APPROVED** [review]
Works as expected. :+1:

**Review by AaronHForgeFlow — APPROVED** [review]
Code review LGTM :+1:

**Review by AdriaGForgeFlow — APPROVED** [review]
Code review :+1:

**Review by HaraldPanten — APPROVED** [review]
Functional review OK 👍

**Review by JordiBForgeFlow — APPROVED** [review]

**Comment by pedrobaeza** [comment]
There has been a problem with merge bot, but it's fixed now, so you can relaunch.

**Comment by HaraldPanten** [comment]
Hi @JordiBForgeFlow can you relaunch, please?

THX!

**Pull request merged**
