### PR TITLE
 [11.0][MIG] sale_stock_picking_blocking_proc_group_by_line

### PR DESCRIPTION
**Pull request by MiquelRForgeFlow**
Standard migration.

Depends on:
- [x] https://github.com/OCA/sale-workflow/pull/673

### CODE REVIEW

**Comment by rafaelbn** [comment]
Please @mreficent rebase thanks!

**Comment by MiquelRForgeFlow** [comment]
@rafaelbn rebased!

**Comment by rousseldenis** [comment]
@MiquelRForgeFlow Is this still applicable ?

**Comment by MiquelRForgeFlow** [comment]
@rousseldenis yes, AFAIK

**Review by rousseldenis — APPROVED** [review]

**Pull request merged**
