### PR TITLE
7.0 product procurement type

### PR DESCRIPTION
**Pull request by lepistone**
migrated from

https://code.launchpad.net/~camptocamp/sale-wkfl/product_procurement_type/+merge/222111

### CODE REVIEW

**Comment by gurneyalex** [comment]
not sure we want this in OCA. More a customer specific addon IMO. Speak up if you want this included. :-1:

**Comment by rdeheele** [comment]
I'm not convinced myself, it's a little on the border between specific and community...it isn't worth the candle : poor added value versus migration efforts...

**Comment by eLBati** [comment]
In case, there still are some open remarks from https://code.launchpad.net/~camptocamp/sale-wkfl/product_procurement_type/+merge/222111 se my diff comments

**Comment by lepistone** [comment]
@rdeheele maybe you could merge that in come public camptocamp repository and close this PR? Thanks!

**Comment by lepistone** [comment]
Ok, I'm closing this one. Thank you

**Pull request closed without merging**
