### PR TITLE
Remove non ported version of sale_quotation_number

### PR DESCRIPTION
**Pull request by yvaucher**
In https://github.com/OCA/sale-workflow/pull/57 `__unported__` folder was not cleaned

This repairs it

(@franksl @eLBati can you review this?)

### CODE REVIEW

**Comment by yvaucher** [comment]
BTW POT file was missing in #57

**Comment by pedrobaeza** [comment]
:+1:

**Comment by jgrandguillaume** [comment]
:+1:

**Comment by eLBati** [comment]
:+1: thanks

**Pull request merged**
