### PR TITLE
[16.0][MIG] sale_order_price_recalculation

### PR DESCRIPTION
**Pull request by andrel-exo**

### CODE REVIEW

**Comment by rousseldenis** [comment]
@arleite Thanks for this. Could you check tests  ?

**Comment by rousseldenis** [comment]
@arleite

**Comment by andrel-exo** [comment]
Unfortunately, I don't have time to carry out the tests, so if anyone would like to take up the matter, I'd appreciate it

**Comment by arleite** [comment]
Unfortunately, I don't have time to carry out the tests, so if anyone would like to take up the matter, I'd appreciate it.

**Comment by CRogos** [comment]
superseded by #2778

**Pull request closed without merging**
