### PR TITLE
[14.0][ADD] sale_cancel_confirm

### PR DESCRIPTION
**Pull request by kittiu**
Depends on,
- [x] base_cancel_confirm https://github.com/OCA/server-ux/pull/297

This module extend `base_cancel_confirm` to make cancel confirmation with cancel reason (none / optional / requried).

Selection_044

image

**Note:** We use `sale_cancel_reason` before, but we have we have requirement to make cancel confirm/reason for many documents (almost 10 kind of documents). Rather than to make xxx_cancel_reason one by one, this way, make it very easy to achieve that.

TODO:

- [ ] Unit test

### CODE REVIEW

**Review by hailangvn — APPROVED** [review]
Code review: LGTM

**Comment by rousseldenis** [comment]
@kittiu Could you rebase ?

**Comment by kittiu** [comment]
> @kittiu Could you rebase ?

Done rebased

**Review by atchuthan — APPROVED** [review]
Travis error seems to be related to another module

```
2021-06-28 09:32:55,333 6627 INFO openerp_test odoo.addons.sale_product_seasonality.tests.test_sale_order: Starting TestSaleOrderCase.test_allowed_products ...
2021-06-28 09:32:55,580 6627 INFO openerp_test odoo.addons.sale_product_seasonality.tests.test_sale_order: ======================================================================
2021-06-28 09:32:55,580 6627 ERROR openerp_test odoo.addons.sale_product_seasonality.tests.test_sale_order: FAIL: TestSaleOrderCase.test_allowed_products
Traceback (most recent call last):
File "/home/travis/build/OCA/sale-workflow/setup/sale_product_seasonality/odoo/addons/sale_product_seasonality/tests/test_sale_order.py", line 129, in test_allowed_products
self.assertEqual(form.season_allowed_product_ids._get_ids(), self.prod2.ids)
AssertionError: Lists differ: [] != [12]
Second list contains 1 additional elements.
First extra element 0:
12
- []
+ [12]
```

**Comment by rousseldenis** [comment]
@kittiu @newtratip Do you plan to add an option to enable this behaviour ?

**Comment by kittiu** [comment]
@rousseldenis ok, I see the problem. I will look back to base_cancel_confirm and also this.

**Comment by kittiu** [comment]
@rousseldenis I enhance on base_cancel_confirm to allow disable this feature. Can you please review/approve?
Next I will disable by default in sale_cancel_confirm.
https://github.com/OCA/server-ux/pull/497

**Comment by kittiu** [comment]
Also this one sale_cancel_confirm,
https://github.com/OCA/sale-workflow/pull/2022

**Pull request merged**
