### PR TITLE
[14.0][MIG] sale_start_end_dates

### PR DESCRIPTION
**Pull request by alexis-via**

### CODE REVIEW

**Comment by lfreeke** [comment]
Thank you for migrating this module. 

I do have a question, is it correct when setting a default start and end date it does't show on the sales order lines?

**Comment by alexis-via** [comment]
@lfreeke When setting a default start and end date on the order AND your product has "Must have start/end dates", then you will have the start/end date on the lines. I just tested it again on v14 and it works as expected.

**Comment by lfreeke** [comment]
> @lfreeke When setting a default start and end date on the order AND your product has "Must have start/end dates", then you will have the start/end date on the lines. I just tested it again on v14 and it works as expected.

@alexis-via Got it. Thanks. 
LGTM :+1:

**Review by lfreeke — APPROVED** [review]
Functional test :+1:

**Review by rvalyi — APPROVED** [review]

**Pull request merged**
