### PR TITLE
[IMP] sale_order_line_sequence: dont take notes into cosideration whe…

### PR DESCRIPTION
**Pull request by JuanyDForgeflow**
Old behavior: When sequencing it also counts note lines as part of the sequence

Current behavior: Now it doesn't count notes as part of the sequence

### CODE REVIEW

**Review by AaronHForgeFlow — CHANGES_REQUESTED** [review]
seems the re-arrange does not work:

image

**Review by AaronHForgeFlow — CHANGES_REQUESTED** [review]
seems the re-arrange does not work:

image

**Review by AaronHForgeFlow — CHANGES_REQUESTED** [review]
seems the re-arrange does not work:

image

**Review by AaronHForgeFlow — CHANGES_REQUESTED** [review]
seems the re-arrange does not work:

image

**Comment by JuanyDForgeflow** [comment]
@AaronHForgeFlow please try again

**Comment by AaronHForgeFlow** [comment]
@JuanyDForgeflow , Rearrange works now. However, I f create several sections and I save the sales order all the sections goes to the bottom. I have to edit again and move the sections in order to put them back to where they were. I wonder if adding a sequence to sections is needed.

**Comment by JuanyDForgeflow** [comment]
@AaronHForgeFlow it's fixed now

**Review by AaronHForgeFlow — APPROVED** [review]
Functional tests

**Comment by AaronHForgeFlow** [comment]
This can be closed, refactor on this module is done on #2636

**Review by AaronHForgeFlow — CHANGES_REQUESTED** [review]
Refactor done, this is not applicable

**Pull request closed without merging**
