### PR TITLE
[FIX] sale_automatic_workflow: Fix tests multi-company issues

### PR DESCRIPTION
**Pull request by joao-p-marques**
Change to the correct company in environment to pick up the correct company dependent fields

@Tecnativa
TT28906

ping @pedrobaeza @victoralmau

### CODE REVIEW

**Review by pedrobaeza — APPROVED** [review]

**Review by victoralmau — APPROVED** [review]

**Comment by pedrobaeza** [comment]
@joao-p-marques please check pre-commit, and please install it locally for avoiding this kind of things.

**Comment by joao-p-marques** [comment]
@pedrobaeza fixed. It's weird because I have it installed locally, and it ran for my commit (only for the files I changed). But the issues in travis were related to another module, which should never happen in the first place :man_shrugging:

**Comment by pedrobaeza** [comment]
Indeed very weird...

/ocabot merge patch

**Pull request merged**
