### PR TITLE
[MIG] : Migrated sale_validity to v13.

### PR DESCRIPTION
**Pull request by sudhir-erpharbor**

### CODE REVIEW

**Comment by rousseldenis** [comment]
@sudhir-erpharbor Thanks for your contribution. Can you check flake8 errors ?

**Comment by sudhir-erpharbor** [comment]
@rousseldenis 

> @sudhir-erpharbor Thanks for your contribution. Can you check flake8 errors ?

Updated the code and fixed the flack8 errors.

**Comment by rousseldenis** [comment]
Relaunched runbot build due to maintenance yesterday

**Comment by gurneyalex** [comment]
https://github.com/sudhir-erpharbor/sale-workflow/pull/1 should fix the runbot build (cc @rousseldenis )

**Comment by sudhir-erpharbor** [comment]
All checks have been passed.
Thanks @gurneyalex for fixing it.

**Review by gurneyalex — APPROVED** [review]

**Review by HaraldPanten — APPROVED** [review]
Functional review 👍

**Review by rousseldenis — APPROVED** [review]

**Pull request merged**
