### PR TITLE
[9.0] [FIX] Wrong Import in test cases for sale_validity

### PR DESCRIPTION
**Pull request by serpentcs-dev1**
Wrong Import in test cases for sale_validity for v9.0

### CODE REVIEW

**Review by LoisRForgeFlow — APPROVED** [review]
Thank you @darshan-serpent

**Review by yajo — APPROVED** [review]

**Review by pedrobaeza — APPROVED** [review]

**Comment by yajo** [comment]
Hey! runbot was ❌ !

**Comment by yajo** [comment]
Oh well, I don't think it was because of this...

**Comment by pedrobaeza** [comment]
Well, it's not this PR fail!

**Comment by LoisRForgeFlow** [comment]
@Yajo the error has been fixed in upstream v8 but still not in 9 I guess (https://github.com/odoo/odoo/issues/17312)

**Pull request merged**
