### PR TITLE
[9.0][IMP][sale_automatic_workflow_payment_mode] use date invoice as date of payment

### PR DESCRIPTION
**Pull request by vrenaville**
In some case automatic payment is activated after a few month.
If you have invoice in currency you can have a different rate, between the invoice date and the payment date
so my proposition is to take the date_invoice as payment date instead of current date

### CODE REVIEW

**Review by simahawk — APPROVED** [review]

**Comment by pedrobaeza** [comment]
@sergio-teruel can you check this?

**Comment by leemannd** [comment]
@sergio-teruel @pedrobaeza Do you still want to check it?

**Review by leemannd — APPROVED** [review]

**Comment by pedrobaeza** [comment]
I would say that you don't want to register the payment in the past...

**Comment by rafaelbn** [comment]
Hi @simahawk @leemannd I think @guewen could be the one who make the las review o just merge it

**Comment by rafaelbn** [comment]
Hi @vrenaville , Why are you  modifying sale_rental in this PR? This PR applies yo  sale_automatic_workflow_payment_mode only, isn't it?

**Comment by rafaelbn** [comment]
Hi @vrenaville do you want this PR or can we close it?

**Comment by leemannd** [comment]
@rafaelbn We are using it in production with success since the creation of this PR. As we integrate it and are able to retrieve it. I think that it is not an issue for us and this particular client.

Sidenote: After searching a bit, the first sentence is telling the base use `In some case automatic payment is activated after a few month.` We had issues with this module and had to deactivate it. This development aims to be more robust in such cases.

So in the end that's your call. If you want to merge it or not.

cc @simahawk

**Comment by simahawk** [comment]
> Hi @vrenaville , Why are you modifying sale_rental in this PR? This PR applies yo sale_automatic_workflow_payment_mode only, isn't it?

this change could be discarded indeed but it won't hurt (explicit catch of generic exception).

**Pull request merged**
