### PR TITLE
[IMP] sale_order_type_quotation_number: store recompute_quotation_seq field

### PR DESCRIPTION
**Pull request by angelgarciadelachica**
In this IMP the `recompute_quotation_seq` field is stored so that it is only recalculated based on the dependent fields

### CODE REVIEW

**Comment by angelgarciadelachica** [comment]
@ValentinVinagre @manuelregidor @HaraldPanten

**Comment by angelgarciadelachica** [comment]
@manuelregidor Can you check this IMP?
THX!

**Review by manuelregidor — APPROVED** [review]
LGTM

**Review by ValentinVinagre — APPROVED** [review]
LGTM 👍🏻

**Review by HaraldPanten — APPROVED** [review]

**Pull request merged**
