### PR TITLE
[15.0][MIG] sale_substate

### PR DESCRIPTION
**Pull request by alexeirivera87**
Hello 

migration to v15

regards

### CODE REVIEW

**Comment by alexeirivera87** [comment]
Hello @sbidoul 

Could you give me some info about how to pass the tests in this PR. I think the issue is related to a recent change in setuptools-odoo for v15?

**Comment by sbidoul** [comment]
I suspect base_substate is not merged. Is it ?

**Comment by alexeirivera87** [comment]
Thanks @sbidoul 

No, not yet. I created a PR  https://github.com/OCA/server-ux/pull/429

**Comment by kittiu** [comment]
Tested locally with https://github.com/OCA/server-ux/pull/429

**Review by kittiu — APPROVED** [review]

**Comment by rousseldenis** [comment]
@alexeirivera87 Could you rebase ?

**Comment by alexeirivera87** [comment]
@rousseldenis 


Sorry for the delay. It's done!

regards

**Review by hildickethan — APPROVED** [review]

**Comment by hitrosol** [comment]
Can't test in runboat.

{"detail":"Not Found"}

**Pull request merged**
