### PR TITLE
[12.0][IMP] add group to create/edit customerinfo

### PR DESCRIPTION
**Pull request by sergiocorato**

### CODE REVIEW

**Review by marcelsavegnago — APPROVED** [review]

**Comment by sergiocorato** [comment]
I miss something on Travis tests: the 2 passed have no trace of `product_supplierinfo_for_customer` module, so it isn't tested.
The 4 failed seems to preinstall correctly the module, but at the end seems to not have been installed.

**Comment by rousseldenis** [comment]
> I miss something on Travis tests: the 2 passed have no trace of `product_supplierinfo_for_customer` module, so it isn't tested.
> The 4 failed seems to preinstall correctly the module, but at the end seems to not have been installed.

Do you have the problem locally if you reproduce install like in travis ?

**Comment by sergiocorato** [comment]
My mistake, sorry.

**Review by HaraldPanten — APPROVED** [review]

**Review by rousseldenis — APPROVED** [review]

**Pull request merged**
