### PR TITLE
[MIG][15.0] sale_order_product_recommendation_secondary_unit: Migration to v15

### PR DESCRIPTION
**Pull request by sergio-teruel**
cc @Tecnativa TT36528

ping @chienandalu @CarlosRoca13

### CODE REVIEW

**Comment by sergio-teruel** [comment]
Ready for review

**Review by CarlosRoca13 — APPROVED** [review]

**Comment by sergio-teruel** [comment]
ping @chienandalu

**Comment by sergio-teruel** [comment]
@chienandalu Can you review? Thanks

**Review by pedrobaeza — APPROVED** [review]
/ocabot migration sale_order_product_recommendation_secondary_unit
/ocabot merge nobump

**Pull request merged**
