### PR TITLE
[15.0][MIG] sale_validity_auto_cancel: Migration to 15.0

### PR DESCRIPTION
**Pull request by dc-oerp**
Migrate sale_validity_auto_cancel module from V13 to V15

### CODE REVIEW

**Comment by dc-oerp** [comment]
Hi @rousseldenis 

Could you please take a look at this pull request?
I think the failed checks are not coming from this module.

Let me know if there is anything that needs to be fixed.

Thank you

**Comment by rousseldenis** [comment]
@dc-oerp Could you please follow : https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-15.0#technical-method-to-migrate-a-module-from-140-to-150-branch ?

As commits history is not respected. Thanks

**Comment by rousseldenis** [comment]
@dc-oerp Do you plan to finish this ?

**Comment by dc-oerp** [comment]
> @dc-oerp Do you plan to finish this ?

I will find time to finish this
Thank you

**Comment by rousseldenis** [comment]
@dc-oerp @JordiMForgeFlow Could you sync in order to keep just one PR ? Thanks

**Comment by dc-oerp** [comment]
@rousseldenis 

OK, I will go ahead and close this since it is already done in another commit

Thank you

**Pull request closed without merging**
