### PR TITLE
[14.0][MIG] sale_stock_line_sequence

### PR DESCRIPTION
**Pull request by OriolMForgeFlow**
Standard migration
Taking into account the refactor done in [!2603](https://github.com/OCA/sale-workflow/pull/2603)

### CODE REVIEW

**Review by AaronHForgeFlow — COMMENTED** [review]
Edit: nevermind, is the refactor. Can't do functional test in runboat

**Review by AaronHForgeFlow — COMMENTED** [review]
Code review LG

**Comment by rousseldenis** [comment]
@OriolMForgeFlow Thanks for this. FYI, you can embed your dependency PR here in order to get tests running and runboat for functional testing.

https://github.com/OCA/maintainer-tools/wiki/Use-temporary-reference%28s%29-to-another-pull-request%28s%29

**Comment by rousseldenis** [comment]
@OriolMForgeFlow @AaronHForgeFlow 

I've tested on runboat and if the order of lines change should change the order of invoice lines, that does not work:

Sale Order after change:

image

Invoice after sale order change:

image

**Comment by rousseldenis** [comment]
> @OriolMForgeFlow @AaronHForgeFlow
> 
> I've tested on runboat and if the order of lines change should change the order of invoice lines, that does not work:
> 
> Sale Order after change:
> 
> image
> 
> Invoice after sale order change:
> 
> image

Oops wrong PR. @OriolMForgeFlow This is for #2603

**Comment by OriolMForgeFlow** [comment]
Thank you for your feedback, @rousseldenis!

The lines in the invoice remain unchanged as we are not utilizing the sequence field, which was causing some issues. Instead, we have introduced a new field called "related_so_sequence," designed as a Char field (SO12345/1 - so_name/sequence). This choice is based on the consideration that an invoice can be generated from multiple Sales Orders. As a result, we cannot use this field to sort the order lines.

Here's an example:

image

**Review by AaronHForgeFlow — APPROVED** [review]
Functional review, Works as expected.

**Review by LoisRForgeFlow — APPROVED** [review]
LGTM!

**Review by rousseldenis — APPROVED** [review]
Code review

**Pull request merged**
