### PR TITLE
[IMP] sale_order_secondary_unit: promote to Stable

### PR DESCRIPTION
**Pull request by toita86**
Needed for https://github.com/OCA/sale-workflow/pull/2735

### CODE REVIEW

**Comment by francesco-ooops** [comment]
@etobella @sergio-teruel can we (as done in https://github.com/OCA/sale-workflow/pull/1984 ?)

**Review by sergio-teruel — APPROVED** [review]

**Comment by francesco-ooops** [comment]
@pedrobaeza merge?

**Comment by pedrobaeza** [comment]
No, as every 14/15/16 branch has the pre-commit problem. It should be fixed first.

**Comment by francesco-ooops** [comment]
> No, as every 14/15/16 branch has the pre-commit problem. It should be fixed first.

sorry, I forgot!

**Comment by francesco-ooops** [comment]
@pedrobaeza merge?

**Review by pedrobaeza — APPROVED** [review]
/ocabot merge patch

**Pull request merged**
