### PR TITLE
[ADD] sale_order_weight: New module to 13.0

### PR DESCRIPTION
**Pull request by manuelcalerosolis**
This module is used to calculate the weight in a sale order.

image

### CODE REVIEW

**Comment by legalsylvain** [comment]
Hi @manuelcalerosolis. I guess this is a port of https://github.com/OCA/sale-workflow/pull/1557.
could you : 
1) first fix the first PR.
2) port the module to 13.0, cherry picking commit. (makes review easier to do, and respect history)

thanks !

**Comment by manuelcalerosolis** [comment]
The PR error https://github.com/OCA/sale-workflow/pull/1557 is codecov/project — 87.99% (-0.30%) compared to 458a159.

I have looked at it but I don't know what to do to solve it, I have put a new method in the tests, which tests the new functionality.

**Comment by legalsylvain** [comment]
@manuelcalerosolis : codecov is an optional test. the PR can be merged without red test. I was more thinking about @rousseldenis remarks.

however, it is about code coverage. If you add test, or demo data, you could improve the coverage of your module (/patch)

**Comment by manuelcalerosolis** [comment]
The changes requested by @rousseldenis are already made, I have increased the tests, anyway I will see if I can include any more tests.

**Pull request closed without merging**
