### PR TITLE
[11.0][FIX] sale_order_type: Remove hard dependency from l10n_generic_coa

### PR DESCRIPTION
**Pull request by SimoRubi**
Issue introduced with https://github.com/OCA/sale-workflow/pull/770.

cc @pedrobaeza

### CODE REVIEW

**Review by pedrobaeza — APPROVED** [review]
Thanks! Fast-tracking when CIs finish

**Comment by pedrobaeza** [comment]
Unfortunately you have introduced some flake8 errors:
```
sale_order_type/tests/test_sale_order_type_rule.py:19:34: W291 trailing whitespace
sale_order_type/tests/test_sale_order_type_rule.py:20:68: E203 whitespace before ','
```

**Comment by SimoRubi** [comment]
noo sorry, I edited directly in github IDE.. :/ now fixing

**Comment by SimoRubi** [comment]
@pedrobaeza travis is now :heavy_check_mark:

**Review by tafaRU — APPROVED** [review]

**Comment by pedrobaeza** [comment]
Thanks

**Pull request merged**
