### PR TITLE
[12.0][sale_product_set][IMP] - Add archive option to product set

### PR DESCRIPTION
**Pull request by sbejaoui**

### CODE REVIEW

**Review by sbidoul — APPROVED** [review]
Code LGTM. 

@gva-acsone for functional testing.

**Review by ThomasBinsfeld — APPROVED** [review]

**Comment by rousseldenis** [comment]
@sbejaoui Don't forget to update module version

**Review by gva-acsone — APPROVED** [review]
Functional test +1

**Pull request closed without merging**
