### PR TITLE
[MIG] migrate 'stock_picking_reorder_lines' to v8

### PR DESCRIPTION
**Pull request by damdam-s**

### CODE REVIEW

**Comment by gurneyalex** [comment]
:+1: thanks for porting

**Comment by pedrobaeza** [comment]
This should be in stock-logistics-workflow repo

**Comment by damdam-s** [comment]
@pedrobaeza : this module is in this project in version 7.0. That's why I migrate them in this repo. Now if it doesn't fit the "good" OCA project, I can move it like you suggested.

**Comment by pedrobaeza** [comment]
Yeah, I think so, because it's more attached to that one, don't you think?

**Comment by damdam-s** [comment]
new PR for this module : https://github.com/OCA/stock-logistics-workflow/pull/139

**Pull request closed without merging**
