### PR TITLE
[12.0][MIG] sale_invoice_policy

### PR DESCRIPTION
**Pull request by AaronHForgeFlow**
Standard Migration

### CODE REVIEW

**Review by rousseldenis — APPROVED** [review]
Code review

**Comment by rousseldenis** [comment]
@AaronHForgeFlow I think there is an incompatibility with sale_milestone_profile_invoicing module

**Comment by AaronHForgeFlow** [comment]
@rousseldenis I will check. Looking at the code it seems both can work together.

Edited: This module makes field invoice_policy computed so users will change a different field, 'default_invoice_policy'. There is no incompatibility from the user perspective. However, from the test perspective, all tests that changes the field invoice_policy to 'delivery' will fail, they need to change the field default_invoice_policy instead. But of course, we cannot do that because those modules does not depend on this one.

I think the best here is just to configure CI to not install both modules simultaneously.

**Comment by rousseldenis** [comment]
@AaronHForgeFlow Do you plan to add few lines of test for missing coverage ?

**Comment by AaronHForgeFlow** [comment]
@rousseldenis Yes.

**Comment by AaronHForgeFlow** [comment]
still planning to improve tests, just a moment :grin:

**Comment by AaronHForgeFlow** [comment]
I think now it is fine. Regards.

**Review by Cedric-Pigeon — APPROVED** [review]
Code review

**Pull request merged**
