### PR TITLE
[15.0][MIG] sale_order_type

### PR DESCRIPTION
**Pull request by juanpgarza**
Standard migration

### CODE REVIEW

**Review by celm1990 — COMMENTED** [review]
Please remove migration script

**Review by celm1990 — APPROVED** [review]
LGTM. 

Pls squash your commits

**Review by celm1990 — APPROVED** [review]

**Comment by pedrobaeza** [comment]
There are several PRs that have been merged meanwhile: #1884 and #1894

Can you please cherry-pick them?

**Comment by juanpgarza** [comment]
> There are several PRs that have been merged meanwhile: #1884 and #1894
> 
> Can you please cherry-pick them?

Done. Thanks!

**Review by pedrobaeza — APPROVED** [review]

**Pull request merged**
