### PR TITLE
[FIX] sale_order_revision

### PR DESCRIPTION
**Pull request by gurneyalex**
wrong keywork name in SaleOrder.copy definition
was breaking sale order duplication

### CODE REVIEW

**Review by PCatinean — APPROVED** [review]

**Comment by pedrobaeza** [comment]
Please change module version number

**Review by leemannd — APPROVED** [review]
Seems legit. Code review only

**Review by simahawk — APPROVED** [review]

**Review by pedrobaeza — APPROVED** [review]
Changed the version number myself, so merging.

**Comment by gurneyalex** [comment]
thanks all for the quick processing of this PR (and kudos to @pedrobaeza for fixing the version number faster than I could read the thread...)

**Pull request merged**
