### PR TITLE
[15.0][FIX] sale_invoice_plan: recompute invoice plan table

### PR DESCRIPTION
**Pull request by ps-tubtim**
This pull request was used to recompute **Amount** in the invoice plan table.
**Amount** in the invoice plan table is computed from the sum of the untaxed amount.

### CODE REVIEW

**Review by rousseldenis — COMMENTED** [review]
@ps-tubtim Maybe a little test for deposit product ?

**Comment by kittiu** [comment]
Functional tested works well.

**Review by kittiu — APPROVED** [review]

**Comment by kittiu** [comment]
Note: this fix seem to be related to the problem discussing in https://github.com/OCA/sale-workflow/pull/2438

**Review by dreispt — APPROVED** [review]

**Pull request merged**
