### PR TITLE
[14.0] [MIG] product_supplierinfo_for_customer_elaboration: Migration to v14

### PR DESCRIPTION
**Pull request by CarlosRoca13**
cc @Tecnativa TT37689

This migration depends of this PR: https://github.com/OCA/sale-workflow/pull/2203

please @sergio-teruel @victoralmau review this

### CODE REVIEW

**Comment by victoralmau** [comment]
Can you rebase to check tests (`sale_elaboration` is already merged)?

**Comment by CarlosRoca13** [comment]
Done @victoralmau

**Review by victoralmau — APPROVED** [review]
Code review OK

**Comment by pedrobaeza** [comment]
/ocabot migration product_supplierinfo_for_customer_elaboration

**Review by sergio-teruel — APPROVED** [review]

**Pull request merged**
