### PR TITLE
[10.0] Auto configure sale_rental module via post_install.py script

### PR DESCRIPTION
**Pull request by alexis-via**
Idea taken from the user experience described in bug #472 (before the rename of the bug report)

### CODE REVIEW

**Comment by atchuthan** [comment]
I agree :+1: but this won't work for newly created users(might be forgotten by users to setup for new odoo users). 
We could add the group(Properties on lines) inherited to employee base group such that the group will be enabled for all users (Existing + New)
my 2 cents

**Comment by alexis-via** [comment]
@atchuthan I will *also* work for newly created users, because it adds the group on the user "default user" (inactive). My tests confirms this.

**Comment by rafaelbn** [comment]
Hi @alexis-via , how is the state of this PR?

**Comment by alexis-via** [comment]
@rafaelbn For me, this PR is ready to be merged.

**Review by rogerv95 — APPROVED** [review]

**Review by atchuthan — APPROVED** [review]

**Pull request merged**
