### PR TITLE
[13.0][FIX] sale_order_product_assortment: Make invisible column product_allowed_id

### PR DESCRIPTION
**Pull request by sergio-teruel**
cc @Tecnativa TT33641

ping @chienandalu @carlosdauden

### CODE REVIEW

**Review by legalsylvain — APPROVED** [review]
Thanks'

**Review by pedrobaeza — APPROVED** [review]

**Review by marcelsavegnago — APPROVED** [review]

**Review by chienandalu — APPROVED** [review]

**Pull request merged**
