### PR TITLE
14.0 mig sale double validation

### PR DESCRIPTION
**Pull request by simoneversienti**

### CODE REVIEW

**Comment by simoneversienti** [comment]
I haven't updated the translation files yet, but in the meantime could someone give me some hints about failed checks?
@yvaucher @tschanzt

**Comment by rousseldenis** [comment]
@simoneversienti Thanks for your contribution. Can you follow migration guidelines ? https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-14.0

Thanks

**Comment by matteoopenf** [comment]
> @simoneversienti Thanks for your contribution. Can you follow migration guidelines ? https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-14.0
> 
> Thanks
Hi @rousseldenis my collegue @simoneversienti  follow the guideline but he start the migration from 12.0 because the migration in 13.0 is not merged but exist.

exept the orgin of migration there is other problem?

Thanks in advance for the help

**Comment by rousseldenis** [comment]
> > @simoneversienti Thanks for your contribution. Can you follow migration guidelines ? https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-14.0
> > Thanks
> > Hi @rousseldenis my collegue @simoneversienti  follow the guideline but he start the migration from 12.0 because the migration in 13.0 is not merged but exist.
> 
> exept the orgin of migration there is other problem?
> 
> Thanks in advance for the help

It seems not. Please take care about "Full process" part especially https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-14.0#technical-method-to-migrate-a-module-from-130-to-140-branch

You can replace 13.0 by 12.0 in the git format-patch command and respect commit messages.

**Comment by simoneversienti** [comment]
> > > @simoneversienti Thanks for your contribution. Can you follow migration guidelines ? https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-14.0
> > > Thanks
> > > Hi @rousseldenis my collegue @simoneversienti  follow the guideline but he start the migration from 12.0 because the migration in 13.0 is not merged but exist.
> > 
> > 
> > exept the orgin of migration there is other problem?
> > Thanks in advance for the help
> 
> It seems not. Please take care about "Full process" part especially https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-14.0#technical-method-to-migrate-a-module-from-130-to-140-branch
> 
> You can replace 13.0 by 12.0 in the git format-patch command and respect commit messages.

Perfect. Can I still take action now to solve the problems or would it be better to close this PR and open a new one, following all the steps?

**Comment by rousseldenis** [comment]
> > > > @simoneversienti Thanks for your contribution. Can you follow migration guidelines ? https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-14.0
> > > > Thanks
> > > > Hi @rousseldenis my collegue @simoneversienti  follow the guideline but he start the migration from 12.0 because the migration in 13.0 is not merged but exist.
> > > 
> > > 
> > > exept the orgin of migration there is other problem?
> > > Thanks in advance for the help
> > 
> > 
> > It seems not. Please take care about "Full process" part especially https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-14.0#technical-method-to-migrate-a-module-from-130-to-140-branch
> > You can replace 13.0 by 12.0 in the git format-patch command and respect commit messages.
> 
> Perfect. Can I still take action now to solve the problems or would it be better to close this PR and open a new one, following all the steps?

Your choice. You can reuse your branch

**Pull request closed without merging**
