### PR TITLE
[16.0][IMP] sale_planner_calendar: Refactor to use calendar.event model instead of sale.planner.calendar.event

### PR DESCRIPTION
**Pull request by sergio-teruel**
@Tecnativa

### CODE REVIEW

**Comment by sergio-teruel** [comment]
@carlosdauden, Have you added this commit from 15 d7935c705e72867df51faf4da8fdfec2ffc6f13b?

**Comment by carlosdauden** [comment]
New commits from 15.0 added

**Comment by carlosdauden** [comment]
@sergio-teruel ready to review

**Review by carlosdauden — APPROVED** [review]

**Comment by carlosdauden** [comment]
ping @CarlosRoca13

**Review by CarlosRoca13 — APPROVED** [review]

**Review by pilarvargas-tecnativa — APPROVED** [review]

**Comment by carlosdauden** [comment]
Ready to merge

**Pull request merged**
