### PR TITLE
[15.0][MIG] sale_fixed_discount

### PR DESCRIPTION
**Pull request by xhnilic3**
PR in order to migrate sale_fixed_discount module to version 15.0

### CODE REVIEW

**Comment by xhnilic3** [comment]
dealing with pre-commit error will be first thing in the morning

**Comment by rousseldenis** [comment]
> dealing with pre-commit error will be first thing in the morning

@xhnilic3 I suggest you to install pre-commit locally before committing. The format will be automatically done to particular configuration of the repository.

**Comment by xhnilic3** [comment]
@rousseldenis i do have it installed. I am sorry for pushing despite the error, but I was not sure how to deal with it correctly, could you provide some advice maybe? :/ How to get rid of that and preserve the functionality?

**Comment by rousseldenis** [comment]
> @rousseldenis i do have it installed. I am sorry for pushing despite the error, but I was not sure how to deal with it correctly, could you provide some advice maybe? :/ How to get rid of that and preserve the functionality?

Just do 'pre-commit install' in your local git repository. Be sure to be based on the last version on the branch version you want to push to. Then, do your changes and commit. Pre-commit will run as here and show you errors (and reformat for some).

**Comment by RachidAlassir** [comment]
There is a bug in [L59](https://github.com/xhnilic3/sale-workflow/blob/15.0-mig-sale_fixed_discount/sale_fixed_discount/models/sale_order.py#L59)
Steps to reproduce: 
Create an sale order and valid it then create an invoice.
I suggest you change it by:
`res = super(SaleOrderLine, self)._prepare_invoice_line(**optional_values)`

**Comment by rousseldenis** [comment]
Closing as already migrated

**Pull request closed without merging**
