### PR TITLE
[12.0][ADD] Down payment for multi company

### PR DESCRIPTION
**Pull request by quentinDupont**
This module extends the functionality of sale module to handle one product per company for down payment

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Shouldn't this go to OCA/multi-company?

**Comment by quentinDupont** [comment]
> Shouldn't this go to OCA/multi-company?

Yep i didn't think about it and i quite agree with you. I will move it after checking runbot and travis

**Comment by pedrobaeza** [comment]
Current trick for me is to not fill company_id in existing down payment product.

**Comment by quentinDupont** [comment]
Moved here : https://github.com/OCA/multi-company/pull/260

**Comment by quentinDupont** [comment]
Moved here : https://github.com/OCA/multi-company/pull/260

**Pull request closed without merging**
