### PR TITLE
[FIX] sale_advance_payment: Residual Amount - Port PR#2738 to v17.0

### PR DESCRIPTION
**Pull request by ellbristow**
See PR https://github.com/OCA/sale-workflow/pull/2738

This is a port of that fix for 17.0

### CODE REVIEW

**Comment by ellbristow** [comment]
@OCA/core-maintainers

**Review by theangryangel — APPROVED** [review]

**Comment by rousseldenis** [comment]
@ellbristow Thanks for this.

Could you remove the administrative commits as they are not relevant for this branch?

You should not modify the original commit too. Did you use oca-port tool to do this? As there is only one commit, you can also cherry-pick it

**Comment by ellbristow** [comment]
@rousseldenis No problem. I'll take a look

**Comment by ellbristow** [comment]
@rousseldenis not sure what happened with my last attempt. I've repushed a new version to the branch without the admin commits etc

**Comment by rousseldenis** [comment]
> @rousseldenis not sure what happened with my last attempt. I've repushed a new version to the branch without the admin commits etc

This is better but not perfect

You shouldn't alter the original commit. Author and commit message should remain the same. As said the authorized operation is a cherry-pick.

**Comment by ellbristow** [comment]
New PR Raised to replace this one:
https://github.com/OCA/sale-workflow/pull/3287

**Pull request closed without merging**
