### PR TITLE
[14.0][MIG] sales_team_security

### PR DESCRIPTION
**Pull request by ivantodorovich**
Migration + split module in 3:

- `sales_team_security`: base module, depends on `sales_team` and implements security on partners
- `sales_team_security_sale`: glue to integrate sales security rules
- `sales_team_security_crm`: glue to integrate crm security rules

I considered moving `sales_team_security_crm` to OCA/crm, but decided to keep it here next to the base module:
1) easier deployment, specially considering it's a glue module
2) easier PR review

I also:
- Added an uninstall_hook to revert changes made to res.groups upon uninstall.
- Replaced "Channel" terms by "Team", as it's more consistent in Odoo terminology

### CODE REVIEW

**Review by danimv5 — APPROVED** [review]
Functional review! LGTM

**Comment by dsolanki-initos** [comment]
partner

Why it show two sales team in customer view?

**Comment by pedrobaeza** [comment]
Please also add #1513

**Comment by dsolanki-initos** [comment]
Hi @ivantodorovich can you please check above comments so that we can merged this PR soon?

**Comment by dsolanki-initos** [comment]
@ivantodorovich If possible please have look

**Comment by dsolanki-initos** [comment]
Hi @ivantodorovich it would be great if can have a look at the comments.

**Comment by ivantodorovich** [comment]
Sorry for taking so long to do this.. it's been some really busy weeks :)

I've just integrated the commit in PR https://github.com/OCA/sale-workflow/pull/1513 here: https://github.com/OCA/sale-workflow/pull/1352/commits/3b1b3ac12c489a0c357753e56732a769dbd5f4e9

**Comment by dsolanki-initos** [comment]
@pedrobaeza it would be great if you can merge this PR.

**Comment by pedrobaeza** [comment]
There are still things being added in previous versions, so we should wait until all of them are merged and then fw-port it here.

**Comment by dsolanki-initos** [comment]
Hi @ivantodorovich can you please check if the changes in previous version is implemented we can update this PR.

**Comment by ivantodorovich** [comment]
Compared to `13.0` only this relevant commit was missing: https://github.com/OCA/sale-workflow/commit/c13eea1f9e1fcd59d187bf81168401f32fb99a3c

I've just integrated it in this PR

**Review by dsolanki-initos — APPROVED** [review]
LGTM

**Comment by flachica** [comment]
Hi @ivantodorovich I have not found any rules that refer to the res.partner model. Is this thought of like this? It is that I cannot find the rule in the 12.0 code and I suspect that, although my client needs it, it is not incorporated in the code for some reason that I do not know.

**Comment by ivantodorovich** [comment]
> Hi @ivantodorovich I have not found any rules that refer to the res.partner model. Is this thought of like this? It is that I cannot find the rule in the 12.0 code and I suspect that, although my client needs it, it is not incorporated in the code for some reason that I do not know.

Hello @flachica 

This is handled in the `ir_rule` model code.
Check this commit out : https://github.com/OCA/sale-workflow/commit/33b15c183cc2fec9b5192e1dbec37bd28f06c20f

**Comment by dsolanki-initos** [comment]
Can we merged this PR?

**Comment by dsolanki-initos** [comment]
It would be great if the maintainers could merge the PR

**Comment by dsolanki-initos** [comment]
It would be great if the maintainers could merge the PR

**Pull request merged**
