### PR TITLE
[12.0][IMP] add barcode to product set and report

### PR DESCRIPTION
**Pull request by sergiocorato**

### CODE REVIEW

**Review by legalsylvain — COMMENTED** [review]
hi @sergiocorato. Thanks for adding that. 
At the first sight, I wonder new kind of nomenclature is not added in the same time. Otherwise, I dont think it will be possible to use this new field in Odoo.
Or did I missed something.

**Comment by sergiocorato** [comment]
Hi @legalsylvain  and thanks for the review.
I'll use this field in another module, but I added some logic for search and a constraint (if I got the point).

**Comment by legalsylvain** [comment]
Hi @sergiocorato. Thanks for your reply. 
naive question : don't you think it should be great to add a new nomenclature.rule like here https://github.com/odoo/odoo/blob/12.0/addons/point_of_sale/data/default_barcode_patterns.xml#L21. 
with a new type, ``product_set`` ?

**Comment by sergiocorato** [comment]
@legalsylvain I wasn't aware of this object, thanks for the info!
I've updated the PR.

**Pull request closed without merging**
