### PR TITLE
PullReq modules porting to 8.0

### PR DESCRIPTION
**Pull request by MRonz70**
Proposed changes for backporting of 
sale_properties_dynamic_fields
and
sale_line_quantity_property_based
to 8.0

Original Authors: https://github.com/agilebg

### CODE REVIEW

**Comment by lepistone** [comment]
Hi, thanks for the PR.

This will probably need to have the original history (not just a copy of the code in one commit). I'd love to hear the opinion of the original authors @eLBati and @tafaRU on this.

Thanks!

**Comment by MRonz70** [comment]
Hi @lepistone, I've already informed @eLBati and @tafaRU by mail about these little correction I've already tested by my own.
They asked me to proceed with PR but forgive me for being a real novice with this community.
Could you please address me with the correct way of creating these sort of PRs?

Thankyou!

**Comment by lepistone** [comment]
Hi @MRonz70.

As I said, it depends whether the original code is on github or not, and what the authors think about it (let's wait for their feedback here).

If the code is on github, we might want to do a git extraction. I can help with the git magic in that case. On the other hand, if the authors don't care, and/or the code is lost deep in launchpad, a simple commit like yours might suffice.

Best

**Comment by eLBati** [comment]
@lepistone in this case, v7 modules are un github https://github.com/OCA/sale-workflow/tree/7.0 but not within `__unported__` folder https://github.com/OCA/sale-workflow/tree/8.0/__unported__

For me, a simple commit is acceptable.
Otherwise, what do you suggest?

**Comment by lepistone** [comment]
To keep history, we'd have to fetch the bzr branch into git, make a branch that contains only that module, and then apply the changes made by @MRonz70. An hour or so of obscure git commands :smile: , but feasible still.

If it's ok for @eLBati and @tafaRU we can also keep this PR as it is. We need a CLA for @MRonz70, though.

Thanks

**Comment by rafaelbn** [comment]
Hi @MRonz70 are you going to continue with this PR?

**Comment by MRonz70** [comment]
no, i'm not working on this anymore


2017-05-31 18:21 GMT+02:00 Rafael Blasco <notifications@github.com>:

**Comment by pedrobaeza** [comment]
This is still red, with conflicting files very old, so I'm closing. If you are still interested in this, feel free to reopen it fixing Travis status and conflicts

**Pull request closed without merging**
