### PR TITLE
[13.0][ADD] sale_validity_auto_cancel

### PR DESCRIPTION
**Pull request by JordiMForgeFlow**
New module to automatically cancel quotations after their expiration plus a configurable number of days.

### CODE REVIEW

**Review by mariadforgeflow — APPROVED** [review]
LGTM!

**Review by GuillemCForgeFlow — APPROVED** [review]
LGTM! :+1:

**Review by JoanSForgeFlow — APPROVED** [review]
LGTM :+1:

**Review by AaronHForgeFlow — APPROVED** [review]
Functional tests

**Comment by JordiMForgeFlow** [comment]
Hi @JoanSForgeFlow @mariadforgeflow @GuillemCForgeFlow @AaronHForgeFlow 

I have added a try-except block for the cancelling to cover cases where the cancelling of one order may fail due to other logics, leaving a log with the exception.

**Review by AaronHForgeFlow — APPROVED** [review]
Good!

**Review by JuanyDForgeflow — APPROVED** [review]
LGTM

**Comment by JordiMForgeFlow** [comment]
Hi @dreispt 

Could you retry the merge command? :)

**Comment by MiquelRForgeFlow** [comment]
> `/ocbot`

typo

**Comment by JasminSForgeFlow** [comment]
Hi @dreispt

Could you retry the merge command?

Thanks

**Pull request merged**
