### PR TITLE
[13.0][FIX] sale_order_product_recommendation: Fix tests. Not order recommendations found due to date data

### PR DESCRIPTION
**Pull request by sergio-teruel**
cc @Tecnativa

ping @carlosdauden @chienandalu

### CODE REVIEW

**Review by carlosdauden — APPROVED** [review]

**Review by chienandalu — APPROVED** [review]

**Review by pedrobaeza — APPROVED** [review]

**Comment by pedrobaeza** [comment]
@sergio-teruel it seems not enough

**Comment by carlosdauden** [comment]
The problem is caused by an additional space in other module:
https://app.travis-ci.com/github/OCA/sale-workflow/jobs/546292343#L546

**Pull request merged**
