### PR TITLE
[15.0][IMP] sale_order_line_price_history: Use just widget to display wizard and update values without saving

### PR DESCRIPTION
**Pull request by CarlosRoca13**
cc @Tecnativa TT46103

ping @pedrobaeza @sergio-teruel

### CODE REVIEW

**Comment by CarlosRoca13** [comment]
Here is an example of how is it working now :smile: 
imp_sale_order_price_history

**Review by pedrobaeza — APPROVED** [review]
Tested and working

**Review by Shide — APPROVED** [review]
Functional test
https://www.loom.com/share/39f0079c56dc465fb30532e50b8f45b8?sid=05426451-8fb7-4ab5-b9db-b145ced5d98d

**Comment by Shide** [comment]
@CarlosRoca13 are you going to port this PR to v16?

**Comment by CarlosRoca13** [comment]
I will do it when I have a chance. If you want to port it, you can do it BTW :smile: 

This PR add discounts https://github.com/OCA/sale-workflow/pull/2814

**Pull request merged**
