### PR TITLE
[16.0][MIG] sale_order_secondary_unit

### PR DESCRIPTION
**Pull request by remihb**
With changes introduced by #2331 for 15.0 (Compatibility with product variants)

Wait for OCA/product-attribute#1325 to be merged

- [ ] Please cherry-pick https://github.com/OCA/sale-workflow/pull/2331

### CODE REVIEW

**Comment by BT-aleonard** [comment]
@remihb Thanks for your contribution, 
Can you add this PR to the OCA's issues on https://github.com/OCA/sale-workflow/issues/2215 and fix the tests?
Thanks :100:

**Comment by pedrobaeza** [comment]
Please cherry-pick #2331

**Comment by nicolascol** [comment]
Could you repair runboat? I want to test the module
@remihb

**Comment by desdelinux** [comment]
ping @remihb

**Comment by fcvalgar** [comment]
> /ocabot rebase

@rafaelbn please rebase, thank you

**Comment by rafaelbn** [comment]
Hello @remihb , are you going to continue with this PR? Let me know please. Thanks.

**Comment by rafaelbn** [comment]
Superseded by https://github.com/OCA/sale-workflow/pull/2635

Closing as no answer

**Pull request closed without merging**
