### PR TITLE
[ADD] add module to deliver when creating invoice

### PR DESCRIPTION
**Pull request by laetitia-gangloff**
In sale advance payment, add option to deliver at the same time than invoice.
If picking are not validable, an error is raised.

### CODE REVIEW

**Comment by Cedric-Pigeon** [comment]
:+1:  Tests and code

**Comment by rafaelbn** [comment]
@laetitia-gangloff @Cedric-Pigeon this PR is failing runbot and travis, please could you review and fix errors? We are in the OCA Code Sprint and are reviewing for get merge, thanks!

**Comment by Cedric-Pigeon** [comment]
@rafaelbn I am in the room also ;-) I will have a look this morning.

**Review by rafaelbn — CHANGES_REQUESTED** [review]
Please add test, as in https://github.com/OCA/sale-workflow/pull/280#issuecomment-199257504 Coverage decreased (-27.0%) to 46.899% . Thanks!

**Comment by rousseldenis** [comment]
Closing this as no activity. @laetitia-gangloff  Please feel free to reopen it if you still need it. Take care of your PR's

**Pull request closed without merging**
