### PR TITLE
10.0 mig sale order lot selection

### PR DESCRIPTION
**Pull request by mourad-ehm**

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Please squash together all the "OCA Transbot" commits.

**Review by eLBati — CHANGES_REQUESTED** [review]
Thanks @mourad-ehm , please check travis

**Comment by mourad-ehm** [comment]
Hi @eLBati , the test with the same product fails in v 9.0. see this pr #415 in which I ask some questions to resolve test fail.
The question is asked also for this contributors :
@hurrinico, @florian-dacosta

**Comment by bealdav** [comment]
:+1:

**Comment by mourad-ehm** [comment]
Hi @eLBati,  Thanks for review. Travis is OK.

**Review by eLBati — APPROVED** [review]
LGTM

**Pull request merged**
