### PR TITLE
[14.0][MIG] sale_stock_delivery_address

### PR DESCRIPTION
**Pull request by BernatPForgeFlow**

### CODE REVIEW

**Review by JoanMForgeFlow — APPROVED** [review]
Functional review OK!

**Review by mariadforgeflow — APPROVED** [review]
LGTM!

**Comment by marcelsavegnago** [comment]
Travis Red

**Comment by BernatPForgeFlow** [comment]
@marcelsavegnago Travis Red because needs #1689 to be merged.

**Comment by BernatPForgeFlow** [comment]
@rousseldenis @marcelsavegnago Ready to merge!

**Comment by rafaelbn** [comment]
Hello @BernatPForgeFlow , could you please check https://github.com/OCA/sale-workflow/pull/1833#issuecomment-1043686332 ? Thank you!

**Comment by dreispt** [comment]
Tests are failing:
https://app.travis-ci.com/github/OCA/sale-workflow/jobs/560222201#L3205

**Comment by BernatPForgeFlow** [comment]
@rafaelbn @dreispt 

I have tested locally the module and is not failing. I don't know why pipeline failed, but reviews are welcome. 

If you accept it maybe we could retry the merge command and see if it passes now.

**Pull request merged**
