### PR TITLE
[16.0][MIG] sale_start_end_dates

### PR DESCRIPTION
**Pull request by alexis-via**
Superseeds migration PR https://github.com/OCA/sale-workflow/pull/2327 I converted onchange to compute methods.

### CODE REVIEW

**Comment by alexis-via** [comment]
Tests are green!

**Review by rousseldenis — APPROVED** [review]
Code review. Indeed, this is better

**Review by dsolanki-initos — APPROVED** [review]
Functional review LGTM.

**Review by DorianMAG — APPROVED** [review]
Thx for this work.
Tested on runboat.
LGTM

**Comment by agent-z28** [comment]
@alexis-via 

1) I found this:

 File "/opt/odoo/auto/addons/sale_start_end_dates/models/sale_order.py", line 184, in _compute_end_date
   elif line.end_date and line.start_date and line.start_date > self.end_date:
 File "/opt/odoo/custom/src/odoo/odoo/fields.py", line 1157, in __get__
   self.recompute(record)
 File "/opt/odoo/custom/src/odoo/odoo/fields.py", line 1365, in recompute
   apply_except_missing(self.compute_value, recs)
 File "/opt/odoo/custom/src/odoo/odoo/fields.py", line 1338, in apply_except_missing
   func(records)
 File "/opt/odoo/custom/src/odoo/odoo/fields.py", line 1387, in compute_value
   records._compute_field_value(self)
 File "/opt/odoo/custom/src/odoo/odoo/models.py", line 4208, in _compute_field_value
   fields.determine(field.compute, self)
 File "/opt/odoo/custom/src/odoo/odoo/fields.py", line 97, in determine
   return needle(*args)
 File "/opt/odoo/auto/addons/sale_start_end_dates/models/sale_order.py", line 169, in _compute_start_date
   elif line.end_date and line.start_date and line.start_date > self.end_date:
 File "/opt/odoo/custom/src/odoo/odoo/fields.py", line 1153, in __get__
   record.ensure_one()
 File "/opt/odoo/custom/src/odoo/odoo/models.py", line 5137, in ensure_one
   raise ValueError("Expected singleton: %s" % self)
alueError: Expected singleton: sale.order.line(45, 46, 47, 48)

2 ) I think it would be nice to have an option, to update all lines with a new default_date

Imagine you work with a long sales template which will be pulled as default. So the whole order lines are there.
Now you have to set it in each line manually!

Maybe onchange just fill out all empty values for order.lines that require it!?

**Comment by DorianMAG** [comment]
Hi @agent-z28, @alexis-via 
I tried to reproduce the problem,
but I did not find.
Do you have any details on this.
Does this require a fix?

**Comment by agent-z28** [comment]
> Hi @agent-z28, @alexis-via I tried to reproduce the problem, but I did not find. Do you have any details on this. Does this require a fix?

Hi i provided a fix here:

https://github.com/akretion/sale-workflow/pull/29/files#diff-9aa1071ea0fb2a2becdd07b45fcd2f44dd74b8f762e497498c06f298e7a81d33R184

https://github.com/akretion/sale-workflow/pull/29

its self instead of line ...

**Review by rafaelbn — APPROVED** [review]
/ocabot merge patch

**Pull request merged**
