### PR TITLE
[15.0][ADD] sale_subscription_oca

### PR DESCRIPTION
**Pull request by carlos-domatix**
This module allows creating subscriptions that generate recurring invoices or orders. It also enables the sale of products that generate subscriptions.

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Hi, Carlos.

If this is generating invoices, it's a bit awkward that is named `sale_subscription`. And a better repository should be `account-invoicing` or `contract` for this.

**Comment by carlos-domatix** [comment]
Hi, Pedro.
This generates invoices and orders, as the user prefers. It also allows selling products that generate subscriptions.
Can you tell me the name you would give it? I can change it to another repository, but it's also a sales flow.

**Comment by pedrobaeza** [comment]
I would just call it then `subscription_oca`, and OCA/contract can be the host.

**Comment by carlos-domatix** [comment]
Thanks, Pedro! Done!

https://github.com/OCA/contract/pull/971

**Pull request closed without merging**
