### PR TITLE
[ADD] Sale Order Line Hide Create Product: New module to 14.0

### PR DESCRIPTION
**Pull request by manuelcalerosolis**
This module change the views of the sales lines so that it does not allow the creation of products on the fly.

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Better to use IMO `web_m2x_options` with the system parameter `create=False`.

**Comment by manuelcalerosolis** [comment]
@pedrobaeza thanks for the info.

web_m2x_options changes the behavior in the entire application, in this case we only seek to hide this possibility in the sales operations, and only with the products.

**Comment by pedrobaeza** [comment]
The quick create option is very harmful in any screen (I'm not talking about the "Create and edit..." one, that lets you cancel), so I disable it entirely for whole Odoo.

**Comment by manuelcalerosolis** [comment]
> The quick create option is very harmful in any screen (I'm not talking about the "Create and edit..." one, that lets you cancel), so I disable it entirely for whole Odoo.

I totally agree with you, it only manages to create incorrect and incomplete customer and product records, but the customer in this case rules.

**Comment by pedrobaeza** [comment]
OK, as you prefer :)

**Pull request closed without merging**
