### PR TITLE
[ADD][10.0] sale_manual_delivery

### PR DESCRIPTION
**Pull request by AaronHForgeFlow**
The Goal of this module is to allow the manual creation of delivery slips.

Supersedes https://github.com/OCA/sale-workflow/pull/935 (can't be reopened)

### CODE REVIEW

**Comment by AaronHForgeFlow** [comment]
Also rebased the branch.

cc @leemannd

**Comment by leemannd** [comment]
@yvaucher Could you please have a look and maybe help us in having this merged?

**Comment by leemannd** [comment]
@AaronHForgeFlow Given the result of the build, there is an high chance it will never be merged.

**Comment by AaronHForgeFlow** [comment]
Travis failed because it never started :S

```
$ python --version
Python 2.7.13
$ pip --version
pip 18.1 from /home/travis/virtualenv/python2.7.13/lib/python2.7/site-packages/pip (python 2.7)
install.1
0.37s$ git clone --depth=1 https://github.com/OCA/maintainer-quality-tools.git ${HOME}/maintainer-quality-tools
install.2
0.00s$ export PATH=${HOME}/maintainer-quality-tools/travis:${PATH}
3.68s$ travis_install_nightly
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-sY9pp3/lazy-object-proxy/
The command "travis_install_nightly" failed and exited with 1 during .
Your build has been stopped.
```
I guess something needs to be changed in the travis config file but no idea what.

**Review by MiquelRForgeFlow — APPROVED** [review]
The code is the same as https://github.com/OCA/sale-workflow/pull/935, which was green when travis executed and also had 4 approvals. Full trust! :+1:

**Review by leemannd — APPROVED** [review]

**Comment by leemannd** [comment]
Thanks @AaronHForgeFlow for the perserverance to have it merged :pray:

**Comment by JuanyDForgeflow** [comment]
@AaronHForgeFlow @leemannd @MiquelRForgeFlow Dependency errors on travis are fixed but there are still two travis failing due to tests

**Review by JuanyDForgeflow — APPROVED** [review]

**Comment by MiquelRForgeFlow** [comment]
All checks are green!!! please @leemannd fins someone to merge this :)

**Comment by leemannd** [comment]
@MiquelRForgeFlow Checking

**Comment by MiquelRForgeFlow** [comment]
Selection_596

any idea?

**Comment by rousseldenis** [comment]
@MiquelRForgeFlow I've updated 10.0 branch. @AaronHForgeFlow Could you rebase ?

**Comment by rousseldenis** [comment]
@MiquelRForgeFlow Tests are failing

**Comment by AaronHForgeFlow** [comment]
I can't wait for this to be merged :partying_face:

**Comment by MiquelRForgeFlow** [comment]
@rousseldenis this is ready

**Comment by MiquelRForgeFlow** [comment]
Hope it doesn't fail due to outdated copier template version 😅

**Pull request merged**
