### PR TITLE
[16.0][IMP] sale_invoice_policy: Make it uninstallable

### PR DESCRIPTION
**Pull request by rousseldenis**

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Doing this, the module is not available in runboat.  It's preferable another solution that doesn't break the compatibility between modules. In fact, as is, `sale_invoice_policy` is incorrect and shouldn't be allowed in OCA, as it breaks some parts when installed.

Just now, we are just hiding the trash under the carpet.

**Comment by rousseldenis** [comment]
> Doing this, the module is not available in runboat. It's preferable another solution that doesn't break the compatibility between modules. In fact, as is, `sale_invoice_policy` is incorrect and shouldn't be allowed in OCA, as it breaks some parts when installed.
> 
> Just now, we are just hiding the trash under the carpet.

Yes, I know but I want to let other people to run their PR before finding a good solution.

As the current implementation is depending on context.

**Comment by pedrobaeza** [comment]
I think you should mark it as installable=False, and the CI is checked on the PR

**Comment by rousseldenis** [comment]
> Just now, we are just hiding the trash under the carpet.

Yes, I'll do that instead and create an issue.

**Comment by pedrobaeza** [comment]
The issue #2725 tackles it.

**Comment by rousseldenis** [comment]
> The issue #2725 tackles it.

Yes, but with this I will solve it. Another should be recreated to reimplement the module.

**Comment by rousseldenis** [comment]
@ljsalvatierra-factorlibre @yankinmax @Cedric-Pigeon sale_invoice_policy is breaking standard behavior. I will make it uninstallable here and will create an issue to reimplement it if necessary.

**Comment by ljsalvatierra-factorlibre** [comment]
> @ljsalvatierra-factorlibre @yankinmax @Cedric-Pigeon sale_invoice_policy is breaking standard behavior. I will make it uninstallable here and will create an issue to reimplement it if necessary.

cc. @ACheung-FactorLibre

**Comment by rousseldenis** [comment]
@Yadier-Tecnativa I've reverted your change during migration of sale_order_invoicing_finished_task module as test result depended on sale_invoice_policy side effect.

https://github.com/OCA/sale-workflow/commit/6e12d22507c5168299200e35000c8150cbb67d41#diff-6eb7f1f7a4095dcbbc28fdb5ecc49b6b69e38fdb15ab3a07d9499f5e68a712b6R163

**Review by pedrobaeza — APPROVED** [review]
Thanks for the investigation and changes:

/ocabot merge patch

**Comment by legalsylvain** [comment]
Hi. @rousseldenis and @pedrobaeza. I'm working on the migration of the OCA modules we use in GRAP from 12.0 to 16.0 and this module is the last ones I have to migrate. is this module still usefull in V16, or can we consider it as "merged into sale" in Openupgrade apriori file.
kind regard.

**Comment by pedrobaeza** [comment]
The module is still useful (although is debatable that is a good business flow to decide the invoicing policy per order instead of per product). The problem was the implementation, that conflicts and breaks any other module coexisting, as it changes an standard stored field by a non-stored one. It was disabled meanwhile.

The attempt of fixing this is in #2763

**Comment by legalsylvain** [comment]
hi @pedrobaeza. Thanks a lot for your quick answer. I'll follow #2763.
have a nice day.

**Pull request merged**
