### PR TITLE
[ADD] sale_automatic_workflow_send_invoice: New module to 13.0

### PR DESCRIPTION
**Pull request by manuelcalerosolis**
Sale automatic workflow send invoice: New module to 13.0

### CODE REVIEW

**Comment by rousseldenis** [comment]
@manuelcalerosolis Thanks for this.

Do you plan to add some tests ?

**Review by HaraldPanten — APPROVED** [review]
Hi, we tried this module in one of our projects and it's functionally working fine. The functional review is OK 👍 

@manuelcalerosolis could you attend Denis's comments?

Thanks for your contribution!

**Comment by manuelcalerosolis** [comment]
I'm going to try to do some tests.

**Comment by rousseldenis** [comment]
@manuelcalerosolis Could you fix pre-commit in order to merge this ?

**Pull request closed without merging**
