### PR TITLE
[12.0][IMP] sale_invoice_plan: enable more than one invoice

### PR DESCRIPTION
**Pull request by marcelsavegnago**

### CODE REVIEW

**Comment by marcelsavegnago** [comment]
ping @rvalyi

**Comment by rvalyi** [comment]
There is indeed a bug without this when you click on "create invoice by plan":

**Review by rvalyi — APPROVED** [review]

**Review by ivantodorovich — APPROVED** [review]
LG

**Review by rousseldenis — APPROVED** [review]

**Comment by marcelsavegnago** [comment]
PSC can you merge this PR please?

**Comment by marcelsavegnago** [comment]
ping

**Pull request merged**
