### PR TITLE
[16.0][MIG] sale_stock_cancel_restriction

### PR DESCRIPTION
**Pull request by aliciagaarzo**
Migration of **sale_stock_cancel_restriction** module to version 16

### CODE REVIEW

**Comment by aliciagaarzo** [comment]
In v16, a wizard is used to cancel orders and the tests fail because I do not include a dependency on the season_id field of the sale_cancel_reason module
```
        wizz = self.sale_order.action_cancel()
        wizz = self.env["sale.order.cancel"].create({"order_id": self.sale_order.id})
        wizz.action_cancel()
        self.assertEqual(
           self.sale_order.picking_ids.state,
           "cancel",
            "After cancelling a picking, the state should be cancelled",
        )
```

**Review by dsolanki-initos — APPROVED** [review]
Functional LGTM.

**Review by hugo-cordoba — APPROVED** [review]
LGTM! (Code Review)

**Pull request merged**
