### PR TITLE
[13.0] sale_blanket_order - Fix wrong taxes

### PR DESCRIPTION
**Pull request by sergioeix**
When you make a blanket sale order supplier taxes were used on each line this PR fix this.

### CODE REVIEW

**Comment by sergioeix** [comment]
Related with this issue #2228

**Comment by francesco-ooops** [comment]
@sergioeix I think you can backport the commit created while migrating to v.14 to fix this issue, see #1865

**Comment by sergioeix** [comment]
@francesco-ooops  I think its only a 13 branch issue, but i will take a look

**Comment by francesco-ooops** [comment]
@sergioeix the issue has been reported since v11, in v14 it has been fixed when migrating

**Comment by sergioeix** [comment]
@francesco-ooops you are rigth, i do exactly the same as its done on the 14 mig. If there is another flow to do a backport instead to make a PR i dont know how to do it :(

**Comment by francesco-ooops** [comment]
I think you should find everything in the [documentation](https://github.com/OCA/odoo-community.org/blob/master/website/Contribution/CONTRIBUTING.rst), if in need you can ask for directions to @OCA/crm-sales-marketing-maintainers

**Comment by mmequignon** [comment]
> @francesco-ooops you are rigth, i do exactly the same as its done on the 14 mig. If there is another flow to do a backport instead to make a PR i dont know how to do it :(

To backport a single commit you have to do a PR anyway. I think the best way is to use `git cherry-pick <COMMIT HASH>`

**Comment by sergioeix** [comment]
Then what should we do with this? I am not an expert but i want to fix this in order other pepole can use it safetly, by now use this module as it is can become in a big issue inside the company accounting stuff.

**Comment by francesco-ooops** [comment]
@pedrobaeza can you point out in the documentation where the process of cherry picking is explained? thanks

**Comment by pedrobaeza** [comment]
It's a general git operation. You can check documentation like this one: https://www.atlassian.com/git/tutorials/cherry-pick

**Comment by francesco-ooops** [comment]
> It's a general git operation. You can check documentation like this one: https://www.atlassian.com/git/tutorials/cherry-pick

IMHO it wouldn't hurt to add it to OCA documentation on commit forward- and back-porting, I've seen many devs ask about this. My two cents 😉

**Comment by sergioeix** [comment]
I can do this git cherry-pick <COMMIT HASH> by myself or this kind of stuff has to be done by someone with special permissions?

**Comment by pedrobaeza** [comment]
You can do it yourself in your branch and propose a PR.

**Comment by sergioeix** [comment]
then i am going to close this PR and make a new one this way

**Pull request closed without merging**
