### PR TITLE
Migration of sale_properties_easy_creation

### PR DESCRIPTION
**Pull request by tafaRU**

### CODE REVIEW

**Comment by eLBati** [comment]
:+1:

**Comment by yvaucher** [comment]
Here you are missing this history https://github.com/OCA/sale-workflow/commits/7.0/sale_properties_easy_creation
And this as well
https://github.com/OCA/sale-workflow/commits/7.0/sale_line_quantity_properties_based

**Comment by tafaRU** [comment]
@yvaucher, is https://github.com/tafaRU/sale-workflow/commit/b4dcd982e4eeacb6a442cc6c24a39775f0337d27 not proper as first stage for module migration? I usually start with `git mv` the module from _unported but in this case it's missing. 
Anyway, how can I recover the history?

**Comment by yvaucher** [comment]
@tafaRU You have 2 choices
1. cherry-pick each commit
2. filter-branch on 7.0 on directories sale_properties_easy_creation and sale_line_quantity_properties_based

Then merge

If you are not used to filter-branch, cherry-pick might be easier.

**Comment by tafaRU** [comment]
@yvaucher I tried to do the following steps:
- create a new branch from 8.0
- git cherry-pick 7ab003ff57daad3cbf4835e05f7fb4c6d2f6db8a 

Right after this I get some conflicts:

```
Changes to be committed:

    new file:   sale_properties_dynamic_fields/__init__.py
    new file:   sale_properties_dynamic_fields/__openerp__.py
    new file:   sale_properties_dynamic_fields/mrp_property.py
    new file:   sale_properties_dynamic_fields/mrp_property_view.xml
    new file:   sale_properties_dynamic_fields/sale.py
    new file:   sale_properties_dynamic_fields/test/properties.yml

Unmerged paths:
  (usa "git add/rm <file>..." come appropriato per la risoluzione)

    eliminato da noi:    product_price_properties_based/sale_demo.xml
    eliminato da noi:    product_price_properties_based/test/sale_order.yml
    entrambi modificati: sale_order_back2draft/__openerp__.py
    entrambi eliminati:  sale_properties_easy/__init__.py
    aggiunto da loro:    sale_properties_easy_creation/__init__.py
    aggiunto da loro:    sale_properties_easy_creation/__openerp__.py
    aggiunto da loro:    sale_properties_easy_creation/mrp_property.py
    aggiunto da loro:    sale_properties_easy_creation/mrp_property_view.xml
    aggiunto da loro:    sale_properties_easy_creation/sale_demo.xml
    aggiunto da loro:    sale_properties_easy_creation/security/ir.model.access.csv
    aggiunto da loro:    sale_properties_easy_creation/test/properties.yml
    aggiunto da noi:     sale_quotation_number/model/__init__.py
```

I may have not understood what you suggested, but it seems to me quite hard to go on in this way till the end. Am I doing something wrong, otherwise, what else do you suggest?

Thanks a lot.

**Comment by yvaucher** [comment]
@tafaRU This commit changes a lot of things in multiple modules some that aren't even present there or have already been modified in 8.0. So you need to ignore/fix those changes.

If you want to pull sale_properties_dynamic_fields, you might need to move it in `__unported__` afterward.

**Comment by eLBati** [comment]
@yvaucher shouldn't `__unported__` be deprecated? (ref https://www.odoo.com/groups/community-59/community-11266932 )

In this particular case, `sale_properties_easy_creation` is not present in `__unported__` of 8.0 branch because the module was added to 7.0 on github directly (not launchpad).
So, it was not added to `__unported__` (and I think this is correct).

I think we need to agree about the generic procedure to follow when porting modules to a new version: unless we don't have one repo per module, I think extracting the history of a single module within a repo would be too onerous for contributors.

What do you think?

**Comment by tafaRU** [comment]
@yvaucher I kept the history by using `git filter-branch` on this other branch: https://github.com/tafaRU/sale-workflow/tree/8.0-sale_properties_easy_creation

Could you please check it? If ok I'll create a new PR.

Thanks in advance.

**Comment by yvaucher** [comment]
Thanks for the effort on this.

It seems good.

I just feel the first commit https://github.com/OCA/sale-workflow/commit/bd4add3395b55269a1421a397b15f3b3fc21a167 is a bit strange as it adds a module instead of renaming it. But I checked and it is how it was done in branch 7.0.

So :+1:

**Comment by tafaRU** [comment]
Superseded by https://github.com/OCA/sale-workflow/pull/167

**Pull request closed without merging**
