### PR TITLE
[9.0] ADD sequence to order sale order type in tree view

### PR DESCRIPTION
**Pull request by nicomacr**
This correction is for these reasons:

- To be able to prioritize the one that is intended to be used by default.
- To be able to prioritize the ones most used

### CODE REVIEW

**Review by Emiq2 — APPROVED** [review]

**Review by LoisRForgeFlow — APPROVED** [review]
LGTM

**Review by ValentinoDefelice — APPROVED** [review]

**Comment by AaronHForgeFlow** [comment]
Edited: I was wrong this module is different :sweat_smile:

**Review by AaronHForgeFlow — APPROVED** [review]
:+1: LGTM

**Review by jjscarafia — APPROVED** [review]

**Comment by jjscarafia** [comment]
@guewen can you please review/approve this?
Thanks!

**Pull request merged**
