### PR TITLE
[15.0][MIG] sale_fixed_discount

### PR DESCRIPTION
**Pull request by ps-tubtim**
From https://github.com/OCA/sale-workflow/pull/2269

### CODE REVIEW

**Comment by CRogos** [comment]
@ps-tubtim could you review the v14 PR https://github.com/OCA/sale-workflow/pull/2507 first, and than we use this (cleaned) version as base of the v15 migration?

**Review by MohamedOsman7 — APPROVED** [review]
Code & functionality LGTM

**Comment by ps-tubtim** [comment]
> @ps-tubtim could you review the v14 PR #2507 first, and than we use this (cleaned) version as base of the v15 migration?

@CRogos I already update the code following PR #2507. Could you review it again?

**Comment by CRogos** [comment]
I am wondering why the v15 MIG contains 33 commits, while the v14 only contains 21 commits. I assume some commits have been squashed/cleanup in the v14 migration. I think it would be better to base the v15 MIG on v14 containing also the improvements from v14 without doing the changes manually again. 
image

Also you should merge these commits, in case they are needed in a migration based on v14.
image

**Comment by pedrobaeza** [comment]
Superseded by #2574

**Pull request closed without merging**
