### PR TITLE
[MIG] sale_restricted_qty

### PR DESCRIPTION
**Pull request by SirAionTech**
Standard migration from `14.0` (https://github.com/OCA/sale-workflow/tree/ab07f15ed44cf13d18eebe4fd952692ff6ddf89e/sale_restricted_qty).

### CODE REVIEW

**Review by dcorio — APPROVED** [review]
LGTM!
tested and working as expected

**Comment by thinkwelltwd** [comment]
For whatever it's worth, #2581 is a v15 PR with numerous code linting improvements and grammatical fixes.

Personally, I'd be glad if that could be the basis for a future iterations of this module, if the code owner decides to merge it.

**Review by antoniocanovas — APPROVED** [review]
Fucntional review Ok !

**Review by pedroguirao — APPROVED** [review]
LGTM!

**Pull request merged**
