### PR TITLE
14.0 mig sale order secondary unit

### PR DESCRIPTION
**Pull request by alexeirivera87**
Migration to v14 of module sale_order_secondary_unit. Regards

### CODE REVIEW

**Comment by alexeirivera87** [comment]
@ernestotejeda

**Review by ernestotejeda — APPROVED** [review]

**Comment by ernestotejeda** [comment]
ping @sergio-teruel @carlosdauden

**Review by sergio-teruel — COMMENTED** [review]
@alexeirivera87 Good job...
Recently I have added a mixin model into product_secondary_unit base module for v13.0
https://github.com/OCA/product-attribute/blob/13.0/product_secondary_unit/models/product_secondary_unit_mixin.py

By theese way you extend any model with less code, you can see an example in this module
https://github.com/OCA/stock-logistics-warehouse/pull/1053

But I know that this changes is in v13.0 version.. 

Would you venture to migrate product_secondary_unit to version 14 to extend sale_order_secondary_unit with less code?

**Comment by Kev-Roche** [comment]
@alexeirivera87 @sergio-teruel @carlosdauden 
Hi, is this PR still alive? If yes, I would like to push a commit in order to add the function dependent vs. independent  (in the last V14 migration version of product_secondary_unit https://github.com/OCA/product-attribute/pull/848) and extend this PR with the mixin model functions as suggested by @sergio-teruel. 
If not, I can replace this PR respectfully about authorship.

**Comment by sergio-teruel** [comment]
Ping @alexeirivera87 Can you answer to @Kev-Roche ??
@Kev-Roche We can wait two days... if we have not response toy can replace this PR

**Comment by Kev-Roche** [comment]
New PR replacing this one : #1671

**Comment by pedrobaeza** [comment]
Superseded by #1671

**Pull request closed without merging**
