### PR TITLE
[ADD] sale_pricelist_triple_discount

### PR DESCRIPTION
**Pull request by SimoRubi**
Bridge module between sale_triple_discount and sale_pricelist_discount.
Depends on #792

### CODE REVIEW

**Comment by SimoRubi** [comment]
One year :tada: 
@OCA/crm-sales-marketing-maintainers can someone please take a look?
Thanks :)

**Review by rousseldenis — APPROVED** [review]
Code review.

IMHO we can merge it.

@SimoRubi Could you rebase to check if this does not break anything ?

**Comment by rousseldenis** [comment]
Ok, you did it yet.

**Comment by SimoRubi** [comment]
yep, I tried and nothing happened :sweat_smile:

**Comment by rousseldenis** [comment]
Let's go forward.

/ocabot merge

**Pull request merged**
