### PR TITLE
[12.0][MIG] sale_procurement_group_by_requested_date

### PR DESCRIPTION
**Pull request by MiquelRForgeFlow**
Standard migration.

### CODE REVIEW

**Review by AaronHForgeFlow — COMMENTED** [review]
Functional test ok. Please fix travis

**Review by AaronHForgeFlow — APPROVED** [review]
LGTM Functional speaking. :+1:

**Comment by rousseldenis** [comment]
@mreficent No need of migration scripts for module name change ?

**Review by rousseldenis — APPROVED** [review]
Code review

**Comment by MiquelRForgeFlow** [comment]
@rousseldenis is done in https://github.com/OCA/OpenUpgrade/commit/b6413a2d8bd55b49442c922926af73a067ec295a 😉

**Comment by rousseldenis** [comment]
@MiquelRForgeFlow Do you keep the two commits ? And do you plan to add tests to improve coverage ?

**Comment by MiquelRForgeFlow** [comment]
@rousseldenis in this case I will not squash, I think it's better separated commits. And for the time being, I don't plan to add more tests.

**Pull request merged**
