### PR TITLE
[FIX] repo error by adding product_uom in tests of sale_cancel_reason

### PR DESCRIPTION
**Pull request by kittiu**
Add product_uom when create order_line to make sure that it pass test

### CODE REVIEW

**Comment by mourad-ehm** [comment]
:+1:

**Comment by bealdav** [comment]
:+1:

**Comment by pedrobaeza** [comment]
Travis is still red.

**Comment by mourad-ehm** [comment]
I checked code and found that product_id and product_uom_id are required in 10.0. So I think that the solution is to make the same change for all modules that create sale lien without product_id or product_uom_id in the same PR.

**Comment by mourad-ehm** [comment]
I add this PR to fix this bug https://github.com/OCA/OCB/pull/625
and for odoo https://github.com/odoo/odoo/pull/17613

**Comment by kittiu** [comment]
This issue is just sample for https://github.com/OCA/sale-workflow/pull/429
As that is fixed, this can be closed.

**Pull request closed without merging**
