### PR TITLE
[15.0][MIG] sale_procurement_group_by_commitment_date

### PR DESCRIPTION
**Pull request by JasminSForgeFlow**
Standard Migration

@ForgeFlow

### CODE REVIEW

**Review by AaronHForgeFlow — COMMENTED** [review]
It works good.

Test failing because some non compatibility with other module, need to update rebel module lists

**Review by AaronHForgeFlow — APPROVED** [review]

**Comment by AaronHForgeFlow** [comment]
Just rebased. Seems test for the module sale_sourced_by_line are failing. Can you please check @JasminSForgeFlow ?

**Comment by JasminSForgeFlow** [comment]
> Just rebased. Seems test for the module sale_sourced_by_line are failing. Can you please check @JasminSForgeFlow ?

It is fixed, Thanks

**Review by AaronHForgeFlow — APPROVED** [review]

**Review by SilvioC2C — APPROVED** [review]
LGTM
@JasminSForgeFlow @AaronHForgeFlow could you please rebase this PR?

**Review by cyrilmanuel — APPROVED** [review]

**Comment by AaronHForgeFlow** [comment]
Rebased. If still green it is ready for the merge IMHO

**Review by PauBForgeFlow — APPROVED** [review]
LGTM!

**Pull request merged**
