### PR TITLE
[10.0][ADD] sale_order_invoicing_finished_task: New module

### PR DESCRIPTION
**Pull request by sergio-teruel**
This module has the same objective as the one proposed in #485 
This proposal tries to be simpler and more generic.
There is some questionable point as the use of picking_policy, but between all we will find a good solution.

@Tecnativa

### CODE REVIEW

**Review by gurneyalex — APPROVED** [review]
Reviewed with Rafael and Sergio, works great.

**Comment by sergio-teruel** [comment]
Thanks..

**Review by leemannd — APPROVED** [review]
Thanks nice work. Thanks!

**Comment by rafaelbn** [comment]
Please @sergio-teruel could you add test to increase coverage? Thanks!

**Comment by sergio-teruel** [comment]
@rafaelbn @gurneyalex 100% tests... :smile:

**Comment by carlosdauden** [comment]
ping @angelmoya

**Comment by rafaelbn** [comment]
Hi @sergio-teruel now runbot fails, I cannot test it. Please could you take a look? Thanks!

**Comment by sergio-teruel** [comment]
@rafaelbn runbot is runing

**Review by rafaelbn — APPROVED** [review]

**Pull request merged**
