### PR TITLE
[13.0][MIG] sale_procurement_group_by_commitment_date

### PR DESCRIPTION
**Pull request by ps-tubtim**
Standard migration

### CODE REVIEW

**Review by danimv5 — APPROVED** [review]
Functional review! LGTM

**Review by eduardgm — APPROVED** [review]
Functionally checked, LGTM 👍🏻

**Comment by kittiu** [comment]
Rebased, please try to merge again. Thanks!

**Comment by misern2** [comment]
@dreispt Could you try to merge again ?   Thanks!

**Review by misern2 — APPROVED** [review]
LGTM :+1:

**Comment by JuanyDForgeflow** [comment]
@ps-tubtim Do you plan to continue with this migration?

**Comment by rousseldenis** [comment]
@ps-tubtim

**Comment by rousseldenis** [comment]
@ps-tubtim Could you run copier adding your module to the rebels list ?

**Pull request merged**
