### PR TITLE
[13.0][MIG] sale_isolated_quotation

### PR DESCRIPTION
**Pull request by newtratip**
**Description**
In some countries/companies, it is already common to separate these two documents. For filing purposes, the document sequence of quotation and sales order has to be separated. In practice, there could be multiple quotations open to a customer, yet only one quotation get converted to the sales order.

This module separate quotation and sales order by adding order_sequence flag in sale.order model.

Each type of document will have separated sequence numbering. Quotation will have only 2 state, Draft and Done. Sales Order work as normal.

Peek 2020-03-23 18-46

### CODE REVIEW

**Review by tonygalmiche — APPROVED** [review]
+1 LGTM

**Review by danimv5 — APPROVED** [review]
Functional review! LGTM

**Comment by houssine78** [comment]
Hi @pedrobaeza I think this PR is ready to be merged. Thanks you !

**Comment by pedrobaeza** [comment]
Merging trusting on reviewers:

/ocabot merge nobump

**Comment by bealdav** [comment]
Please @newtratip might try a rebase, maybe it could fix the problem. Thanks a lot

**Comment by newtratip** [comment]
> Please @newtratip might try a rebase, maybe it could fix the problem. Thanks a lot

@bealdav Can you suggest me about rebase ?

**Comment by bealdav** [comment]
Oh just because merge failed.
Please @pedrobaeza could you try again and if it fails once again, maybe a rebase could solve the problem or not.

I haven't investigated by I have to port the module in v14 ;-)

**Comment by pedrobaeza** [comment]
/ocabot merge nobump

It didn't complete because the Travis rate exhausted issue, but nothing to do with the code itself.

**Pull request merged**
