### PR TITLE
[16.0] [MIG] sale_order_line_sequence: Migration to 16.0

### PR DESCRIPTION
**Pull request by DorianMAG**

### CODE REVIEW

**Review by flotho — APPROVED** [review]
functionnal review tested on production OK
easy code migration
LGTM

**Comment by AaronHForgeFlow** [comment]
A refactor is done in v14: https://github.com/OCA/sale-workflow/pull/2603 with high chances of being merged

**Review by JulienMartinez — APPROVED** [review]
Test in runbot
LGTM

**Comment by DorianMAG** [comment]
> A refactor is done in v14: #2603 with high chances of being merged
Thx @AaronHForgeFlow , i will check this
Regards

**Review by rafaelbn — APPROVED** [review]
/ocabot merge patch

**Pull request merged**
