### PR TITLE
[ADD] sale_order_discount_fast_change_ui

### PR DESCRIPTION
**Pull request by paradoxxxzero**

### CODE REVIEW

**Review by hparfr — COMMENTED** [review]
Please add the group product.group_discount_per_so_line to the button

**Review by rousseldenis — APPROVED** [review]
LGTM. Code review

**Review by hparfr — APPROVED** [review]

**Review by mourad-ehm — APPROVED** [review]

**Comment by mourad-ehm** [comment]
Code review

**Comment by francesco-ooops** [comment]
@paradoxxxzero this module has no readme files, could you add them?

**Comment by paradoxxxzero** [comment]
> @paradoxxxzero this module has no readme files, could you add them?

#3054

**Pull request merged**
