### PR TITLE
[MIG] sale_order_weight: Migrated to 10.0

### PR DESCRIPTION
**Pull request by angedras**

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Please put this is sale-reporting. If it's a migration, where it's the original module?

**Comment by angedras** [comment]
I started from https://github.com/OCA/sale-workflow/tree/8.0/sale_order_weight

**Comment by pedrobaeza** [comment]
OK, I see. That module should be initially in the other repo, so the ideal is that you move it to there. You can cherry-pick the corresponding commits in OCA/sale-reporting branch and then add your changes on top. At least, you should follow this migration guide (changing 9 by 8) if you don't change the repository: https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-10.0

**Comment by rafaelbn** [comment]
Hi @angedras , please could move module? We are reviewing from de OCA code sprint! Thanks!

**Comment by hurrinico** [comment]
@pedrobaeza @rafaelbn how i can cherrypick all the commit on sale_order_weight on my sale_reporting repository?
Is good enough if we do another pr in sale-reporting where we add the module?

**Comment by pedrobaeza** [comment]
Follow migration guide: https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-10.0#technical-method-to-migrate-a-module-from-90-to-100-branch

but changing this line:
```
git format-patch --stdout origin/10.0..origin/9.0 -- $MODULE | git am -3
```
to
```
git remote add sale-workflow https://github.com/OCA/sale-workflow
git fetch sale-workflow
git format-patch --stdout origin/10.0..sale-workflow/9.0 -- $MODULE | git am -3
```

**Comment by hurrinico** [comment]
Ok but how i move it to sale-reporting?

**Comment by pedrobaeza** [comment]
You have to follow these instructions on sale-reporting cloned copy, close this PR and open a new one there. This way, you will have the commit history, but in the other repo.

**Comment by rafaelbn** [comment]
I set `invalid`as must be closed in this repo

**Comment by hurrinico** [comment]
Create this https://github.com/OCA/sale-reporting/pull/39 so you can close this one

**Pull request closed without merging**
