### PR TITLE
[10.0] [FIX] [sale_isolated_quotation] Doesn't follow sale.quotation sequence if sale.view_order_form has "name" field set to readonly="0"

### PR DESCRIPTION
**Pull request by rsullivan2704**
This is my first pull request so if I've made any mistakes or missed something please feel free to let me know and I will try to correct them.

This is a fix for #601 which I submitted a short while ago.

I followed the convention for getting 'name' from vals used in the sale.order class of the sale module, which appears to have fixed the issue.

I functionally tested this using a fresh db with only the sale_isolated_quotation module and any dependencies installed in demo mode. It now applies the correct sequence with the *name* field set to either `readonly="0"` or `readonly="1"`

### CODE REVIEW

**Review by kittiu — APPROVED** [review]
Functional tested ok.

**Comment by rousseldenis** [comment]
@rsullivan2704 Could you see why Travis is red ?

**Comment by rsullivan2704** [comment]
> @rsullivan2704 Could you see why Travis is red ?

@rousseldenis Let me preface by saying I'm not a professional developer and have zero experience with Travis or any other CI for that matter, so please excuse me if I'm not interpreting the error correctly. That said, the issue appears to be related to the sale_exception module.

Specifically, it is failing with the error "AssertionError: False is not true" on line#65 of the test_multi_records.py module. See below:

```
2019-09-23 16:36:41,809 5886 ERROR openerp_test odoo.addons.sale_exception.tests.test_multi_records: FAIL: test_sale_order_exception (odoo.addons.sale_exception.tests.test_multi_records.TestSaleExceptionMultiRecord)
2019-09-23 16:36:41,809 5886 ERROR openerp_test odoo.addons.sale_exception.tests.test_multi_records: Traceback (most recent call last):
2019-09-23 16:36:41,809 5886 ERROR openerp_test odoo.addons.sale_exception.tests.test_multi_records: `   File "/home/travis/build/OCA/sale-workflow/sale_exception/tests/test_multi_records.py", line 65, in test_sale_order_exception
2019-09-23 16:36:41,809 5886 ERROR openerp_test odoo.addons.sale_exception.tests.test_multi_records: `     self.assertTrue(exception_no_sol in so2.exception_ids)
2019-09-23 16:36:41,809 5886 ERROR openerp_test odoo.addons.sale_exception.tests.test_multi_records: ` AssertionError: False is not true
2019-09-23 16:36:41,809 5886 INFO openerp_test odoo.addons.sale_exception.tests.test_multi_records: Ran 7 tests in 73.459s
```


https://github.com/OCA/sale-workflow/blob/0d52aa8f07fb516774bc9cc349462003ec5fb453/sale_exception/tests/test_multi_records.py#L65
I cloned a fresh copy of the repository and all dependencies, ran the tests locally, and received the same error.

I'm not familiar with the sale_exception module so I'm sorry I cannot provide any more insight.

**Comment by rousseldenis** [comment]
@rsullivan2704 No problem. In the meantime, we encountered same errors in other PR's. Investigations in progress.

**Comment by rousseldenis** [comment]
Closing as very old. Feel free to reopen it if needed.

**Pull request closed without merging**
