### PR TITLE
[16.0][PORT] sale_quotation_number: allow customizable quotation sequence

### PR DESCRIPTION
**Pull request by MohamedOsman7**
Same Changes: #3310

### CODE REVIEW

**Review by CRogos — APPROVED** [review]
LGTM code + tested

**Comment by diggy128** [comment]
Can this be merged please?

**Comment by CRogos** [comment]
@diggy128 can you add the second review?

**Comment by diggy128** [comment]
Code review LGTM

**Comment by CRogos** [comment]
@diggy128 
image

@pedrobaeza could you merge?

**Pull request merged**
