### PR TITLE
[FIX] security

### PR DESCRIPTION
**Pull request by etobella**
There was a mistake on the definition of permissions.

### CODE REVIEW

**Review by LoisRForgeFlow — APPROVED** [review]

**Comment by LoisRForgeFlow** [comment]
CI errors are fixed here I think: https://github.com/OCA/sale-workflow/pull/739

**Comment by pedrobaeza** [comment]
Merged, so please rebase

**Comment by etobella** [comment]
@pedrobaeza Merged

**Review by pedrobaeza — APPROVED** [review]

**Comment by pedrobaeza** [comment]
Next time, please try to follow commit message guidelines: https://www.odoo.com/documentation/11.0/reference/guidelines.html#commit-message-header

**Pull request merged**
