### PR TITLE
[15.0][MIG] sale_delivery_split_date: Migration to 15.0

### PR DESCRIPTION
**Pull request by yankinmax**

### CODE REVIEW

**Comment by yankinmax** [comment]
@MiquelRForgeFlow can you pls help to fix the tests?

**Comment by yankinmax** [comment]
> @MiquelRForgeFlow can you pls help to fix the tests?

it's strange, but tests were failing and I couldn't find a solution
but they ok now, so no need thanks

**Comment by yankinmax** [comment]
@MiquelRForgeFlow @AaronHForgeFlow @rousseldenis can you pls review?

**Review by MiquelRForgeFlow — APPROVED** [review]
LGTM

**Review by gurneyalex — APPROVED** [review]

**Comment by yankinmax** [comment]
> /ocabot merge nobump

@gurneyalex maybe do it again? or what is happening here?

**Pull request merged**
